# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_INFINIBAND_ERDMA) := erdma.o

erdma-y :=\
	erdma_cm.o erdma_cmd.o erdma_cmdq.o erdma_compat.o erdma_cq.o\
	erdma_debugfs.o erdma_eq.o erdma_ioctl.o erdma_main.o erdma_qp.o\
	erdma_stats.o erdma_verbs.o compat/sw_av.o compat/sw_comp.o compat/sw_cq.o\
	compat/sw_dev.o compat/sw_icrc.o compat/sw_mcast.o compat/sw_mr.o compat/sw_net.o\
	compat/sw_opcode.o compat/sw_pool.o compat/sw_qp.o compat/sw_queue.o compat/sw_recv.o\
	compat/sw_req.o compat/sw_resp.o compat/sw_task.o compat/sw_verbs.o
