// Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#ifndef NBL_MSGQ_AGED_H
#define NBL_MSGQ_AGED_H 1

#include <linux/types.h>

#define NBL_MSGQ_AGED_BASE (0x00FA8000)

#define NBL_MSGQ_AGED_INT_STATUS_ADDR  (0xfa8000)
#define NBL_MSGQ_AGED_INT_STATUS_DEPTH (1)
#define NBL_MSGQ_AGED_INT_STATUS_WIDTH (32)
#define NBL_MSGQ_AGED_INT_STATUS_DWLEN (1)
union msgq_aged_int_status_u {
	struct msgq_aged_int_status {
		u32 fatal_err:1;         /* [00:00] Default:0x0 RWC */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 RWC */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 RWC */
		u32 data_ucor_err:1;     /* [03:03] Default:0x0 RWC */
		u32 data_cor_err:1;      /* [04:04] Default:0x0 RWC */
		u32 cif_err:1;           /* [05:05] Default:0x0 RWC */
		u32 rsv:26;              /* [31:06] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MSGQ_AGED_INT_STATUS_DWLEN];
} __packed;

#define NBL_MSGQ_AGED_INT_MASK_ADDR  (0xfa8004)
#define NBL_MSGQ_AGED_INT_MASK_DEPTH (1)
#define NBL_MSGQ_AGED_INT_MASK_WIDTH (32)
#define NBL_MSGQ_AGED_INT_MASK_DWLEN (1)
union msgq_aged_int_mask_u {
	struct msgq_aged_int_mask {
		u32 fatal_err:1;         /* [00:00] Default:0x0 RW */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 RW */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 RW */
		u32 data_ucor_err:1;     /* [03:03] Default:0x0 RW */
		u32 data_cor_err:1;      /* [04:04] Default:0x0 RW */
		u32 cif_err:1;           /* [05:05] Default:0x0 RW */
		u32 rsv:26;              /* [31:06] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MSGQ_AGED_INT_MASK_DWLEN];
} __packed;

#define NBL_MSGQ_AGED_INT_SET_ADDR  (0xfa8008)
#define NBL_MSGQ_AGED_INT_SET_DEPTH (1)
#define NBL_MSGQ_AGED_INT_SET_WIDTH (32)
#define NBL_MSGQ_AGED_INT_SET_DWLEN (1)
union msgq_aged_int_set_u {
	struct msgq_aged_int_set {
		u32 fatal_err:1;         /* [00:00] Default:0x0 WO */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 WO */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 WO */
		u32 data_ucor_err:1;     /* [03:03] Default:0x0 WO */
		u32 data_cor_err:1;      /* [04:04] Default:0x0 WO */
		u32 cif_err:1;           /* [05:05] Default:0x0 WO */
		u32 rsv:26;              /* [31:06] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MSGQ_AGED_INT_SET_DWLEN];
} __packed;

#define NBL_MSGQ_AGED_INIT_DONE_ADDR  (0xfa800c)
#define NBL_MSGQ_AGED_INIT_DONE_DEPTH (1)
#define NBL_MSGQ_AGED_INIT_DONE_WIDTH (32)
#define NBL_MSGQ_AGED_INIT_DONE_DWLEN (1)
union msgq_aged_init_done_u {
	struct msgq_aged_init_done {
		u32 done:1;              /* [00:00] Default:0x0 RO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MSGQ_AGED_INIT_DONE_DWLEN];
} __packed;

#define NBL_MSGQ_AGED_IDROP_ADDR  (0xfa8058)
#define NBL_MSGQ_AGED_IDROP_DEPTH (1)
#define NBL_MSGQ_AGED_IDROP_WIDTH (32)
#define NBL_MSGQ_AGED_IDROP_DWLEN (1)
union msgq_aged_idrop_u {
	struct msgq_aged_idrop {
		u32 wen_drop_cnt:16;     /* [15:00] Default:0x0 SCTR */
		u32 weoc_drop_cnt:16;    /* [31:16] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_MSGQ_AGED_IDROP_DWLEN];
} __packed;

#define NBL_MSGQ_AGED_CAR_CTRL_ADDR  (0xfa805c)
#define NBL_MSGQ_AGED_CAR_CTRL_DEPTH (1)
#define NBL_MSGQ_AGED_CAR_CTRL_WIDTH (32)
#define NBL_MSGQ_AGED_CAR_CTRL_DWLEN (1)
union msgq_aged_car_ctrl_u {
	struct msgq_aged_car_ctrl {
		u32 sctr_car:1;          /* [00:00] Default:0x1 RW */
		u32 rctr_car:1;          /* [01:01] Default:0x1 RW */
		u32 rc_car:1;            /* [02:02] Default:0x1 RW */
		u32 tbl_rc_car:1;        /* [03:03] Default:0x1 RW */
		u32 rsv:28;              /* [31:04] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MSGQ_AGED_CAR_CTRL_DWLEN];
} __packed;

#define NBL_MSGQ_AGED_FLOW_EN_ADDR  (0xfa8060)
#define NBL_MSGQ_AGED_FLOW_EN_DEPTH (1)
#define NBL_MSGQ_AGED_FLOW_EN_WIDTH (32)
#define NBL_MSGQ_AGED_FLOW_EN_DWLEN (1)
union msgq_aged_flow_en_u {
	struct msgq_aged_flow_en {
		u32 imsgq_aged_cnt_en:1; /* [00:00] Default:0x1 RW */
		u32 omsgq_aged_cnt_en:1; /* [01:01] Default:0x1 RW */
		u32 rsv:30;              /* [31:02] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MSGQ_AGED_FLOW_EN_DWLEN];
} __packed;

#define NBL_MSGQ_AGED_CIF_ERR_INFO_ADDR  (0xfa8064)
#define NBL_MSGQ_AGED_CIF_ERR_INFO_DEPTH (1)
#define NBL_MSGQ_AGED_CIF_ERR_INFO_WIDTH (32)
#define NBL_MSGQ_AGED_CIF_ERR_INFO_DWLEN (1)
union msgq_aged_cif_err_info_u {
	struct msgq_aged_cif_err_info {
		u32 addr:30;             /* [29:00] Default:0x0 RO */
		u32 wr_err:1;            /* [30:30] Default:0x0 RO */
		u32 ucor_err:1;          /* [31:31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MSGQ_AGED_CIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_MSGQ_AGED_MODE_ADDR  (0xfa8100)
#define NBL_MSGQ_AGED_MODE_DEPTH (1)
#define NBL_MSGQ_AGED_MODE_WIDTH (32)
#define NBL_MSGQ_AGED_MODE_DWLEN (1)
union msgq_aged_mode_u {
	struct msgq_aged_mode {
		u32 msgq_aged_mode:1;    /* [00:00] Default:0x1 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MSGQ_AGED_MODE_DWLEN];
} __packed;

#define NBL_MSGQ_AGED_EN_ADDR  (0xfa8104)
#define NBL_MSGQ_AGED_EN_DEPTH (1)
#define NBL_MSGQ_AGED_EN_WIDTH (32)
#define NBL_MSGQ_AGED_EN_DWLEN (1)
union msgq_aged_en_u {
	struct msgq_aged_en {
		u32 msgq_aged_en:1;      /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MSGQ_AGED_EN_DWLEN];
} __packed;

#define NBL_MSGQ_AGED_RING_BASE_ADDR_L_ADDR  (0xfa8108)
#define NBL_MSGQ_AGED_RING_BASE_ADDR_L_DEPTH (1)
#define NBL_MSGQ_AGED_RING_BASE_ADDR_L_WIDTH (32)
#define NBL_MSGQ_AGED_RING_BASE_ADDR_L_DWLEN (1)
union msgq_aged_ring_base_addr_l_u {
	struct msgq_aged_ring_base_addr_l {
		u32 base_addr_l:32;      /* [31:00] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_MSGQ_AGED_RING_BASE_ADDR_L_DWLEN];
} __packed;

#define NBL_MSGQ_AGED_RING_BASE_ADDR_H_ADDR  (0xfa810c)
#define NBL_MSGQ_AGED_RING_BASE_ADDR_H_DEPTH (1)
#define NBL_MSGQ_AGED_RING_BASE_ADDR_H_WIDTH (32)
#define NBL_MSGQ_AGED_RING_BASE_ADDR_H_DWLEN (1)
union msgq_aged_ring_base_addr_h_u {
	struct msgq_aged_ring_base_addr_h {
		u32 base_addr_h:32;      /* [31:00] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_MSGQ_AGED_RING_BASE_ADDR_H_DWLEN];
} __packed;

#define NBL_MSGQ_AGED_RING_SIZE_MASK_ADDR  (0xfa8110)
#define NBL_MSGQ_AGED_RING_SIZE_MASK_DEPTH (1)
#define NBL_MSGQ_AGED_RING_SIZE_MASK_WIDTH (32)
#define NBL_MSGQ_AGED_RING_SIZE_MASK_DWLEN (1)
union msgq_aged_ring_size_mask_u {
	struct msgq_aged_ring_size_mask {
		u32 size_mask:16;        /* [15:00] Default:0x0 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MSGQ_AGED_RING_SIZE_MASK_DWLEN];
} __packed;

#define NBL_MSGQ_AGED_RING_TPNTR_ADDR  (0xfa8114)
#define NBL_MSGQ_AGED_RING_TPNTR_DEPTH (1)
#define NBL_MSGQ_AGED_RING_TPNTR_WIDTH (32)
#define NBL_MSGQ_AGED_RING_TPNTR_DWLEN (1)
union msgq_aged_ring_tpntr_u {
	struct msgq_aged_ring_tpntr {
		u32 tpntr:16;            /* [15:00] Default:0x0 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MSGQ_AGED_RING_TPNTR_DWLEN];
} __packed;

#define NBL_MSGQ_AGED_RING_HPNTR_ADDR  (0xfa8118)
#define NBL_MSGQ_AGED_RING_HPNTR_DEPTH (1)
#define NBL_MSGQ_AGED_RING_HPNTR_WIDTH (32)
#define NBL_MSGQ_AGED_RING_HPNTR_DWLEN (1)
union msgq_aged_ring_hpntr_u {
	struct msgq_aged_ring_hpntr {
		u32 hpntr:16;            /* [15:00] Default:0x0 RO */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MSGQ_AGED_RING_HPNTR_DWLEN];
} __packed;

#define NBL_MSGQ_AGED_RING_HPNTR_RST_ADDR  (0xfa811c)
#define NBL_MSGQ_AGED_RING_HPNTR_RST_DEPTH (1)
#define NBL_MSGQ_AGED_RING_HPNTR_RST_WIDTH (32)
#define NBL_MSGQ_AGED_RING_HPNTR_RST_DWLEN (1)
union msgq_aged_ring_hpntr_rst_u {
	struct msgq_aged_ring_hpntr_rst {
		u32 hpntr_rst:1;         /* [00:00] Default:0x0 WO */
		u32 rdy:1;               /* [01:01] Default:0x1 RO */
		u32 rsv:30;              /* [31:02] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MSGQ_AGED_RING_HPNTR_RST_DWLEN];
} __packed;

#define NBL_MSGQ_AGED_BURST_LEN_ADDR  (0xfa8120)
#define NBL_MSGQ_AGED_BURST_LEN_DEPTH (1)
#define NBL_MSGQ_AGED_BURST_LEN_WIDTH (32)
#define NBL_MSGQ_AGED_BURST_LEN_DWLEN (1)
union msgq_aged_burst_len_u {
	struct msgq_aged_burst_len {
		u32 burst_len:6;         /* [05:00] Default:0x1 RW */
		u32 rsv:26;              /* [31:06] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MSGQ_AGED_BURST_LEN_DWLEN];
} __packed;

#define NBL_MSGQ_AGED_TIMEOUT_VALUE_ADDR  (0xfa8124)
#define NBL_MSGQ_AGED_TIMEOUT_VALUE_DEPTH (1)
#define NBL_MSGQ_AGED_TIMEOUT_VALUE_WIDTH (32)
#define NBL_MSGQ_AGED_TIMEOUT_VALUE_DWLEN (1)
union msgq_aged_timeout_value_u {
	struct msgq_aged_timeout_value {
		u32 timeout_value:32;    /* [31:00] Default:0x190 RW */
	} __packed info;
	u32 data[NBL_MSGQ_AGED_TIMEOUT_VALUE_DWLEN];
} __packed;

#define NBL_MSGQ_AGED_DIF_MODE_ADDR  (0xfa8128)
#define NBL_MSGQ_AGED_DIF_MODE_DEPTH (1)
#define NBL_MSGQ_AGED_DIF_MODE_WIDTH (32)
#define NBL_MSGQ_AGED_DIF_MODE_DWLEN (1)
union msgq_aged_dif_mode_u {
	struct msgq_aged_dif_mode {
		u32 dif_mode:3;          /* [02:00] Default:0x2 RW */
		u32 rsv:29;              /* [31:03] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MSGQ_AGED_DIF_MODE_DWLEN];
} __packed;

#define NBL_MSGQ_AGED_DIF_INFO_ADDR  (0xfa812c)
#define NBL_MSGQ_AGED_DIF_INFO_DEPTH (1)
#define NBL_MSGQ_AGED_DIF_INFO_WIDTH (32)
#define NBL_MSGQ_AGED_DIF_INFO_DWLEN (1)
union msgq_aged_dif_info_u {
	struct msgq_aged_dif_info {
		u32 dif_info:16;         /* [15:00] Default:0x0 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MSGQ_AGED_DIF_INFO_DWLEN];
} __packed;

#define NBL_MSGQ_AGED_DIF_BDF_ADDR  (0xfa8130)
#define NBL_MSGQ_AGED_DIF_BDF_DEPTH (1)
#define NBL_MSGQ_AGED_DIF_BDF_WIDTH (32)
#define NBL_MSGQ_AGED_DIF_BDF_DWLEN (1)
union msgq_aged_dif_bdf_u {
	struct msgq_aged_dif_bdf {
		u32 dif_bdf:16;          /* [15:00] Default:0x0 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MSGQ_AGED_DIF_BDF_DWLEN];
} __packed;

#define NBL_MSGQ_AGED_DIF_INT_ADDR  (0xfa8134)
#define NBL_MSGQ_AGED_DIF_INT_DEPTH (1)
#define NBL_MSGQ_AGED_DIF_INT_WIDTH (32)
#define NBL_MSGQ_AGED_DIF_INT_DWLEN (1)
union msgq_aged_dif_int_u {
	struct msgq_aged_dif_int {
		u32 dif_int:1;           /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_MSGQ_AGED_DIF_INT_DWLEN];
} __packed;

#define NBL_MSGQ_AGED_MDL_INFO_ADDR  (0xfa8138)
#define NBL_MSGQ_AGED_MDL_INFO_DEPTH (1)
#define NBL_MSGQ_AGED_MDL_INFO_WIDTH (32)
#define NBL_MSGQ_AGED_MDL_INFO_DWLEN (1)
union msgq_aged_mdl_info_u {
	struct msgq_aged_mdl_info {
		u32 version_id:16;       /* [15:00] Default:0x0001 RO */
		u32 prj_id:16;           /* [31:16] Default:0x0020 RO */
	} __packed info;
	u32 data[NBL_MSGQ_AGED_MDL_INFO_DWLEN];
} __packed;

#define NBL_MSGQ_AGED_VERSION_ADDR  (0xfa813c)
#define NBL_MSGQ_AGED_VERSION_DEPTH (1)
#define NBL_MSGQ_AGED_VERSION_WIDTH (32)
#define NBL_MSGQ_AGED_VERSION_DWLEN (1)
union msgq_aged_version_u {
	struct msgq_aged_version {
		u32 date:32;             /* [31:00] Default:0x20220615 RO */
	} __packed info;
	u32 data[NBL_MSGQ_AGED_VERSION_DWLEN];
} __packed;

#endif
