// Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#ifndef NBL_DPRBAC_H
#define NBL_DPRBAC_H 1

#include <linux/types.h>

#define NBL_DPRBAC_BASE (0x00904000)

#define NBL_DPRBAC_INT_STATUS_ADDR  (0x904000)
#define NBL_DPRBAC_INT_STATUS_DEPTH (1)
#define NBL_DPRBAC_INT_STATUS_WIDTH (32)
#define NBL_DPRBAC_INT_STATUS_DWLEN (1)
union dprbac_int_status_u {
	struct dprbac_int_status {
		u32 fatal_err:1;         /* [0] Default:0x0 RWC */
		u32 fifo_underflow:1;    /* [1] Default:0x0 RWC */
		u32 fifo_overflow:1;     /* [2] Default:0x0 RWC */
		u32 cif_err:1;           /* [3] Default:0x0 RWC */
		u32 cfg_err:1;           /* [4] Default:0x0 RWC */
		u32 ucor_err:1;          /* [5] Default:0x0 RWC */
		u32 cor_err:1;           /* [6] Default:0x0 RWC */
		u32 soft_lifetime:1;     /* [7] Default:0x0 RWC */
		u32 hard_lifetime:1;     /* [8] Default:0x0 RWC */
		u32 pkt_err:1;           /* [9] Default:0x0 RWC */
		u32 esn_ovf:1;           /* [10] Default:0x0 RWC */
		u32 rsv:21;              /* [31:11] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_INT_STATUS_DWLEN];
} __packed;

#define NBL_DPRBAC_INT_MASK_ADDR  (0x904004)
#define NBL_DPRBAC_INT_MASK_DEPTH (1)
#define NBL_DPRBAC_INT_MASK_WIDTH (32)
#define NBL_DPRBAC_INT_MASK_DWLEN (1)
union dprbac_int_mask_u {
	struct dprbac_int_mask {
		u32 fatal_err:1;         /* [0] Default:0x0 RW */
		u32 fifo_underflow:1;    /* [1] Default:0x0 RW */
		u32 fifo_overflow:1;     /* [2] Default:0x0 RW */
		u32 cif_err:1;           /* [3] Default:0x0 RW */
		u32 cfg_err:1;           /* [4] Default:0x0 RW */
		u32 ucor_err:1;          /* [5] Default:0x0 RW */
		u32 cor_err:1;           /* [6] Default:0x0 RW */
		u32 soft_lifetime:1;     /* [7] Default:0x0 RW */
		u32 hard_lifetime:1;     /* [8] Default:0x0 RW */
		u32 pkt_err:1;           /* [9] Default:0x0 RW */
		u32 esn_ovf:1;           /* [10] Default:0x0 RW */
		u32 rsv:21;              /* [31:11] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_INT_MASK_DWLEN];
} __packed;

#define NBL_DPRBAC_INT_SET_ADDR  (0x904008)
#define NBL_DPRBAC_INT_SET_DEPTH (1)
#define NBL_DPRBAC_INT_SET_WIDTH (32)
#define NBL_DPRBAC_INT_SET_DWLEN (1)
union dprbac_int_set_u {
	struct dprbac_int_set {
		u32 fatal_err:1;         /* [0] Default:0x0 WO */
		u32 fifo_underflow:1;    /* [1] Default:0x0 WO */
		u32 fifo_overflow:1;     /* [2] Default:0x0 WO */
		u32 cif_err:1;           /* [3] Default:0x0 WO */
		u32 cfg_err:1;           /* [4] Default:0x0 WO */
		u32 ucor_err:1;          /* [5] Default:0x0 WO */
		u32 cor_err:1;           /* [6] Default:0x0 WO */
		u32 soft_lifetime:1;     /* [7] Default:0x0 WO */
		u32 hard_lifetime:1;     /* [8] Default:0x0 WO */
		u32 pkt_err:1;           /* [9] Default:0x0 WO */
		u32 esn_ovf:1;           /* [10] Default:0x0 WO */
		u32 rsv:21;              /* [31:11] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_INT_SET_DWLEN];
} __packed;

#define NBL_DPRBAC_ESN_OVF_INFO_ADDR  (0x904010)
#define NBL_DPRBAC_ESN_OVF_INFO_DEPTH (1)
#define NBL_DPRBAC_ESN_OVF_INFO_WIDTH (32)
#define NBL_DPRBAC_ESN_OVF_INFO_DWLEN (1)
union dprbac_esn_ovf_info_u {
	struct dprbac_esn_ovf_info {
		u32 sad_index:11;        /* [10:0] Default:0x0 RO */
		u32 rsv:21;              /* [31:11] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_ESN_OVF_INFO_DWLEN];
} __packed;

#define NBL_DPRBAC_LIFETIME_INFO_ADDR  (0x904014)
#define NBL_DPRBAC_LIFETIME_INFO_DEPTH (1)
#define NBL_DPRBAC_LIFETIME_INFO_WIDTH (32)
#define NBL_DPRBAC_LIFETIME_INFO_DWLEN (1)
union dprbac_lifetime_info_u {
	struct dprbac_lifetime_info {
		u32 soft_sad_index:11;   /* [10:0] Default:0x0 RO */
		u32 rsv1:5;              /* [15:11] Default:0x0 RO */
		u32 hard_sad_index:11;   /* [26:16] Default:0x0 RO */
		u32 rsv:5;               /* [31:27] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_LIFETIME_INFO_DWLEN];
} __packed;

#define NBL_DPRBAC_UCOR_ERR_INFO_ADDR  (0x904024)
#define NBL_DPRBAC_UCOR_ERR_INFO_DEPTH (1)
#define NBL_DPRBAC_UCOR_ERR_INFO_WIDTH (32)
#define NBL_DPRBAC_UCOR_ERR_INFO_DWLEN (1)
union dprbac_ucor_err_info_u {
	struct dprbac_ucor_err_info {
		u32 addr:16;             /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_UCOR_ERR_INFO_DWLEN];
} __packed;

#define NBL_DPRBAC_COR_ERR_INFO_ADDR  (0x90402c)
#define NBL_DPRBAC_COR_ERR_INFO_DEPTH (1)
#define NBL_DPRBAC_COR_ERR_INFO_WIDTH (32)
#define NBL_DPRBAC_COR_ERR_INFO_DWLEN (1)
union dprbac_cor_err_info_u {
	struct dprbac_cor_err_info {
		u32 addr:16;             /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_COR_ERR_INFO_DWLEN];
} __packed;

#define NBL_DPRBAC_CFG_ERR_INFO_ADDR  (0x904034)
#define NBL_DPRBAC_CFG_ERR_INFO_DEPTH (1)
#define NBL_DPRBAC_CFG_ERR_INFO_WIDTH (32)
#define NBL_DPRBAC_CFG_ERR_INFO_DWLEN (1)
union dprbac_cfg_err_info_u {
	struct dprbac_cfg_err_info {
		u32 addr:16;             /* [15:0] Default:0x0 RO */
		u32 id:6;                /* [21:16] Default:0x0 RO */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_CFG_ERR_INFO_DWLEN];
} __packed;

#define NBL_DPRBAC_CIF_ERR_INFO_ADDR  (0x904040)
#define NBL_DPRBAC_CIF_ERR_INFO_DEPTH (1)
#define NBL_DPRBAC_CIF_ERR_INFO_WIDTH (32)
#define NBL_DPRBAC_CIF_ERR_INFO_DWLEN (1)
union dprbac_cif_err_info_u {
	struct dprbac_cif_err_info {
		u32 addr:30;             /* [29:0] Default:0x0 RO */
		u32 wr_err:1;            /* [30] Default:0x0 RO */
		u32 ucor_err:1;          /* [31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_CIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_DPRBAC_PKT_ERR_INFO_ADDR  (0x904048)
#define NBL_DPRBAC_PKT_ERR_INFO_DEPTH (1)
#define NBL_DPRBAC_PKT_ERR_INFO_WIDTH (32)
#define NBL_DPRBAC_PKT_ERR_INFO_DWLEN (1)
union dprbac_pkt_err_info_u {
	struct dprbac_pkt_err_info {
		u32 dport:16;            /* [15:0] Default:0x0 RO */
		u32 pkt_len:16;          /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_PKT_ERR_INFO_DWLEN];
} __packed;

#define NBL_DPRBAC_CAR_CTRL_ADDR  (0x904100)
#define NBL_DPRBAC_CAR_CTRL_DEPTH (1)
#define NBL_DPRBAC_CAR_CTRL_WIDTH (32)
#define NBL_DPRBAC_CAR_CTRL_DWLEN (1)
union dprbac_car_ctrl_u {
	struct dprbac_car_ctrl {
		u32 sctr_car:1;          /* [0] Default:0x1 RW */
		u32 rctr_car:1;          /* [1] Default:0x1 RW */
		u32 rc_car:1;            /* [2] Default:0x1 RW */
		u32 tbl_rc_car:1;        /* [3] Default:0x1 RW */
		u32 rsv:28;              /* [31:4] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_CAR_CTRL_DWLEN];
} __packed;

#define NBL_DPRBAC_ENABLE_ADDR  (0x904114)
#define NBL_DPRBAC_ENABLE_DEPTH (1)
#define NBL_DPRBAC_ENABLE_WIDTH (32)
#define NBL_DPRBAC_ENABLE_DWLEN (1)
union dprbac_enable_u {
	struct dprbac_enable {
		u32 prbac:1;             /* [0] Default:0x0 RW */
		u32 mf_fwd:1;            /* [1] Default:0x1 RW */
		u32 ipv4_nat_csm:1;      /* [2] Default:0x0 RW */
		u32 ipv6_nat_csm:1;      /* [3] Default:0x1 RW */
		u32 rsv:28;              /* [31:4] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_ENABLE_DWLEN];
} __packed;

#define NBL_DPRBAC_CLK_GATE_ADDR  (0x904118)
#define NBL_DPRBAC_CLK_GATE_DEPTH (1)
#define NBL_DPRBAC_CLK_GATE_WIDTH (32)
#define NBL_DPRBAC_CLK_GATE_DWLEN (1)
union dprbac_clk_gate_u {
	struct dprbac_clk_gate {
		u32 clk_en:1;            /* [0] Default:0x0 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_CLK_GATE_DWLEN];
} __packed;

#define NBL_DPRBAC_INIT_START_ADDR  (0x904124)
#define NBL_DPRBAC_INIT_START_DEPTH (1)
#define NBL_DPRBAC_INIT_START_WIDTH (32)
#define NBL_DPRBAC_INIT_START_DWLEN (1)
union dprbac_init_start_u {
	struct dprbac_init_start {
		u32 start:1;             /* [0] Default:0x0 WO */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_INIT_START_DWLEN];
} __packed;

#define NBL_DPRBAC_INIT_DONE_ADDR  (0x904128)
#define NBL_DPRBAC_INIT_DONE_DEPTH (1)
#define NBL_DPRBAC_INIT_DONE_WIDTH (32)
#define NBL_DPRBAC_INIT_DONE_DWLEN (1)
union dprbac_init_done_u {
	struct dprbac_init_done {
		u32 done:1;              /* [0] Default:0x0 RO */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_INIT_DONE_DWLEN];
} __packed;

#define NBL_DPRBAC_NAT_ADDR  (0x90412c)
#define NBL_DPRBAC_NAT_DEPTH (1)
#define NBL_DPRBAC_NAT_WIDTH (32)
#define NBL_DPRBAC_NAT_DWLEN (1)
union dprbac_nat_u {
	struct dprbac_nat {
		u32 rsv:16;              /* [15:0] Default:0x0 RO */
		u32 sport:16;            /* [31:16] Default:4500 RW */
	} __packed info;
	u32 data[NBL_DPRBAC_NAT_DWLEN];
} __packed;

#define NBL_DPRBAC_VLAN_TYPE0_ADDR  (0x904130)
#define NBL_DPRBAC_VLAN_TYPE0_DEPTH (1)
#define NBL_DPRBAC_VLAN_TYPE0_WIDTH (32)
#define NBL_DPRBAC_VLAN_TYPE0_DWLEN (1)
union dprbac_vlan_type0_u {
	struct dprbac_vlan_type0 {
		u32 tpid0:16;            /* [15:0] Default:0x88A8 RW */
		u32 tpid1:16;            /* [31:16] Default:0x9100 RW */
	} __packed info;
	u32 data[NBL_DPRBAC_VLAN_TYPE0_DWLEN];
} __packed;

#define NBL_DPRBAC_VLAN_TYPE1_ADDR  (0x904134)
#define NBL_DPRBAC_VLAN_TYPE1_DEPTH (1)
#define NBL_DPRBAC_VLAN_TYPE1_WIDTH (32)
#define NBL_DPRBAC_VLAN_TYPE1_DWLEN (1)
union dprbac_vlan_type1_u {
	struct dprbac_vlan_type1 {
		u32 tpid2:16;            /* [15:0] Default:0x0 RW */
		u32 tpid3:16;            /* [31:16] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_DPRBAC_VLAN_TYPE1_DWLEN];
} __packed;

#define NBL_DPRBAC_VLAN_ENABLE_ADDR  (0x904140)
#define NBL_DPRBAC_VLAN_ENABLE_DEPTH (1)
#define NBL_DPRBAC_VLAN_ENABLE_WIDTH (32)
#define NBL_DPRBAC_VLAN_ENABLE_DWLEN (1)
union dprbac_vlan_enable_u {
	struct dprbac_vlan_enable {
		u32 tpid0:1;             /* [0] Default:0x1 RW */
		u32 tpid1:1;             /* [1] Default:0x1 RW */
		u32 tpid2:1;             /* [2] Default:0x0 RW */
		u32 tpid3:1;             /* [3] Default:0x0 RW */
		u32 rsv:28;              /* [31:4] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_VLAN_ENABLE_DWLEN];
} __packed;

#define NBL_DPRBAC_DROP_ADDR  (0x904180)
#define NBL_DPRBAC_DROP_DEPTH (1)
#define NBL_DPRBAC_DROP_WIDTH (32)
#define NBL_DPRBAC_DROP_DWLEN (1)
union dprbac_drop_u {
	struct dprbac_drop {
		u32 prbac_bp:1;          /* [0] Default:0x1 RW */
		u32 md_drop:1;           /* [1] Default:0x1 RW */
		u32 md_errcode:1;        /* [2] Default:0x0 RW */
		u32 rsv:29;              /* [31:3] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_DROP_DWLEN];
} __packed;

#define NBL_DPRBAC_MTU_ADDR  (0x904184)
#define NBL_DPRBAC_MTU_DEPTH (1)
#define NBL_DPRBAC_MTU_WIDTH (32)
#define NBL_DPRBAC_MTU_DWLEN (1)
union dprbac_mtu_u {
	struct dprbac_mtu {
		u32 len:14;              /* [13:0] Default:9600 RW */
		u32 rsv:18;              /* [31:14] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_MTU_DWLEN];
} __packed;

#define NBL_DPRBAC_WRR_WT_ADDR  (0x904200)
#define NBL_DPRBAC_WRR_WT_DEPTH (1)
#define NBL_DPRBAC_WRR_WT_WIDTH (32)
#define NBL_DPRBAC_WRR_WT_DWLEN (1)
union dprbac_wrr_wt_u {
	struct dprbac_wrr_wt {
		u32 prbac:4;             /* [3:0] Default:0x1 RW */
		u32 rsv1:12;             /* [15:4] Default:0x0 RO */
		u32 normal:8;            /* [23:16] Default:0x3 RW */
		u32 rsv:8;               /* [31:24] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_WRR_WT_DWLEN];
} __packed;

#define NBL_DPRBAC_SAD_LIFETIME_ADDR  (0x904204)
#define NBL_DPRBAC_SAD_LIFETIME_DEPTH (1)
#define NBL_DPRBAC_SAD_LIFETIME_WIDTH (32)
#define NBL_DPRBAC_SAD_LIFETIME_DWLEN (1)
union dprbac_sad_lifetime_u {
	struct dprbac_sad_lifetime {
		u32 sad_index:11;        /* [10:0] Default:0x0 RW */
		u32 rsv2:5;              /* [15:11] Default:0x0 RW */
		u32 msb_value:1;         /* [16] Default:0x1 RW */
		u32 flag_value:1;        /* [17] Default:0x1 RW */
		u32 rsv1:2;              /* [19:18] Default:0x0 RO */
		u32 msb_wen:1;           /* [20] Default:0x0 RWW */
		u32 flag_wen:1;          /* [21] Default:0x0 RWW */
		u32 rsv:10;              /* [31:22] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_SAD_LIFETIME_DWLEN];
} __packed;

#define NBL_DPRBAC_LIFETIME_DIFF_ADDR  (0x904208)
#define NBL_DPRBAC_LIFETIME_DIFF_DEPTH (1)
#define NBL_DPRBAC_LIFETIME_DIFF_WIDTH (32)
#define NBL_DPRBAC_LIFETIME_DIFF_DWLEN (1)
union dprbac_lifetime_diff_u {
	struct dprbac_lifetime_diff {
		u32 value:32;            /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_DPRBAC_LIFETIME_DIFF_DWLEN];
} __packed;

#define NBL_DPRBAC_PADDING_DAT0_ADDR  (0x904300)
#define NBL_DPRBAC_PADDING_DAT0_DEPTH (1)
#define NBL_DPRBAC_PADDING_DAT0_WIDTH (32)
#define NBL_DPRBAC_PADDING_DAT0_DWLEN (1)
union dprbac_padding_dat0_u {
	struct dprbac_padding_dat0 {
		u32 data:32;             /* [31:0] Default:0x01020304 RW */
	} __packed info;
	u32 data[NBL_DPRBAC_PADDING_DAT0_DWLEN];
} __packed;

#define NBL_DPRBAC_PADDING_DAT1_ADDR  (0x904304)
#define NBL_DPRBAC_PADDING_DAT1_DEPTH (1)
#define NBL_DPRBAC_PADDING_DAT1_WIDTH (32)
#define NBL_DPRBAC_PADDING_DAT1_DWLEN (1)
union dprbac_padding_dat1_u {
	struct dprbac_padding_dat1 {
		u32 data:32;             /* [31:0] Default:0x05060708 RW */
	} __packed info;
	u32 data[NBL_DPRBAC_PADDING_DAT1_DWLEN];
} __packed;

#define NBL_DPRBAC_PADDING_DAT2_ADDR  (0x904308)
#define NBL_DPRBAC_PADDING_DAT2_DEPTH (1)
#define NBL_DPRBAC_PADDING_DAT2_WIDTH (32)
#define NBL_DPRBAC_PADDING_DAT2_DWLEN (1)
union dprbac_padding_dat2_u {
	struct dprbac_padding_dat2 {
		u32 data:32;             /* [31:0] Default:0x090a0b0c RW */
	} __packed info;
	u32 data[NBL_DPRBAC_PADDING_DAT2_DWLEN];
} __packed;

#define NBL_DPRBAC_PADDING_DAT3_ADDR  (0x90430c)
#define NBL_DPRBAC_PADDING_DAT3_DEPTH (1)
#define NBL_DPRBAC_PADDING_DAT3_WIDTH (32)
#define NBL_DPRBAC_PADDING_DAT3_DWLEN (1)
union dprbac_padding_dat3_u {
	struct dprbac_padding_dat3 {
		u32 data:32;             /* [31:0] Default:0x0d0e0f10 RW */
	} __packed info;
	u32 data[NBL_DPRBAC_PADDING_DAT3_DWLEN];
} __packed;

#define NBL_DPRBAC_PADDING_ALIGN_LEN_ADDR  (0x904310)
#define NBL_DPRBAC_PADDING_ALIGN_LEN_DEPTH (1)
#define NBL_DPRBAC_PADDING_ALIGN_LEN_WIDTH (32)
#define NBL_DPRBAC_PADDING_ALIGN_LEN_DWLEN (1)
union dprbac_padding_align_len_u {
	struct dprbac_padding_align_len {
		u32 info:1;              /* [0] Default:0x0 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_PADDING_ALIGN_LEN_DWLEN];
} __packed;

#define NBL_DPRBAC_MF_VALID_EXTRACT_ADDR  (0x904378)
#define NBL_DPRBAC_MF_VALID_EXTRACT_DEPTH (1)
#define NBL_DPRBAC_MF_VALID_EXTRACT_WIDTH (32)
#define NBL_DPRBAC_MF_VALID_EXTRACT_DWLEN (1)
union dprbac_mf_valid_extract_u {
	struct dprbac_mf_valid_extract {
		u32 offset:5;            /* [4:0] Default:5 RW */
		u32 en:1;                /* [5] Default:0x1 RW */
		u32 rsv:26;              /* [31:6] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_MF_VALID_EXTRACT_DWLEN];
} __packed;

#define NBL_DPRBAC_DPORT_EXTRACT_ADDR  (0x90437c)
#define NBL_DPRBAC_DPORT_EXTRACT_DEPTH (1)
#define NBL_DPRBAC_DPORT_EXTRACT_WIDTH (32)
#define NBL_DPRBAC_DPORT_EXTRACT_DWLEN (1)
union dprbac_dport_extract_u {
	struct dprbac_dport_extract {
		u32 id:6;                /* [5:0] Default:0x9 RW */
		u32 rsv:26;              /* [31:6] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_DPORT_EXTRACT_DWLEN];
} __packed;

#define NBL_DPRBAC_SAD_IDX_EXTRACT_ADDR  (0x904380)
#define NBL_DPRBAC_SAD_IDX_EXTRACT_DEPTH (1)
#define NBL_DPRBAC_SAD_IDX_EXTRACT_WIDTH (32)
#define NBL_DPRBAC_SAD_IDX_EXTRACT_DWLEN (1)
union dprbac_sad_idx_extract_u {
	struct dprbac_sad_idx_extract {
		u32 id:6;                /* [5:0] Default:17 RW */
		u32 en:1;                /* [6] Default:0x1 RW */
		u32 rsv:25;              /* [31:7] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_SAD_IDX_EXTRACT_DWLEN];
} __packed;

#define NBL_DPRBAC_SAD_IDX_FILTER_ADDR  (0x904384)
#define NBL_DPRBAC_SAD_IDX_FILTER_DEPTH (1)
#define NBL_DPRBAC_SAD_IDX_FILTER_WIDTH (32)
#define NBL_DPRBAC_SAD_IDX_FILTER_DWLEN (1)
union dprbac_sad_idx_filter_u {
	struct dprbac_sad_idx_filter {
		u32 btm:30;              /* [29:0] Default:0x8000 RW */
		u32 rsv:2;               /* [31:30] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_SAD_IDX_FILTER_DWLEN];
} __packed;

#define NBL_DPRBAC_XOFF_TO_DPED_ADDR  (0x904430)
#define NBL_DPRBAC_XOFF_TO_DPED_DEPTH (1)
#define NBL_DPRBAC_XOFF_TO_DPED_WIDTH (32)
#define NBL_DPRBAC_XOFF_TO_DPED_DWLEN (1)
union dprbac_xoff_to_dped_u {
	struct dprbac_xoff_to_dped {
		u32 bp_set:1;            /* [0] Default:0x0 RW */
		u32 bp_mask:1;           /* [1] Default:0x0 RW */
		u32 rsv:30;              /* [31:2] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_XOFF_TO_DPED_DWLEN];
} __packed;

#define NBL_DPRBAC_XOFF_FROM_DDMUX_ADDR  (0x904434)
#define NBL_DPRBAC_XOFF_FROM_DDMUX_DEPTH (1)
#define NBL_DPRBAC_XOFF_FROM_DDMUX_WIDTH (32)
#define NBL_DPRBAC_XOFF_FROM_DDMUX_DWLEN (1)
union dprbac_xoff_from_ddmux_u {
	struct dprbac_xoff_from_ddmux {
		u32 bp_set:1;            /* [0] Default:0x0 RW */
		u32 bp_mask:1;           /* [1] Default:0x0 RW */
		u32 rsv:30;              /* [31:2] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_XOFF_FROM_DDMUX_DWLEN];
} __packed;

#define NBL_DPRBAC_WIDE_TABLE_TIME_ADDR  (0x905000)
#define NBL_DPRBAC_WIDE_TABLE_TIME_DEPTH (1)
#define NBL_DPRBAC_WIDE_TABLE_TIME_WIDTH (32)
#define NBL_DPRBAC_WIDE_TABLE_TIME_DWLEN (1)
union dprbac_wide_table_time_u {
	struct dprbac_wide_table_time {
		u32 xoff_th:8;           /* [7:0] Default:128 RW */
		u32 rsv:24;              /* [31:8] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_WIDE_TABLE_TIME_DWLEN];
} __packed;

#define NBL_DPRBAC_SAD_IV_TABLE_ADDR  (0x914000)
#define NBL_DPRBAC_SAD_IV_TABLE_DEPTH (2048)
#define NBL_DPRBAC_SAD_IV_TABLE_WIDTH (64)
#define NBL_DPRBAC_SAD_IV_TABLE_DWLEN (2)
union dprbac_sad_iv_table_u {
	struct dprbac_sad_iv_table {
		u32 iv_arr[2];           /* [63:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_DPRBAC_SAD_IV_TABLE_DWLEN];
} __packed;
#define NBL_DPRBAC_SAD_IV_TABLE_REG(r) (NBL_DPRBAC_SAD_IV_TABLE_ADDR + \
		(NBL_DPRBAC_SAD_IV_TABLE_DWLEN * 4) * (r))

#define NBL_DPRBAC_SAD_ESN_TABLE_ADDR  (0x924000)
#define NBL_DPRBAC_SAD_ESN_TABLE_DEPTH (2048)
#define NBL_DPRBAC_SAD_ESN_TABLE_WIDTH (128)
#define NBL_DPRBAC_SAD_ESN_TABLE_DWLEN (4)
union dprbac_sad_esn_table_u {
	struct dprbac_sad_esn_table {
		u32 sn:32;               /* [31:0] Default:0x0 RW */
		u32 esn:32;              /* [63:32] Default:0x0 RW */
		u32 wrap_en:1;           /* [64] Default:0x0 RW */
		u32 enable:1;            /* [65] Default:0x0 RW */
		u32 rsv_l:32;            /* [127:66] Default:0x0 RO */
		u32 rsv_h:30;            /* [127:66] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_SAD_ESN_TABLE_DWLEN];
} __packed;
#define NBL_DPRBAC_SAD_ESN_TABLE_REG(r) (NBL_DPRBAC_SAD_ESN_TABLE_ADDR + \
		(NBL_DPRBAC_SAD_ESN_TABLE_DWLEN * 4) * (r))

#define NBL_DPRBAC_SAD_LIFETIME_TABLE_ADDR  (0x934000)
#define NBL_DPRBAC_SAD_LIFETIME_TABLE_DEPTH (2048)
#define NBL_DPRBAC_SAD_LIFETIME_TABLE_WIDTH (128)
#define NBL_DPRBAC_SAD_LIFETIME_TABLE_DWLEN (4)
union dprbac_sad_lifetime_table_u {
	struct dprbac_sad_lifetime_table {
		u32 diff:32;             /* [31:0] Default:0x0 RW */
		u32 cnt:32;              /* [63:32] Default:0x0 RW */
		u32 flag:1;              /* [64] Default:0x0 RW */
		u32 unit:1;              /* [65] Default:0x0 RW */
		u32 enable:1;            /* [66] Default:0x0 RW */
		u32 rsv_l:32;            /* [127:67] Default:0x0 RO */
		u32 rsv_h:29;            /* [127:67] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_SAD_LIFETIME_TABLE_DWLEN];
} __packed;
#define NBL_DPRBAC_SAD_LIFETIME_TABLE_REG(r) (NBL_DPRBAC_SAD_LIFETIME_TABLE_ADDR + \
		(NBL_DPRBAC_SAD_LIFETIME_TABLE_DWLEN * 4) * (r))

#define NBL_DPRBAC_SAD_CRYPTO_INFO_TABLE_ADDR  (0x944000)
#define NBL_DPRBAC_SAD_CRYPTO_INFO_TABLE_DEPTH (2048)
#define NBL_DPRBAC_SAD_CRYPTO_INFO_TABLE_WIDTH (512)
#define NBL_DPRBAC_SAD_CRYPTO_INFO_TABLE_DWLEN (16)
union dprbac_sad_crypto_info_table_u {
	struct dprbac_sad_crypto_info_table {
		u32 key_arr[8];          /* [255:0] Default:0x0 RW */
		u32 salt:32;             /* [287:256] Default:0x0 RW */
		u32 crypto_type:3;       /* [290:288] Default:0x0 RW */
		u32 tunnel_mode:1;       /* [291] Default:0x0 RW */
		u32 icv_len:2;           /* [293:292] Default:0x0 RW */
		u32 rsv:25;              /* [511:295] Default:0x0 RO */
		u32 rsv_arr[6];          /* [511:295] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_SAD_CRYPTO_INFO_TABLE_DWLEN];
} __packed;
#define NBL_DPRBAC_SAD_CRYPTO_INFO_TABLE_REG(r) (NBL_DPRBAC_SAD_CRYPTO_INFO_TABLE_ADDR + \
		(NBL_DPRBAC_SAD_CRYPTO_INFO_TABLE_DWLEN * 4) * (r))

#define NBL_DPRBAC_SAD_ENCAP_INFO_TABLE_ADDR  (0x964000)
#define NBL_DPRBAC_SAD_ENCAP_INFO_TABLE_DEPTH (2048)
#define NBL_DPRBAC_SAD_ENCAP_INFO_TABLE_WIDTH (512)
#define NBL_DPRBAC_SAD_ENCAP_INFO_TABLE_DWLEN (16)
union dprbac_sad_encap_info_table_u {
	struct dprbac_sad_encap_info_table {
		u32 dip_addr_arr[4];     /* [127:0] Default:0x0 RW */
		u32 sip_addr_arr[4];     /* [255:128] Default:0x0 RW */
		u32 spi:32;              /* [287:256] Default:0x0 RW */
		u32 dport:16;            /* [303:288] Default:0x0 RW */
		u32 nat_flag:1;          /* [304] Default:0x0 RW */
		u32 rsv:15;              /* [511:305] Default:0x0 RO */
		u32 rsv_arr[6];          /* [511:305] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DPRBAC_SAD_ENCAP_INFO_TABLE_DWLEN];
} __packed;
#define NBL_DPRBAC_SAD_ENCAP_INFO_TABLE_REG(r) (NBL_DPRBAC_SAD_ENCAP_INFO_TABLE_ADDR + \
		(NBL_DPRBAC_SAD_ENCAP_INFO_TABLE_DWLEN * 4) * (r))

#endif
