// Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#ifndef NBL_CTRLQ_HOST_H
#define NBL_CTRLQ_HOST_H 1

#include <linux/types.h>

#define NBL_CTRLQ_HOST_BASE (0x00F8C000)

#define NBL_CTRLQ_HOST_INT_STATUS_ADDR  (0xf8c000)
#define NBL_CTRLQ_HOST_INT_STATUS_DEPTH (1)
#define NBL_CTRLQ_HOST_INT_STATUS_WIDTH (32)
#define NBL_CTRLQ_HOST_INT_STATUS_DWLEN (1)
union ctrlq_host_int_status_u {
	struct ctrlq_host_int_status {
		u32 fatal_err:1;         /* [00:00] Default:0x0 RWC */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 RWC */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 RWC */
		u32 rsv5:1;              /* [03:03] Default:0x0 RO */
		u32 cif_err:1;           /* [04:04] Default:0x0 RWC */
		u32 rsv4:1;              /* [05:05] Default:0x0 RO */
		u32 rsv3:1;              /* [06:06] Default:0x0 RO */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 RWC */
		u32 rsv2:1;              /* [08:08] Default:0x0 RO */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_INT_STATUS_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_INT_MASK_ADDR  (0xf8c004)
#define NBL_CTRLQ_HOST_INT_MASK_DEPTH (1)
#define NBL_CTRLQ_HOST_INT_MASK_WIDTH (32)
#define NBL_CTRLQ_HOST_INT_MASK_DWLEN (1)
union ctrlq_host_int_mask_u {
	struct ctrlq_host_int_mask {
		u32 fatal_err:1;         /* [00:00] Default:0x0 RW */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 RW */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 RW */
		u32 rsv5:1;              /* [03:03] Default:0x0 RO */
		u32 cif_err:1;           /* [04:04] Default:0x0 RW */
		u32 rsv4:1;              /* [05:05] Default:0x0 RO */
		u32 rsv3:1;              /* [06:06] Default:0x0 RO */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 RW */
		u32 rsv2:1;              /* [08:08] Default:0x0 RO */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_INT_MASK_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_INT_SET_ADDR  (0xf8c008)
#define NBL_CTRLQ_HOST_INT_SET_DEPTH (1)
#define NBL_CTRLQ_HOST_INT_SET_WIDTH (32)
#define NBL_CTRLQ_HOST_INT_SET_DWLEN (1)
union ctrlq_host_int_set_u {
	struct ctrlq_host_int_set {
		u32 fatal_err:1;         /* [00:00] Default:0x0 WO */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 WO */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 WO */
		u32 rsv5:1;              /* [03:03] Default:0x0 RO */
		u32 cif_err:1;           /* [04:04] Default:0x0 WO */
		u32 rsv4:1;              /* [05:05] Default:0x0 RO */
		u32 rsv3:1;              /* [06:06] Default:0x0 RO */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 WO */
		u32 rsv2:1;              /* [08:08] Default:0x0 RO */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_INT_SET_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_INIT_DONE_ADDR  (0xf8c00c)
#define NBL_CTRLQ_HOST_INIT_DONE_DEPTH (1)
#define NBL_CTRLQ_HOST_INIT_DONE_WIDTH (32)
#define NBL_CTRLQ_HOST_INIT_DONE_DWLEN (1)
union ctrlq_host_init_done_u {
	struct ctrlq_host_init_done {
		u32 done:1;              /* [00:00] Default:0x0 RO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_INIT_DONE_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_CIF_ERR_INFO_ADDR  (0xf8c040)
#define NBL_CTRLQ_HOST_CIF_ERR_INFO_DEPTH (1)
#define NBL_CTRLQ_HOST_CIF_ERR_INFO_WIDTH (32)
#define NBL_CTRLQ_HOST_CIF_ERR_INFO_DWLEN (1)
union ctrlq_host_cif_err_info_u {
	struct ctrlq_host_cif_err_info {
		u32 addr:30;             /* [29:00] Default:0x0 RO */
		u32 wr_err:1;            /* [30:30] Default:0x0 RO */
		u32 ucor_err:1;          /* [31:31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_CIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_CAR_CTRL_ADDR  (0xf8c100)
#define NBL_CTRLQ_HOST_CAR_CTRL_DEPTH (1)
#define NBL_CTRLQ_HOST_CAR_CTRL_WIDTH (32)
#define NBL_CTRLQ_HOST_CAR_CTRL_DWLEN (1)
union ctrlq_host_car_ctrl_u {
	struct ctrlq_host_car_ctrl {
		u32 sctr_car:1;          /* [00:00] Default:0x1 RW */
		u32 rctr_car:1;          /* [01:01] Default:0x1 RW */
		u32 rc_car:1;            /* [02:02] Default:0x1 RW */
		u32 tbl_rc_car:1;        /* [03:03] Default:0x1 RW */
		u32 rsv:28;              /* [31:04] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_CAR_CTRL_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_QUEUE_SIZE_ADDR  (0xf8c200)
#define NBL_CTRLQ_HOST_QUEUE_SIZE_DEPTH (1)
#define NBL_CTRLQ_HOST_QUEUE_SIZE_WIDTH (32)
#define NBL_CTRLQ_HOST_QUEUE_SIZE_DWLEN (1)
union ctrlq_host_queue_size_u {
	struct ctrlq_host_queue_size {
		u32 mask:16;             /* [15:0] Default:0x0 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_QUEUE_SIZE_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_QUEUE_BASE_ADDR_ADDR  (0xf8c204)
#define NBL_CTRLQ_HOST_QUEUE_BASE_ADDR_DEPTH (1)
#define NBL_CTRLQ_HOST_QUEUE_BASE_ADDR_WIDTH (64)
#define NBL_CTRLQ_HOST_QUEUE_BASE_ADDR_DWLEN (2)
union ctrlq_host_queue_base_addr_u {
	struct ctrlq_host_queue_base_addr {
		u32 val_arr[2];          /* [63:00] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_QUEUE_BASE_ADDR_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_QUEUE_RESET_ADDR  (0xf8c20c)
#define NBL_CTRLQ_HOST_QUEUE_RESET_DEPTH (1)
#define NBL_CTRLQ_HOST_QUEUE_RESET_WIDTH (32)
#define NBL_CTRLQ_HOST_QUEUE_RESET_DWLEN (1)
union ctrlq_host_queue_reset_u {
	struct ctrlq_host_queue_reset {
		u32 vld:1;               /* [00:00] Default:0x0 WO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_QUEUE_RESET_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_QUEUE_NOTIFY_ADDR  (0xf8c210)
#define NBL_CTRLQ_HOST_QUEUE_NOTIFY_DEPTH (1)
#define NBL_CTRLQ_HOST_QUEUE_NOTIFY_WIDTH (32)
#define NBL_CTRLQ_HOST_QUEUE_NOTIFY_DWLEN (1)
union ctrlq_host_queue_notify_u {
	struct ctrlq_host_queue_notify {
		u32 vld:1;               /* [00:00] Default:0x0 WO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_QUEUE_NOTIFY_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_BDF_ADDR  (0xf8c214)
#define NBL_CTRLQ_HOST_BDF_DEPTH (1)
#define NBL_CTRLQ_HOST_BDF_WIDTH (32)
#define NBL_CTRLQ_HOST_BDF_DWLEN (1)
union ctrlq_host_bdf_u {
	struct ctrlq_host_bdf {
		u32 bdf:16;              /* [15:0] Default:0x0 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_BDF_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_INTTERUPT_ADDR  (0xf8c218)
#define NBL_CTRLQ_HOST_INTTERUPT_DEPTH (1)
#define NBL_CTRLQ_HOST_INTTERUPT_WIDTH (32)
#define NBL_CTRLQ_HOST_INTTERUPT_DWLEN (1)
union ctrlq_host_intterupt_u {
	struct ctrlq_host_intterupt {
		u32 en:1;                /* [0] Default:0x0 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_INTTERUPT_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_MSIX_ADDR  (0xf8c21c)
#define NBL_CTRLQ_HOST_MSIX_DEPTH (1)
#define NBL_CTRLQ_HOST_MSIX_WIDTH (32)
#define NBL_CTRLQ_HOST_MSIX_DWLEN (1)
union ctrlq_host_msix_u {
	struct ctrlq_host_msix {
		u32 idx:16;              /* [15:0] Default:0x0 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_MSIX_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_QUEUE_STATE_BUSY_ADDR  (0xf8c900)
#define NBL_CTRLQ_HOST_QUEUE_STATE_BUSY_DEPTH (1)
#define NBL_CTRLQ_HOST_QUEUE_STATE_BUSY_WIDTH (32)
#define NBL_CTRLQ_HOST_QUEUE_STATE_BUSY_DWLEN (1)
union ctrlq_host_queue_state_busy_u {
	struct ctrlq_host_queue_state_busy {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_QUEUE_STATE_BUSY_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_DQDESC_DESC0_ADDR  (0xf8c914)
#define NBL_CTRLQ_HOST_DQDESC_DESC0_DEPTH (1)
#define NBL_CTRLQ_HOST_DQDESC_DESC0_WIDTH (32)
#define NBL_CTRLQ_HOST_DQDESC_DESC0_DWLEN (1)
union ctrlq_host_dqdesc_desc0_u {
	struct ctrlq_host_dqdesc_desc0 {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_DQDESC_DESC0_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_DQDESC_DESC1_ADDR  (0xf8c918)
#define NBL_CTRLQ_HOST_DQDESC_DESC1_DEPTH (1)
#define NBL_CTRLQ_HOST_DQDESC_DESC1_WIDTH (32)
#define NBL_CTRLQ_HOST_DQDESC_DESC1_DWLEN (1)
union ctrlq_host_dqdesc_desc1_u {
	struct ctrlq_host_dqdesc_desc1 {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_DQDESC_DESC1_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_DQDESC_DESC2_ADDR  (0xf8c91c)
#define NBL_CTRLQ_HOST_DQDESC_DESC2_DEPTH (1)
#define NBL_CTRLQ_HOST_DQDESC_DESC2_WIDTH (32)
#define NBL_CTRLQ_HOST_DQDESC_DESC2_DWLEN (1)
union ctrlq_host_dqdesc_desc2_u {
	struct ctrlq_host_dqdesc_desc2 {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_DQDESC_DESC2_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_DQDESC_DESC3_ADDR  (0xf8c920)
#define NBL_CTRLQ_HOST_DQDESC_DESC3_DEPTH (1)
#define NBL_CTRLQ_HOST_DQDESC_DESC3_WIDTH (32)
#define NBL_CTRLQ_HOST_DQDESC_DESC3_DWLEN (1)
union ctrlq_host_dqdesc_desc3_u {
	struct ctrlq_host_dqdesc_desc3 {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_DQDESC_DESC3_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_DQDESC_DESC4_ADDR  (0xf8c924)
#define NBL_CTRLQ_HOST_DQDESC_DESC4_DEPTH (1)
#define NBL_CTRLQ_HOST_DQDESC_DESC4_WIDTH (32)
#define NBL_CTRLQ_HOST_DQDESC_DESC4_DWLEN (1)
union ctrlq_host_dqdesc_desc4_u {
	struct ctrlq_host_dqdesc_desc4 {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_DQDESC_DESC4_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_DQDESC_DESC5_ADDR  (0xf8c928)
#define NBL_CTRLQ_HOST_DQDESC_DESC5_DEPTH (1)
#define NBL_CTRLQ_HOST_DQDESC_DESC5_WIDTH (32)
#define NBL_CTRLQ_HOST_DQDESC_DESC5_DWLEN (1)
union ctrlq_host_dqdesc_desc5_u {
	struct ctrlq_host_dqdesc_desc5 {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_DQDESC_DESC5_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_DQDESC_DESC6_ADDR  (0xf8c92c)
#define NBL_CTRLQ_HOST_DQDESC_DESC6_DEPTH (1)
#define NBL_CTRLQ_HOST_DQDESC_DESC6_WIDTH (32)
#define NBL_CTRLQ_HOST_DQDESC_DESC6_DWLEN (1)
union ctrlq_host_dqdesc_desc6_u {
	struct ctrlq_host_dqdesc_desc6 {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_DQDESC_DESC6_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_DQDESC_DESC7_ADDR  (0xf8c930)
#define NBL_CTRLQ_HOST_DQDESC_DESC7_DEPTH (1)
#define NBL_CTRLQ_HOST_DQDESC_DESC7_WIDTH (32)
#define NBL_CTRLQ_HOST_DQDESC_DESC7_DWLEN (1)
union ctrlq_host_dqdesc_desc7_u {
	struct ctrlq_host_dqdesc_desc7 {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_DQDESC_DESC7_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_H2EDMA_RD_ACK_REQ_ADDR  (0xf8c938)
#define NBL_CTRLQ_HOST_H2EDMA_RD_ACK_REQ_DEPTH (1)
#define NBL_CTRLQ_HOST_H2EDMA_RD_ACK_REQ_WIDTH (32)
#define NBL_CTRLQ_HOST_H2EDMA_RD_ACK_REQ_DWLEN (1)
union ctrlq_host_h2edma_rd_ack_req_u {
	struct ctrlq_host_h2edma_rd_ack_req {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_H2EDMA_RD_ACK_REQ_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_H2EDMA_RD_RVLD_EOB_ADDR  (0xf8c93c)
#define NBL_CTRLQ_HOST_H2EDMA_RD_RVLD_EOB_DEPTH (1)
#define NBL_CTRLQ_HOST_H2EDMA_RD_RVLD_EOB_WIDTH (32)
#define NBL_CTRLQ_HOST_H2EDMA_RD_RVLD_EOB_DWLEN (1)
union ctrlq_host_h2edma_rd_rvld_eob_u {
	struct ctrlq_host_h2edma_rd_rvld_eob {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_H2EDMA_RD_RVLD_EOB_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_H2EDMA_WR_ACK_REQ_ADDR  (0xf8c940)
#define NBL_CTRLQ_HOST_H2EDMA_WR_ACK_REQ_DEPTH (1)
#define NBL_CTRLQ_HOST_H2EDMA_WR_ACK_REQ_WIDTH (32)
#define NBL_CTRLQ_HOST_H2EDMA_WR_ACK_REQ_DWLEN (1)
union ctrlq_host_h2edma_wr_ack_req_u {
	struct ctrlq_host_h2edma_wr_ack_req {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_H2EDMA_WR_ACK_REQ_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_H2EDMA_WR_WVLD_EOB_ADDR  (0xf8c944)
#define NBL_CTRLQ_HOST_H2EDMA_WR_WVLD_EOB_DEPTH (1)
#define NBL_CTRLQ_HOST_H2EDMA_WR_WVLD_EOB_WIDTH (32)
#define NBL_CTRLQ_HOST_H2EDMA_WR_WVLD_EOB_DWLEN (1)
union ctrlq_host_h2edma_wr_wvld_eob_u {
	struct ctrlq_host_h2edma_wr_wvld_eob {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_H2EDMA_WR_WVLD_EOB_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_H2EDMA_WR1_ACK_REQ_ADDR  (0xf8c948)
#define NBL_CTRLQ_HOST_H2EDMA_WR1_ACK_REQ_DEPTH (1)
#define NBL_CTRLQ_HOST_H2EDMA_WR1_ACK_REQ_WIDTH (32)
#define NBL_CTRLQ_HOST_H2EDMA_WR1_ACK_REQ_DWLEN (1)
union ctrlq_host_h2edma_wr1_ack_req_u {
	struct ctrlq_host_h2edma_wr1_ack_req {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_H2EDMA_WR1_ACK_REQ_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_H2EDMA_WR1_WVLD_EOB_ADDR  (0xf8c94c)
#define NBL_CTRLQ_HOST_H2EDMA_WR1_WVLD_EOB_DEPTH (1)
#define NBL_CTRLQ_HOST_H2EDMA_WR1_WVLD_EOB_WIDTH (32)
#define NBL_CTRLQ_HOST_H2EDMA_WR1_WVLD_EOB_DWLEN (1)
union ctrlq_host_h2edma_wr1_wvld_eob_u {
	struct ctrlq_host_h2edma_wr1_wvld_eob {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_H2EDMA_WR1_WVLD_EOB_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_E2HDMA_RD_ACK_REQ_ADDR  (0xf8c958)
#define NBL_CTRLQ_HOST_E2HDMA_RD_ACK_REQ_DEPTH (1)
#define NBL_CTRLQ_HOST_E2HDMA_RD_ACK_REQ_WIDTH (32)
#define NBL_CTRLQ_HOST_E2HDMA_RD_ACK_REQ_DWLEN (1)
union ctrlq_host_e2hdma_rd_ack_req_u {
	struct ctrlq_host_e2hdma_rd_ack_req {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_E2HDMA_RD_ACK_REQ_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_E2HDMA_RD_RVLD_EOB_ADDR  (0xf8c95c)
#define NBL_CTRLQ_HOST_E2HDMA_RD_RVLD_EOB_DEPTH (1)
#define NBL_CTRLQ_HOST_E2HDMA_RD_RVLD_EOB_WIDTH (32)
#define NBL_CTRLQ_HOST_E2HDMA_RD_RVLD_EOB_DWLEN (1)
union ctrlq_host_e2hdma_rd_rvld_eob_u {
	struct ctrlq_host_e2hdma_rd_rvld_eob {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_E2HDMA_RD_RVLD_EOB_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_E2HDMA_WR_ACK_REQ_ADDR  (0xf8c960)
#define NBL_CTRLQ_HOST_E2HDMA_WR_ACK_REQ_DEPTH (1)
#define NBL_CTRLQ_HOST_E2HDMA_WR_ACK_REQ_WIDTH (32)
#define NBL_CTRLQ_HOST_E2HDMA_WR_ACK_REQ_DWLEN (1)
union ctrlq_host_e2hdma_wr_ack_req_u {
	struct ctrlq_host_e2hdma_wr_ack_req {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_E2HDMA_WR_ACK_REQ_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_E2HDMA_WR_WVLD_EOB_ADDR  (0xf8c964)
#define NBL_CTRLQ_HOST_E2HDMA_WR_WVLD_EOB_DEPTH (1)
#define NBL_CTRLQ_HOST_E2HDMA_WR_WVLD_EOB_WIDTH (32)
#define NBL_CTRLQ_HOST_E2HDMA_WR_WVLD_EOB_DWLEN (1)
union ctrlq_host_e2hdma_wr_wvld_eob_u {
	struct ctrlq_host_e2hdma_wr_wvld_eob {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_E2HDMA_WR_WVLD_EOB_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_E2HDMA_WR1_ACK_REQ_ADDR  (0xf8c968)
#define NBL_CTRLQ_HOST_E2HDMA_WR1_ACK_REQ_DEPTH (1)
#define NBL_CTRLQ_HOST_E2HDMA_WR1_ACK_REQ_WIDTH (32)
#define NBL_CTRLQ_HOST_E2HDMA_WR1_ACK_REQ_DWLEN (1)
union ctrlq_host_e2hdma_wr1_ack_req_u {
	struct ctrlq_host_e2hdma_wr1_ack_req {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_E2HDMA_WR1_ACK_REQ_DWLEN];
} __packed;

#define NBL_CTRLQ_HOST_E2HDMA_WR1_WVLD_EOB_ADDR  (0xf8c96c)
#define NBL_CTRLQ_HOST_E2HDMA_WR1_WVLD_EOB_DEPTH (1)
#define NBL_CTRLQ_HOST_E2HDMA_WR1_WVLD_EOB_WIDTH (32)
#define NBL_CTRLQ_HOST_E2HDMA_WR1_WVLD_EOB_DWLEN (1)
union ctrlq_host_e2hdma_wr1_wvld_eob_u {
	struct ctrlq_host_e2hdma_wr1_wvld_eob {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_HOST_E2HDMA_WR1_WVLD_EOB_DWLEN];
} __packed;

#endif
