// Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#ifndef NBL_USTAT_H
#define NBL_USTAT_H 1

#include <linux/types.h>

#define NBL_USTAT_BASE (0x0011C000)

#define NBL_USTAT_INT_STATUS_ADDR  (0x11c000)
#define NBL_USTAT_INT_STATUS_DEPTH (1)
#define NBL_USTAT_INT_STATUS_WIDTH (32)
#define NBL_USTAT_INT_STATUS_DWLEN (1)
union ustat_int_status_u {
	struct ustat_int_status {
		u32 ucor_err:1;          /* [0] Default:0x0 RWC */
		u32 cor_err:1;           /* [1] Default:0x0 RWC */
		u32 fifo_uflw_err:1;     /* [2] Default:0x0 RWC */
		u32 fifo_dflw_err:1;     /* [3] Default:0x0 RWC */
		u32 cif_err:1;           /* [4] Default:0x0 RWC */
		u32 parity_err:1;        /* [5] Default:0x0 RWC */
		u32 stat_type_err:1;     /* [6] Default:0x0 RWC */
		u32 tbl_conflict_err:1;  /* [7] Default:0X0 RWC */
		u32 rsv:24;              /* [31:8] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_INT_STATUS_DWLEN];
} __packed;

#define NBL_USTAT_INT_MASK_ADDR  (0x11c004)
#define NBL_USTAT_INT_MASK_DEPTH (1)
#define NBL_USTAT_INT_MASK_WIDTH (32)
#define NBL_USTAT_INT_MASK_DWLEN (1)
union ustat_int_mask_u {
	struct ustat_int_mask {
		u32 ucor_err:1;          /* [0] Default:0x0 RW */
		u32 cor_err:1;           /* [1] Default:0x0 RW */
		u32 fifo_uflw_err:1;     /* [2] Default:0x0 RW */
		u32 fifo_dflw_err:1;     /* [3] Default:0x0 RW */
		u32 cif_err:1;           /* [4] Default:0x0 RW */
		u32 parity_err:1;        /* [5] Default:0x0 RW */
		u32 stat_type_err:1;     /* [6] Default:0x0 RW */
		u32 tbl_conflict_err:1;  /* [7] Default:0X0 RW */
		u32 rsv:24;              /* [31:8] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_INT_MASK_DWLEN];
} __packed;

#define NBL_USTAT_INT_SET_ADDR  (0x11c008)
#define NBL_USTAT_INT_SET_DEPTH (1)
#define NBL_USTAT_INT_SET_WIDTH (32)
#define NBL_USTAT_INT_SET_DWLEN (1)
union ustat_int_set_u {
	struct ustat_int_set {
		u32 ucor_err:1;          /* [0] Default:0x0 WO */
		u32 cor_err:1;           /* [1] Default:0x0 WO */
		u32 fifo_uflw_err:1;     /* [2] Default:0x0 WO */
		u32 fifo_dflw_err:1;     /* [3] Default:0x0 WO */
		u32 cif_err:1;           /* [4] Default:0x0 WO */
		u32 parity_err:1;        /* [5] Default:0x0 WO */
		u32 stat_type_err:1;     /* [6] Default:0x0 WO */
		u32 tbl_conflict_err:1;  /* [7] Default:0x0 WO */
		u32 rsv:24;              /* [31:8] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_INT_SET_DWLEN];
} __packed;

#define NBL_USTAT_COR_ERR_INFO_ADDR  (0x11c00c)
#define NBL_USTAT_COR_ERR_INFO_DEPTH (1)
#define NBL_USTAT_COR_ERR_INFO_WIDTH (32)
#define NBL_USTAT_COR_ERR_INFO_DWLEN (1)
union ustat_cor_err_info_u {
	struct ustat_cor_err_info {
		u32 addr:10;             /* [9:0] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_COR_ERR_INFO_DWLEN];
} __packed;

#define NBL_USTAT_PARITY_ERR_INFO_ADDR  (0x11c01c)
#define NBL_USTAT_PARITY_ERR_INFO_DEPTH (1)
#define NBL_USTAT_PARITY_ERR_INFO_WIDTH (32)
#define NBL_USTAT_PARITY_ERR_INFO_DWLEN (1)
union ustat_parity_err_info_u {
	struct ustat_parity_err_info {
		u32 ram_id:4;            /* [3:0] Default:0x0 RO */
		u32 addr:10;             /* [13:4] Default:0x0 RO */
		u32 rsv:18;              /* [31:14] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_PARITY_ERR_INFO_DWLEN];
} __packed;

#define NBL_USTAT_CIF_ERR_INFO_ADDR  (0x11c024)
#define NBL_USTAT_CIF_ERR_INFO_DEPTH (1)
#define NBL_USTAT_CIF_ERR_INFO_WIDTH (32)
#define NBL_USTAT_CIF_ERR_INFO_DWLEN (1)
union ustat_cif_err_info_u {
	struct ustat_cif_err_info {
		u32 addr:30;             /* [29:0] Default:0x0 RO */
		u32 wr_err:1;            /* [30] Default:0x0 RO */
		u32 ucor_err:1;          /* [31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_CIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_USTAT_TBL_CONFLICT_ERR_INFO_ADDR  (0x11c030)
#define NBL_USTAT_TBL_CONFLICT_ERR_INFO_DEPTH (1)
#define NBL_USTAT_TBL_CONFLICT_ERR_INFO_WIDTH (32)
#define NBL_USTAT_TBL_CONFLICT_ERR_INFO_DWLEN (1)
union ustat_tbl_conflict_err_info_u {
	struct ustat_tbl_conflict_err_info {
		u32 tbl_id:4;            /* [3:0] Default:0x0 RO */
		u32 rsv:28;              /* [31:4] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_TBL_CONFLICT_ERR_INFO_DWLEN];
} __packed;

#define NBL_USTAT_CAR_CTRL_ADDR  (0x11c100)
#define NBL_USTAT_CAR_CTRL_DEPTH (1)
#define NBL_USTAT_CAR_CTRL_WIDTH (32)
#define NBL_USTAT_CAR_CTRL_DWLEN (1)
union ustat_car_ctrl_u {
	struct ustat_car_ctrl {
		u32 sctr_car:1;          /* [0] Default:0x0 RW */
		u32 rctr_car:1;          /* [1] Default:0x0 RW */
		u32 rc_car:1;            /* [2] Default:0x1 RW */
		u32 tbl_rc_car:1;        /* [3] Default:0x0 RW */
		u32 rsv:28;              /* [31:4] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_CAR_CTRL_DWLEN];
} __packed;

#define NBL_USTAT_INIT_START_ADDR  (0x11c104)
#define NBL_USTAT_INIT_START_DEPTH (1)
#define NBL_USTAT_INIT_START_WIDTH (32)
#define NBL_USTAT_INIT_START_DWLEN (1)
union ustat_init_start_u {
	struct ustat_init_start {
		u32 init_start:1;        /* [0] Default:0x0 WO */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_INIT_START_DWLEN];
} __packed;

#define NBL_USTAT_CPU_READ_CLR_ADDR  (0x11c108)
#define NBL_USTAT_CPU_READ_CLR_DEPTH (1)
#define NBL_USTAT_CPU_READ_CLR_WIDTH (32)
#define NBL_USTAT_CPU_READ_CLR_DWLEN (1)
union ustat_cpu_read_clr_u {
	struct ustat_cpu_read_clr {
		u32 cpu_clr:1;           /* [0] Default:0x0 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_CPU_READ_CLR_DWLEN];
} __packed;

#define NBL_USTAT_GLB_CLR_ADDR  (0x11c10c)
#define NBL_USTAT_GLB_CLR_DEPTH (1)
#define NBL_USTAT_GLB_CLR_WIDTH (32)
#define NBL_USTAT_GLB_CLR_DWLEN (1)
union ustat_glb_clr_u {
	struct ustat_glb_clr {
		u32 glb_clr:1;           /* [0] Default:0x0 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_GLB_CLR_DWLEN];
} __packed;

#define NBL_USTAT_SEP_CLR_ADDR  (0x11c110)
#define NBL_USTAT_SEP_CLR_DEPTH (1)
#define NBL_USTAT_SEP_CLR_WIDTH (32)
#define NBL_USTAT_SEP_CLR_DWLEN (1)
union ustat_sep_clr_u {
	struct ustat_sep_clr {
		u32 vsi_tbl_clr:1;       /* [0] Default:0x0 RW */
		u32 ptype_tbl_clr:1;     /* [1] Default:0x0 RW */
		u32 err_code_tbl_clr:1;  /* [2] Default:0x0 RW */
		u32 rsv:29;              /* [31:3] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_SEP_CLR_DWLEN];
} __packed;

#define NBL_USTAT_CFG_TEST_ADDR  (0x11c118)
#define NBL_USTAT_CFG_TEST_DEPTH (1)
#define NBL_USTAT_CFG_TEST_WIDTH (32)
#define NBL_USTAT_CFG_TEST_DWLEN (1)
union ustat_cfg_test_u {
	struct ustat_cfg_test {
		u32 test:32;             /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_USTAT_CFG_TEST_DWLEN];
} __packed;

#define NBL_USTAT_INIT_DONE_ADDR  (0x11c200)
#define NBL_USTAT_INIT_DONE_DEPTH (1)
#define NBL_USTAT_INIT_DONE_WIDTH (32)
#define NBL_USTAT_INIT_DONE_DWLEN (1)
union ustat_init_done_u {
	struct ustat_init_done {
		u32 init_done:1;         /* [0] Default:0x0 RO */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_INIT_DONE_DWLEN];
} __packed;

#define NBL_USTAT_GLB_CLR_DONE_ADDR  (0x11c204)
#define NBL_USTAT_GLB_CLR_DONE_DEPTH (1)
#define NBL_USTAT_GLB_CLR_DONE_WIDTH (32)
#define NBL_USTAT_GLB_CLR_DONE_DWLEN (1)
union ustat_glb_clr_done_u {
	struct ustat_glb_clr_done {
		u32 glb_clr_done:1;      /* [0] Default:0x0 RO */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_GLB_CLR_DONE_DWLEN];
} __packed;

#define NBL_USTAT_SEP_CLR_DONE_ADDR  (0x11c208)
#define NBL_USTAT_SEP_CLR_DONE_DEPTH (1)
#define NBL_USTAT_SEP_CLR_DONE_WIDTH (32)
#define NBL_USTAT_SEP_CLR_DONE_DWLEN (1)
union ustat_sep_clr_done_u {
	struct ustat_sep_clr_done {
		u32 vsi_tbl_done:1;      /* [0] Default:0x0 RO */
		u32 ptype_tbl_done:1;    /* [1] Default:0x0 RO */
		u32 err_code_tbl_done:1; /* [2] Default:0x0 RO */
		u32 rsv:29;              /* [31:3] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_SEP_CLR_DONE_DWLEN];
} __packed;

#define NBL_USTAT_ERR_CODE_STAT_ETH0_ADDR  (0x11c400)
#define NBL_USTAT_ERR_CODE_STAT_ETH0_DEPTH (16)
#define NBL_USTAT_ERR_CODE_STAT_ETH0_WIDTH (32)
#define NBL_USTAT_ERR_CODE_STAT_ETH0_DWLEN (1)
union ustat_err_code_stat_eth0_u {
	struct ustat_err_code_stat_eth0 {
		u32 fwd_pkt_cnt:32;      /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_ERR_CODE_STAT_ETH0_DWLEN];
} __packed;
#define NBL_USTAT_ERR_CODE_STAT_ETH0_REG(r) (NBL_USTAT_ERR_CODE_STAT_ETH0_ADDR + \
		(NBL_USTAT_ERR_CODE_STAT_ETH0_DWLEN * 4) * (r))

#define NBL_USTAT_ERR_CODE_STAT_ETH1_ADDR  (0x11c500)
#define NBL_USTAT_ERR_CODE_STAT_ETH1_DEPTH (16)
#define NBL_USTAT_ERR_CODE_STAT_ETH1_WIDTH (32)
#define NBL_USTAT_ERR_CODE_STAT_ETH1_DWLEN (1)
union ustat_err_code_stat_eth1_u {
	struct ustat_err_code_stat_eth1 {
		u32 fwd_pkt_cnt:32;      /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_ERR_CODE_STAT_ETH1_DWLEN];
} __packed;
#define NBL_USTAT_ERR_CODE_STAT_ETH1_REG(r) (NBL_USTAT_ERR_CODE_STAT_ETH1_ADDR + \
		(NBL_USTAT_ERR_CODE_STAT_ETH1_DWLEN * 4) * (r))

#define NBL_USTAT_ERR_CODE_STAT_ETH2_ADDR  (0x11c600)
#define NBL_USTAT_ERR_CODE_STAT_ETH2_DEPTH (16)
#define NBL_USTAT_ERR_CODE_STAT_ETH2_WIDTH (32)
#define NBL_USTAT_ERR_CODE_STAT_ETH2_DWLEN (1)
union ustat_err_code_stat_eth2_u {
	struct ustat_err_code_stat_eth2 {
		u32 fwd_pkt_cnt:32;      /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_ERR_CODE_STAT_ETH2_DWLEN];
} __packed;
#define NBL_USTAT_ERR_CODE_STAT_ETH2_REG(r) (NBL_USTAT_ERR_CODE_STAT_ETH2_ADDR + \
		(NBL_USTAT_ERR_CODE_STAT_ETH2_DWLEN * 4) * (r))

#define NBL_USTAT_ERR_CODE_STAT_ETH3_ADDR  (0x11c700)
#define NBL_USTAT_ERR_CODE_STAT_ETH3_DEPTH (16)
#define NBL_USTAT_ERR_CODE_STAT_ETH3_WIDTH (32)
#define NBL_USTAT_ERR_CODE_STAT_ETH3_DWLEN (1)
union ustat_err_code_stat_eth3_u {
	struct ustat_err_code_stat_eth3 {
		u32 fwd_pkt_cnt:32;      /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_ERR_CODE_STAT_ETH3_DWLEN];
} __packed;
#define NBL_USTAT_ERR_CODE_STAT_ETH3_REG(r) (NBL_USTAT_ERR_CODE_STAT_ETH3_ADDR + \
		(NBL_USTAT_ERR_CODE_STAT_ETH3_DWLEN * 4) * (r))

#define NBL_USTAT_ERR_CODE_STAT_LOOPBACK_ADDR  (0x11c800)
#define NBL_USTAT_ERR_CODE_STAT_LOOPBACK_DEPTH (16)
#define NBL_USTAT_ERR_CODE_STAT_LOOPBACK_WIDTH (32)
#define NBL_USTAT_ERR_CODE_STAT_LOOPBACK_DWLEN (1)
union ustat_err_code_stat_loopback_u {
	struct ustat_err_code_stat_loopback {
		u32 fwd_pkt_cnt:32;      /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_ERR_CODE_STAT_LOOPBACK_DWLEN];
} __packed;
#define NBL_USTAT_ERR_CODE_STAT_LOOPBACK_REG(r) (NBL_USTAT_ERR_CODE_STAT_LOOPBACK_ADDR + \
		(NBL_USTAT_ERR_CODE_STAT_LOOPBACK_DWLEN * 4) * (r))

#define NBL_USTAT_PTYPE_STAT_ETH0_ADDR  (0x11d000)
#define NBL_USTAT_PTYPE_STAT_ETH0_DEPTH (256)
#define NBL_USTAT_PTYPE_STAT_ETH0_WIDTH (32)
#define NBL_USTAT_PTYPE_STAT_ETH0_DWLEN (1)
union ustat_ptype_stat_eth0_u {
	struct ustat_ptype_stat_eth0 {
		u32 fwd_pkt_cnt:32;      /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_PTYPE_STAT_ETH0_DWLEN];
} __packed;
#define NBL_USTAT_PTYPE_STAT_ETH0_REG(r) (NBL_USTAT_PTYPE_STAT_ETH0_ADDR + \
		(NBL_USTAT_PTYPE_STAT_ETH0_DWLEN * 4) * (r))

#define NBL_USTAT_PTYPE_STAT_ETH1_ADDR  (0x11d400)
#define NBL_USTAT_PTYPE_STAT_ETH1_DEPTH (256)
#define NBL_USTAT_PTYPE_STAT_ETH1_WIDTH (32)
#define NBL_USTAT_PTYPE_STAT_ETH1_DWLEN (1)
union ustat_ptype_stat_eth1_u {
	struct ustat_ptype_stat_eth1 {
		u32 fwd_pkt_cnt:32;      /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_PTYPE_STAT_ETH1_DWLEN];
} __packed;
#define NBL_USTAT_PTYPE_STAT_ETH1_REG(r) (NBL_USTAT_PTYPE_STAT_ETH1_ADDR + \
		(NBL_USTAT_PTYPE_STAT_ETH1_DWLEN * 4) * (r))

#define NBL_USTAT_PTYPE_STAT_ETH2_ADDR  (0x11d800)
#define NBL_USTAT_PTYPE_STAT_ETH2_DEPTH (256)
#define NBL_USTAT_PTYPE_STAT_ETH2_WIDTH (32)
#define NBL_USTAT_PTYPE_STAT_ETH2_DWLEN (1)
union ustat_ptype_stat_eth2_u {
	struct ustat_ptype_stat_eth2 {
		u32 fwd_pkt_cnt:32;      /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_PTYPE_STAT_ETH2_DWLEN];
} __packed;
#define NBL_USTAT_PTYPE_STAT_ETH2_REG(r) (NBL_USTAT_PTYPE_STAT_ETH2_ADDR + \
		(NBL_USTAT_PTYPE_STAT_ETH2_DWLEN * 4) * (r))

#define NBL_USTAT_PTYPE_STAT_ETH3_ADDR  (0x11dc00)
#define NBL_USTAT_PTYPE_STAT_ETH3_DEPTH (256)
#define NBL_USTAT_PTYPE_STAT_ETH3_WIDTH (32)
#define NBL_USTAT_PTYPE_STAT_ETH3_DWLEN (1)
union ustat_ptype_stat_eth3_u {
	struct ustat_ptype_stat_eth3 {
		u32 fwd_pkt_cnt:32;      /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_PTYPE_STAT_ETH3_DWLEN];
} __packed;
#define NBL_USTAT_PTYPE_STAT_ETH3_REG(r) (NBL_USTAT_PTYPE_STAT_ETH3_ADDR + \
		(NBL_USTAT_PTYPE_STAT_ETH3_DWLEN * 4) * (r))

#define NBL_USTAT_PTYPE_STAT_LOOPBACK_ADDR  (0x11e000)
#define NBL_USTAT_PTYPE_STAT_LOOPBACK_DEPTH (256)
#define NBL_USTAT_PTYPE_STAT_LOOPBACK_WIDTH (32)
#define NBL_USTAT_PTYPE_STAT_LOOPBACK_DWLEN (1)
union ustat_ptype_stat_loopback_u {
	struct ustat_ptype_stat_loopback {
		u32 fwd_pkt_cnt:32;      /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_PTYPE_STAT_LOOPBACK_DWLEN];
} __packed;
#define NBL_USTAT_PTYPE_STAT_LOOPBACK_REG(r) (NBL_USTAT_PTYPE_STAT_LOOPBACK_ADDR + \
		(NBL_USTAT_PTYPE_STAT_LOOPBACK_DWLEN * 4) * (r))

#define NBL_USTAT_VSI_STAT_ADDR  (0x124000)
#define NBL_USTAT_VSI_STAT_DEPTH (1024)
#define NBL_USTAT_VSI_STAT_WIDTH (128)
#define NBL_USTAT_VSI_STAT_DWLEN (4)
union ustat_vsi_stat_u {
	struct ustat_vsi_stat {
		u32 fwd_byte_cnt_low:32; /* [31:0] Default:0x0 RO */
		u32 fwd_byte_cnt_high:32; /* [63:32] Default:0x0 RO */
		u32 fwd_pkt_cnt_low:32;  /* [95:64] Default:0x0 RO */
		u32 fwd_pkt_cnt_high:32; /* [127:96] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_USTAT_VSI_STAT_DWLEN];
} __packed;
#define NBL_USTAT_VSI_STAT_REG(r) (NBL_USTAT_VSI_STAT_ADDR + \
		(NBL_USTAT_VSI_STAT_DWLEN * 4) * (r))

#endif
