// Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#ifndef NBL_FIFO_CH_H
#define NBL_FIFO_CH_H 1

#include <linux/types.h>

#define NBL_FIFO_CH_BASE (0x00FAC000)

#define NBL_FIFO_CH_INT_STATUS_ADDR  (0xfac000)
#define NBL_FIFO_CH_INT_STATUS_DEPTH (1)
#define NBL_FIFO_CH_INT_STATUS_WIDTH (32)
#define NBL_FIFO_CH_INT_STATUS_DWLEN (1)
union fifo_ch_int_status_u {
	struct fifo_ch_int_status {
		u32 fatal_err:1;         /* [00:00] Default:0x0 RWC */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 RWC */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 RWC */
		u32 rsv4:1;              /* [03:03] Default:0x0 RO */
		u32 cif_err:1;           /* [04:04] Default:0x0 RWC */
		u32 rsv3:1;              /* [05:05] Default:0x0 RO */
		u32 rsv2:1;              /* [06:06] Default:0x0 RO */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 RWC */
		u32 data_cor_err:1;      /* [08:08] Default:0x0 RWC */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FIFO_CH_INT_STATUS_DWLEN];
} __packed;

#define NBL_FIFO_CH_INT_MASK_ADDR  (0xfac004)
#define NBL_FIFO_CH_INT_MASK_DEPTH (1)
#define NBL_FIFO_CH_INT_MASK_WIDTH (32)
#define NBL_FIFO_CH_INT_MASK_DWLEN (1)
union fifo_ch_int_mask_u {
	struct fifo_ch_int_mask {
		u32 fatal_err:1;         /* [00:00] Default:0x0 RW */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 RW */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 RW */
		u32 rsv4:1;              /* [03:03] Default:0x0 RO */
		u32 cif_err:1;           /* [04:04] Default:0x0 RW */
		u32 rsv3:1;              /* [05:05] Default:0x0 RO */
		u32 rsv2:1;              /* [06:06] Default:0x0 RO */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 RW */
		u32 data_cor_err:1;      /* [08:08] Default:0x0 RW */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FIFO_CH_INT_MASK_DWLEN];
} __packed;

#define NBL_FIFO_CH_INT_SET_ADDR  (0xfac008)
#define NBL_FIFO_CH_INT_SET_DEPTH (1)
#define NBL_FIFO_CH_INT_SET_WIDTH (32)
#define NBL_FIFO_CH_INT_SET_DWLEN (1)
union fifo_ch_int_set_u {
	struct fifo_ch_int_set {
		u32 fatal_err:1;         /* [00:00] Default:0x0 WO */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 WO */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 WO */
		u32 rsv4:1;              /* [03:03] Default:0x0 RO */
		u32 cif_err:1;           /* [04:04] Default:0x0 WO */
		u32 rsv3:1;              /* [05:05] Default:0x0 RO */
		u32 rsv2:1;              /* [06:06] Default:0x0 RO */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 WO */
		u32 data_cor_err:1;      /* [08:08] Default:0x0 WO */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FIFO_CH_INT_SET_DWLEN];
} __packed;

#define NBL_FIFO_CH_INIT_DONE_ADDR  (0xfac00c)
#define NBL_FIFO_CH_INIT_DONE_DEPTH (1)
#define NBL_FIFO_CH_INIT_DONE_WIDTH (32)
#define NBL_FIFO_CH_INIT_DONE_DWLEN (1)
union fifo_ch_init_done_u {
	struct fifo_ch_init_done {
		u32 done:1;              /* [00:00] Default:0x0 RO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FIFO_CH_INIT_DONE_DWLEN];
} __packed;

#define NBL_FIFO_CH_CIF_ERR_INFO_ADDR  (0xfac040)
#define NBL_FIFO_CH_CIF_ERR_INFO_DEPTH (1)
#define NBL_FIFO_CH_CIF_ERR_INFO_WIDTH (32)
#define NBL_FIFO_CH_CIF_ERR_INFO_DWLEN (1)
union fifo_ch_cif_err_info_u {
	struct fifo_ch_cif_err_info {
		u32 addr:30;             /* [29:00] Default:0x0 RO */
		u32 wr_err:1;            /* [30:30] Default:0x0 RO */
		u32 ucor_err:1;          /* [31:31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FIFO_CH_CIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_FIFO_CH_CAR_CTRL_ADDR  (0xfac100)
#define NBL_FIFO_CH_CAR_CTRL_DEPTH (1)
#define NBL_FIFO_CH_CAR_CTRL_WIDTH (32)
#define NBL_FIFO_CH_CAR_CTRL_DWLEN (1)
union fifo_ch_car_ctrl_u {
	struct fifo_ch_car_ctrl {
		u32 sctr_car:1;          /* [00:00] Default:0x1 RW */
		u32 rctr_car:1;          /* [01:01] Default:0x1 RW */
		u32 rc_car:1;            /* [02:02] Default:0x1 RW */
		u32 tbl_rc_car:1;        /* [03:03] Default:0x1 RW */
		u32 rsv:28;              /* [31:04] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FIFO_CH_CAR_CTRL_DWLEN];
} __packed;

#define NBL_FIFO_CH_EMULATOR_READY_ADDR  (0xfac214)
#define NBL_FIFO_CH_EMULATOR_READY_DEPTH (1)
#define NBL_FIFO_CH_EMULATOR_READY_WIDTH (32)
#define NBL_FIFO_CH_EMULATOR_READY_DWLEN (1)
union fifo_ch_emulator_ready_u {
	struct fifo_ch_emulator_ready {
		u32 ecpu_emulater_ready:1; /* [0] Default:0x0 RW */
		u32 rsv1:15;             /* [15:1] Default:0x0 RO */
		u32 debug_flag:8;        /* [23:16] Default:0x0 RW */
		u32 rsv:8;               /* [31:24] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FIFO_CH_EMULATOR_READY_DWLEN];
} __packed;

#define NBL_FIFO_CH_EMULATOR_BIOS_WAIT_ADDR  (0xfac218)
#define NBL_FIFO_CH_EMULATOR_BIOS_WAIT_DEPTH (1)
#define NBL_FIFO_CH_EMULATOR_BIOS_WAIT_WIDTH (32)
#define NBL_FIFO_CH_EMULATOR_BIOS_WAIT_DWLEN (1)
union fifo_ch_emulator_bios_wait_u {
	struct fifo_ch_emulator_bios_wait {
		u32 cnt:8;               /* [7:0] Default:0x0 RW */
		u32 rsv1:8;              /* [15:8] Default:0x0 RO */
		u32 debug_flag:8;        /* [23:16] Default:0x0 RW */
		u32 rsv:8;               /* [31:24] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FIFO_CH_EMULATOR_BIOS_WAIT_DWLEN];
} __packed;

#define NBL_FIFO_CH_SHARE_BUF_ADDR  (0xfac21c)
#define NBL_FIFO_CH_SHARE_BUF_DEPTH (1)
#define NBL_FIFO_CH_SHARE_BUF_WIDTH (32)
#define NBL_FIFO_CH_SHARE_BUF_DWLEN (1)
union fifo_ch_share_buf_u {
	struct fifo_ch_share_buf {
		u32 intr:1;              /* [0:0] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_FIFO_CH_SHARE_BUF_DWLEN];
} __packed;

#define NBL_FIFO_CH_SHARE_RF_ADDR  (0xfac400)
#define NBL_FIFO_CH_SHARE_RF_DEPTH (64)
#define NBL_FIFO_CH_SHARE_RF_WIDTH (32)
#define NBL_FIFO_CH_SHARE_RF_DWLEN (1)
union fifo_ch_share_rf_u {
	struct fifo_ch_share_rf {
		u32 val:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_FIFO_CH_SHARE_RF_DWLEN];
} __packed;
#define NBL_FIFO_CH_SHARE_RF_REG(r) (NBL_FIFO_CH_SHARE_RF_ADDR + \
		(NBL_FIFO_CH_SHARE_RF_DWLEN * 4) * (r))

#endif
