// Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#ifndef NBL_URMUX_H
#define NBL_URMUX_H 1

#include <linux/types.h>

#define NBL_URMUX_BASE (0x00008000)

#define NBL_URMUX_INT_STATUS_ADDR  (0x8000)
#define NBL_URMUX_INT_STATUS_DEPTH (1)
#define NBL_URMUX_INT_STATUS_WIDTH (32)
#define NBL_URMUX_INT_STATUS_DWLEN (1)
union urmux_int_status_u {
	struct urmux_int_status {
		u32 ucor_err:1;          /* [0] Default:0x0 RWC */
		u32 cor_err:1;           /* [1] Default:0x0 RWC */
		u32 fifo_uflw_err:1;     /* [2] Default:0x0 RWC */
		u32 fifo_dflw_err:1;     /* [3] Default:0x0 RWC */
		u32 parity_err:1;        /* [4] Default:0x0 RWC */
		u32 lowp:1;              /* [5] Default:0x0 RWC */
		u32 cif_err:1;           /* [6] Default:0x0 RWC */
		u32 eth0_drop:1;         /* [7] Default:0x0 RWC */
		u32 eth1_drop:1;         /* [8] Default:0x0 RWC */
		u32 eth2_drop:1;         /* [9] Default:0x0 RWC */
		u32 eth3_drop:1;         /* [10] Default:0x0 RWC */
		u32 rsv:21;              /* [31:11] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_URMUX_INT_STATUS_DWLEN];
} __packed;

#define NBL_URMUX_INT_MASK_ADDR  (0x8004)
#define NBL_URMUX_INT_MASK_DEPTH (1)
#define NBL_URMUX_INT_MASK_WIDTH (32)
#define NBL_URMUX_INT_MASK_DWLEN (1)
union urmux_int_mask_u {
	struct urmux_int_mask {
		u32 ucor_err:1;          /* [0] Default:0x0 RW */
		u32 cor_err:1;           /* [1] Default:0x0 RW */
		u32 fifo_uflw_err:1;     /* [2] Default:0x0 RW */
		u32 fifo_dflw_err:1;     /* [3] Default:0x0 RW */
		u32 parity_err:1;        /* [4] Default:0x0 RW */
		u32 lowp:1;              /* [5] Default:0x0 RW */
		u32 cif_err:1;           /* [6] Default:0x0 RW */
		u32 eth0_drop:1;         /* [7] Default:0x0 RW */
		u32 eth1_drop:1;         /* [8] Default:0x0 RW */
		u32 eth2_drop:1;         /* [9] Default:0x0 RW */
		u32 eth3_drop:1;         /* [10] Default:0x0 RW */
		u32 rsv:21;              /* [31:11] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_URMUX_INT_MASK_DWLEN];
} __packed;

#define NBL_URMUX_INT_SET_ADDR  (0x8008)
#define NBL_URMUX_INT_SET_DEPTH (1)
#define NBL_URMUX_INT_SET_WIDTH (32)
#define NBL_URMUX_INT_SET_DWLEN (1)
union urmux_int_set_u {
	struct urmux_int_set {
		u32 ucor_err:1;          /* [0] Default:0x0 WO */
		u32 cor_err:1;           /* [1] Default:0x0 WO */
		u32 fifo_uflw_err:1;     /* [2] Default:0x0 WO */
		u32 fifo_dflw_err:1;     /* [3] Default:0x0 WO */
		u32 parity_err:1;        /* [4] Default:0x0 WO */
		u32 lowp:1;              /* [5] Default:0x0 WO */
		u32 cif_err:1;           /* [6] Default:0x0 WO */
		u32 eth0_drop:1;         /* [7] Default:0x0 WO */
		u32 eth1_drop:1;         /* [8] Default:0x0 WO */
		u32 eth2_drop:1;         /* [9] Default:0x0 WO */
		u32 eth3_drop:1;         /* [10] Default:0x0 WO */
		u32 rsv:21;              /* [31:11] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_URMUX_INT_SET_DWLEN];
} __packed;

#define NBL_URMUX_UCOR_ERR_INFO_ADDR  (0x800c)
#define NBL_URMUX_UCOR_ERR_INFO_DEPTH (1)
#define NBL_URMUX_UCOR_ERR_INFO_WIDTH (32)
#define NBL_URMUX_UCOR_ERR_INFO_DWLEN (1)
union urmux_ucor_err_info_u {
	struct urmux_ucor_err_info {
		u32 ram_addr:28;         /* [27:0] Default:0x0 RO */
		u32 ram_id:4;            /* [31:28] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_URMUX_UCOR_ERR_INFO_DWLEN];
} __packed;

#define NBL_URMUX_COR_ERR_INFO_ADDR  (0x8014)
#define NBL_URMUX_COR_ERR_INFO_DEPTH (1)
#define NBL_URMUX_COR_ERR_INFO_WIDTH (32)
#define NBL_URMUX_COR_ERR_INFO_DWLEN (1)
union urmux_cor_err_info_u {
	struct urmux_cor_err_info {
		u32 ram_addr:28;         /* [27:0] Default:0x0 RO */
		u32 ram_id:4;            /* [31:28] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_URMUX_COR_ERR_INFO_DWLEN];
} __packed;

#define NBL_URMUX_PARITY_ERR_INFO_ADDR  (0x802c)
#define NBL_URMUX_PARITY_ERR_INFO_DEPTH (1)
#define NBL_URMUX_PARITY_ERR_INFO_WIDTH (32)
#define NBL_URMUX_PARITY_ERR_INFO_DWLEN (1)
union urmux_parity_err_info_u {
	struct urmux_parity_err_info {
		u32 ram_addr:28;         /* [27:0] Default:0x0 RO */
		u32 ram_id:4;            /* [31:28] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_URMUX_PARITY_ERR_INFO_DWLEN];
} __packed;

#define NBL_URMUX_CIF_ERR_INFO_ADDR  (0x8038)
#define NBL_URMUX_CIF_ERR_INFO_DEPTH (1)
#define NBL_URMUX_CIF_ERR_INFO_WIDTH (32)
#define NBL_URMUX_CIF_ERR_INFO_DWLEN (1)
union urmux_cif_err_info_u {
	struct urmux_cif_err_info {
		u32 addr:30;             /* [29:0] Default:0x0 RO */
		u32 wr_err:1;            /* [30] Default:0x0 RO */
		u32 ucor_err:1;          /* [31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_URMUX_CIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_URMUX_CAR_CTRL_ADDR  (0x8100)
#define NBL_URMUX_CAR_CTRL_DEPTH (1)
#define NBL_URMUX_CAR_CTRL_WIDTH (32)
#define NBL_URMUX_CAR_CTRL_DWLEN (1)
union urmux_car_ctrl_u {
	struct urmux_car_ctrl {
		u32 sctr_car:1;          /* [0] Default:0x1 RW */
		u32 rctr_car:1;          /* [1] Default:0x1 RW */
		u32 rc_car:1;            /* [2] Default:0x1 RW */
		u32 tbl_rc_car:1;        /* [3] Default:0x1 RW */
		u32 rsv:28;              /* [31:4] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_URMUX_CAR_CTRL_DWLEN];
} __packed;

#define NBL_URMUX_PKT_LEN_ADDR  (0x8104)
#define NBL_URMUX_PKT_LEN_DEPTH (1)
#define NBL_URMUX_PKT_LEN_WIDTH (32)
#define NBL_URMUX_PKT_LEN_DWLEN (1)
union urmux_pkt_len_u {
	struct urmux_pkt_len {
		u32 min:7;               /* [6:0] Default:60 RW */
		u32 rsv1:8;              /* [14:7] Default:0x0 RO */
		u32 min_chk_en:1;        /* [15] Default:0x1 RW */
		u32 max:14;              /* [29:16] Default:9600 RW */
		u32 rsv:1;               /* [30] Default:0x0 RO */
		u32 max_chk_en:1;        /* [31] Default:0x1 RW */
	} __packed info;
	u32 data[NBL_URMUX_PKT_LEN_DWLEN];
} __packed;

#define NBL_URMUX_ETH0_DROP_TH_ADDR  (0x8130)
#define NBL_URMUX_ETH0_DROP_TH_DEPTH (1)
#define NBL_URMUX_ETH0_DROP_TH_WIDTH (32)
#define NBL_URMUX_ETH0_DROP_TH_DWLEN (1)
union urmux_eth0_drop_th_u {
	struct urmux_eth0_drop_th {
		u32 info_drop_th:9;      /* [8:0] Default:240 RW */
		u32 rsv1:7;              /* [15:9] Default:0x0 RO */
		u32 data_drop_th:9;      /* [24:16] Default:240 RW */
		u32 rsv:7;               /* [31:25] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_URMUX_ETH0_DROP_TH_DWLEN];
} __packed;

#define NBL_URMUX_ETH1_DROP_TH_ADDR  (0x8134)
#define NBL_URMUX_ETH1_DROP_TH_DEPTH (1)
#define NBL_URMUX_ETH1_DROP_TH_WIDTH (32)
#define NBL_URMUX_ETH1_DROP_TH_DWLEN (1)
union urmux_eth1_drop_th_u {
	struct urmux_eth1_drop_th {
		u32 info_drop_th:9;      /* [8:0] Default:240 RW */
		u32 rsv1:7;              /* [15:9] Default:0x0 RO */
		u32 data_drop_th:9;      /* [24:16] Default:240 RW */
		u32 rsv:7;               /* [31:25] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_URMUX_ETH1_DROP_TH_DWLEN];
} __packed;

#define NBL_URMUX_ETH2_DROP_TH_ADDR  (0x8138)
#define NBL_URMUX_ETH2_DROP_TH_DEPTH (1)
#define NBL_URMUX_ETH2_DROP_TH_WIDTH (32)
#define NBL_URMUX_ETH2_DROP_TH_DWLEN (1)
union urmux_eth2_drop_th_u {
	struct urmux_eth2_drop_th {
		u32 info_drop_th:9;      /* [8:0] Default:240 RW */
		u32 rsv1:7;              /* [15:9] Default:0x0 RO */
		u32 data_drop_th:9;      /* [24:16] Default:240 RW */
		u32 rsv:7;               /* [31:25] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_URMUX_ETH2_DROP_TH_DWLEN];
} __packed;

#define NBL_URMUX_ETH3_DROP_TH_ADDR  (0x813c)
#define NBL_URMUX_ETH3_DROP_TH_DEPTH (1)
#define NBL_URMUX_ETH3_DROP_TH_WIDTH (32)
#define NBL_URMUX_ETH3_DROP_TH_DWLEN (1)
union urmux_eth3_drop_th_u {
	struct urmux_eth3_drop_th {
		u32 info_drop_th:9;      /* [8:0] Default:240 RW */
		u32 rsv1:7;              /* [15:9] Default:0x0 RO */
		u32 data_drop_th:9;      /* [24:16] Default:240 RW */
		u32 rsv:7;               /* [31:25] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_URMUX_ETH3_DROP_TH_DWLEN];
} __packed;

#define NBL_URMUX_DDMUX_FC_TH_ADDR  (0x8150)
#define NBL_URMUX_DDMUX_FC_TH_DEPTH (1)
#define NBL_URMUX_DDMUX_FC_TH_WIDTH (32)
#define NBL_URMUX_DDMUX_FC_TH_DWLEN (1)
union urmux_ddmux_fc_th_u {
	struct urmux_ddmux_fc_th {
		u32 info_fc_th:10;       /* [9:0] Default:320 RW */
		u32 rsv1:6;              /* [15:10] Default:0x0 RO */
		u32 data_fc_th:10;       /* [25:16] Default:320 RW */
		u32 rsv:6;               /* [31:26] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_URMUX_DDMUX_FC_TH_DWLEN];
} __packed;

#define NBL_URMUX_DDMUX_LINK_FC_EN_ADDR  (0x8158)
#define NBL_URMUX_DDMUX_LINK_FC_EN_DEPTH (1)
#define NBL_URMUX_DDMUX_LINK_FC_EN_WIDTH (32)
#define NBL_URMUX_DDMUX_LINK_FC_EN_DWLEN (1)
union urmux_ddmux_link_fc_en_u {
	struct urmux_ddmux_link_fc_en {
		u32 loop_link_fc_en:1;   /* [0] Default:0x1 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_URMUX_DDMUX_LINK_FC_EN_DWLEN];
} __packed;

#define NBL_URMUX_SEOP_CHK_EN_ADDR  (0x815c)
#define NBL_URMUX_SEOP_CHK_EN_DEPTH (1)
#define NBL_URMUX_SEOP_CHK_EN_WIDTH (32)
#define NBL_URMUX_SEOP_CHK_EN_DWLEN (1)
union urmux_seop_chk_en_u {
	struct urmux_seop_chk_en {
		u32 eth0_seop_chk_en:1;  /* [0] Default:0x1 RW */
		u32 eth1_seop_chk_en:1;  /* [1] Default:0x1 RW */
		u32 eth2_seop_chk_en:1;  /* [2] Default:0x1 RW */
		u32 eth3_seop_chk_en:1;  /* [3] Default:0x1 RW */
		u32 rsv:28;              /* [31:4] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_URMUX_SEOP_CHK_EN_DWLEN];
} __packed;

#define NBL_URMUX_LOWP_TIME_ADDR  (0x8160)
#define NBL_URMUX_LOWP_TIME_DEPTH (1)
#define NBL_URMUX_LOWP_TIME_WIDTH (64)
#define NBL_URMUX_LOWP_TIME_DWLEN (2)
union urmux_lowp_time_u {
	struct urmux_lowp_time {
		u32 lowp_time_arr[2];    /* [63:0] Default:0x3938700 RW */
	} __packed info;
	u32 data[NBL_URMUX_LOWP_TIME_DWLEN];
} __packed;

#define NBL_URMUX_LOWP_EN_ADDR  (0x8168)
#define NBL_URMUX_LOWP_EN_DEPTH (1)
#define NBL_URMUX_LOWP_EN_WIDTH (32)
#define NBL_URMUX_LOWP_EN_DWLEN (1)
union urmux_lowp_en_u {
	struct urmux_lowp_en {
		u32 lowp_en:1;           /* [0] Default:0x0 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_URMUX_LOWP_EN_DWLEN];
} __packed;

#define NBL_URMUX_TDM_SLOT_LEN_ADDR  (0x816c)
#define NBL_URMUX_TDM_SLOT_LEN_DEPTH (1)
#define NBL_URMUX_TDM_SLOT_LEN_WIDTH (32)
#define NBL_URMUX_TDM_SLOT_LEN_DWLEN (1)
union urmux_tdm_slot_len_u {
	struct urmux_tdm_slot_len {
		u32 len:4;               /* [3:0] Default:0xf RW */
		u32 rsv:28;              /* [31:4] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_URMUX_TDM_SLOT_LEN_DWLEN];
} __packed;

#define NBL_URMUX_TDM_SLOT_ID_0_ADDR  (0x8170)
#define NBL_URMUX_TDM_SLOT_ID_0_DEPTH (1)
#define NBL_URMUX_TDM_SLOT_ID_0_WIDTH (32)
#define NBL_URMUX_TDM_SLOT_ID_0_DWLEN (1)
union urmux_tdm_slot_id_0_u {
	struct urmux_tdm_slot_id_0 {
		u32 slot0_id:3;          /* [2:0] Default:0x0 RW */
		u32 rsv3:5;              /* [7:3] Default:0x0 RO */
		u32 slot1_id:3;          /* [10:8] Default:0x1 RW */
		u32 rsv2:5;              /* [15:11] Default:0x0 RO */
		u32 slot2_id:3;          /* [18:16] Default:0x2 RW */
		u32 rsv1:5;              /* [23:19] Default:0x0 RO */
		u32 slot3_id:3;          /* [26:24] Default:0x3 RW */
		u32 rsv:5;               /* [31:27] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_URMUX_TDM_SLOT_ID_0_DWLEN];
} __packed;

#define NBL_URMUX_TDM_SLOT_ID_1_ADDR  (0x8174)
#define NBL_URMUX_TDM_SLOT_ID_1_DEPTH (1)
#define NBL_URMUX_TDM_SLOT_ID_1_WIDTH (32)
#define NBL_URMUX_TDM_SLOT_ID_1_DWLEN (1)
union urmux_tdm_slot_id_1_u {
	struct urmux_tdm_slot_id_1 {
		u32 slot4_id:3;          /* [2:0] Default:0x4 RW */
		u32 rsv3:5;              /* [7:3] Default:0x0 RO */
		u32 slot5_id:3;          /* [10:8] Default:0x0 RW */
		u32 rsv2:5;              /* [15:11] Default:0x0 RO */
		u32 slot6_id:3;          /* [18:16] Default:0x1 RW */
		u32 rsv1:5;              /* [23:19] Default:0x0 RO */
		u32 slot7_id:3;          /* [26:24] Default:0x2 RW */
		u32 rsv:5;               /* [31:27] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_URMUX_TDM_SLOT_ID_1_DWLEN];
} __packed;

#define NBL_URMUX_TDM_SLOT_ID_2_ADDR  (0x8178)
#define NBL_URMUX_TDM_SLOT_ID_2_DEPTH (1)
#define NBL_URMUX_TDM_SLOT_ID_2_WIDTH (32)
#define NBL_URMUX_TDM_SLOT_ID_2_DWLEN (1)
union urmux_tdm_slot_id_2_u {
	struct urmux_tdm_slot_id_2 {
		u32 slot8_id:3;          /* [2:0] Default:0x3 RW */
		u32 rsv3:5;              /* [7:3] Default:0x0 RO */
		u32 slot9_id:3;          /* [10:8] Default:0x4 RW */
		u32 rsv2:5;              /* [15:11] Default:0x0 RO */
		u32 slot10_id:3;         /* [18:16] Default:0x0 RW */
		u32 rsv1:5;              /* [23:19] Default:0x0 RO */
		u32 slot11_id:3;         /* [26:24] Default:0x1 RW */
		u32 rsv:5;               /* [31:27] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_URMUX_TDM_SLOT_ID_2_DWLEN];
} __packed;

#define NBL_URMUX_TDM_SLOT_ID_3_ADDR  (0x817c)
#define NBL_URMUX_TDM_SLOT_ID_3_DEPTH (1)
#define NBL_URMUX_TDM_SLOT_ID_3_WIDTH (32)
#define NBL_URMUX_TDM_SLOT_ID_3_DWLEN (1)
union urmux_tdm_slot_id_3_u {
	struct urmux_tdm_slot_id_3 {
		u32 slot12_id:3;         /* [2:0] Default:0x2 RW */
		u32 rsv2:5;              /* [7:3] Default:0x0 RO */
		u32 slot13_id:3;         /* [10:8] Default:0x3 RW */
		u32 rsv1:5;              /* [15:11] Default:0x0 RO */
		u32 slot14_id:3;         /* [18:16] Default:0x4 RW */
		u32 rsv:13;              /* [31:19] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_URMUX_TDM_SLOT_ID_3_DWLEN];
} __packed;

#define NBL_URMUX_ETH0_RX_SOP_ADDR  (0x8800)
#define NBL_URMUX_ETH0_RX_SOP_DEPTH (1)
#define NBL_URMUX_ETH0_RX_SOP_WIDTH (32)
#define NBL_URMUX_ETH0_RX_SOP_DWLEN (1)
union urmux_eth0_rx_sop_u {
	struct urmux_eth0_rx_sop {
		u32 sop_cnt:32;          /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH0_RX_SOP_DWLEN];
} __packed;

#define NBL_URMUX_ETH0_RX_EOP_ADDR  (0x8804)
#define NBL_URMUX_ETH0_RX_EOP_DEPTH (1)
#define NBL_URMUX_ETH0_RX_EOP_WIDTH (32)
#define NBL_URMUX_ETH0_RX_EOP_DWLEN (1)
union urmux_eth0_rx_eop_u {
	struct urmux_eth0_rx_eop {
		u32 eop_cnt:32;          /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH0_RX_EOP_DWLEN];
} __packed;

#define NBL_URMUX_ETH0_RX_PKT_ADDR  (0x8808)
#define NBL_URMUX_ETH0_RX_PKT_DEPTH (1)
#define NBL_URMUX_ETH0_RX_PKT_WIDTH (32)
#define NBL_URMUX_ETH0_RX_PKT_DWLEN (1)
union urmux_eth0_rx_pkt_u {
	struct urmux_eth0_rx_pkt {
		u32 eth0_rx_pkt:32;      /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH0_RX_PKT_DWLEN];
} __packed;

#define NBL_URMUX_ETH0_RX_BYTE_ADDR  (0x880c)
#define NBL_URMUX_ETH0_RX_BYTE_DEPTH (1)
#define NBL_URMUX_ETH0_RX_BYTE_WIDTH (64)
#define NBL_URMUX_ETH0_RX_BYTE_DWLEN (2)
union urmux_eth0_rx_byte_u {
	struct urmux_eth0_rx_byte {
		u32 eth0_rx_byte_arr[2]; /* [63:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH0_RX_BYTE_DWLEN];
} __packed;

#define NBL_URMUX_ETH0_RX_UC_ADDR  (0x8814)
#define NBL_URMUX_ETH0_RX_UC_DEPTH (1)
#define NBL_URMUX_ETH0_RX_UC_WIDTH (32)
#define NBL_URMUX_ETH0_RX_UC_DWLEN (1)
union urmux_eth0_rx_uc_u {
	struct urmux_eth0_rx_uc {
		u32 eth0_rx_uc:32;       /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH0_RX_UC_DWLEN];
} __packed;

#define NBL_URMUX_ETH0_RX_MC_ADDR  (0x8818)
#define NBL_URMUX_ETH0_RX_MC_DEPTH (1)
#define NBL_URMUX_ETH0_RX_MC_WIDTH (32)
#define NBL_URMUX_ETH0_RX_MC_DWLEN (1)
union urmux_eth0_rx_mc_u {
	struct urmux_eth0_rx_mc {
		u32 eth0_rx_mc:32;       /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH0_RX_MC_DWLEN];
} __packed;

#define NBL_URMUX_ETH0_RX_BC_ADDR  (0x881c)
#define NBL_URMUX_ETH0_RX_BC_DEPTH (1)
#define NBL_URMUX_ETH0_RX_BC_WIDTH (32)
#define NBL_URMUX_ETH0_RX_BC_DWLEN (1)
union urmux_eth0_rx_bc_u {
	struct urmux_eth0_rx_bc {
		u32 eth0_rx_bc:32;       /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH0_RX_BC_DWLEN];
} __packed;

#define NBL_URMUX_ETH0_RX_LESS_60_ADDR  (0x8820)
#define NBL_URMUX_ETH0_RX_LESS_60_DEPTH (1)
#define NBL_URMUX_ETH0_RX_LESS_60_WIDTH (32)
#define NBL_URMUX_ETH0_RX_LESS_60_DWLEN (1)
union urmux_eth0_rx_less_60_u {
	struct urmux_eth0_rx_less_60 {
		u32 eth0_rx_less_60:32;  /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH0_RX_LESS_60_DWLEN];
} __packed;

#define NBL_URMUX_ETH0_RX_61_123_ADDR  (0x8828)
#define NBL_URMUX_ETH0_RX_61_123_DEPTH (1)
#define NBL_URMUX_ETH0_RX_61_123_WIDTH (32)
#define NBL_URMUX_ETH0_RX_61_123_DWLEN (1)
union urmux_eth0_rx_61_123_u {
	struct urmux_eth0_rx_61_123 {
		u32 eth0_rx_61_123:32;   /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH0_RX_61_123_DWLEN];
} __packed;

#define NBL_URMUX_ETH0_RX_124_251_ADDR  (0x882c)
#define NBL_URMUX_ETH0_RX_124_251_DEPTH (1)
#define NBL_URMUX_ETH0_RX_124_251_WIDTH (32)
#define NBL_URMUX_ETH0_RX_124_251_DWLEN (1)
union urmux_eth0_rx_124_251_u {
	struct urmux_eth0_rx_124_251 {
		u32 eth0_rx_124_251:32;  /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH0_RX_124_251_DWLEN];
} __packed;

#define NBL_URMUX_ETH0_RX_252_507_ADDR  (0x8830)
#define NBL_URMUX_ETH0_RX_252_507_DEPTH (1)
#define NBL_URMUX_ETH0_RX_252_507_WIDTH (32)
#define NBL_URMUX_ETH0_RX_252_507_DWLEN (1)
union urmux_eth0_rx_252_507_u {
	struct urmux_eth0_rx_252_507 {
		u32 eth0_rx_252_507:32;  /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH0_RX_252_507_DWLEN];
} __packed;

#define NBL_URMUX_ETH0_RX_508_1019_ADDR  (0x8834)
#define NBL_URMUX_ETH0_RX_508_1019_DEPTH (1)
#define NBL_URMUX_ETH0_RX_508_1019_WIDTH (32)
#define NBL_URMUX_ETH0_RX_508_1019_DWLEN (1)
union urmux_eth0_rx_508_1019_u {
	struct urmux_eth0_rx_508_1019 {
		u32 eth0_rx_508_1019:32; /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH0_RX_508_1019_DWLEN];
} __packed;

#define NBL_URMUX_ETH0_RX_1020_1514_ADDR  (0x8838)
#define NBL_URMUX_ETH0_RX_1020_1514_DEPTH (1)
#define NBL_URMUX_ETH0_RX_1020_1514_WIDTH (32)
#define NBL_URMUX_ETH0_RX_1020_1514_DWLEN (1)
union urmux_eth0_rx_1020_1514_u {
	struct urmux_eth0_rx_1020_1514 {
		u32 eth0_rx_1020_1514:32; /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH0_RX_1020_1514_DWLEN];
} __packed;

#define NBL_URMUX_ETH0_RX_LARGE_1514_ADDR  (0x883c)
#define NBL_URMUX_ETH0_RX_LARGE_1514_DEPTH (1)
#define NBL_URMUX_ETH0_RX_LARGE_1514_WIDTH (32)
#define NBL_URMUX_ETH0_RX_LARGE_1514_DWLEN (1)
union urmux_eth0_rx_large_1514_u {
	struct urmux_eth0_rx_large_1514 {
		u32 eth0_rx_large_1514:32; /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH0_RX_LARGE_1514_DWLEN];
} __packed;

#define NBL_URMUX_ETH0_RX_MAC_ERR_ADDR  (0x8840)
#define NBL_URMUX_ETH0_RX_MAC_ERR_DEPTH (1)
#define NBL_URMUX_ETH0_RX_MAC_ERR_WIDTH (32)
#define NBL_URMUX_ETH0_RX_MAC_ERR_DWLEN (1)
union urmux_eth0_rx_mac_err_u {
	struct urmux_eth0_rx_mac_err {
		u32 eth0_rx_mac_err:32;  /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH0_RX_MAC_ERR_DWLEN];
} __packed;

#define NBL_URMUX_ETH0_RX_OVERLONG_ADDR  (0x8844)
#define NBL_URMUX_ETH0_RX_OVERLONG_DEPTH (1)
#define NBL_URMUX_ETH0_RX_OVERLONG_WIDTH (32)
#define NBL_URMUX_ETH0_RX_OVERLONG_DWLEN (1)
union urmux_eth0_rx_overlong_u {
	struct urmux_eth0_rx_overlong {
		u32 eth0_rx_overlong:32; /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH0_RX_OVERLONG_DWLEN];
} __packed;

#define NBL_URMUX_ETH0_RX_OVERSHORT_ADDR  (0x8848)
#define NBL_URMUX_ETH0_RX_OVERSHORT_DEPTH (1)
#define NBL_URMUX_ETH0_RX_OVERSHORT_WIDTH (32)
#define NBL_URMUX_ETH0_RX_OVERSHORT_DWLEN (1)
union urmux_eth0_rx_overshort_u {
	struct urmux_eth0_rx_overshort {
		u32 eth0_rx_overshort:32; /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH0_RX_OVERSHORT_DWLEN];
} __packed;

#define NBL_URMUX_ETH0_RX_SEOP_ERR_ADDR  (0x884c)
#define NBL_URMUX_ETH0_RX_SEOP_ERR_DEPTH (1)
#define NBL_URMUX_ETH0_RX_SEOP_ERR_WIDTH (32)
#define NBL_URMUX_ETH0_RX_SEOP_ERR_DWLEN (1)
union urmux_eth0_rx_seop_err_u {
	struct urmux_eth0_rx_seop_err {
		u32 eth0_rx_seop_err:32; /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH0_RX_SEOP_ERR_DWLEN];
} __packed;

#define NBL_URMUX_ETH1_RX_SOP_ADDR  (0x8900)
#define NBL_URMUX_ETH1_RX_SOP_DEPTH (1)
#define NBL_URMUX_ETH1_RX_SOP_WIDTH (32)
#define NBL_URMUX_ETH1_RX_SOP_DWLEN (1)
union urmux_eth1_rx_sop_u {
	struct urmux_eth1_rx_sop {
		u32 sop_cnt:32;          /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH1_RX_SOP_DWLEN];
} __packed;

#define NBL_URMUX_ETH1_RX_EOP_ADDR  (0x8904)
#define NBL_URMUX_ETH1_RX_EOP_DEPTH (1)
#define NBL_URMUX_ETH1_RX_EOP_WIDTH (32)
#define NBL_URMUX_ETH1_RX_EOP_DWLEN (1)
union urmux_eth1_rx_eop_u {
	struct urmux_eth1_rx_eop {
		u32 eop_cnt:32;          /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH1_RX_EOP_DWLEN];
} __packed;

#define NBL_URMUX_ETH1_RX_PKT_ADDR  (0x8908)
#define NBL_URMUX_ETH1_RX_PKT_DEPTH (1)
#define NBL_URMUX_ETH1_RX_PKT_WIDTH (32)
#define NBL_URMUX_ETH1_RX_PKT_DWLEN (1)
union urmux_eth1_rx_pkt_u {
	struct urmux_eth1_rx_pkt {
		u32 eth1_rx_pkt:32;      /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH1_RX_PKT_DWLEN];
} __packed;

#define NBL_URMUX_ETH1_RX_BYTE_ADDR  (0x890c)
#define NBL_URMUX_ETH1_RX_BYTE_DEPTH (1)
#define NBL_URMUX_ETH1_RX_BYTE_WIDTH (64)
#define NBL_URMUX_ETH1_RX_BYTE_DWLEN (2)
union urmux_eth1_rx_byte_u {
	struct urmux_eth1_rx_byte {
		u32 eth1_rx_byte_arr[2]; /* [63:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH1_RX_BYTE_DWLEN];
} __packed;

#define NBL_URMUX_ETH1_RX_UC_ADDR  (0x8914)
#define NBL_URMUX_ETH1_RX_UC_DEPTH (1)
#define NBL_URMUX_ETH1_RX_UC_WIDTH (32)
#define NBL_URMUX_ETH1_RX_UC_DWLEN (1)
union urmux_eth1_rx_uc_u {
	struct urmux_eth1_rx_uc {
		u32 eth1_rx_uc:32;       /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH1_RX_UC_DWLEN];
} __packed;

#define NBL_URMUX_ETH1_RX_MC_ADDR  (0x8918)
#define NBL_URMUX_ETH1_RX_MC_DEPTH (1)
#define NBL_URMUX_ETH1_RX_MC_WIDTH (32)
#define NBL_URMUX_ETH1_RX_MC_DWLEN (1)
union urmux_eth1_rx_mc_u {
	struct urmux_eth1_rx_mc {
		u32 eth1_rx_mc:32;       /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH1_RX_MC_DWLEN];
} __packed;

#define NBL_URMUX_ETH1_RX_BC_ADDR  (0x891c)
#define NBL_URMUX_ETH1_RX_BC_DEPTH (1)
#define NBL_URMUX_ETH1_RX_BC_WIDTH (32)
#define NBL_URMUX_ETH1_RX_BC_DWLEN (1)
union urmux_eth1_rx_bc_u {
	struct urmux_eth1_rx_bc {
		u32 eth1_rx_bc:32;       /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH1_RX_BC_DWLEN];
} __packed;

#define NBL_URMUX_ETH1_RX_LESS_60_ADDR  (0x8920)
#define NBL_URMUX_ETH1_RX_LESS_60_DEPTH (1)
#define NBL_URMUX_ETH1_RX_LESS_60_WIDTH (32)
#define NBL_URMUX_ETH1_RX_LESS_60_DWLEN (1)
union urmux_eth1_rx_less_60_u {
	struct urmux_eth1_rx_less_60 {
		u32 eth1_rx_less_60:32;  /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH1_RX_LESS_60_DWLEN];
} __packed;

#define NBL_URMUX_ETH1_RX_61_123_ADDR  (0x8928)
#define NBL_URMUX_ETH1_RX_61_123_DEPTH (1)
#define NBL_URMUX_ETH1_RX_61_123_WIDTH (32)
#define NBL_URMUX_ETH1_RX_61_123_DWLEN (1)
union urmux_eth1_rx_61_123_u {
	struct urmux_eth1_rx_61_123 {
		u32 eth1_rx_61_123:32;   /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH1_RX_61_123_DWLEN];
} __packed;

#define NBL_URMUX_ETH1_RX_124_251_ADDR  (0x892c)
#define NBL_URMUX_ETH1_RX_124_251_DEPTH (1)
#define NBL_URMUX_ETH1_RX_124_251_WIDTH (32)
#define NBL_URMUX_ETH1_RX_124_251_DWLEN (1)
union urmux_eth1_rx_124_251_u {
	struct urmux_eth1_rx_124_251 {
		u32 eth1_rx_124_251:32;  /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH1_RX_124_251_DWLEN];
} __packed;

#define NBL_URMUX_ETH1_RX_252_507_ADDR  (0x8930)
#define NBL_URMUX_ETH1_RX_252_507_DEPTH (1)
#define NBL_URMUX_ETH1_RX_252_507_WIDTH (32)
#define NBL_URMUX_ETH1_RX_252_507_DWLEN (1)
union urmux_eth1_rx_252_507_u {
	struct urmux_eth1_rx_252_507 {
		u32 eth1_rx_252_507:32;  /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH1_RX_252_507_DWLEN];
} __packed;

#define NBL_URMUX_ETH1_RX_508_1019_ADDR  (0x8934)
#define NBL_URMUX_ETH1_RX_508_1019_DEPTH (1)
#define NBL_URMUX_ETH1_RX_508_1019_WIDTH (32)
#define NBL_URMUX_ETH1_RX_508_1019_DWLEN (1)
union urmux_eth1_rx_508_1019_u {
	struct urmux_eth1_rx_508_1019 {
		u32 eth1_rx_508_1019:32; /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH1_RX_508_1019_DWLEN];
} __packed;

#define NBL_URMUX_ETH1_RX_1020_1514_ADDR  (0x8938)
#define NBL_URMUX_ETH1_RX_1020_1514_DEPTH (1)
#define NBL_URMUX_ETH1_RX_1020_1514_WIDTH (32)
#define NBL_URMUX_ETH1_RX_1020_1514_DWLEN (1)
union urmux_eth1_rx_1020_1514_u {
	struct urmux_eth1_rx_1020_1514 {
		u32 eth1_rx_1020_1514:32; /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH1_RX_1020_1514_DWLEN];
} __packed;

#define NBL_URMUX_ETH1_RX_LARGE_1514_ADDR  (0x893c)
#define NBL_URMUX_ETH1_RX_LARGE_1514_DEPTH (1)
#define NBL_URMUX_ETH1_RX_LARGE_1514_WIDTH (32)
#define NBL_URMUX_ETH1_RX_LARGE_1514_DWLEN (1)
union urmux_eth1_rx_large_1514_u {
	struct urmux_eth1_rx_large_1514 {
		u32 eth1_rx_large_1514:32; /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH1_RX_LARGE_1514_DWLEN];
} __packed;

#define NBL_URMUX_ETH1_RX_MAC_ERR_ADDR  (0x8940)
#define NBL_URMUX_ETH1_RX_MAC_ERR_DEPTH (1)
#define NBL_URMUX_ETH1_RX_MAC_ERR_WIDTH (32)
#define NBL_URMUX_ETH1_RX_MAC_ERR_DWLEN (1)
union urmux_eth1_rx_mac_err_u {
	struct urmux_eth1_rx_mac_err {
		u32 eth1_rx_mac_err:32;  /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH1_RX_MAC_ERR_DWLEN];
} __packed;

#define NBL_URMUX_ETH1_RX_OVERLONG_ADDR  (0x8944)
#define NBL_URMUX_ETH1_RX_OVERLONG_DEPTH (1)
#define NBL_URMUX_ETH1_RX_OVERLONG_WIDTH (32)
#define NBL_URMUX_ETH1_RX_OVERLONG_DWLEN (1)
union urmux_eth1_rx_overlong_u {
	struct urmux_eth1_rx_overlong {
		u32 eth1_rx_overlong:32; /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH1_RX_OVERLONG_DWLEN];
} __packed;

#define NBL_URMUX_ETH1_RX_OVERSHORT_ADDR  (0x8948)
#define NBL_URMUX_ETH1_RX_OVERSHORT_DEPTH (1)
#define NBL_URMUX_ETH1_RX_OVERSHORT_WIDTH (32)
#define NBL_URMUX_ETH1_RX_OVERSHORT_DWLEN (1)
union urmux_eth1_rx_overshort_u {
	struct urmux_eth1_rx_overshort {
		u32 eth1_rx_overshort:32; /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH1_RX_OVERSHORT_DWLEN];
} __packed;

#define NBL_URMUX_ETH1_RX_SEOP_ERR_ADDR  (0x894c)
#define NBL_URMUX_ETH1_RX_SEOP_ERR_DEPTH (1)
#define NBL_URMUX_ETH1_RX_SEOP_ERR_WIDTH (32)
#define NBL_URMUX_ETH1_RX_SEOP_ERR_DWLEN (1)
union urmux_eth1_rx_seop_err_u {
	struct urmux_eth1_rx_seop_err {
		u32 eth1_rx_seop_err:32; /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH1_RX_SEOP_ERR_DWLEN];
} __packed;

#define NBL_URMUX_ETH2_RX_SOP_ADDR  (0x8a00)
#define NBL_URMUX_ETH2_RX_SOP_DEPTH (1)
#define NBL_URMUX_ETH2_RX_SOP_WIDTH (32)
#define NBL_URMUX_ETH2_RX_SOP_DWLEN (1)
union urmux_eth2_rx_sop_u {
	struct urmux_eth2_rx_sop {
		u32 sop_cnt:32;          /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH2_RX_SOP_DWLEN];
} __packed;

#define NBL_URMUX_ETH2_RX_EOP_ADDR  (0x8a04)
#define NBL_URMUX_ETH2_RX_EOP_DEPTH (1)
#define NBL_URMUX_ETH2_RX_EOP_WIDTH (32)
#define NBL_URMUX_ETH2_RX_EOP_DWLEN (1)
union urmux_eth2_rx_eop_u {
	struct urmux_eth2_rx_eop {
		u32 eop_cnt:32;          /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH2_RX_EOP_DWLEN];
} __packed;

#define NBL_URMUX_ETH2_RX_PKT_ADDR  (0x8a08)
#define NBL_URMUX_ETH2_RX_PKT_DEPTH (1)
#define NBL_URMUX_ETH2_RX_PKT_WIDTH (32)
#define NBL_URMUX_ETH2_RX_PKT_DWLEN (1)
union urmux_eth2_rx_pkt_u {
	struct urmux_eth2_rx_pkt {
		u32 eth2_rx_pkt:32;      /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH2_RX_PKT_DWLEN];
} __packed;

#define NBL_URMUX_ETH2_RX_BYTE_ADDR  (0x8a0c)
#define NBL_URMUX_ETH2_RX_BYTE_DEPTH (1)
#define NBL_URMUX_ETH2_RX_BYTE_WIDTH (64)
#define NBL_URMUX_ETH2_RX_BYTE_DWLEN (2)
union urmux_eth2_rx_byte_u {
	struct urmux_eth2_rx_byte {
		u32 eth2_rx_byte_arr[2]; /* [63:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH2_RX_BYTE_DWLEN];
} __packed;

#define NBL_URMUX_ETH2_RX_UC_ADDR  (0x8a14)
#define NBL_URMUX_ETH2_RX_UC_DEPTH (1)
#define NBL_URMUX_ETH2_RX_UC_WIDTH (32)
#define NBL_URMUX_ETH2_RX_UC_DWLEN (1)
union urmux_eth2_rx_uc_u {
	struct urmux_eth2_rx_uc {
		u32 eth2_rx_uc:32;       /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH2_RX_UC_DWLEN];
} __packed;

#define NBL_URMUX_ETH2_RX_MC_ADDR  (0x8a18)
#define NBL_URMUX_ETH2_RX_MC_DEPTH (1)
#define NBL_URMUX_ETH2_RX_MC_WIDTH (32)
#define NBL_URMUX_ETH2_RX_MC_DWLEN (1)
union urmux_eth2_rx_mc_u {
	struct urmux_eth2_rx_mc {
		u32 eth2_rx_mc:32;       /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH2_RX_MC_DWLEN];
} __packed;

#define NBL_URMUX_ETH2_RX_BC_ADDR  (0x8a1c)
#define NBL_URMUX_ETH2_RX_BC_DEPTH (1)
#define NBL_URMUX_ETH2_RX_BC_WIDTH (32)
#define NBL_URMUX_ETH2_RX_BC_DWLEN (1)
union urmux_eth2_rx_bc_u {
	struct urmux_eth2_rx_bc {
		u32 eth2_rx_bc:32;       /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH2_RX_BC_DWLEN];
} __packed;

#define NBL_URMUX_ETH2_RX_LESS_60_ADDR  (0x8a20)
#define NBL_URMUX_ETH2_RX_LESS_60_DEPTH (1)
#define NBL_URMUX_ETH2_RX_LESS_60_WIDTH (32)
#define NBL_URMUX_ETH2_RX_LESS_60_DWLEN (1)
union urmux_eth2_rx_less_60_u {
	struct urmux_eth2_rx_less_60 {
		u32 eth2_rx_less_60:32;  /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH2_RX_LESS_60_DWLEN];
} __packed;

#define NBL_URMUX_ETH2_RX_61_123_ADDR  (0x8a28)
#define NBL_URMUX_ETH2_RX_61_123_DEPTH (1)
#define NBL_URMUX_ETH2_RX_61_123_WIDTH (32)
#define NBL_URMUX_ETH2_RX_61_123_DWLEN (1)
union urmux_eth2_rx_61_123_u {
	struct urmux_eth2_rx_61_123 {
		u32 eth2_rx_61_123:32;   /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH2_RX_61_123_DWLEN];
} __packed;

#define NBL_URMUX_ETH2_RX_124_251_ADDR  (0x8a2c)
#define NBL_URMUX_ETH2_RX_124_251_DEPTH (1)
#define NBL_URMUX_ETH2_RX_124_251_WIDTH (32)
#define NBL_URMUX_ETH2_RX_124_251_DWLEN (1)
union urmux_eth2_rx_124_251_u {
	struct urmux_eth2_rx_124_251 {
		u32 eth2_rx_124_251:32;  /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH2_RX_124_251_DWLEN];
} __packed;

#define NBL_URMUX_ETH2_RX_252_507_ADDR  (0x8a30)
#define NBL_URMUX_ETH2_RX_252_507_DEPTH (1)
#define NBL_URMUX_ETH2_RX_252_507_WIDTH (32)
#define NBL_URMUX_ETH2_RX_252_507_DWLEN (1)
union urmux_eth2_rx_252_507_u {
	struct urmux_eth2_rx_252_507 {
		u32 eth2_rx_252_507:32;  /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH2_RX_252_507_DWLEN];
} __packed;

#define NBL_URMUX_ETH2_RX_508_1019_ADDR  (0x8a34)
#define NBL_URMUX_ETH2_RX_508_1019_DEPTH (1)
#define NBL_URMUX_ETH2_RX_508_1019_WIDTH (32)
#define NBL_URMUX_ETH2_RX_508_1019_DWLEN (1)
union urmux_eth2_rx_508_1019_u {
	struct urmux_eth2_rx_508_1019 {
		u32 eth2_rx_508_1019:32; /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH2_RX_508_1019_DWLEN];
} __packed;

#define NBL_URMUX_ETH2_RX_1020_1514_ADDR  (0x8a38)
#define NBL_URMUX_ETH2_RX_1020_1514_DEPTH (1)
#define NBL_URMUX_ETH2_RX_1020_1514_WIDTH (32)
#define NBL_URMUX_ETH2_RX_1020_1514_DWLEN (1)
union urmux_eth2_rx_1020_1514_u {
	struct urmux_eth2_rx_1020_1514 {
		u32 eth2_rx_1020_1514:32; /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH2_RX_1020_1514_DWLEN];
} __packed;

#define NBL_URMUX_ETH2_RX_LARGE_1514_ADDR  (0x8a3c)
#define NBL_URMUX_ETH2_RX_LARGE_1514_DEPTH (1)
#define NBL_URMUX_ETH2_RX_LARGE_1514_WIDTH (32)
#define NBL_URMUX_ETH2_RX_LARGE_1514_DWLEN (1)
union urmux_eth2_rx_large_1514_u {
	struct urmux_eth2_rx_large_1514 {
		u32 eth2_rx_large_1514:32; /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH2_RX_LARGE_1514_DWLEN];
} __packed;

#define NBL_URMUX_ETH2_RX_MAC_ERR_ADDR  (0x8a40)
#define NBL_URMUX_ETH2_RX_MAC_ERR_DEPTH (1)
#define NBL_URMUX_ETH2_RX_MAC_ERR_WIDTH (32)
#define NBL_URMUX_ETH2_RX_MAC_ERR_DWLEN (1)
union urmux_eth2_rx_mac_err_u {
	struct urmux_eth2_rx_mac_err {
		u32 eth2_rx_mac_err:32;  /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH2_RX_MAC_ERR_DWLEN];
} __packed;

#define NBL_URMUX_ETH2_RX_OVERLONG_ADDR  (0x8a44)
#define NBL_URMUX_ETH2_RX_OVERLONG_DEPTH (1)
#define NBL_URMUX_ETH2_RX_OVERLONG_WIDTH (32)
#define NBL_URMUX_ETH2_RX_OVERLONG_DWLEN (1)
union urmux_eth2_rx_overlong_u {
	struct urmux_eth2_rx_overlong {
		u32 eth2_rx_overlong:32; /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH2_RX_OVERLONG_DWLEN];
} __packed;

#define NBL_URMUX_ETH2_RX_OVERSHORT_ADDR  (0x8a48)
#define NBL_URMUX_ETH2_RX_OVERSHORT_DEPTH (1)
#define NBL_URMUX_ETH2_RX_OVERSHORT_WIDTH (32)
#define NBL_URMUX_ETH2_RX_OVERSHORT_DWLEN (1)
union urmux_eth2_rx_overshort_u {
	struct urmux_eth2_rx_overshort {
		u32 eth2_rx_overshort:32; /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH2_RX_OVERSHORT_DWLEN];
} __packed;

#define NBL_URMUX_ETH2_RX_SEOP_ERR_ADDR  (0x8a4c)
#define NBL_URMUX_ETH2_RX_SEOP_ERR_DEPTH (1)
#define NBL_URMUX_ETH2_RX_SEOP_ERR_WIDTH (32)
#define NBL_URMUX_ETH2_RX_SEOP_ERR_DWLEN (1)
union urmux_eth2_rx_seop_err_u {
	struct urmux_eth2_rx_seop_err {
		u32 eth2_rx_seop_err:32; /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH2_RX_SEOP_ERR_DWLEN];
} __packed;

#define NBL_URMUX_ETH3_RX_SOP_ADDR  (0x8b00)
#define NBL_URMUX_ETH3_RX_SOP_DEPTH (1)
#define NBL_URMUX_ETH3_RX_SOP_WIDTH (32)
#define NBL_URMUX_ETH3_RX_SOP_DWLEN (1)
union urmux_eth3_rx_sop_u {
	struct urmux_eth3_rx_sop {
		u32 sop_cnt:32;          /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH3_RX_SOP_DWLEN];
} __packed;

#define NBL_URMUX_ETH3_RX_EOP_ADDR  (0x8b04)
#define NBL_URMUX_ETH3_RX_EOP_DEPTH (1)
#define NBL_URMUX_ETH3_RX_EOP_WIDTH (32)
#define NBL_URMUX_ETH3_RX_EOP_DWLEN (1)
union urmux_eth3_rx_eop_u {
	struct urmux_eth3_rx_eop {
		u32 eop_cnt:32;          /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH3_RX_EOP_DWLEN];
} __packed;

#define NBL_URMUX_ETH3_RX_PKT_ADDR  (0x8b08)
#define NBL_URMUX_ETH3_RX_PKT_DEPTH (1)
#define NBL_URMUX_ETH3_RX_PKT_WIDTH (32)
#define NBL_URMUX_ETH3_RX_PKT_DWLEN (1)
union urmux_eth3_rx_pkt_u {
	struct urmux_eth3_rx_pkt {
		u32 eth3_rx_pkt:32;      /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH3_RX_PKT_DWLEN];
} __packed;

#define NBL_URMUX_ETH3_RX_BYTE_ADDR  (0x8b0c)
#define NBL_URMUX_ETH3_RX_BYTE_DEPTH (1)
#define NBL_URMUX_ETH3_RX_BYTE_WIDTH (64)
#define NBL_URMUX_ETH3_RX_BYTE_DWLEN (2)
union urmux_eth3_rx_byte_u {
	struct urmux_eth3_rx_byte {
		u32 eth3_rx_byte_arr[2]; /* [63:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH3_RX_BYTE_DWLEN];
} __packed;

#define NBL_URMUX_ETH3_RX_UC_ADDR  (0x8b14)
#define NBL_URMUX_ETH3_RX_UC_DEPTH (1)
#define NBL_URMUX_ETH3_RX_UC_WIDTH (32)
#define NBL_URMUX_ETH3_RX_UC_DWLEN (1)
union urmux_eth3_rx_uc_u {
	struct urmux_eth3_rx_uc {
		u32 eth3_rx_uc:32;       /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH3_RX_UC_DWLEN];
} __packed;

#define NBL_URMUX_ETH3_RX_MC_ADDR  (0x8b18)
#define NBL_URMUX_ETH3_RX_MC_DEPTH (1)
#define NBL_URMUX_ETH3_RX_MC_WIDTH (32)
#define NBL_URMUX_ETH3_RX_MC_DWLEN (1)
union urmux_eth3_rx_mc_u {
	struct urmux_eth3_rx_mc {
		u32 eth3_rx_mc:32;       /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH3_RX_MC_DWLEN];
} __packed;

#define NBL_URMUX_ETH3_RX_BC_ADDR  (0x8b1c)
#define NBL_URMUX_ETH3_RX_BC_DEPTH (1)
#define NBL_URMUX_ETH3_RX_BC_WIDTH (32)
#define NBL_URMUX_ETH3_RX_BC_DWLEN (1)
union urmux_eth3_rx_bc_u {
	struct urmux_eth3_rx_bc {
		u32 eth3_rx_bc:32;       /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH3_RX_BC_DWLEN];
} __packed;

#define NBL_URMUX_ETH3_RX_LESS_60_ADDR  (0x8b20)
#define NBL_URMUX_ETH3_RX_LESS_60_DEPTH (1)
#define NBL_URMUX_ETH3_RX_LESS_60_WIDTH (32)
#define NBL_URMUX_ETH3_RX_LESS_60_DWLEN (1)
union urmux_eth3_rx_less_60_u {
	struct urmux_eth3_rx_less_60 {
		u32 eth3_rx_less_60:32;  /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH3_RX_LESS_60_DWLEN];
} __packed;

#define NBL_URMUX_ETH3_RX_61_123_ADDR  (0x8b28)
#define NBL_URMUX_ETH3_RX_61_123_DEPTH (1)
#define NBL_URMUX_ETH3_RX_61_123_WIDTH (32)
#define NBL_URMUX_ETH3_RX_61_123_DWLEN (1)
union urmux_eth3_rx_61_123_u {
	struct urmux_eth3_rx_61_123 {
		u32 eth3_rx_61_123:32;   /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH3_RX_61_123_DWLEN];
} __packed;

#define NBL_URMUX_ETH3_RX_124_251_ADDR  (0x8b2c)
#define NBL_URMUX_ETH3_RX_124_251_DEPTH (1)
#define NBL_URMUX_ETH3_RX_124_251_WIDTH (32)
#define NBL_URMUX_ETH3_RX_124_251_DWLEN (1)
union urmux_eth3_rx_124_251_u {
	struct urmux_eth3_rx_124_251 {
		u32 eth3_rx_124_251:32;  /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH3_RX_124_251_DWLEN];
} __packed;

#define NBL_URMUX_ETH3_RX_252_507_ADDR  (0x8b30)
#define NBL_URMUX_ETH3_RX_252_507_DEPTH (1)
#define NBL_URMUX_ETH3_RX_252_507_WIDTH (32)
#define NBL_URMUX_ETH3_RX_252_507_DWLEN (1)
union urmux_eth3_rx_252_507_u {
	struct urmux_eth3_rx_252_507 {
		u32 eth3_rx_252_507:32;  /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH3_RX_252_507_DWLEN];
} __packed;

#define NBL_URMUX_ETH3_RX_508_1019_ADDR  (0x8b34)
#define NBL_URMUX_ETH3_RX_508_1019_DEPTH (1)
#define NBL_URMUX_ETH3_RX_508_1019_WIDTH (32)
#define NBL_URMUX_ETH3_RX_508_1019_DWLEN (1)
union urmux_eth3_rx_508_1019_u {
	struct urmux_eth3_rx_508_1019 {
		u32 eth3_rx_508_1019:32; /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH3_RX_508_1019_DWLEN];
} __packed;

#define NBL_URMUX_ETH3_RX_1020_1514_ADDR  (0x8b38)
#define NBL_URMUX_ETH3_RX_1020_1514_DEPTH (1)
#define NBL_URMUX_ETH3_RX_1020_1514_WIDTH (32)
#define NBL_URMUX_ETH3_RX_1020_1514_DWLEN (1)
union urmux_eth3_rx_1020_1514_u {
	struct urmux_eth3_rx_1020_1514 {
		u32 eth3_rx_1020_1514:32; /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH3_RX_1020_1514_DWLEN];
} __packed;

#define NBL_URMUX_ETH3_RX_LARGE_1514_ADDR  (0x8b3c)
#define NBL_URMUX_ETH3_RX_LARGE_1514_DEPTH (1)
#define NBL_URMUX_ETH3_RX_LARGE_1514_WIDTH (32)
#define NBL_URMUX_ETH3_RX_LARGE_1514_DWLEN (1)
union urmux_eth3_rx_large_1514_u {
	struct urmux_eth3_rx_large_1514 {
		u32 eth3_rx_large_1514:32; /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH3_RX_LARGE_1514_DWLEN];
} __packed;

#define NBL_URMUX_ETH3_RX_MAC_ERR_ADDR  (0x8b40)
#define NBL_URMUX_ETH3_RX_MAC_ERR_DEPTH (1)
#define NBL_URMUX_ETH3_RX_MAC_ERR_WIDTH (32)
#define NBL_URMUX_ETH3_RX_MAC_ERR_DWLEN (1)
union urmux_eth3_rx_mac_err_u {
	struct urmux_eth3_rx_mac_err {
		u32 eth3_rx_mac_err:32;  /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH3_RX_MAC_ERR_DWLEN];
} __packed;

#define NBL_URMUX_ETH3_RX_OVERLONG_ADDR  (0x8b44)
#define NBL_URMUX_ETH3_RX_OVERLONG_DEPTH (1)
#define NBL_URMUX_ETH3_RX_OVERLONG_WIDTH (32)
#define NBL_URMUX_ETH3_RX_OVERLONG_DWLEN (1)
union urmux_eth3_rx_overlong_u {
	struct urmux_eth3_rx_overlong {
		u32 eth3_rx_overlong:32; /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH3_RX_OVERLONG_DWLEN];
} __packed;

#define NBL_URMUX_ETH3_RX_OVERSHORT_ADDR  (0x8b48)
#define NBL_URMUX_ETH3_RX_OVERSHORT_DEPTH (1)
#define NBL_URMUX_ETH3_RX_OVERSHORT_WIDTH (32)
#define NBL_URMUX_ETH3_RX_OVERSHORT_DWLEN (1)
union urmux_eth3_rx_overshort_u {
	struct urmux_eth3_rx_overshort {
		u32 eth3_rx_overshort:32; /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH3_RX_OVERSHORT_DWLEN];
} __packed;

#define NBL_URMUX_ETH3_RX_SEOP_ERR_ADDR  (0x8b4c)
#define NBL_URMUX_ETH3_RX_SEOP_ERR_DEPTH (1)
#define NBL_URMUX_ETH3_RX_SEOP_ERR_WIDTH (32)
#define NBL_URMUX_ETH3_RX_SEOP_ERR_DWLEN (1)
union urmux_eth3_rx_seop_err_u {
	struct urmux_eth3_rx_seop_err {
		u32 eth3_rx_seop_err:32; /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_URMUX_ETH3_RX_SEOP_ERR_DWLEN];
} __packed;

#endif
