// Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#ifndef NBL_UBM_H
#define NBL_UBM_H 1

#include <linux/types.h>

#define NBL_UBM_BASE (0x0010C000)

#define NBL_UBM_INT_STATUS_ADDR  (0x10c000)
#define NBL_UBM_INT_STATUS_DEPTH (1)
#define NBL_UBM_INT_STATUS_WIDTH (32)
#define NBL_UBM_INT_STATUS_DWLEN (1)
union ubm_int_status_u {
	struct ubm_int_status {
		u32 ucor_err:1;          /* [0] Default:0x0 RWC */
		u32 fifo_w_err:1;        /* [1] Default:0x0 RWC */
		u32 fifo_r_err:1;        /* [2] Default:0x0 RWC */
		u32 mif_wr_err:1;        /* [3] Default:0x0 RWC */
		u32 mif_rd_err:1;        /* [4] Default:0x0 RWC */
		u32 bitmap_pntr_err:1;   /* [5] Default:0x0 RWC */
		u32 tail_pntr_err:1;     /* [6] Default:0x0 RWC */
		u32 weight_pntr_err:1;   /* [7] Default:0x0 RWC */
		u32 cor_err:1;           /* [8] Default:0x0 RWC */
		u32 cif_err:1;           /* [9] Default:0x0 RWC */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UBM_INT_STATUS_DWLEN];
} __packed;

#define NBL_UBM_INT_MASK_ADDR  (0x10c004)
#define NBL_UBM_INT_MASK_DEPTH (1)
#define NBL_UBM_INT_MASK_WIDTH (32)
#define NBL_UBM_INT_MASK_DWLEN (1)
union ubm_int_mask_u {
	struct ubm_int_mask {
		u32 ucor_err:1;          /* [0] Default:0x0 RW */
		u32 fifo_w_err:1;        /* [1] Default:0x0 RW */
		u32 fifo_r_err:1;        /* [2] Default:0x0 RW */
		u32 mif_wr_err:1;        /* [3] Default:0x0 RW */
		u32 mif_rd_err:1;        /* [4] Default:0x0 RW */
		u32 bitmap_pntr_err:1;   /* [5] Default:0x0 RW */
		u32 tail_pntr_err:1;     /* [6] Default:0x0 RW */
		u32 weight_pntr_err:1;   /* [7] Default:0x0 RW */
		u32 cor_err:1;           /* [8] Default:0x0 RW */
		u32 cif_err:1;           /* [9] Default:0x0 RW */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UBM_INT_MASK_DWLEN];
} __packed;

#define NBL_UBM_INT_SET_ADDR  (0x10c008)
#define NBL_UBM_INT_SET_DEPTH (1)
#define NBL_UBM_INT_SET_WIDTH (32)
#define NBL_UBM_INT_SET_DWLEN (1)
union ubm_int_set_u {
	struct ubm_int_set {
		u32 ucor_err:1;          /* [0] Default:0x0 WO */
		u32 fifo_w_err:1;        /* [1] Default:0x0 WO */
		u32 fifo_r_err:1;        /* [2] Default:0x0 WO */
		u32 mif_wr_err:1;        /* [3] Default:0x0 WO */
		u32 mif_rd_err:1;        /* [4] Default:0x0 WO */
		u32 bitmap_pntr_err:1;   /* [5] Default:0x0 WO */
		u32 tail_pntr_err:1;     /* [6] Default:0x0 WO */
		u32 weight_pntr_err:1;   /* [7] Default:0x0 WO */
		u32 cor_err:1;           /* [8] Default:0x0 WO */
		u32 cif_err:1;           /* [9] Default:0x0 WO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UBM_INT_SET_DWLEN];
} __packed;

#define NBL_UBM_UCOR_ERR_INFO_ADDR  (0x10c00c)
#define NBL_UBM_UCOR_ERR_INFO_DEPTH (1)
#define NBL_UBM_UCOR_ERR_INFO_WIDTH (32)
#define NBL_UBM_UCOR_ERR_INFO_DWLEN (1)
union ubm_ucor_err_info_u {
	struct ubm_ucor_err_info {
		u32 ram_addr:12;         /* [11:0] Default:0x0 RO */
		u32 rsv1:4;              /* [15:12] Default:0x0 RO */
		u32 ram_id:4;            /* [19:16] Default:0x0 RO */
		u32 rsv:12;              /* [31:20] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UBM_UCOR_ERR_INFO_DWLEN];
} __packed;

#define NBL_UBM_MIF_WR_ERR_INFO_ADDR  (0x10c02c)
#define NBL_UBM_MIF_WR_ERR_INFO_DEPTH (1)
#define NBL_UBM_MIF_WR_ERR_INFO_WIDTH (32)
#define NBL_UBM_MIF_WR_ERR_INFO_DWLEN (1)
union ubm_mif_wr_err_info_u {
	struct ubm_mif_wr_err_info {
		u32 sel:1;               /* [0] Default:0x0 RO */
		u32 err_type_id:2;       /* [2:1] Default:0x0 RO */
		u32 rsv:29;              /* [31:3] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UBM_MIF_WR_ERR_INFO_DWLEN];
} __packed;

#define NBL_UBM_MIF_RD_ERR_INFO_ADDR  (0x10c034)
#define NBL_UBM_MIF_RD_ERR_INFO_DEPTH (1)
#define NBL_UBM_MIF_RD_ERR_INFO_WIDTH (32)
#define NBL_UBM_MIF_RD_ERR_INFO_DWLEN (1)
union ubm_mif_rd_err_info_u {
	struct ubm_mif_rd_err_info {
		u32 sel:1;               /* [0] Default:0x0 RO */
		u32 err_type_id:1;       /* [1] Default:0x0 RO */
		u32 rsv:30;              /* [31:2] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UBM_MIF_RD_ERR_INFO_DWLEN];
} __packed;

#define NBL_UBM_WEIGHT_PNTR_ERR_INFO_ADDR  (0x10c03c)
#define NBL_UBM_WEIGHT_PNTR_ERR_INFO_DEPTH (1)
#define NBL_UBM_WEIGHT_PNTR_ERR_INFO_WIDTH (32)
#define NBL_UBM_WEIGHT_PNTR_ERR_INFO_DWLEN (1)
union ubm_weight_pntr_err_info_u {
	struct ubm_weight_pntr_err_info {
		u32 ram_addr:12;         /* [11:0] Default:0x0 RO */
		u32 rsv:20;              /* [31:12] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UBM_WEIGHT_PNTR_ERR_INFO_DWLEN];
} __packed;

#define NBL_UBM_TAIL_PNTR_ERR_INFO_ADDR  (0x10c044)
#define NBL_UBM_TAIL_PNTR_ERR_INFO_DEPTH (1)
#define NBL_UBM_TAIL_PNTR_ERR_INFO_WIDTH (32)
#define NBL_UBM_TAIL_PNTR_ERR_INFO_DWLEN (1)
union ubm_tail_pntr_err_info_u {
	struct ubm_tail_pntr_err_info {
		u32 head_pntr:12;        /* [11:0] Default:0x0 RO */
		u32 rsv:20;              /* [31:12] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UBM_TAIL_PNTR_ERR_INFO_DWLEN];
} __packed;

#define NBL_UBM_BITMAP_PNTR_ERR_INFO_ADDR  (0x10c04c)
#define NBL_UBM_BITMAP_PNTR_ERR_INFO_DEPTH (1)
#define NBL_UBM_BITMAP_PNTR_ERR_INFO_WIDTH (32)
#define NBL_UBM_BITMAP_PNTR_ERR_INFO_DWLEN (1)
union ubm_bitmap_pntr_err_info_u {
	struct ubm_bitmap_pntr_err_info {
		u32 ram_addr:12;         /* [11:0] Default:0x0 RO */
		u32 rsv:20;              /* [31:12] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UBM_BITMAP_PNTR_ERR_INFO_DWLEN];
} __packed;

#define NBL_UBM_PNTR_AGING_INFO_ADDR  (0x10c054)
#define NBL_UBM_PNTR_AGING_INFO_DEPTH (1)
#define NBL_UBM_PNTR_AGING_INFO_WIDTH (32)
#define NBL_UBM_PNTR_AGING_INFO_DWLEN (1)
union ubm_pntr_aging_info_u {
	struct ubm_pntr_aging_info {
		u32 addr:12;             /* [11:0] Default:0x0 RO */
		u32 rsv:20;              /* [31:12] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UBM_PNTR_AGING_INFO_DWLEN];
} __packed;

#define NBL_UBM_COR_ERR_INFO_ADDR  (0x10c05c)
#define NBL_UBM_COR_ERR_INFO_DEPTH (1)
#define NBL_UBM_COR_ERR_INFO_WIDTH (32)
#define NBL_UBM_COR_ERR_INFO_DWLEN (1)
union ubm_cor_err_info_u {
	struct ubm_cor_err_info {
		u32 ram_addr:12;         /* [11:0] Default:0x0 RO */
		u32 rsv1:4;              /* [15:12] Default:0x0 RO */
		u32 ram_id:4;            /* [19:16] Default:0x0 RO */
		u32 rsv:12;              /* [31:20] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UBM_COR_ERR_INFO_DWLEN];
} __packed;

#define NBL_UBM_CIF_ERR_INFO_ADDR  (0x10c064)
#define NBL_UBM_CIF_ERR_INFO_DEPTH (1)
#define NBL_UBM_CIF_ERR_INFO_WIDTH (32)
#define NBL_UBM_CIF_ERR_INFO_DWLEN (1)
union ubm_cif_err_info_u {
	struct ubm_cif_err_info {
		u32 addr:30;             /* [29:0] Default:0x0 RO */
		u32 wr_err:1;            /* [30] Default:0x0 RO */
		u32 ucor_err:1;          /* [31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UBM_CIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_UBM_CAR_CTRL_ADDR  (0x10c100)
#define NBL_UBM_CAR_CTRL_DEPTH (1)
#define NBL_UBM_CAR_CTRL_WIDTH (32)
#define NBL_UBM_CAR_CTRL_DWLEN (1)
union ubm_car_ctrl_u {
	struct ubm_car_ctrl {
		u32 sctr_car:1;          /* [0] Default:0x1 RW */
		u32 rctr_car:1;          /* [1] Default:0x1 RW */
		u32 rc_car:1;            /* [2] Default:0x1 RW */
		u32 tbl_rc_car:1;        /* [3] Default:0x1 RW */
		u32 rsv:28;              /* [31:4] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UBM_CAR_CTRL_DWLEN];
} __packed;

#define NBL_UBM_INIT_START_ADDR  (0x10c104)
#define NBL_UBM_INIT_START_DEPTH (1)
#define NBL_UBM_INIT_START_WIDTH (32)
#define NBL_UBM_INIT_START_DWLEN (1)
union ubm_init_start_u {
	struct ubm_init_start {
		u32 init_start:1;        /* [0] Default:0x0 WO */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UBM_INIT_START_DWLEN];
} __packed;

#define NBL_UBM_AGING_EN_ADDR  (0x10c120)
#define NBL_UBM_AGING_EN_DEPTH (1)
#define NBL_UBM_AGING_EN_WIDTH (32)
#define NBL_UBM_AGING_EN_DWLEN (1)
union ubm_aging_en_u {
	struct ubm_aging_en {
		u32 vld:1;               /* [0] Default:0x0 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UBM_AGING_EN_DWLEN];
} __packed;

#define NBL_UBM_AGING_TIME_UNIT_ADDR  (0x10c124)
#define NBL_UBM_AGING_TIME_UNIT_DEPTH (1)
#define NBL_UBM_AGING_TIME_UNIT_WIDTH (32)
#define NBL_UBM_AGING_TIME_UNIT_DWLEN (1)
union ubm_aging_time_unit_u {
	struct ubm_aging_time_unit {
		u32 value:32;            /* [31:0] Default:0xffff RW */
	} __packed info;
	u32 data[NBL_UBM_AGING_TIME_UNIT_DWLEN];
} __packed;

#define NBL_UBM_LIST_RAM_RD_ADDR  (0x10c128)
#define NBL_UBM_LIST_RAM_RD_DEPTH (1)
#define NBL_UBM_LIST_RAM_RD_WIDTH (32)
#define NBL_UBM_LIST_RAM_RD_DWLEN (1)
union ubm_list_ram_rd_u {
	struct ubm_list_ram_rd {
		u32 sel:1;               /* [0] Default:0x0 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UBM_LIST_RAM_RD_DWLEN];
} __packed;

#define NBL_UBM_INIT_DONE_ADDR  (0x10c200)
#define NBL_UBM_INIT_DONE_DEPTH (1)
#define NBL_UBM_INIT_DONE_WIDTH (32)
#define NBL_UBM_INIT_DONE_DWLEN (1)
union ubm_init_done_u {
	struct ubm_init_done {
		u32 done:1;              /* [0] Default:0x0 RO */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UBM_INIT_DONE_DWLEN];
} __packed;

#define NBL_UBM_NFULL_HISTORY_ADDR  (0x10c218)
#define NBL_UBM_NFULL_HISTORY_DEPTH (1)
#define NBL_UBM_NFULL_HISTORY_WIDTH (32)
#define NBL_UBM_NFULL_HISTORY_DWLEN (1)
union ubm_nfull_history_u {
	struct ubm_nfull_history {
		u32 ped:1;               /* [0] Default:0x0 RC */
		u32 uqm:1;               /* [1] Default:0x0 RC */
		u32 split:1;             /* [2] Default:0x0 RC */
		u32 chk:1;               /* [3] Default:0x0 RC */
		u32 pntr:1;              /* [4] Default:0x0 RC */
		u32 rsv:27;              /* [31:5] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UBM_NFULL_HISTORY_DWLEN];
} __packed;

#define NBL_UBM_NAFULL_HISTORY_ADDR  (0x10c21c)
#define NBL_UBM_NAFULL_HISTORY_DEPTH (1)
#define NBL_UBM_NAFULL_HISTORY_WIDTH (32)
#define NBL_UBM_NAFULL_HISTORY_DWLEN (1)
union ubm_nafull_history_u {
	struct ubm_nafull_history {
		u32 ped:1;               /* [0] Default:0x0 RC */
		u32 uqm:1;               /* [1] Default:0x0 RC */
		u32 split:1;             /* [2] Default:0x0 RC */
		u32 chk:1;               /* [3] Default:0x0 RC */
		u32 pntr:1;              /* [4] Default:0x0 RC */
		u32 rsv:27;              /* [31:5] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UBM_NAFULL_HISTORY_DWLEN];
} __packed;

#define NBL_UBM_WERR_HISTORY_ADDR  (0x10c220)
#define NBL_UBM_WERR_HISTORY_DEPTH (1)
#define NBL_UBM_WERR_HISTORY_WIDTH (32)
#define NBL_UBM_WERR_HISTORY_DWLEN (1)
union ubm_werr_history_u {
	struct ubm_werr_history {
		u32 ped:1;               /* [0] Default:0x0 RC */
		u32 uqm:1;               /* [1] Default:0x0 RC */
		u32 split:1;             /* [2] Default:0x0 RC */
		u32 chk:1;               /* [3] Default:0x0 RC */
		u32 pntr:1;              /* [4] Default:0x0 RC */
		u32 rsv:27;              /* [31:5] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UBM_WERR_HISTORY_DWLEN];
} __packed;

#define NBL_UBM_RERR_HISTORY_ADDR  (0x10c224)
#define NBL_UBM_RERR_HISTORY_DEPTH (1)
#define NBL_UBM_RERR_HISTORY_WIDTH (32)
#define NBL_UBM_RERR_HISTORY_DWLEN (1)
union ubm_rerr_history_u {
	struct ubm_rerr_history {
		u32 ped:1;               /* [0] Default:0x0 RC */
		u32 uqm:1;               /* [1] Default:0x0 RC */
		u32 split:1;             /* [2] Default:0x0 RC */
		u32 chk:1;               /* [3] Default:0x0 RC */
		u32 pntr:1;              /* [4] Default:0x0 RC */
		u32 rsv:27;              /* [31:5] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UBM_RERR_HISTORY_DWLEN];
} __packed;

#define NBL_UBM_BITMAP_RAM_STATUS_CURR_ADDR  (0x10c400)
#define NBL_UBM_BITMAP_RAM_STATUS_CURR_DEPTH (128)
#define NBL_UBM_BITMAP_RAM_STATUS_CURR_WIDTH (32)
#define NBL_UBM_BITMAP_RAM_STATUS_CURR_DWLEN (1)
union ubm_bitmap_ram_status_curr_u {
	struct ubm_bitmap_ram_status_curr {
		u32 bitmap_pntr:32;      /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UBM_BITMAP_RAM_STATUS_CURR_DWLEN];
} __packed;
#define NBL_UBM_BITMAP_RAM_STATUS_CURR_REG(r) (NBL_UBM_BITMAP_RAM_STATUS_CURR_ADDR + \
		(NBL_UBM_BITMAP_RAM_STATUS_CURR_DWLEN * 4) * (r))

#define NBL_UBM_LIST_RAM_ADDR  (0x110000)
#define NBL_UBM_LIST_RAM_DEPTH (4096)
#define NBL_UBM_LIST_RAM_WIDTH (32)
#define NBL_UBM_LIST_RAM_DWLEN (1)
union ubm_list_ram_u {
	struct ubm_list_ram {
		u32 pntr:13;             /* [12:0] Default:0x0 RO */
		u32 rsv:19;              /* [31:13] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UBM_LIST_RAM_DWLEN];
} __packed;
#define NBL_UBM_LIST_RAM_REG(r) (NBL_UBM_LIST_RAM_ADDR + \
		(NBL_UBM_LIST_RAM_DWLEN * 4) * (r))

#endif
