// Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#ifndef NBL_CTRLQ_EMP_H
#define NBL_CTRLQ_EMP_H 1

#include <linux/types.h>

#define NBL_CTRLQ_EMP_BASE (0x00F90000)

#define NBL_CTRLQ_EMP_INT_STATUS_ADDR  (0xf90000)
#define NBL_CTRLQ_EMP_INT_STATUS_DEPTH (1)
#define NBL_CTRLQ_EMP_INT_STATUS_WIDTH (32)
#define NBL_CTRLQ_EMP_INT_STATUS_DWLEN (1)
union ctrlq_emp_int_status_u {
	struct ctrlq_emp_int_status {
		u32 fatal_err:1;         /* [00:00] Default:0x0 RWC */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 RWC */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 RWC */
		u32 rsv5:1;              /* [03:03] Default:0x0 RO */
		u32 cif_err:1;           /* [04:04] Default:0x0 RWC */
		u32 rsv4:1;              /* [05:05] Default:0x0 RO */
		u32 rsv3:1;              /* [06:06] Default:0x0 RO */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 RWC */
		u32 rsv2:1;              /* [08:08] Default:0x0 RO */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_INT_STATUS_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_INT_MASK_ADDR  (0xf90004)
#define NBL_CTRLQ_EMP_INT_MASK_DEPTH (1)
#define NBL_CTRLQ_EMP_INT_MASK_WIDTH (32)
#define NBL_CTRLQ_EMP_INT_MASK_DWLEN (1)
union ctrlq_emp_int_mask_u {
	struct ctrlq_emp_int_mask {
		u32 fatal_err:1;         /* [00:00] Default:0x0 RW */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 RW */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 RW */
		u32 rsv5:1;              /* [03:03] Default:0x0 RO */
		u32 cif_err:1;           /* [04:04] Default:0x0 RW */
		u32 rsv4:1;              /* [05:05] Default:0x0 RO */
		u32 rsv3:1;              /* [06:06] Default:0x0 RO */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 RW */
		u32 rsv2:1;              /* [08:08] Default:0x0 RO */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_INT_MASK_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_INT_SET_ADDR  (0xf90008)
#define NBL_CTRLQ_EMP_INT_SET_DEPTH (1)
#define NBL_CTRLQ_EMP_INT_SET_WIDTH (32)
#define NBL_CTRLQ_EMP_INT_SET_DWLEN (1)
union ctrlq_emp_int_set_u {
	struct ctrlq_emp_int_set {
		u32 fatal_err:1;         /* [00:00] Default:0x0 WO */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 WO */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 WO */
		u32 rsv5:1;              /* [03:03] Default:0x0 RO */
		u32 cif_err:1;           /* [04:04] Default:0x0 WO */
		u32 rsv4:1;              /* [05:05] Default:0x0 RO */
		u32 rsv3:1;              /* [06:06] Default:0x0 RO */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 WO */
		u32 rsv2:1;              /* [08:08] Default:0x0 RO */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_INT_SET_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_INIT_DONE_ADDR  (0xf9000c)
#define NBL_CTRLQ_EMP_INIT_DONE_DEPTH (1)
#define NBL_CTRLQ_EMP_INIT_DONE_WIDTH (32)
#define NBL_CTRLQ_EMP_INIT_DONE_DWLEN (1)
union ctrlq_emp_init_done_u {
	struct ctrlq_emp_init_done {
		u32 done:1;              /* [00:00] Default:0x0 RO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_INIT_DONE_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_CIF_ERR_INFO_ADDR  (0xf90040)
#define NBL_CTRLQ_EMP_CIF_ERR_INFO_DEPTH (1)
#define NBL_CTRLQ_EMP_CIF_ERR_INFO_WIDTH (32)
#define NBL_CTRLQ_EMP_CIF_ERR_INFO_DWLEN (1)
union ctrlq_emp_cif_err_info_u {
	struct ctrlq_emp_cif_err_info {
		u32 addr:30;             /* [29:00] Default:0x0 RO */
		u32 wr_err:1;            /* [30:30] Default:0x0 RO */
		u32 ucor_err:1;          /* [31:31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_CIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_CAR_CTRL_ADDR  (0xf90100)
#define NBL_CTRLQ_EMP_CAR_CTRL_DEPTH (1)
#define NBL_CTRLQ_EMP_CAR_CTRL_WIDTH (32)
#define NBL_CTRLQ_EMP_CAR_CTRL_DWLEN (1)
union ctrlq_emp_car_ctrl_u {
	struct ctrlq_emp_car_ctrl {
		u32 sctr_car:1;          /* [00:00] Default:0x1 RW */
		u32 rctr_car:1;          /* [01:01] Default:0x1 RW */
		u32 rc_car:1;            /* [02:02] Default:0x1 RW */
		u32 tbl_rc_car:1;        /* [03:03] Default:0x1 RW */
		u32 rsv:28;              /* [31:04] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_CAR_CTRL_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_QUEUE_SIZE_ADDR  (0xf90200)
#define NBL_CTRLQ_EMP_QUEUE_SIZE_DEPTH (1)
#define NBL_CTRLQ_EMP_QUEUE_SIZE_WIDTH (32)
#define NBL_CTRLQ_EMP_QUEUE_SIZE_DWLEN (1)
union ctrlq_emp_queue_size_u {
	struct ctrlq_emp_queue_size {
		u32 mask:16;             /* [15:0] Default:0x0 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_QUEUE_SIZE_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_QUEUE_BASE_ADDR_ADDR  (0xf90204)
#define NBL_CTRLQ_EMP_QUEUE_BASE_ADDR_DEPTH (1)
#define NBL_CTRLQ_EMP_QUEUE_BASE_ADDR_WIDTH (64)
#define NBL_CTRLQ_EMP_QUEUE_BASE_ADDR_DWLEN (2)
union ctrlq_emp_queue_base_addr_u {
	struct ctrlq_emp_queue_base_addr {
		u32 val_arr[2];          /* [63:00] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_QUEUE_BASE_ADDR_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_QUEUE_RESET_ADDR  (0xf9020c)
#define NBL_CTRLQ_EMP_QUEUE_RESET_DEPTH (1)
#define NBL_CTRLQ_EMP_QUEUE_RESET_WIDTH (32)
#define NBL_CTRLQ_EMP_QUEUE_RESET_DWLEN (1)
union ctrlq_emp_queue_reset_u {
	struct ctrlq_emp_queue_reset {
		u32 vld:1;               /* [00:00] Default:0x0 WO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_QUEUE_RESET_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_QUEUE_NOTIFY_ADDR  (0xf90210)
#define NBL_CTRLQ_EMP_QUEUE_NOTIFY_DEPTH (1)
#define NBL_CTRLQ_EMP_QUEUE_NOTIFY_WIDTH (32)
#define NBL_CTRLQ_EMP_QUEUE_NOTIFY_DWLEN (1)
union ctrlq_emp_queue_notify_u {
	struct ctrlq_emp_queue_notify {
		u32 vld:1;               /* [00:00] Default:0x0 WO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_QUEUE_NOTIFY_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_BDF_ADDR  (0xf90214)
#define NBL_CTRLQ_EMP_BDF_DEPTH (1)
#define NBL_CTRLQ_EMP_BDF_WIDTH (32)
#define NBL_CTRLQ_EMP_BDF_DWLEN (1)
union ctrlq_emp_bdf_u {
	struct ctrlq_emp_bdf {
		u32 bdf:16;              /* [15:0] Default:0x0 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_BDF_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_INTTERUPT_ADDR  (0xf90218)
#define NBL_CTRLQ_EMP_INTTERUPT_DEPTH (1)
#define NBL_CTRLQ_EMP_INTTERUPT_WIDTH (32)
#define NBL_CTRLQ_EMP_INTTERUPT_DWLEN (1)
union ctrlq_emp_intterupt_u {
	struct ctrlq_emp_intterupt {
		u32 en:1;                /* [0] Default:0x0 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_INTTERUPT_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_MSIX_ADDR  (0xf9021c)
#define NBL_CTRLQ_EMP_MSIX_DEPTH (1)
#define NBL_CTRLQ_EMP_MSIX_WIDTH (32)
#define NBL_CTRLQ_EMP_MSIX_DWLEN (1)
union ctrlq_emp_msix_u {
	struct ctrlq_emp_msix {
		u32 idx:16;              /* [15:0] Default:0x0 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_MSIX_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_MODE_ADDR  (0xf90220)
#define NBL_CTRLQ_EMP_MODE_DEPTH (1)
#define NBL_CTRLQ_EMP_MODE_WIDTH (32)
#define NBL_CTRLQ_EMP_MODE_DWLEN (1)
union ctrlq_emp_mode_u {
	struct ctrlq_emp_mode {
		u32 sel:1;               /* [0] Default:0x0 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_MODE_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_INT_CLR_ADDR  (0xf90224)
#define NBL_CTRLQ_EMP_INT_CLR_DEPTH (1)
#define NBL_CTRLQ_EMP_INT_CLR_WIDTH (32)
#define NBL_CTRLQ_EMP_INT_CLR_DWLEN (1)
union ctrlq_emp_int_clr_u {
	struct ctrlq_emp_int_clr {
		u32 en:1;                /* [0] Default:0x0 WO */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_INT_CLR_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_AXI_TIMEOUT_ADDR  (0xf9022c)
#define NBL_CTRLQ_EMP_AXI_TIMEOUT_DEPTH (1)
#define NBL_CTRLQ_EMP_AXI_TIMEOUT_WIDTH (32)
#define NBL_CTRLQ_EMP_AXI_TIMEOUT_DWLEN (1)
union ctrlq_emp_axi_timeout_u {
	struct ctrlq_emp_axi_timeout {
		u32 val:32;              /* [31:0] Default:0x5fffff RW */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_AXI_TIMEOUT_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_QUEUE_STATE_BUSY_ADDR  (0xf90900)
#define NBL_CTRLQ_EMP_QUEUE_STATE_BUSY_DEPTH (1)
#define NBL_CTRLQ_EMP_QUEUE_STATE_BUSY_WIDTH (32)
#define NBL_CTRLQ_EMP_QUEUE_STATE_BUSY_DWLEN (1)
union ctrlq_emp_queue_state_busy_u {
	struct ctrlq_emp_queue_state_busy {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_QUEUE_STATE_BUSY_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_DQDESC_DESC0_ADDR  (0xf90914)
#define NBL_CTRLQ_EMP_DQDESC_DESC0_DEPTH (1)
#define NBL_CTRLQ_EMP_DQDESC_DESC0_WIDTH (32)
#define NBL_CTRLQ_EMP_DQDESC_DESC0_DWLEN (1)
union ctrlq_emp_dqdesc_desc0_u {
	struct ctrlq_emp_dqdesc_desc0 {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_DQDESC_DESC0_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_DQDESC_DESC1_ADDR  (0xf90918)
#define NBL_CTRLQ_EMP_DQDESC_DESC1_DEPTH (1)
#define NBL_CTRLQ_EMP_DQDESC_DESC1_WIDTH (32)
#define NBL_CTRLQ_EMP_DQDESC_DESC1_DWLEN (1)
union ctrlq_emp_dqdesc_desc1_u {
	struct ctrlq_emp_dqdesc_desc1 {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_DQDESC_DESC1_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_DQDESC_DESC2_ADDR  (0xf9091c)
#define NBL_CTRLQ_EMP_DQDESC_DESC2_DEPTH (1)
#define NBL_CTRLQ_EMP_DQDESC_DESC2_WIDTH (32)
#define NBL_CTRLQ_EMP_DQDESC_DESC2_DWLEN (1)
union ctrlq_emp_dqdesc_desc2_u {
	struct ctrlq_emp_dqdesc_desc2 {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_DQDESC_DESC2_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_DQDESC_DESC3_ADDR  (0xf90920)
#define NBL_CTRLQ_EMP_DQDESC_DESC3_DEPTH (1)
#define NBL_CTRLQ_EMP_DQDESC_DESC3_WIDTH (32)
#define NBL_CTRLQ_EMP_DQDESC_DESC3_DWLEN (1)
union ctrlq_emp_dqdesc_desc3_u {
	struct ctrlq_emp_dqdesc_desc3 {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_DQDESC_DESC3_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_DQDESC_DESC4_ADDR  (0xf90924)
#define NBL_CTRLQ_EMP_DQDESC_DESC4_DEPTH (1)
#define NBL_CTRLQ_EMP_DQDESC_DESC4_WIDTH (32)
#define NBL_CTRLQ_EMP_DQDESC_DESC4_DWLEN (1)
union ctrlq_emp_dqdesc_desc4_u {
	struct ctrlq_emp_dqdesc_desc4 {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_DQDESC_DESC4_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_DQDESC_DESC5_ADDR  (0xf90928)
#define NBL_CTRLQ_EMP_DQDESC_DESC5_DEPTH (1)
#define NBL_CTRLQ_EMP_DQDESC_DESC5_WIDTH (32)
#define NBL_CTRLQ_EMP_DQDESC_DESC5_DWLEN (1)
union ctrlq_emp_dqdesc_desc5_u {
	struct ctrlq_emp_dqdesc_desc5 {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_DQDESC_DESC5_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_DQDESC_DESC6_ADDR  (0xf9092c)
#define NBL_CTRLQ_EMP_DQDESC_DESC6_DEPTH (1)
#define NBL_CTRLQ_EMP_DQDESC_DESC6_WIDTH (32)
#define NBL_CTRLQ_EMP_DQDESC_DESC6_DWLEN (1)
union ctrlq_emp_dqdesc_desc6_u {
	struct ctrlq_emp_dqdesc_desc6 {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_DQDESC_DESC6_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_DQDESC_DESC7_ADDR  (0xf90930)
#define NBL_CTRLQ_EMP_DQDESC_DESC7_DEPTH (1)
#define NBL_CTRLQ_EMP_DQDESC_DESC7_WIDTH (32)
#define NBL_CTRLQ_EMP_DQDESC_DESC7_DWLEN (1)
union ctrlq_emp_dqdesc_desc7_u {
	struct ctrlq_emp_dqdesc_desc7 {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_DQDESC_DESC7_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_H2EDMA_RD_ACK_REQ_ADDR  (0xf90938)
#define NBL_CTRLQ_EMP_H2EDMA_RD_ACK_REQ_DEPTH (1)
#define NBL_CTRLQ_EMP_H2EDMA_RD_ACK_REQ_WIDTH (32)
#define NBL_CTRLQ_EMP_H2EDMA_RD_ACK_REQ_DWLEN (1)
union ctrlq_emp_h2edma_rd_ack_req_u {
	struct ctrlq_emp_h2edma_rd_ack_req {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_H2EDMA_RD_ACK_REQ_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_H2EDMA_RD_RVLD_EOB_ADDR  (0xf9093c)
#define NBL_CTRLQ_EMP_H2EDMA_RD_RVLD_EOB_DEPTH (1)
#define NBL_CTRLQ_EMP_H2EDMA_RD_RVLD_EOB_WIDTH (32)
#define NBL_CTRLQ_EMP_H2EDMA_RD_RVLD_EOB_DWLEN (1)
union ctrlq_emp_h2edma_rd_rvld_eob_u {
	struct ctrlq_emp_h2edma_rd_rvld_eob {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_H2EDMA_RD_RVLD_EOB_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_H2EDMA_WR_ACK_REQ_ADDR  (0xf90940)
#define NBL_CTRLQ_EMP_H2EDMA_WR_ACK_REQ_DEPTH (1)
#define NBL_CTRLQ_EMP_H2EDMA_WR_ACK_REQ_WIDTH (32)
#define NBL_CTRLQ_EMP_H2EDMA_WR_ACK_REQ_DWLEN (1)
union ctrlq_emp_h2edma_wr_ack_req_u {
	struct ctrlq_emp_h2edma_wr_ack_req {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_H2EDMA_WR_ACK_REQ_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_H2EDMA_WR_WVLD_EOB_ADDR  (0xf90944)
#define NBL_CTRLQ_EMP_H2EDMA_WR_WVLD_EOB_DEPTH (1)
#define NBL_CTRLQ_EMP_H2EDMA_WR_WVLD_EOB_WIDTH (32)
#define NBL_CTRLQ_EMP_H2EDMA_WR_WVLD_EOB_DWLEN (1)
union ctrlq_emp_h2edma_wr_wvld_eob_u {
	struct ctrlq_emp_h2edma_wr_wvld_eob {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_H2EDMA_WR_WVLD_EOB_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_H2EDMA_WR1_ACK_REQ_ADDR  (0xf90948)
#define NBL_CTRLQ_EMP_H2EDMA_WR1_ACK_REQ_DEPTH (1)
#define NBL_CTRLQ_EMP_H2EDMA_WR1_ACK_REQ_WIDTH (32)
#define NBL_CTRLQ_EMP_H2EDMA_WR1_ACK_REQ_DWLEN (1)
union ctrlq_emp_h2edma_wr1_ack_req_u {
	struct ctrlq_emp_h2edma_wr1_ack_req {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_H2EDMA_WR1_ACK_REQ_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_H2EDMA_WR1_WVLD_EOB_ADDR  (0xf9094c)
#define NBL_CTRLQ_EMP_H2EDMA_WR1_WVLD_EOB_DEPTH (1)
#define NBL_CTRLQ_EMP_H2EDMA_WR1_WVLD_EOB_WIDTH (32)
#define NBL_CTRLQ_EMP_H2EDMA_WR1_WVLD_EOB_DWLEN (1)
union ctrlq_emp_h2edma_wr1_wvld_eob_u {
	struct ctrlq_emp_h2edma_wr1_wvld_eob {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_H2EDMA_WR1_WVLD_EOB_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_E2HDMA_RD_ACK_REQ_ADDR  (0xf90958)
#define NBL_CTRLQ_EMP_E2HDMA_RD_ACK_REQ_DEPTH (1)
#define NBL_CTRLQ_EMP_E2HDMA_RD_ACK_REQ_WIDTH (32)
#define NBL_CTRLQ_EMP_E2HDMA_RD_ACK_REQ_DWLEN (1)
union ctrlq_emp_e2hdma_rd_ack_req_u {
	struct ctrlq_emp_e2hdma_rd_ack_req {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_E2HDMA_RD_ACK_REQ_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_E2HDMA_RD_RVLD_EOB_ADDR  (0xf9095c)
#define NBL_CTRLQ_EMP_E2HDMA_RD_RVLD_EOB_DEPTH (1)
#define NBL_CTRLQ_EMP_E2HDMA_RD_RVLD_EOB_WIDTH (32)
#define NBL_CTRLQ_EMP_E2HDMA_RD_RVLD_EOB_DWLEN (1)
union ctrlq_emp_e2hdma_rd_rvld_eob_u {
	struct ctrlq_emp_e2hdma_rd_rvld_eob {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_E2HDMA_RD_RVLD_EOB_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_E2HDMA_WR_ACK_REQ_ADDR  (0xf90960)
#define NBL_CTRLQ_EMP_E2HDMA_WR_ACK_REQ_DEPTH (1)
#define NBL_CTRLQ_EMP_E2HDMA_WR_ACK_REQ_WIDTH (32)
#define NBL_CTRLQ_EMP_E2HDMA_WR_ACK_REQ_DWLEN (1)
union ctrlq_emp_e2hdma_wr_ack_req_u {
	struct ctrlq_emp_e2hdma_wr_ack_req {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_E2HDMA_WR_ACK_REQ_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_E2HDMA_WR_WVLD_EOB_ADDR  (0xf90964)
#define NBL_CTRLQ_EMP_E2HDMA_WR_WVLD_EOB_DEPTH (1)
#define NBL_CTRLQ_EMP_E2HDMA_WR_WVLD_EOB_WIDTH (32)
#define NBL_CTRLQ_EMP_E2HDMA_WR_WVLD_EOB_DWLEN (1)
union ctrlq_emp_e2hdma_wr_wvld_eob_u {
	struct ctrlq_emp_e2hdma_wr_wvld_eob {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_E2HDMA_WR_WVLD_EOB_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_E2HDMA_WR1_ACK_REQ_ADDR  (0xf90968)
#define NBL_CTRLQ_EMP_E2HDMA_WR1_ACK_REQ_DEPTH (1)
#define NBL_CTRLQ_EMP_E2HDMA_WR1_ACK_REQ_WIDTH (32)
#define NBL_CTRLQ_EMP_E2HDMA_WR1_ACK_REQ_DWLEN (1)
union ctrlq_emp_e2hdma_wr1_ack_req_u {
	struct ctrlq_emp_e2hdma_wr1_ack_req {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_E2HDMA_WR1_ACK_REQ_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_E2HDMA_WR1_WVLD_EOB_ADDR  (0xf9096c)
#define NBL_CTRLQ_EMP_E2HDMA_WR1_WVLD_EOB_DEPTH (1)
#define NBL_CTRLQ_EMP_E2HDMA_WR1_WVLD_EOB_WIDTH (32)
#define NBL_CTRLQ_EMP_E2HDMA_WR1_WVLD_EOB_DWLEN (1)
union ctrlq_emp_e2hdma_wr1_wvld_eob_u {
	struct ctrlq_emp_e2hdma_wr1_wvld_eob {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_E2HDMA_WR1_WVLD_EOB_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_WDIF_ERR_ADDR  (0xf90a00)
#define NBL_CTRLQ_EMP_WDIF_ERR_DEPTH (1)
#define NBL_CTRLQ_EMP_WDIF_ERR_WIDTH (32)
#define NBL_CTRLQ_EMP_WDIF_ERR_DWLEN (1)
union ctrlq_emp_wdif_err_u {
	struct ctrlq_emp_wdif_err {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_WDIF_ERR_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_WDIF_ERR_INFO_ADDR  (0xf90a04)
#define NBL_CTRLQ_EMP_WDIF_ERR_INFO_DEPTH (1)
#define NBL_CTRLQ_EMP_WDIF_ERR_INFO_WIDTH (32)
#define NBL_CTRLQ_EMP_WDIF_ERR_INFO_DWLEN (1)
union ctrlq_emp_wdif_err_info_u {
	struct ctrlq_emp_wdif_err_info {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_WDIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_WDIF_DEBUG_ADDR  (0xf90a20)
#define NBL_CTRLQ_EMP_WDIF_DEBUG_DEPTH (1)
#define NBL_CTRLQ_EMP_WDIF_DEBUG_WIDTH (32)
#define NBL_CTRLQ_EMP_WDIF_DEBUG_DWLEN (1)
union ctrlq_emp_wdif_debug_u {
	struct ctrlq_emp_wdif_debug {
		u32 bdg:32;              /* [31:0] Default:0x1 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_WDIF_DEBUG_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_RDIF_ERR_ADDR  (0xf90a24)
#define NBL_CTRLQ_EMP_RDIF_ERR_DEPTH (1)
#define NBL_CTRLQ_EMP_RDIF_ERR_WIDTH (32)
#define NBL_CTRLQ_EMP_RDIF_ERR_DWLEN (1)
union ctrlq_emp_rdif_err_u {
	struct ctrlq_emp_rdif_err {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_RDIF_ERR_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_RDIF_DEBUG_INFO_ADDR  (0xf90a48)
#define NBL_CTRLQ_EMP_RDIF_DEBUG_INFO_DEPTH (1)
#define NBL_CTRLQ_EMP_RDIF_DEBUG_INFO_WIDTH (32)
#define NBL_CTRLQ_EMP_RDIF_DEBUG_INFO_DWLEN (1)
union ctrlq_emp_rdif_debug_info_u {
	struct ctrlq_emp_rdif_debug_info {
		u32 bdg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_RDIF_DEBUG_INFO_DWLEN];
} __packed;

#define NBL_CTRLQ_EMP_DIF2AXI_ERR_ADDR  (0xf90a54)
#define NBL_CTRLQ_EMP_DIF2AXI_ERR_DEPTH (1)
#define NBL_CTRLQ_EMP_DIF2AXI_ERR_WIDTH (32)
#define NBL_CTRLQ_EMP_DIF2AXI_ERR_DWLEN (1)
union ctrlq_emp_dif2axi_err_u {
	struct ctrlq_emp_dif2axi_err {
		u32 axi_bresp:16;        /* [15:00] Default:0x0 RO */
		u32 axi_rresp:16;        /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CTRLQ_EMP_DIF2AXI_ERR_DWLEN];
} __packed;

#endif
