// Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#ifndef NBL_PCIE_ECPU_H
#define NBL_PCIE_ECPU_H 1

#include <linux/types.h>

#define NBL_PCIE_ECPU_BASE (0x01404000)

#define NBL_PCIE_ECPU_INT_STATUS_ADDR  (0x1404000)
#define NBL_PCIE_ECPU_INT_STATUS_DEPTH (1)
#define NBL_PCIE_ECPU_INT_STATUS_WIDTH (32)
#define NBL_PCIE_ECPU_INT_STATUS_DWLEN (1)
union pcie_ecpu_int_status_u {
	struct pcie_ecpu_int_status {
		u32 fatal_err:1;         /* [00:00] Default:0x0 RWC */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 RWC */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 RWC */
		u32 rsv3:1;              /* [03:03] Default:0x0 RO */
		u32 cif_err:1;           /* [04:04] Default:0x0 RWC */
		u32 rsv2:1;              /* [05:05] Default:0x0 RO */
		u32 cfg_err:1;           /* [06:06] Default:0x0 RWC */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 RWC */
		u32 data_cor_err:1;      /* [08:08] Default:0x0 RWC */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_INT_STATUS_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_INT_MASK_ADDR  (0x1404004)
#define NBL_PCIE_ECPU_INT_MASK_DEPTH (1)
#define NBL_PCIE_ECPU_INT_MASK_WIDTH (32)
#define NBL_PCIE_ECPU_INT_MASK_DWLEN (1)
union pcie_ecpu_int_mask_u {
	struct pcie_ecpu_int_mask {
		u32 fatal_err:1;         /* [00:00] Default:0x0 RW */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 RW */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 RW */
		u32 rsv3:1;              /* [03:03] Default:0x0 RO */
		u32 cif_err:1;           /* [04:04] Default:0x0 RW */
		u32 rsv2:1;              /* [05:05] Default:0x0 RO */
		u32 cfg_err:1;           /* [06:06] Default:0x0 RW */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 RW */
		u32 data_cor_err:1;      /* [08:08] Default:0x0 RW */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_INT_MASK_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_INT_SET_ADDR  (0x1404008)
#define NBL_PCIE_ECPU_INT_SET_DEPTH (1)
#define NBL_PCIE_ECPU_INT_SET_WIDTH (32)
#define NBL_PCIE_ECPU_INT_SET_DWLEN (1)
union pcie_ecpu_int_set_u {
	struct pcie_ecpu_int_set {
		u32 fatal_err:1;         /* [00:00] Default:0x0 WO */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 WO */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 WO */
		u32 rsv3:1;              /* [03:03] Default:0x0 RO */
		u32 cif_err:1;           /* [04:04] Default:0x0 WO */
		u32 rsv2:1;              /* [05:05] Default:0x0 RO */
		u32 cfg_err:1;           /* [06:06] Default:0x0 WO */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 WO */
		u32 data_cor_err:1;      /* [08:08] Default:0x0 WO */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_INT_SET_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_INIT_DONE_ADDR  (0x140400c)
#define NBL_PCIE_ECPU_INIT_DONE_DEPTH (1)
#define NBL_PCIE_ECPU_INIT_DONE_WIDTH (32)
#define NBL_PCIE_ECPU_INIT_DONE_DWLEN (1)
union pcie_ecpu_init_done_u {
	struct pcie_ecpu_init_done {
		u32 done:1;              /* [00:00] Default:0x1 RO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_INIT_DONE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_CIF_ERR_INFO_ADDR  (0x1404040)
#define NBL_PCIE_ECPU_CIF_ERR_INFO_DEPTH (1)
#define NBL_PCIE_ECPU_CIF_ERR_INFO_WIDTH (32)
#define NBL_PCIE_ECPU_CIF_ERR_INFO_DWLEN (1)
union pcie_ecpu_cif_err_info_u {
	struct pcie_ecpu_cif_err_info {
		u32 addr:30;             /* [29:00] Default:0x0 RO */
		u32 wr_err:1;            /* [30:30] Default:0x0 RO */
		u32 ucor_err:1;          /* [31:31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_CIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_CAR_CTRL_ADDR  (0x1404100)
#define NBL_PCIE_ECPU_CAR_CTRL_DEPTH (1)
#define NBL_PCIE_ECPU_CAR_CTRL_WIDTH (32)
#define NBL_PCIE_ECPU_CAR_CTRL_DWLEN (1)
union pcie_ecpu_car_ctrl_u {
	struct pcie_ecpu_car_ctrl {
		u32 sctr_car:1;          /* [00:00] Default:0x1 RW */
		u32 rctr_car:1;          /* [01:01] Default:0x1 RW */
		u32 rc_car:1;            /* [02:02] Default:0x1 RW */
		u32 tbl_rc_car:1;        /* [03:03] Default:0x1 RW */
		u32 rsv:28;              /* [31:04] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_CAR_CTRL_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_CLOCK_FREQ_ADDR  (0x1404200)
#define NBL_PCIE_ECPU_TL_CLOCK_FREQ_DEPTH (1)
#define NBL_PCIE_ECPU_TL_CLOCK_FREQ_WIDTH (32)
#define NBL_PCIE_ECPU_TL_CLOCK_FREQ_DWLEN (1)
union pcie_ecpu_tl_clock_freq_u {
	struct pcie_ecpu_tl_clock_freq {
		u32 dbg:32;              /* [31:00] Default:0x258 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_CLOCK_FREQ_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_OBS_SEL_EN_ADDR  (0x1404304)
#define NBL_PCIE_ECPU_OBS_SEL_EN_DEPTH (1)
#define NBL_PCIE_ECPU_OBS_SEL_EN_WIDTH (32)
#define NBL_PCIE_ECPU_OBS_SEL_EN_DWLEN (1)
union pcie_ecpu_obs_sel_en_u {
	struct pcie_ecpu_obs_sel_en {
		u32 dbg:16;              /* [15:00] Default:0x0 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_OBS_SEL_EN_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PF_MASK_ADDR  (0x1405004)
#define NBL_PCIE_ECPU_K_PF_MASK_DEPTH (1)
#define NBL_PCIE_ECPU_K_PF_MASK_WIDTH (32)
#define NBL_PCIE_ECPU_K_PF_MASK_DWLEN (1)
union pcie_ecpu_k_pf_mask_u {
	struct pcie_ecpu_k_pf_mask {
		u32 dbg:6;               /* [05:00] Default:0x0 RW */
		u32 rsv:26;              /* [31:06] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PF_MASK_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PF_VPD_ADDR  (0x1405008)
#define NBL_PCIE_ECPU_K_PF_VPD_DEPTH (1)
#define NBL_PCIE_ECPU_K_PF_VPD_WIDTH (32)
#define NBL_PCIE_ECPU_K_PF_VPD_DWLEN (1)
union pcie_ecpu_k_pf_vpd_u {
	struct pcie_ecpu_k_pf_vpd {
		u32 dbg:6;               /* [05:00] Default:0x3f RW */
		u32 rsv:26;              /* [31:06] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PF_VPD_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PF0_VENDOR_DEVICE_ADDR  (0x140500c)
#define NBL_PCIE_ECPU_K_PF0_VENDOR_DEVICE_DEPTH (1)
#define NBL_PCIE_ECPU_K_PF0_VENDOR_DEVICE_WIDTH (32)
#define NBL_PCIE_ECPU_K_PF0_VENDOR_DEVICE_DWLEN (1)
union pcie_ecpu_k_pf0_vendor_device_u {
	struct pcie_ecpu_k_pf0_vendor_device {
		u32 id:32;               /* [31:00] Default:0x30001F0F RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PF0_VENDOR_DEVICE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PF0_REV_CLASS_CODE_ADDR  (0x1405010)
#define NBL_PCIE_ECPU_K_PF0_REV_CLASS_CODE_DEPTH (1)
#define NBL_PCIE_ECPU_K_PF0_REV_CLASS_CODE_WIDTH (32)
#define NBL_PCIE_ECPU_K_PF0_REV_CLASS_CODE_DWLEN (1)
union pcie_ecpu_k_pf0_rev_class_code_u {
	struct pcie_ecpu_k_pf0_rev_class_code {
		u32 id:32;               /* [31:00] Default:0x02000000 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PF0_REV_CLASS_CODE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PF0_SUB_VENDOR_DEVICE_ADDR  (0x1405014)
#define NBL_PCIE_ECPU_K_PF0_SUB_VENDOR_DEVICE_DEPTH (1)
#define NBL_PCIE_ECPU_K_PF0_SUB_VENDOR_DEVICE_WIDTH (32)
#define NBL_PCIE_ECPU_K_PF0_SUB_VENDOR_DEVICE_DWLEN (1)
union pcie_ecpu_k_pf0_sub_vendor_device_u {
	struct pcie_ecpu_k_pf0_sub_vendor_device {
		u32 id:32;               /* [31:00] Default:0x00011F0F RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PF0_SUB_VENDOR_DEVICE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PF1_VENDOR_DEVICE_ADDR  (0x1405018)
#define NBL_PCIE_ECPU_K_PF1_VENDOR_DEVICE_DEPTH (1)
#define NBL_PCIE_ECPU_K_PF1_VENDOR_DEVICE_WIDTH (32)
#define NBL_PCIE_ECPU_K_PF1_VENDOR_DEVICE_DWLEN (1)
union pcie_ecpu_k_pf1_vendor_device_u {
	struct pcie_ecpu_k_pf1_vendor_device {
		u32 id:32;               /* [31:00] Default:0x30011F0F RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PF1_VENDOR_DEVICE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PF1_REV_CLASS_CODE_ADDR  (0x140501c)
#define NBL_PCIE_ECPU_K_PF1_REV_CLASS_CODE_DEPTH (1)
#define NBL_PCIE_ECPU_K_PF1_REV_CLASS_CODE_WIDTH (32)
#define NBL_PCIE_ECPU_K_PF1_REV_CLASS_CODE_DWLEN (1)
union pcie_ecpu_k_pf1_rev_class_code_u {
	struct pcie_ecpu_k_pf1_rev_class_code {
		u32 id:32;               /* [31:00] Default:0x02000000 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PF1_REV_CLASS_CODE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PF1_SUB_VENDOR_DEVICE_ADDR  (0x1405020)
#define NBL_PCIE_ECPU_K_PF1_SUB_VENDOR_DEVICE_DEPTH (1)
#define NBL_PCIE_ECPU_K_PF1_SUB_VENDOR_DEVICE_WIDTH (32)
#define NBL_PCIE_ECPU_K_PF1_SUB_VENDOR_DEVICE_DWLEN (1)
union pcie_ecpu_k_pf1_sub_vendor_device_u {
	struct pcie_ecpu_k_pf1_sub_vendor_device {
		u32 id:32;               /* [31:00] Default:0x00011F0F RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PF1_SUB_VENDOR_DEVICE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PF2_VENDOR_DEVICE_ADDR  (0x1405024)
#define NBL_PCIE_ECPU_K_PF2_VENDOR_DEVICE_DEPTH (1)
#define NBL_PCIE_ECPU_K_PF2_VENDOR_DEVICE_WIDTH (32)
#define NBL_PCIE_ECPU_K_PF2_VENDOR_DEVICE_DWLEN (1)
union pcie_ecpu_k_pf2_vendor_device_u {
	struct pcie_ecpu_k_pf2_vendor_device {
		u32 id:32;               /* [31:00] Default:0x30021F0F RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PF2_VENDOR_DEVICE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PF2_REV_CLASS_CODE_ADDR  (0x1405028)
#define NBL_PCIE_ECPU_K_PF2_REV_CLASS_CODE_DEPTH (1)
#define NBL_PCIE_ECPU_K_PF2_REV_CLASS_CODE_WIDTH (32)
#define NBL_PCIE_ECPU_K_PF2_REV_CLASS_CODE_DWLEN (1)
union pcie_ecpu_k_pf2_rev_class_code_u {
	struct pcie_ecpu_k_pf2_rev_class_code {
		u32 id:32;               /* [31:00] Default:0x02000000 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PF2_REV_CLASS_CODE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PF2_SUB_VENDOR_DEVICE_ADDR  (0x140502c)
#define NBL_PCIE_ECPU_K_PF2_SUB_VENDOR_DEVICE_DEPTH (1)
#define NBL_PCIE_ECPU_K_PF2_SUB_VENDOR_DEVICE_WIDTH (32)
#define NBL_PCIE_ECPU_K_PF2_SUB_VENDOR_DEVICE_DWLEN (1)
union pcie_ecpu_k_pf2_sub_vendor_device_u {
	struct pcie_ecpu_k_pf2_sub_vendor_device {
		u32 id:32;               /* [31:00] Default:0x00011F0F RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PF2_SUB_VENDOR_DEVICE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PF3_VENDOR_DEVICE_ADDR  (0x1405030)
#define NBL_PCIE_ECPU_K_PF3_VENDOR_DEVICE_DEPTH (1)
#define NBL_PCIE_ECPU_K_PF3_VENDOR_DEVICE_WIDTH (32)
#define NBL_PCIE_ECPU_K_PF3_VENDOR_DEVICE_DWLEN (1)
union pcie_ecpu_k_pf3_vendor_device_u {
	struct pcie_ecpu_k_pf3_vendor_device {
		u32 id:32;               /* [31:00] Default:0x30031F0F RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PF3_VENDOR_DEVICE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PF3_REV_CLASS_CODE_ADDR  (0x1405034)
#define NBL_PCIE_ECPU_K_PF3_REV_CLASS_CODE_DEPTH (1)
#define NBL_PCIE_ECPU_K_PF3_REV_CLASS_CODE_WIDTH (32)
#define NBL_PCIE_ECPU_K_PF3_REV_CLASS_CODE_DWLEN (1)
union pcie_ecpu_k_pf3_rev_class_code_u {
	struct pcie_ecpu_k_pf3_rev_class_code {
		u32 id:32;               /* [31:00] Default:0x02000000 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PF3_REV_CLASS_CODE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PF3_SUB_VENDOR_DEVICE_ADDR  (0x1405038)
#define NBL_PCIE_ECPU_K_PF3_SUB_VENDOR_DEVICE_DEPTH (1)
#define NBL_PCIE_ECPU_K_PF3_SUB_VENDOR_DEVICE_WIDTH (32)
#define NBL_PCIE_ECPU_K_PF3_SUB_VENDOR_DEVICE_DWLEN (1)
union pcie_ecpu_k_pf3_sub_vendor_device_u {
	struct pcie_ecpu_k_pf3_sub_vendor_device {
		u32 id:32;               /* [31:00] Default:0x00011F0F RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PF3_SUB_VENDOR_DEVICE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PF4_VENDOR_DEVICE_ADDR  (0x140503c)
#define NBL_PCIE_ECPU_K_PF4_VENDOR_DEVICE_DEPTH (1)
#define NBL_PCIE_ECPU_K_PF4_VENDOR_DEVICE_WIDTH (32)
#define NBL_PCIE_ECPU_K_PF4_VENDOR_DEVICE_DWLEN (1)
union pcie_ecpu_k_pf4_vendor_device_u {
	struct pcie_ecpu_k_pf4_vendor_device {
		u32 id:32;               /* [31:00] Default:0x30041F0F RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PF4_VENDOR_DEVICE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PF4_REV_CLASS_CODE_ADDR  (0x1405040)
#define NBL_PCIE_ECPU_K_PF4_REV_CLASS_CODE_DEPTH (1)
#define NBL_PCIE_ECPU_K_PF4_REV_CLASS_CODE_WIDTH (32)
#define NBL_PCIE_ECPU_K_PF4_REV_CLASS_CODE_DWLEN (1)
union pcie_ecpu_k_pf4_rev_class_code_u {
	struct pcie_ecpu_k_pf4_rev_class_code {
		u32 id:32;               /* [31:00] Default:0x02000000 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PF4_REV_CLASS_CODE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PF4_SUB_VENDOR_DEVICE_ADDR  (0x1405044)
#define NBL_PCIE_ECPU_K_PF4_SUB_VENDOR_DEVICE_DEPTH (1)
#define NBL_PCIE_ECPU_K_PF4_SUB_VENDOR_DEVICE_WIDTH (32)
#define NBL_PCIE_ECPU_K_PF4_SUB_VENDOR_DEVICE_DWLEN (1)
union pcie_ecpu_k_pf4_sub_vendor_device_u {
	struct pcie_ecpu_k_pf4_sub_vendor_device {
		u32 id:32;               /* [31:00] Default:0x00011F0F RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PF4_SUB_VENDOR_DEVICE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PF5_VENDOR_DEVICE_ADDR  (0x1405048)
#define NBL_PCIE_ECPU_K_PF5_VENDOR_DEVICE_DEPTH (1)
#define NBL_PCIE_ECPU_K_PF5_VENDOR_DEVICE_WIDTH (32)
#define NBL_PCIE_ECPU_K_PF5_VENDOR_DEVICE_DWLEN (1)
union pcie_ecpu_k_pf5_vendor_device_u {
	struct pcie_ecpu_k_pf5_vendor_device {
		u32 id:32;               /* [31:00] Default:0x30051F0F RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PF5_VENDOR_DEVICE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PF5_REV_CLASS_CODE_ADDR  (0x140504c)
#define NBL_PCIE_ECPU_K_PF5_REV_CLASS_CODE_DEPTH (1)
#define NBL_PCIE_ECPU_K_PF5_REV_CLASS_CODE_WIDTH (32)
#define NBL_PCIE_ECPU_K_PF5_REV_CLASS_CODE_DWLEN (1)
union pcie_ecpu_k_pf5_rev_class_code_u {
	struct pcie_ecpu_k_pf5_rev_class_code {
		u32 id:32;               /* [31:00] Default:0x02000000 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PF5_REV_CLASS_CODE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PF5_SUB_VENDOR_DEVICE_ADDR  (0x1405050)
#define NBL_PCIE_ECPU_K_PF5_SUB_VENDOR_DEVICE_DEPTH (1)
#define NBL_PCIE_ECPU_K_PF5_SUB_VENDOR_DEVICE_WIDTH (32)
#define NBL_PCIE_ECPU_K_PF5_SUB_VENDOR_DEVICE_DWLEN (1)
union pcie_ecpu_k_pf5_sub_vendor_device_u {
	struct pcie_ecpu_k_pf5_sub_vendor_device {
		u32 id:32;               /* [31:00] Default:0x00011F0F RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PF5_SUB_VENDOR_DEVICE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_PMA0_MEM_DEEPSLEEP_ADDR  (0x14050a0)
#define NBL_PCIE_ECPU_PMA0_MEM_DEEPSLEEP_DEPTH (1)
#define NBL_PCIE_ECPU_PMA0_MEM_DEEPSLEEP_WIDTH (32)
#define NBL_PCIE_ECPU_PMA0_MEM_DEEPSLEEP_DWLEN (1)
union pcie_ecpu_pma0_mem_deepsleep_u {
	struct pcie_ecpu_pma0_mem_deepsleep {
		u32 dbg:1;               /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_PMA0_MEM_DEEPSLEEP_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_PMA0_PRGM_PARITY_ENABLE_ADDR  (0x14050a4)
#define NBL_PCIE_ECPU_PMA0_PRGM_PARITY_ENABLE_DEPTH (1)
#define NBL_PCIE_ECPU_PMA0_PRGM_PARITY_ENABLE_WIDTH (32)
#define NBL_PCIE_ECPU_PMA0_PRGM_PARITY_ENABLE_DWLEN (1)
union pcie_ecpu_pma0_prgm_parity_enable_u {
	struct pcie_ecpu_pma0_prgm_parity_enable {
		u32 dbg:1;               /* [00:00] Default:0x1 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_PMA0_PRGM_PARITY_ENABLE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_PMA_PMLD_LOCK_REG_ADDR  (0x14050c0)
#define NBL_PCIE_ECPU_PMA_PMLD_LOCK_REG_DEPTH (1)
#define NBL_PCIE_ECPU_PMA_PMLD_LOCK_REG_WIDTH (32)
#define NBL_PCIE_ECPU_PMA_PMLD_LOCK_REG_DWLEN (1)
union pcie_ecpu_pma_pmld_lock_reg_u {
	struct pcie_ecpu_pma_pmld_lock_reg {
		u32 dbg:32;              /* [31:00] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_PMA_PMLD_LOCK_REG_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_PMA0_PHY_CTRL_REFCLK_ADDR  (0x14050c8)
#define NBL_PCIE_ECPU_PMA0_PHY_CTRL_REFCLK_DEPTH (1)
#define NBL_PCIE_ECPU_PMA0_PHY_CTRL_REFCLK_WIDTH (32)
#define NBL_PCIE_ECPU_PMA0_PHY_CTRL_REFCLK_DWLEN (1)
union pcie_ecpu_pma0_phy_ctrl_refclk_u {
	struct pcie_ecpu_pma0_phy_ctrl_refclk {
		u32 dbg:5;               /* [04:00] Default:0x14 RW */
		u32 rsv:27;              /* [31:05] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_PMA0_PHY_CTRL_REFCLK_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_PMA0_PHY_CTRL_VDDA_SEL_ADDR  (0x14050cc)
#define NBL_PCIE_ECPU_PMA0_PHY_CTRL_VDDA_SEL_DEPTH (1)
#define NBL_PCIE_ECPU_PMA0_PHY_CTRL_VDDA_SEL_WIDTH (32)
#define NBL_PCIE_ECPU_PMA0_PHY_CTRL_VDDA_SEL_DWLEN (1)
union pcie_ecpu_pma0_phy_ctrl_vdda_sel_u {
	struct pcie_ecpu_pma0_phy_ctrl_vdda_sel {
		u32 dbg:1;               /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_PMA0_PHY_CTRL_VDDA_SEL_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_PMA0_PHY_CTRL_VDDHA_SEL_ADDR  (0x14050d0)
#define NBL_PCIE_ECPU_PMA0_PHY_CTRL_VDDHA_SEL_DEPTH (1)
#define NBL_PCIE_ECPU_PMA0_PHY_CTRL_VDDHA_SEL_WIDTH (32)
#define NBL_PCIE_ECPU_PMA0_PHY_CTRL_VDDHA_SEL_DWLEN (1)
union pcie_ecpu_pma0_phy_ctrl_vddha_sel_u {
	struct pcie_ecpu_pma0_phy_ctrl_vddha_sel {
		u32 dbg:1;               /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_PMA0_PHY_CTRL_VDDHA_SEL_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PM_EVENT_ADDR  (0x1406100)
#define NBL_PCIE_ECPU_TL_PM_EVENT_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PM_EVENT_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PM_EVENT_DWLEN (1)
union pcie_ecpu_tl_pm_event_u {
	struct pcie_ecpu_tl_pm_event {
		u32 dbg:6;               /* [05:00] Default:0x0 RW */
		u32 rsv:26;              /* [31:06] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PM_EVENT_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_CLK_GATE_ADDR  (0x1406104)
#define NBL_PCIE_ECPU_TL_CLK_GATE_DEPTH (1)
#define NBL_PCIE_ECPU_TL_CLK_GATE_WIDTH (32)
#define NBL_PCIE_ECPU_TL_CLK_GATE_DWLEN (1)
union pcie_ecpu_tl_clk_gate_u {
	struct pcie_ecpu_tl_clk_gate {
		u32 dbg:1;               /* [00:00] Default:0x0 RO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_CLK_GATE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_LINK_UP_ADDR  (0x1406108)
#define NBL_PCIE_ECPU_LINK_UP_DEPTH (1)
#define NBL_PCIE_ECPU_LINK_UP_WIDTH (32)
#define NBL_PCIE_ECPU_LINK_UP_DWLEN (1)
union pcie_ecpu_link_up_u {
	struct pcie_ecpu_link_up {
		u32 dbg:1;               /* [00:00] Default:0x0 RO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_LINK_UP_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_MPERST_N_ADDR  (0x140610c)
#define NBL_PCIE_ECPU_MPERST_N_DEPTH (1)
#define NBL_PCIE_ECPU_MPERST_N_WIDTH (32)
#define NBL_PCIE_ECPU_MPERST_N_DWLEN (1)
union pcie_ecpu_mperst_n_u {
	struct pcie_ecpu_mperst_n {
		u32 dbg:1;               /* [00:00] Default:0x0 RO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_MPERST_N_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PM_L2_STATUS_ADDR  (0x1406110)
#define NBL_PCIE_ECPU_TL_PM_L2_STATUS_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PM_L2_STATUS_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PM_L2_STATUS_DWLEN (1)
union pcie_ecpu_tl_pm_l2_status_u {
	struct pcie_ecpu_tl_pm_l2_status {
		u32 dbg:1;               /* [00:00] Default:0x0 RO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PM_L2_STATUS_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_PL_LTSSM_ADDR  (0x1406114)
#define NBL_PCIE_ECPU_PL_LTSSM_DEPTH (1)
#define NBL_PCIE_ECPU_PL_LTSSM_WIDTH (32)
#define NBL_PCIE_ECPU_PL_LTSSM_DWLEN (1)
union pcie_ecpu_pl_ltssm_u {
	struct pcie_ecpu_pl_ltssm {
		u32 dbg:5;               /* [04:00] Default:0x0 RO */
		u32 rsv:27;              /* [31:05] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_PL_LTSSM_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_LTSSM_HISTORY0_ADDR  (0x1406118)
#define NBL_PCIE_ECPU_LTSSM_HISTORY0_DEPTH (1)
#define NBL_PCIE_ECPU_LTSSM_HISTORY0_WIDTH (32)
#define NBL_PCIE_ECPU_LTSSM_HISTORY0_DWLEN (1)
union pcie_ecpu_ltssm_history0_u {
	struct pcie_ecpu_ltssm_history0 {
		u32 dbg:32;              /* [31:00] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_LTSSM_HISTORY0_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_LTSSM_HISTORY1_ADDR  (0x140611c)
#define NBL_PCIE_ECPU_LTSSM_HISTORY1_DEPTH (1)
#define NBL_PCIE_ECPU_LTSSM_HISTORY1_WIDTH (32)
#define NBL_PCIE_ECPU_LTSSM_HISTORY1_DWLEN (1)
union pcie_ecpu_ltssm_history1_u {
	struct pcie_ecpu_ltssm_history1 {
		u32 dbg:32;              /* [31:00] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_LTSSM_HISTORY1_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_LTSSM_HISTORY2_ADDR  (0x1406120)
#define NBL_PCIE_ECPU_LTSSM_HISTORY2_DEPTH (1)
#define NBL_PCIE_ECPU_LTSSM_HISTORY2_WIDTH (32)
#define NBL_PCIE_ECPU_LTSSM_HISTORY2_DWLEN (1)
union pcie_ecpu_ltssm_history2_u {
	struct pcie_ecpu_ltssm_history2 {
		u32 dbg:32;              /* [31:00] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_LTSSM_HISTORY2_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_LTSSM_HISTORY3_ADDR  (0x1406124)
#define NBL_PCIE_ECPU_LTSSM_HISTORY3_DEPTH (1)
#define NBL_PCIE_ECPU_LTSSM_HISTORY3_WIDTH (32)
#define NBL_PCIE_ECPU_LTSSM_HISTORY3_DWLEN (1)
union pcie_ecpu_ltssm_history3_u {
	struct pcie_ecpu_ltssm_history3 {
		u32 dbg:32;              /* [31:00] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_LTSSM_HISTORY3_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_CFG_REGS0_ADDR  (0x1406130)
#define NBL_PCIE_ECPU_TL_CFG_REGS0_DEPTH (1)
#define NBL_PCIE_ECPU_TL_CFG_REGS0_WIDTH (32)
#define NBL_PCIE_ECPU_TL_CFG_REGS0_DWLEN (1)
union pcie_ecpu_tl_cfg_regs0_u {
	struct pcie_ecpu_tl_cfg_regs0 {
		u32 dbg:28;              /* [27:00] Default:0x0 RO */
		u32 rsv:4;               /* [31:28] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_CFG_REGS0_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_CFG_REGS1_ADDR  (0x1406134)
#define NBL_PCIE_ECPU_TL_CFG_REGS1_DEPTH (1)
#define NBL_PCIE_ECPU_TL_CFG_REGS1_WIDTH (32)
#define NBL_PCIE_ECPU_TL_CFG_REGS1_DWLEN (1)
union pcie_ecpu_tl_cfg_regs1_u {
	struct pcie_ecpu_tl_cfg_regs1 {
		u32 dbg:12;              /* [11:00] Default:0x0 RO */
		u32 rsv:20;              /* [31:12] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_CFG_REGS1_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_CFG_REGS2_ADDR  (0x1406138)
#define NBL_PCIE_ECPU_TL_CFG_REGS2_DEPTH (1)
#define NBL_PCIE_ECPU_TL_CFG_REGS2_WIDTH (32)
#define NBL_PCIE_ECPU_TL_CFG_REGS2_DWLEN (1)
union pcie_ecpu_tl_cfg_regs2_u {
	struct pcie_ecpu_tl_cfg_regs2 {
		u32 dbg:1;               /* [00:00] Default:0x0 RO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_CFG_REGS2_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PF0_VPD_ADDR  (0x1406200)
#define NBL_PCIE_ECPU_TL_PF0_VPD_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PF0_VPD_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PF0_VPD_DWLEN (1)
union pcie_ecpu_tl_pf0_vpd_u {
	struct pcie_ecpu_tl_pf0_vpd {
		u32 addr:15;             /* [14:00] Default:0x0 RO */
		u32 flag:1;              /* [15] Default:0x0 RO */
		u32 enable:1;            /* [16] Default:0x0 RO */
		u32 status:4;            /* [20:17] Default:0x0 RO */
		u32 rsv:11;              /* [31:21] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PF0_VPD_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PF0_VPD_WR_ADDR  (0x1406204)
#define NBL_PCIE_ECPU_TL_PF0_VPD_WR_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PF0_VPD_WR_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PF0_VPD_WR_DWLEN (1)
union pcie_ecpu_tl_pf0_vpd_wr_u {
	struct pcie_ecpu_tl_pf0_vpd_wr {
		u32 data:32;             /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PF0_VPD_WR_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PF0_VPD_RD_ADDR  (0x1406208)
#define NBL_PCIE_ECPU_TL_PF0_VPD_RD_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PF0_VPD_RD_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PF0_VPD_RD_DWLEN (1)
union pcie_ecpu_tl_pf0_vpd_rd_u {
	struct pcie_ecpu_tl_pf0_vpd_rd {
		u32 data:32;             /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PF0_VPD_RD_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PF0_VPD_R_ADDR  (0x140620c)
#define NBL_PCIE_ECPU_TL_PF0_VPD_R_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PF0_VPD_R_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PF0_VPD_R_DWLEN (1)
union pcie_ecpu_tl_pf0_vpd_r_u {
	struct pcie_ecpu_tl_pf0_vpd_r {
		u32 ready:1;             /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PF0_VPD_R_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PF1_VPD_ADDR  (0x1406210)
#define NBL_PCIE_ECPU_TL_PF1_VPD_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PF1_VPD_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PF1_VPD_DWLEN (1)
union pcie_ecpu_tl_pf1_vpd_u {
	struct pcie_ecpu_tl_pf1_vpd {
		u32 addr:15;             /* [14:00] Default:0x0 RO */
		u32 flag:1;              /* [15] Default:0x0 RO */
		u32 enable:1;            /* [16] Default:0x0 RO */
		u32 status:4;            /* [20:17] Default:0x0 RO */
		u32 rsv:11;              /* [31:21] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PF1_VPD_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PF1_VPD_WR_ADDR  (0x1406214)
#define NBL_PCIE_ECPU_TL_PF1_VPD_WR_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PF1_VPD_WR_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PF1_VPD_WR_DWLEN (1)
union pcie_ecpu_tl_pf1_vpd_wr_u {
	struct pcie_ecpu_tl_pf1_vpd_wr {
		u32 data:32;             /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PF1_VPD_WR_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PF1_VPD_RD_ADDR  (0x1406218)
#define NBL_PCIE_ECPU_TL_PF1_VPD_RD_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PF1_VPD_RD_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PF1_VPD_RD_DWLEN (1)
union pcie_ecpu_tl_pf1_vpd_rd_u {
	struct pcie_ecpu_tl_pf1_vpd_rd {
		u32 data:32;             /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PF1_VPD_RD_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PF1_VPD_R_ADDR  (0x140621c)
#define NBL_PCIE_ECPU_TL_PF1_VPD_R_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PF1_VPD_R_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PF1_VPD_R_DWLEN (1)
union pcie_ecpu_tl_pf1_vpd_r_u {
	struct pcie_ecpu_tl_pf1_vpd_r {
		u32 ready:1;             /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PF1_VPD_R_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PF2_VPD_ADDR  (0x1406220)
#define NBL_PCIE_ECPU_TL_PF2_VPD_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PF2_VPD_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PF2_VPD_DWLEN (1)
union pcie_ecpu_tl_pf2_vpd_u {
	struct pcie_ecpu_tl_pf2_vpd {
		u32 addr:15;             /* [14:00] Default:0x0 RO */
		u32 flag:1;              /* [15] Default:0x0 RO */
		u32 enable:1;            /* [16] Default:0x0 RO */
		u32 status:4;            /* [20:17] Default:0x0 RO */
		u32 rsv:11;              /* [31:21] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PF2_VPD_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PF2_VPD_WR_ADDR  (0x1406224)
#define NBL_PCIE_ECPU_TL_PF2_VPD_WR_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PF2_VPD_WR_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PF2_VPD_WR_DWLEN (1)
union pcie_ecpu_tl_pf2_vpd_wr_u {
	struct pcie_ecpu_tl_pf2_vpd_wr {
		u32 data:32;             /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PF2_VPD_WR_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PF2_VPD_RD_ADDR  (0x1406228)
#define NBL_PCIE_ECPU_TL_PF2_VPD_RD_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PF2_VPD_RD_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PF2_VPD_RD_DWLEN (1)
union pcie_ecpu_tl_pf2_vpd_rd_u {
	struct pcie_ecpu_tl_pf2_vpd_rd {
		u32 data:32;             /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PF2_VPD_RD_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PF2_VPD_R_ADDR  (0x140622c)
#define NBL_PCIE_ECPU_TL_PF2_VPD_R_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PF2_VPD_R_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PF2_VPD_R_DWLEN (1)
union pcie_ecpu_tl_pf2_vpd_r_u {
	struct pcie_ecpu_tl_pf2_vpd_r {
		u32 ready:1;             /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PF2_VPD_R_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PF3_VPD_ADDR  (0x1406230)
#define NBL_PCIE_ECPU_TL_PF3_VPD_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PF3_VPD_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PF3_VPD_DWLEN (1)
union pcie_ecpu_tl_pf3_vpd_u {
	struct pcie_ecpu_tl_pf3_vpd {
		u32 addr:15;             /* [14:00] Default:0x0 RO */
		u32 flag:1;              /* [15] Default:0x0 RO */
		u32 enable:1;            /* [16] Default:0x0 RO */
		u32 status:4;            /* [20:17] Default:0x0 RO */
		u32 rsv:11;              /* [31:21] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PF3_VPD_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PF3_VPD_WR_ADDR  (0x1406234)
#define NBL_PCIE_ECPU_TL_PF3_VPD_WR_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PF3_VPD_WR_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PF3_VPD_WR_DWLEN (1)
union pcie_ecpu_tl_pf3_vpd_wr_u {
	struct pcie_ecpu_tl_pf3_vpd_wr {
		u32 data:32;             /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PF3_VPD_WR_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PF3_VPD_RD_ADDR  (0x1406238)
#define NBL_PCIE_ECPU_TL_PF3_VPD_RD_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PF3_VPD_RD_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PF3_VPD_RD_DWLEN (1)
union pcie_ecpu_tl_pf3_vpd_rd_u {
	struct pcie_ecpu_tl_pf3_vpd_rd {
		u32 data:32;             /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PF3_VPD_RD_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PF3_VPD_R_ADDR  (0x140623c)
#define NBL_PCIE_ECPU_TL_PF3_VPD_R_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PF3_VPD_R_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PF3_VPD_R_DWLEN (1)
union pcie_ecpu_tl_pf3_vpd_r_u {
	struct pcie_ecpu_tl_pf3_vpd_r {
		u32 ready:1;             /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PF3_VPD_R_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PF4_VPD_ADDR  (0x1406240)
#define NBL_PCIE_ECPU_TL_PF4_VPD_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PF4_VPD_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PF4_VPD_DWLEN (1)
union pcie_ecpu_tl_pf4_vpd_u {
	struct pcie_ecpu_tl_pf4_vpd {
		u32 addr:15;             /* [14:00] Default:0x0 RO */
		u32 flag:1;              /* [15] Default:0x0 RO */
		u32 enable:1;            /* [16] Default:0x0 RO */
		u32 status:4;            /* [20:17] Default:0x0 RO */
		u32 rsv:11;              /* [31:21] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PF4_VPD_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PF4_VPD_WR_ADDR  (0x1406244)
#define NBL_PCIE_ECPU_TL_PF4_VPD_WR_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PF4_VPD_WR_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PF4_VPD_WR_DWLEN (1)
union pcie_ecpu_tl_pf4_vpd_wr_u {
	struct pcie_ecpu_tl_pf4_vpd_wr {
		u32 data:32;             /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PF4_VPD_WR_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PF4_VPD_RD_ADDR  (0x1406248)
#define NBL_PCIE_ECPU_TL_PF4_VPD_RD_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PF4_VPD_RD_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PF4_VPD_RD_DWLEN (1)
union pcie_ecpu_tl_pf4_vpd_rd_u {
	struct pcie_ecpu_tl_pf4_vpd_rd {
		u32 data:32;             /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PF4_VPD_RD_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PF4_VPD_R_ADDR  (0x140624c)
#define NBL_PCIE_ECPU_TL_PF4_VPD_R_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PF4_VPD_R_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PF4_VPD_R_DWLEN (1)
union pcie_ecpu_tl_pf4_vpd_r_u {
	struct pcie_ecpu_tl_pf4_vpd_r {
		u32 ready:1;             /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PF4_VPD_R_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PF5_VPD_ADDR  (0x1406250)
#define NBL_PCIE_ECPU_TL_PF5_VPD_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PF5_VPD_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PF5_VPD_DWLEN (1)
union pcie_ecpu_tl_pf5_vpd_u {
	struct pcie_ecpu_tl_pf5_vpd {
		u32 addr:15;             /* [14:00] Default:0x0 RO */
		u32 flag:1;              /* [15] Default:0x0 RO */
		u32 enable:1;            /* [16] Default:0x0 RO */
		u32 status:4;            /* [20:17] Default:0x0 RO */
		u32 rsv:11;              /* [31:21] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PF5_VPD_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PF5_VPD_WR_ADDR  (0x1406254)
#define NBL_PCIE_ECPU_TL_PF5_VPD_WR_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PF5_VPD_WR_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PF5_VPD_WR_DWLEN (1)
union pcie_ecpu_tl_pf5_vpd_wr_u {
	struct pcie_ecpu_tl_pf5_vpd_wr {
		u32 data:32;             /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PF5_VPD_WR_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PF5_VPD_RD_ADDR  (0x1406258)
#define NBL_PCIE_ECPU_TL_PF5_VPD_RD_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PF5_VPD_RD_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PF5_VPD_RD_DWLEN (1)
union pcie_ecpu_tl_pf5_vpd_rd_u {
	struct pcie_ecpu_tl_pf5_vpd_rd {
		u32 data:32;             /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PF5_VPD_RD_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_PF5_VPD_R_ADDR  (0x140625c)
#define NBL_PCIE_ECPU_TL_PF5_VPD_R_DEPTH (1)
#define NBL_PCIE_ECPU_TL_PF5_VPD_R_WIDTH (32)
#define NBL_PCIE_ECPU_TL_PF5_VPD_R_DWLEN (1)
union pcie_ecpu_tl_pf5_vpd_r_u {
	struct pcie_ecpu_tl_pf5_vpd_r {
		u32 ready:1;             /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_PF5_VPD_R_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_GEN_SPEED_ADDR  (0x1407000)
#define NBL_PCIE_ECPU_K_GEN_SPEED_DEPTH (1)
#define NBL_PCIE_ECPU_K_GEN_SPEED_WIDTH (32)
#define NBL_PCIE_ECPU_K_GEN_SPEED_DWLEN (1)
union pcie_ecpu_k_gen_speed_u {
	struct pcie_ecpu_k_gen_speed {
		u32 dbg:4;               /* [03:00] Default:0xF RW */
		u32 rsv:28;              /* [31:04] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_GEN_SPEED_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_GEN_LANE_REVERSAL_ADDR  (0x1407004)
#define NBL_PCIE_ECPU_K_GEN_LANE_REVERSAL_DEPTH (1)
#define NBL_PCIE_ECPU_K_GEN_LANE_REVERSAL_WIDTH (32)
#define NBL_PCIE_ECPU_K_GEN_LANE_REVERSAL_DWLEN (1)
union pcie_ecpu_k_gen_lane_reversal_u {
	struct pcie_ecpu_k_gen_lane_reversal {
		u32 dbg:1;               /* [00:00] Default:0x1 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_GEN_LANE_REVERSAL_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_GEN_EQU_PHA23_ADDR  (0x1407008)
#define NBL_PCIE_ECPU_K_GEN_EQU_PHA23_DEPTH (1)
#define NBL_PCIE_ECPU_K_GEN_EQU_PHA23_WIDTH (32)
#define NBL_PCIE_ECPU_K_GEN_EQU_PHA23_DWLEN (1)
union pcie_ecpu_k_gen_equ_pha23_u {
	struct pcie_ecpu_k_gen_equ_pha23 {
		u32 dbg:1;               /* [00:00] Default:0x1 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_GEN_EQU_PHA23_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_GEN_LANE_DISABLE_ADDR  (0x140700c)
#define NBL_PCIE_ECPU_K_GEN_LANE_DISABLE_DEPTH (1)
#define NBL_PCIE_ECPU_K_GEN_LANE_DISABLE_WIDTH (32)
#define NBL_PCIE_ECPU_K_GEN_LANE_DISABLE_DWLEN (1)
union pcie_ecpu_k_gen_lane_disable_u {
	struct pcie_ecpu_k_gen_lane_disable {
		u32 dbg:4;               /* [03:00] Default:0x0 RW */
		u32 rsv:28;              /* [31:04] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_GEN_LANE_DISABLE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_GEN_USE_RXELECILDE_ADDR  (0x1407010)
#define NBL_PCIE_ECPU_K_GEN_USE_RXELECILDE_DEPTH (1)
#define NBL_PCIE_ECPU_K_GEN_USE_RXELECILDE_WIDTH (32)
#define NBL_PCIE_ECPU_K_GEN_USE_RXELECILDE_DWLEN (1)
union pcie_ecpu_k_gen_use_rxelecilde_u {
	struct pcie_ecpu_k_gen_use_rxelecilde {
		u32 dbg:1;               /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_GEN_USE_RXELECILDE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_GEN_ERR_MODE_ADDR  (0x1407014)
#define NBL_PCIE_ECPU_K_GEN_ERR_MODE_DEPTH (1)
#define NBL_PCIE_ECPU_K_GEN_ERR_MODE_WIDTH (32)
#define NBL_PCIE_ECPU_K_GEN_ERR_MODE_DWLEN (1)
union pcie_ecpu_k_gen_err_mode_u {
	struct pcie_ecpu_k_gen_err_mode {
		u32 dbg:2;               /* [01:00] Default:0x1 RW */
		u32 rsv:30;              /* [31:02] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_GEN_ERR_MODE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_GEN_RX_VLD_FILTER_EN_ADDR  (0x1407018)
#define NBL_PCIE_ECPU_K_GEN_RX_VLD_FILTER_EN_DEPTH (1)
#define NBL_PCIE_ECPU_K_GEN_RX_VLD_FILTER_EN_WIDTH (32)
#define NBL_PCIE_ECPU_K_GEN_RX_VLD_FILTER_EN_DWLEN (1)
union pcie_ecpu_k_gen_rx_vld_filter_en_u {
	struct pcie_ecpu_k_gen_rx_vld_filter_en {
		u32 dbg:1;               /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_GEN_RX_VLD_FILTER_EN_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_10B_TAG_REQUESTER_SUPPORT_ADDR  (0x140701c)
#define NBL_PCIE_ECPU_K_10B_TAG_REQUESTER_SUPPORT_DEPTH (1)
#define NBL_PCIE_ECPU_K_10B_TAG_REQUESTER_SUPPORT_WIDTH (32)
#define NBL_PCIE_ECPU_K_10B_TAG_REQUESTER_SUPPORT_DWLEN (1)
union pcie_ecpu_k_10b_tag_requester_support_u {
	struct pcie_ecpu_k_10b_tag_requester_support {
		u32 dbg:1;               /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_10B_TAG_REQUESTER_SUPPORT_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_10B_TAG_COMPLETER_SUPPORT_ADDR  (0x1407020)
#define NBL_PCIE_ECPU_K_10B_TAG_COMPLETER_SUPPORT_DEPTH (1)
#define NBL_PCIE_ECPU_K_10B_TAG_COMPLETER_SUPPORT_WIDTH (32)
#define NBL_PCIE_ECPU_K_10B_TAG_COMPLETER_SUPPORT_DWLEN (1)
union pcie_ecpu_k_10b_tag_completer_support_u {
	struct pcie_ecpu_k_10b_tag_completer_support {
		u32 dbg:1;               /* [00:00] Default:0x1 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_10B_TAG_COMPLETER_SUPPORT_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PCI_PM_ADDR  (0x1407028)
#define NBL_PCIE_ECPU_K_PCI_PM_DEPTH (1)
#define NBL_PCIE_ECPU_K_PCI_PM_WIDTH (32)
#define NBL_PCIE_ECPU_K_PCI_PM_DWLEN (1)
union pcie_ecpu_k_pci_pm_u {
	struct pcie_ecpu_k_pci_pm {
		u32 dbg:10;              /* [09:00] Default:0x320 RW */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PCI_PM_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PEX_EP_ACCEPT_LATENCY_ADDR  (0x140702c)
#define NBL_PCIE_ECPU_K_PEX_EP_ACCEPT_LATENCY_DEPTH (1)
#define NBL_PCIE_ECPU_K_PEX_EP_ACCEPT_LATENCY_WIDTH (32)
#define NBL_PCIE_ECPU_K_PEX_EP_ACCEPT_LATENCY_DWLEN (1)
union pcie_ecpu_k_pex_ep_accept_latency_u {
	struct pcie_ecpu_k_pex_ep_accept_latency {
		u32 dbg:6;               /* [05:00] Default:0x33 RW */
		u32 rsv:26;              /* [31:06] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PEX_EP_ACCEPT_LATENCY_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PEX_COMPTO_ADDR  (0x1407030)
#define NBL_PCIE_ECPU_K_PEX_COMPTO_DEPTH (1)
#define NBL_PCIE_ECPU_K_PEX_COMPTO_WIDTH (32)
#define NBL_PCIE_ECPU_K_PEX_COMPTO_DWLEN (1)
union pcie_ecpu_k_pex_compto_u {
	struct pcie_ecpu_k_pex_compto {
		u32 dbg:5;               /* [04:00] Default:0x13 RW */
		u32 rsv:27;              /* [31:05] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PEX_COMPTO_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PEX_LINK_CAP_ADDR  (0x1407034)
#define NBL_PCIE_ECPU_K_PEX_LINK_CAP_DEPTH (1)
#define NBL_PCIE_ECPU_K_PEX_LINK_CAP_WIDTH (32)
#define NBL_PCIE_ECPU_K_PEX_LINK_CAP_DWLEN (1)
union pcie_ecpu_k_pex_link_cap_u {
	struct pcie_ecpu_k_pex_link_cap {
		u32 dbg:11;              /* [10:00] Default:0x57 RW */
		u32 rsv:21;              /* [31:11] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PEX_LINK_CAP_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PEX_EC_VECTOR_SIZE_ADDR  (0x1407038)
#define NBL_PCIE_ECPU_K_PEX_EC_VECTOR_SIZE_DEPTH (1)
#define NBL_PCIE_ECPU_K_PEX_EC_VECTOR_SIZE_WIDTH (32)
#define NBL_PCIE_ECPU_K_PEX_EC_VECTOR_SIZE_DWLEN (1)
union pcie_ecpu_k_pex_ec_vector_size_u {
	struct pcie_ecpu_k_pex_ec_vector_size {
		u32 dbg:7;               /* [06:00] Default:0x3f RW */
		u32 rsv:25;              /* [31:07] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PEX_EC_VECTOR_SIZE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PEX_ASPM_ENTRY_DELAY_ADDR  (0x140703c)
#define NBL_PCIE_ECPU_K_PEX_ASPM_ENTRY_DELAY_DEPTH (1)
#define NBL_PCIE_ECPU_K_PEX_ASPM_ENTRY_DELAY_WIDTH (32)
#define NBL_PCIE_ECPU_K_PEX_ASPM_ENTRY_DELAY_DWLEN (1)
union pcie_ecpu_k_pex_aspm_entry_delay_u {
	struct pcie_ecpu_k_pex_aspm_entry_delay {
		u32 dbg:15;              /* [14:00] Default:0x190c RW */
		u32 rsv:17;              /* [31:15] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PEX_ASPM_ENTRY_DELAY_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PEX_FTS_NUM_ADDR  (0x1407040)
#define NBL_PCIE_ECPU_K_PEX_FTS_NUM_DEPTH (1)
#define NBL_PCIE_ECPU_K_PEX_FTS_NUM_WIDTH (32)
#define NBL_PCIE_ECPU_K_PEX_FTS_NUM_DWLEN (1)
union pcie_ecpu_k_pex_fts_num_u {
	struct pcie_ecpu_k_pex_fts_num {
		u32 dbg:32;              /* [31:0] Default:0x3c3cd2d2 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PEX_FTS_NUM_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_PEX_L1_PM_ADDR  (0x1407044)
#define NBL_PCIE_ECPU_K_PEX_L1_PM_DEPTH (1)
#define NBL_PCIE_ECPU_K_PEX_L1_PM_WIDTH (32)
#define NBL_PCIE_ECPU_K_PEX_L1_PM_DWLEN (1)
union pcie_ecpu_k_pex_l1_pm_u {
	struct pcie_ecpu_k_pex_l1_pm {
		u32 dbg:28;              /* [27:00] Default:0x0 RW */
		u32 rsv:4;               /* [31:28] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_PEX_L1_PM_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_EQUPRESET_USER1_ADDR  (0x1407048)
#define NBL_PCIE_ECPU_K_EQUPRESET_USER1_DEPTH (1)
#define NBL_PCIE_ECPU_K_EQUPRESET_USER1_WIDTH (32)
#define NBL_PCIE_ECPU_K_EQUPRESET_USER1_DWLEN (1)
union pcie_ecpu_k_equpreset_user1_u {
	struct pcie_ecpu_k_equpreset_user1 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_EQUPRESET_USER1_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_EQUPRESET_USER2_ADDR  (0x140704c)
#define NBL_PCIE_ECPU_K_EQUPRESET_USER2_DEPTH (1)
#define NBL_PCIE_ECPU_K_EQUPRESET_USER2_WIDTH (32)
#define NBL_PCIE_ECPU_K_EQUPRESET_USER2_DWLEN (1)
union pcie_ecpu_k_equpreset_user2_u {
	struct pcie_ecpu_k_equpreset_user2 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_EQUPRESET_USER2_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_EQUPRESET_USER3_ADDR  (0x1407050)
#define NBL_PCIE_ECPU_K_EQUPRESET_USER3_DEPTH (1)
#define NBL_PCIE_ECPU_K_EQUPRESET_USER3_WIDTH (32)
#define NBL_PCIE_ECPU_K_EQUPRESET_USER3_DWLEN (1)
union pcie_ecpu_k_equpreset_user3_u {
	struct pcie_ecpu_k_equpreset_user3 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_EQUPRESET_USER3_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_EQUPRESET_USER4_ADDR  (0x1407054)
#define NBL_PCIE_ECPU_K_EQUPRESET_USER4_DEPTH (1)
#define NBL_PCIE_ECPU_K_EQUPRESET_USER4_WIDTH (32)
#define NBL_PCIE_ECPU_K_EQUPRESET_USER4_DWLEN (1)
union pcie_ecpu_k_equpreset_user4_u {
	struct pcie_ecpu_k_equpreset_user4 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_EQUPRESET_USER4_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_EQUPRESET_USER5_ADDR  (0x1407058)
#define NBL_PCIE_ECPU_K_EQUPRESET_USER5_DEPTH (1)
#define NBL_PCIE_ECPU_K_EQUPRESET_USER5_WIDTH (32)
#define NBL_PCIE_ECPU_K_EQUPRESET_USER5_DWLEN (1)
union pcie_ecpu_k_equpreset_user5_u {
	struct pcie_ecpu_k_equpreset_user5 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_EQUPRESET_USER5_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_EQUPRESET_USER6_ADDR  (0x140705c)
#define NBL_PCIE_ECPU_K_EQUPRESET_USER6_DEPTH (1)
#define NBL_PCIE_ECPU_K_EQUPRESET_USER6_WIDTH (32)
#define NBL_PCIE_ECPU_K_EQUPRESET_USER6_DWLEN (1)
union pcie_ecpu_k_equpreset_user6_u {
	struct pcie_ecpu_k_equpreset_user6 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_EQUPRESET_USER6_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_EQUPRESET_USER7_ADDR  (0x1407060)
#define NBL_PCIE_ECPU_K_EQUPRESET_USER7_DEPTH (1)
#define NBL_PCIE_ECPU_K_EQUPRESET_USER7_WIDTH (32)
#define NBL_PCIE_ECPU_K_EQUPRESET_USER7_DWLEN (1)
union pcie_ecpu_k_equpreset_user7_u {
	struct pcie_ecpu_k_equpreset_user7 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_EQUPRESET_USER7_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_EQUPRESET_USER8_ADDR  (0x1407064)
#define NBL_PCIE_ECPU_K_EQUPRESET_USER8_DEPTH (1)
#define NBL_PCIE_ECPU_K_EQUPRESET_USER8_WIDTH (32)
#define NBL_PCIE_ECPU_K_EQUPRESET_USER8_DWLEN (1)
union pcie_ecpu_k_equpreset_user8_u {
	struct pcie_ecpu_k_equpreset_user8 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_EQUPRESET_USER8_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_EQUPRESET16_USER1_ADDR  (0x1407068)
#define NBL_PCIE_ECPU_K_EQUPRESET16_USER1_DEPTH (1)
#define NBL_PCIE_ECPU_K_EQUPRESET16_USER1_WIDTH (32)
#define NBL_PCIE_ECPU_K_EQUPRESET16_USER1_DWLEN (1)
union pcie_ecpu_k_equpreset16_user1_u {
	struct pcie_ecpu_k_equpreset16_user1 {
		u32 dbg:32;              /* [31:0] Default:0xf4f4f4f4 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_EQUPRESET16_USER1_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_EQUPRESET16_USER2_ADDR  (0x140706c)
#define NBL_PCIE_ECPU_K_EQUPRESET16_USER2_DEPTH (1)
#define NBL_PCIE_ECPU_K_EQUPRESET16_USER2_WIDTH (32)
#define NBL_PCIE_ECPU_K_EQUPRESET16_USER2_DWLEN (1)
union pcie_ecpu_k_equpreset16_user2_u {
	struct pcie_ecpu_k_equpreset16_user2 {
		u32 dbg:32;              /* [31:0] Default:0xf4f4f4f4 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_EQUPRESET16_USER2_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_EQUPRESET16_USER3_ADDR  (0x1407070)
#define NBL_PCIE_ECPU_K_EQUPRESET16_USER3_DEPTH (1)
#define NBL_PCIE_ECPU_K_EQUPRESET16_USER3_WIDTH (32)
#define NBL_PCIE_ECPU_K_EQUPRESET16_USER3_DWLEN (1)
union pcie_ecpu_k_equpreset16_user3_u {
	struct pcie_ecpu_k_equpreset16_user3 {
		u32 dbg:32;              /* [31:0] Default:0xf4f4f4f4 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_EQUPRESET16_USER3_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_EQUPRESET16_USER4_ADDR  (0x1407074)
#define NBL_PCIE_ECPU_K_EQUPRESET16_USER4_DEPTH (1)
#define NBL_PCIE_ECPU_K_EQUPRESET16_USER4_WIDTH (32)
#define NBL_PCIE_ECPU_K_EQUPRESET16_USER4_DWLEN (1)
union pcie_ecpu_k_equpreset16_user4_u {
	struct pcie_ecpu_k_equpreset16_user4 {
		u32 dbg:32;              /* [31:0] Default:0xf4f4f4f4 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_EQUPRESET16_USER4_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_TIMER_USER1_ADDR  (0x1407078)
#define NBL_PCIE_ECPU_K_TIMER_USER1_DEPTH (1)
#define NBL_PCIE_ECPU_K_TIMER_USER1_WIDTH (32)
#define NBL_PCIE_ECPU_K_TIMER_USER1_DWLEN (1)
union pcie_ecpu_k_timer_user1_u {
	struct pcie_ecpu_k_timer_user1 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_TIMER_USER1_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_TIMER_USER2_ADDR  (0x140707c)
#define NBL_PCIE_ECPU_K_TIMER_USER2_DEPTH (1)
#define NBL_PCIE_ECPU_K_TIMER_USER2_WIDTH (32)
#define NBL_PCIE_ECPU_K_TIMER_USER2_DWLEN (1)
union pcie_ecpu_k_timer_user2_u {
	struct pcie_ecpu_k_timer_user2 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_TIMER_USER2_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_TIMER_USER3_ADDR  (0x1407080)
#define NBL_PCIE_ECPU_K_TIMER_USER3_DEPTH (1)
#define NBL_PCIE_ECPU_K_TIMER_USER3_WIDTH (32)
#define NBL_PCIE_ECPU_K_TIMER_USER3_DWLEN (1)
union pcie_ecpu_k_timer_user3_u {
	struct pcie_ecpu_k_timer_user3 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_TIMER_USER3_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_TIMER_USER4_ADDR  (0x1407084)
#define NBL_PCIE_ECPU_K_TIMER_USER4_DEPTH (1)
#define NBL_PCIE_ECPU_K_TIMER_USER4_WIDTH (32)
#define NBL_PCIE_ECPU_K_TIMER_USER4_DWLEN (1)
union pcie_ecpu_k_timer_user4_u {
	struct pcie_ecpu_k_timer_user4 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_TIMER_USER4_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_TIMER_USER5_ADDR  (0x1407088)
#define NBL_PCIE_ECPU_K_TIMER_USER5_DEPTH (1)
#define NBL_PCIE_ECPU_K_TIMER_USER5_WIDTH (32)
#define NBL_PCIE_ECPU_K_TIMER_USER5_DWLEN (1)
union pcie_ecpu_k_timer_user5_u {
	struct pcie_ecpu_k_timer_user5 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_TIMER_USER5_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_TIMER_USER6_ADDR  (0x140708c)
#define NBL_PCIE_ECPU_K_TIMER_USER6_DEPTH (1)
#define NBL_PCIE_ECPU_K_TIMER_USER6_WIDTH (32)
#define NBL_PCIE_ECPU_K_TIMER_USER6_DWLEN (1)
union pcie_ecpu_k_timer_user6_u {
	struct pcie_ecpu_k_timer_user6 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_TIMER_USER6_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_TIMER_USER7_ADDR  (0x1407090)
#define NBL_PCIE_ECPU_K_TIMER_USER7_DEPTH (1)
#define NBL_PCIE_ECPU_K_TIMER_USER7_WIDTH (32)
#define NBL_PCIE_ECPU_K_TIMER_USER7_DWLEN (1)
union pcie_ecpu_k_timer_user7_u {
	struct pcie_ecpu_k_timer_user7 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_TIMER_USER7_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_TIMER_USER8_ADDR  (0x1407094)
#define NBL_PCIE_ECPU_K_TIMER_USER8_DEPTH (1)
#define NBL_PCIE_ECPU_K_TIMER_USER8_WIDTH (32)
#define NBL_PCIE_ECPU_K_TIMER_USER8_DWLEN (1)
union pcie_ecpu_k_timer_user8_u {
	struct pcie_ecpu_k_timer_user8 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_TIMER_USER8_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_TIMER_USER9_ADDR  (0x1407098)
#define NBL_PCIE_ECPU_K_TIMER_USER9_DEPTH (1)
#define NBL_PCIE_ECPU_K_TIMER_USER9_WIDTH (32)
#define NBL_PCIE_ECPU_K_TIMER_USER9_DWLEN (1)
union pcie_ecpu_k_timer_user9_u {
	struct pcie_ecpu_k_timer_user9 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_TIMER_USER9_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_TIMER_USER10_ADDR  (0x140709c)
#define NBL_PCIE_ECPU_K_TIMER_USER10_DEPTH (1)
#define NBL_PCIE_ECPU_K_TIMER_USER10_WIDTH (32)
#define NBL_PCIE_ECPU_K_TIMER_USER10_DWLEN (1)
union pcie_ecpu_k_timer_user10_u {
	struct pcie_ecpu_k_timer_user10 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_TIMER_USER10_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_TIMER_USER11_ADDR  (0x14070a0)
#define NBL_PCIE_ECPU_K_TIMER_USER11_DEPTH (1)
#define NBL_PCIE_ECPU_K_TIMER_USER11_WIDTH (32)
#define NBL_PCIE_ECPU_K_TIMER_USER11_DWLEN (1)
union pcie_ecpu_k_timer_user11_u {
	struct pcie_ecpu_k_timer_user11 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_TIMER_USER11_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_TIMER_USER12_ADDR  (0x14070a4)
#define NBL_PCIE_ECPU_K_TIMER_USER12_DEPTH (1)
#define NBL_PCIE_ECPU_K_TIMER_USER12_WIDTH (32)
#define NBL_PCIE_ECPU_K_TIMER_USER12_DWLEN (1)
union pcie_ecpu_k_timer_user12_u {
	struct pcie_ecpu_k_timer_user12 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_TIMER_USER12_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_TIMER_USER13_ADDR  (0x14070a8)
#define NBL_PCIE_ECPU_K_TIMER_USER13_DEPTH (1)
#define NBL_PCIE_ECPU_K_TIMER_USER13_WIDTH (32)
#define NBL_PCIE_ECPU_K_TIMER_USER13_DWLEN (1)
union pcie_ecpu_k_timer_user13_u {
	struct pcie_ecpu_k_timer_user13 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_TIMER_USER13_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_TIMER_USER14_ADDR  (0x14070ac)
#define NBL_PCIE_ECPU_K_TIMER_USER14_DEPTH (1)
#define NBL_PCIE_ECPU_K_TIMER_USER14_WIDTH (32)
#define NBL_PCIE_ECPU_K_TIMER_USER14_DWLEN (1)
union pcie_ecpu_k_timer_user14_u {
	struct pcie_ecpu_k_timer_user14 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_TIMER_USER14_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_TIMER_USER15_ADDR  (0x14070b0)
#define NBL_PCIE_ECPU_K_TIMER_USER15_DEPTH (1)
#define NBL_PCIE_ECPU_K_TIMER_USER15_WIDTH (32)
#define NBL_PCIE_ECPU_K_TIMER_USER15_DWLEN (1)
union pcie_ecpu_k_timer_user15_u {
	struct pcie_ecpu_k_timer_user15 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_TIMER_USER15_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_TIMER_USER16_ADDR  (0x14070b4)
#define NBL_PCIE_ECPU_K_TIMER_USER16_DEPTH (1)
#define NBL_PCIE_ECPU_K_TIMER_USER16_WIDTH (32)
#define NBL_PCIE_ECPU_K_TIMER_USER16_DWLEN (1)
union pcie_ecpu_k_timer_user16_u {
	struct pcie_ecpu_k_timer_user16 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_TIMER_USER16_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_TIMER_USER17_ADDR  (0x14070b8)
#define NBL_PCIE_ECPU_K_TIMER_USER17_DEPTH (1)
#define NBL_PCIE_ECPU_K_TIMER_USER17_WIDTH (32)
#define NBL_PCIE_ECPU_K_TIMER_USER17_DWLEN (1)
union pcie_ecpu_k_timer_user17_u {
	struct pcie_ecpu_k_timer_user17 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_TIMER_USER17_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_TIMER_USER18_ADDR  (0x14070bc)
#define NBL_PCIE_ECPU_K_TIMER_USER18_DEPTH (1)
#define NBL_PCIE_ECPU_K_TIMER_USER18_WIDTH (32)
#define NBL_PCIE_ECPU_K_TIMER_USER18_DWLEN (1)
union pcie_ecpu_k_timer_user18_u {
	struct pcie_ecpu_k_timer_user18 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_TIMER_USER18_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_TIMER_USER19_ADDR  (0x14070c0)
#define NBL_PCIE_ECPU_K_TIMER_USER19_DEPTH (1)
#define NBL_PCIE_ECPU_K_TIMER_USER19_WIDTH (32)
#define NBL_PCIE_ECPU_K_TIMER_USER19_DWLEN (1)
union pcie_ecpu_k_timer_user19_u {
	struct pcie_ecpu_k_timer_user19 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_TIMER_USER19_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_TIMER_USER20_ADDR  (0x14070c4)
#define NBL_PCIE_ECPU_K_TIMER_USER20_DEPTH (1)
#define NBL_PCIE_ECPU_K_TIMER_USER20_WIDTH (32)
#define NBL_PCIE_ECPU_K_TIMER_USER20_DWLEN (1)
union pcie_ecpu_k_timer_user20_u {
	struct pcie_ecpu_k_timer_user20 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_TIMER_USER20_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_TIMER_USER21_ADDR  (0x14070c8)
#define NBL_PCIE_ECPU_K_TIMER_USER21_DEPTH (1)
#define NBL_PCIE_ECPU_K_TIMER_USER21_WIDTH (32)
#define NBL_PCIE_ECPU_K_TIMER_USER21_DWLEN (1)
union pcie_ecpu_k_timer_user21_u {
	struct pcie_ecpu_k_timer_user21 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_TIMER_USER21_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_TIMER_USER22_ADDR  (0x14070cc)
#define NBL_PCIE_ECPU_K_TIMER_USER22_DEPTH (1)
#define NBL_PCIE_ECPU_K_TIMER_USER22_WIDTH (32)
#define NBL_PCIE_ECPU_K_TIMER_USER22_DWLEN (1)
union pcie_ecpu_k_timer_user22_u {
	struct pcie_ecpu_k_timer_user22 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_TIMER_USER22_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_TIMER_USER23_ADDR  (0x14070d0)
#define NBL_PCIE_ECPU_K_TIMER_USER23_DEPTH (1)
#define NBL_PCIE_ECPU_K_TIMER_USER23_WIDTH (32)
#define NBL_PCIE_ECPU_K_TIMER_USER23_DWLEN (1)
union pcie_ecpu_k_timer_user23_u {
	struct pcie_ecpu_k_timer_user23 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_TIMER_USER23_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_K_TIMER_USER24_ADDR  (0x14070d4)
#define NBL_PCIE_ECPU_K_TIMER_USER24_DEPTH (1)
#define NBL_PCIE_ECPU_K_TIMER_USER24_WIDTH (32)
#define NBL_PCIE_ECPU_K_TIMER_USER24_DWLEN (1)
union pcie_ecpu_k_timer_user24_u {
	struct pcie_ecpu_k_timer_user24 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_K_TIMER_USER24_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TEST_OUT_CLR_ADDR  (0x1408000)
#define NBL_PCIE_ECPU_TEST_OUT_CLR_DEPTH (1)
#define NBL_PCIE_ECPU_TEST_OUT_CLR_WIDTH (32)
#define NBL_PCIE_ECPU_TEST_OUT_CLR_DWLEN (1)
union pcie_ecpu_test_out_clr_u {
	struct pcie_ecpu_test_out_clr {
		u32 dbg:1;               /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TEST_OUT_CLR_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_ERROR_ADDR  (0x1414000)
#define NBL_PCIE_ECPU_ERROR_DEPTH (1)
#define NBL_PCIE_ECPU_ERROR_WIDTH (32)
#define NBL_PCIE_ECPU_ERROR_DWLEN (1)
union pcie_ecpu_error_u {
	struct pcie_ecpu_error {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_ERROR_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_WARNING_ADDR  (0x1414004)
#define NBL_PCIE_ECPU_WARNING_DEPTH (1)
#define NBL_PCIE_ECPU_WARNING_WIDTH (32)
#define NBL_PCIE_ECPU_WARNING_DWLEN (1)
union pcie_ecpu_warning_u {
	struct pcie_ecpu_warning {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_WARNING_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_LAST_ERR_ADDR  (0x1414090)
#define NBL_PCIE_ECPU_LAST_ERR_DEPTH (1)
#define NBL_PCIE_ECPU_LAST_ERR_WIDTH (32)
#define NBL_PCIE_ECPU_LAST_ERR_DWLEN (1)
union pcie_ecpu_last_err_u {
	struct pcie_ecpu_last_err {
		u32 index:18;            /* [17:0] Default:0x0 RO */
		u32 rsv:14;              /* [31:18] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_LAST_ERR_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TEST_IN_ADDR  (0x1415028)
#define NBL_PCIE_ECPU_TEST_IN_DEPTH (1)
#define NBL_PCIE_ECPU_TEST_IN_WIDTH (64)
#define NBL_PCIE_ECPU_TEST_IN_DWLEN (2)
union pcie_ecpu_test_in_u {
	struct pcie_ecpu_test_in {
		u32 dbg_arr[2];          /* [63:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TEST_IN_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TEST_IN_ERRINJ_ADDR  (0x1415030)
#define NBL_PCIE_ECPU_TEST_IN_ERRINJ_DEPTH (1)
#define NBL_PCIE_ECPU_TEST_IN_ERRINJ_WIDTH (32)
#define NBL_PCIE_ECPU_TEST_IN_ERRINJ_DWLEN (1)
union pcie_ecpu_test_in_errinj_u {
	struct pcie_ecpu_test_in_errinj {
		u32 dbg:32;              /* [31:00] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TEST_IN_ERRINJ_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_PL_LTSSM_ENABLE_ADDR  (0x1415034)
#define NBL_PCIE_ECPU_PL_LTSSM_ENABLE_DEPTH (1)
#define NBL_PCIE_ECPU_PL_LTSSM_ENABLE_WIDTH (32)
#define NBL_PCIE_ECPU_PL_LTSSM_ENABLE_DWLEN (1)
union pcie_ecpu_pl_ltssm_enable_u {
	struct pcie_ecpu_pl_ltssm_enable {
		u32 dbg:1;               /* [00:00] Default:0x1 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_PL_LTSSM_ENABLE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_PL_EQU_PHASE_ADDR  (0x141503c)
#define NBL_PCIE_ECPU_PL_EQU_PHASE_DEPTH (1)
#define NBL_PCIE_ECPU_PL_EQU_PHASE_WIDTH (32)
#define NBL_PCIE_ECPU_PL_EQU_PHASE_DWLEN (1)
union pcie_ecpu_pl_equ_phase_u {
	struct pcie_ecpu_pl_equ_phase {
		u32 dbg:2;               /* [01:00] Default:0x0 RO */
		u32 rsv:30;              /* [31:02] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_PL_EQU_PHASE_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_CFG_BUSDEV_ADDR  (0x1415040)
#define NBL_PCIE_ECPU_TL_CFG_BUSDEV_DEPTH (1)
#define NBL_PCIE_ECPU_TL_CFG_BUSDEV_WIDTH (32)
#define NBL_PCIE_ECPU_TL_CFG_BUSDEV_DWLEN (1)
union pcie_ecpu_tl_cfg_busdev_u {
	struct pcie_ecpu_tl_cfg_busdev {
		u32 dbg:13;              /* [12:00] Default:0x0 RO */
		u32 rsv:19;              /* [31:13] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_CFG_BUSDEV_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TL_REPORT_TIMER_ADDR  (0x1415044)
#define NBL_PCIE_ECPU_TL_REPORT_TIMER_DEPTH (1)
#define NBL_PCIE_ECPU_TL_REPORT_TIMER_WIDTH (32)
#define NBL_PCIE_ECPU_TL_REPORT_TIMER_DWLEN (1)
union pcie_ecpu_tl_report_timer_u {
	struct pcie_ecpu_tl_report_timer {
		u32 dbg:4;               /* [03:00] Default:0x0 RO */
		u32 rsv:28;              /* [31:04] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TL_REPORT_TIMER_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TEST_OUT_TL_ADDR  (0x1415048)
#define NBL_PCIE_ECPU_TEST_OUT_TL_DEPTH (8)
#define NBL_PCIE_ECPU_TEST_OUT_TL_WIDTH (32)
#define NBL_PCIE_ECPU_TEST_OUT_TL_DWLEN (1)
union pcie_ecpu_test_out_tl_u {
	struct pcie_ecpu_test_out_tl {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TEST_OUT_TL_DWLEN];
} __packed;
#define NBL_PCIE_ECPU_TEST_OUT_TL_REG(r) (NBL_PCIE_ECPU_TEST_OUT_TL_ADDR + \
		(NBL_PCIE_ECPU_TEST_OUT_TL_DWLEN * 4) * (r))

#define NBL_PCIE_ECPU_TEST_OUT_PL_ADDR  (0x1415068)
#define NBL_PCIE_ECPU_TEST_OUT_PL_DEPTH (8)
#define NBL_PCIE_ECPU_TEST_OUT_PL_WIDTH (32)
#define NBL_PCIE_ECPU_TEST_OUT_PL_DWLEN (1)
union pcie_ecpu_test_out_pl_u {
	struct pcie_ecpu_test_out_pl {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TEST_OUT_PL_DWLEN];
} __packed;
#define NBL_PCIE_ECPU_TEST_OUT_PL_REG(r) (NBL_PCIE_ECPU_TEST_OUT_PL_ADDR + \
		(NBL_PCIE_ECPU_TEST_OUT_PL_DWLEN * 4) * (r))

#define NBL_PCIE_ECPU_TEST_OUT_EQU_ADDR  (0x1415088)
#define NBL_PCIE_ECPU_TEST_OUT_EQU_DEPTH (32)
#define NBL_PCIE_ECPU_TEST_OUT_EQU_WIDTH (32)
#define NBL_PCIE_ECPU_TEST_OUT_EQU_DWLEN (1)
union pcie_ecpu_test_out_equ_u {
	struct pcie_ecpu_test_out_equ {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TEST_OUT_EQU_DWLEN];
} __packed;
#define NBL_PCIE_ECPU_TEST_OUT_EQU_REG(r) (NBL_PCIE_ECPU_TEST_OUT_EQU_ADDR + \
		(NBL_PCIE_ECPU_TEST_OUT_EQU_DWLEN * 4) * (r))

#define NBL_PCIE_ECPU_TEST_OUT_PERF_ADDR  (0x1415188)
#define NBL_PCIE_ECPU_TEST_OUT_PERF_DEPTH (4)
#define NBL_PCIE_ECPU_TEST_OUT_PERF_WIDTH (32)
#define NBL_PCIE_ECPU_TEST_OUT_PERF_DWLEN (1)
union pcie_ecpu_test_out_perf_u {
	struct pcie_ecpu_test_out_perf {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TEST_OUT_PERF_DWLEN];
} __packed;
#define NBL_PCIE_ECPU_TEST_OUT_PERF_REG(r) (NBL_PCIE_ECPU_TEST_OUT_PERF_ADDR + \
		(NBL_PCIE_ECPU_TEST_OUT_PERF_DWLEN * 4) * (r))

#define NBL_PCIE_ECPU_TEST_OUT_RXVAL_ADDR  (0x1415198)
#define NBL_PCIE_ECPU_TEST_OUT_RXVAL_DEPTH (1)
#define NBL_PCIE_ECPU_TEST_OUT_RXVAL_WIDTH (32)
#define NBL_PCIE_ECPU_TEST_OUT_RXVAL_DWLEN (1)
union pcie_ecpu_test_out_rxval_u {
	struct pcie_ecpu_test_out_rxval {
		u32 dbg:8;               /* [07:00] Default:0x0 RO */
		u32 rsv:24;              /* [31:08] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TEST_OUT_RXVAL_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TEST_OUT_RXDATA_ADDR  (0x141519c)
#define NBL_PCIE_ECPU_TEST_OUT_RXDATA_DEPTH (8)
#define NBL_PCIE_ECPU_TEST_OUT_RXDATA_WIDTH (32)
#define NBL_PCIE_ECPU_TEST_OUT_RXDATA_DWLEN (1)
union pcie_ecpu_test_out_rxdata_u {
	struct pcie_ecpu_test_out_rxdata {
		u32 dbg:32;              /* [31:00] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TEST_OUT_RXDATA_DWLEN];
} __packed;
#define NBL_PCIE_ECPU_TEST_OUT_RXDATA_REG(r) (NBL_PCIE_ECPU_TEST_OUT_RXDATA_ADDR + \
		(NBL_PCIE_ECPU_TEST_OUT_RXDATA_DWLEN * 4) * (r))

#define NBL_PCIE_ECPU_TEST_OUT_RXDATAK_ADDR  (0x14151dc)
#define NBL_PCIE_ECPU_TEST_OUT_RXDATAK_DEPTH (1)
#define NBL_PCIE_ECPU_TEST_OUT_RXDATAK_WIDTH (32)
#define NBL_PCIE_ECPU_TEST_OUT_RXDATAK_DWLEN (1)
union pcie_ecpu_test_out_rxdatak_u {
	struct pcie_ecpu_test_out_rxdatak {
		u32 dbg:32;              /* [31:00] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TEST_OUT_RXDATAK_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TEST_OUT_TXVAL_ADDR  (0x14151e4)
#define NBL_PCIE_ECPU_TEST_OUT_TXVAL_DEPTH (1)
#define NBL_PCIE_ECPU_TEST_OUT_TXVAL_WIDTH (32)
#define NBL_PCIE_ECPU_TEST_OUT_TXVAL_DWLEN (1)
union pcie_ecpu_test_out_txval_u {
	struct pcie_ecpu_test_out_txval {
		u32 dbg:8;               /* [07:00] Default:0x0 RO */
		u32 rsv:24;              /* [31:08] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TEST_OUT_TXVAL_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_TEST_OUT_TXDATA_ADDR  (0x14151e8)
#define NBL_PCIE_ECPU_TEST_OUT_TXDATA_DEPTH (8)
#define NBL_PCIE_ECPU_TEST_OUT_TXDATA_WIDTH (32)
#define NBL_PCIE_ECPU_TEST_OUT_TXDATA_DWLEN (1)
union pcie_ecpu_test_out_txdata_u {
	struct pcie_ecpu_test_out_txdata {
		u32 dbg:32;              /* [31:00] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TEST_OUT_TXDATA_DWLEN];
} __packed;
#define NBL_PCIE_ECPU_TEST_OUT_TXDATA_REG(r) (NBL_PCIE_ECPU_TEST_OUT_TXDATA_ADDR + \
		(NBL_PCIE_ECPU_TEST_OUT_TXDATA_DWLEN * 4) * (r))

#define NBL_PCIE_ECPU_TEST_OUT_TXDATAK_ADDR  (0x1415228)
#define NBL_PCIE_ECPU_TEST_OUT_TXDATAK_DEPTH (1)
#define NBL_PCIE_ECPU_TEST_OUT_TXDATAK_WIDTH (32)
#define NBL_PCIE_ECPU_TEST_OUT_TXDATAK_DWLEN (1)
union pcie_ecpu_test_out_txdatak_u {
	struct pcie_ecpu_test_out_txdatak {
		u32 dbg:32;              /* [31:00] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_TEST_OUT_TXDATAK_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_DTEST_O_ADDR  (0x1415230)
#define NBL_PCIE_ECPU_DTEST_O_DEPTH (1)
#define NBL_PCIE_ECPU_DTEST_O_WIDTH (32)
#define NBL_PCIE_ECPU_DTEST_O_DWLEN (1)
union pcie_ecpu_dtest_o_u {
	struct pcie_ecpu_dtest_o {
		u32 dbg:12;              /* [11:00] Default:0x0 RO */
		u32 rsv:20;              /* [31:12] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_DTEST_O_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_PMA0_DTEST_ADDR  (0x1415234)
#define NBL_PCIE_ECPU_PMA0_DTEST_DEPTH (1)
#define NBL_PCIE_ECPU_PMA0_DTEST_WIDTH (32)
#define NBL_PCIE_ECPU_PMA0_DTEST_DWLEN (1)
union pcie_ecpu_pma0_dtest_u {
	struct pcie_ecpu_pma0_dtest {
		u32 dbg:12;              /* [11:00] Default:0x0 RO */
		u32 rsv:20;              /* [31:12] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_PMA0_DTEST_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_PMA0_ERR_ADDR  (0x1415238)
#define NBL_PCIE_ECPU_PMA0_ERR_DEPTH (1)
#define NBL_PCIE_ECPU_PMA0_ERR_WIDTH (32)
#define NBL_PCIE_ECPU_PMA0_ERR_DWLEN (1)
union pcie_ecpu_pma0_err_u {
	struct pcie_ecpu_pma0_err {
		u32 dbg:1;               /* [00:00] Default:0x0 RO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_PMA0_ERR_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_PMA0_PRGM_PARITY_ERR_ADDR  (0x141523c)
#define NBL_PCIE_ECPU_PMA0_PRGM_PARITY_ERR_DEPTH (1)
#define NBL_PCIE_ECPU_PMA0_PRGM_PARITY_ERR_WIDTH (32)
#define NBL_PCIE_ECPU_PMA0_PRGM_PARITY_ERR_DWLEN (1)
union pcie_ecpu_pma0_prgm_parity_err_u {
	struct pcie_ecpu_pma0_prgm_parity_err {
		u32 dbg:1;               /* [00:00] Default:0x0 RO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_PMA0_PRGM_PARITY_ERR_DWLEN];
} __packed;

#define NBL_PCIE_ECPU_PMA0_PMLD_ADDR  (0x141c000)
#define NBL_PCIE_ECPU_PMA0_PMLD_DEPTH (1)
#define NBL_PCIE_ECPU_PMA0_PMLD_WIDTH (32)
#define NBL_PCIE_ECPU_PMA0_PMLD_DWLEN (1)
union pcie_ecpu_pma0_pmld_u {
	struct pcie_ecpu_pma0_pmld {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCIE_ECPU_PMA0_PMLD_DWLEN];
} __packed;

#endif
