// Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#ifndef NBL_PTLP_H
#define NBL_PTLP_H 1

#include <linux/types.h>

#define NBL_PTLP_BASE (0x00F48000)

#define NBL_PTLP_INT_STATUS_ADDR  (0xf48000)
#define NBL_PTLP_INT_STATUS_DEPTH (1)
#define NBL_PTLP_INT_STATUS_WIDTH (32)
#define NBL_PTLP_INT_STATUS_DWLEN (1)
union ptlp_int_status_u {
	struct ptlp_int_status {
		u32 fatal_err:1;         /* [00:00] Default:0x0 RWC */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 RWC */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 RWC */
		u32 rsv3:1;              /* [03:03] Default:0x0 RO */
		u32 cif_err:1;           /* [04:04] Default:0x0 RWC */
		u32 rsv2:1;              /* [05:05] Default:0x0 RO */
		u32 cfg_err:1;           /* [06:06] Default:0x0 RWC */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 RWC */
		u32 data_cor_err:1;      /* [08:08] Default:0x0 RWC */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_INT_STATUS_DWLEN];
} __packed;

#define NBL_PTLP_INT_MASK_ADDR  (0xf48004)
#define NBL_PTLP_INT_MASK_DEPTH (1)
#define NBL_PTLP_INT_MASK_WIDTH (32)
#define NBL_PTLP_INT_MASK_DWLEN (1)
union ptlp_int_mask_u {
	struct ptlp_int_mask {
		u32 fatal_err:1;         /* [00:00] Default:0x0 RW */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 RW */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 RW */
		u32 rsv3:1;              /* [03:03] Default:0x0 RO */
		u32 cif_err:1;           /* [04:04] Default:0x0 RW */
		u32 rsv2:1;              /* [05:05] Default:0x0 RO */
		u32 cfg_err:1;           /* [06:06] Default:0x0 RW */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 RW */
		u32 data_cor_err:1;      /* [08:08] Default:0x0 RW */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_INT_MASK_DWLEN];
} __packed;

#define NBL_PTLP_INT_SET_ADDR  (0xf48008)
#define NBL_PTLP_INT_SET_DEPTH (1)
#define NBL_PTLP_INT_SET_WIDTH (32)
#define NBL_PTLP_INT_SET_DWLEN (1)
union ptlp_int_set_u {
	struct ptlp_int_set {
		u32 fatal_err:1;         /* [00:00] Default:0x0 WO */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 WO */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 WO */
		u32 rsv3:1;              /* [03:03] Default:0x0 RO */
		u32 cif_err:1;           /* [04:04] Default:0x0 WO */
		u32 rsv2:1;              /* [05:05] Default:0x0 RO */
		u32 cfg_err:1;           /* [06:06] Default:0x0 WO */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 WO */
		u32 data_cor_err:1;      /* [08:08] Default:0x0 WO */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_INT_SET_DWLEN];
} __packed;

#define NBL_PTLP_INIT_DONE_ADDR  (0xf4800c)
#define NBL_PTLP_INIT_DONE_DEPTH (1)
#define NBL_PTLP_INIT_DONE_WIDTH (32)
#define NBL_PTLP_INIT_DONE_DWLEN (1)
union ptlp_init_done_u {
	struct ptlp_init_done {
		u32 done:1;              /* [00:00] Default:0x0 RO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_INIT_DONE_DWLEN];
} __packed;

#define NBL_PTLP_CIF_ERR_INFO_ADDR  (0xf48040)
#define NBL_PTLP_CIF_ERR_INFO_DEPTH (1)
#define NBL_PTLP_CIF_ERR_INFO_WIDTH (32)
#define NBL_PTLP_CIF_ERR_INFO_DWLEN (1)
union ptlp_cif_err_info_u {
	struct ptlp_cif_err_info {
		u32 addr:30;             /* [29:00] Default:0x0 RO */
		u32 wr_err:1;            /* [30:30] Default:0x0 RO */
		u32 ucor_err:1;          /* [31:31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_CIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_PTLP_CAR_CTRL_ADDR  (0xf48100)
#define NBL_PTLP_CAR_CTRL_DEPTH (1)
#define NBL_PTLP_CAR_CTRL_WIDTH (32)
#define NBL_PTLP_CAR_CTRL_DWLEN (1)
union ptlp_car_ctrl_u {
	struct ptlp_car_ctrl {
		u32 sctr_car:1;          /* [00:00] Default:0x1 RW */
		u32 rctr_car:1;          /* [01:01] Default:0x1 RW */
		u32 rc_car:1;            /* [02:02] Default:0x1 RW */
		u32 tbl_rc_car:1;        /* [03:03] Default:0x1 RW */
		u32 rsv:28;              /* [31:04] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_CAR_CTRL_DWLEN];
} __packed;

#define NBL_PTLP_WDIF_BDF_ADDR  (0xf490e4)
#define NBL_PTLP_WDIF_BDF_DEPTH (1)
#define NBL_PTLP_WDIF_BDF_WIDTH (32)
#define NBL_PTLP_WDIF_BDF_DWLEN (1)
union ptlp_wdif_bdf_u {
	struct ptlp_wdif_bdf {
		u32 dbg:16;              /* [15:00] Default:0x0 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_WDIF_BDF_DWLEN];
} __packed;

#define NBL_PTLP_AXI_READY_ADDR  (0xf490e8)
#define NBL_PTLP_AXI_READY_DEPTH (1)
#define NBL_PTLP_AXI_READY_WIDTH (32)
#define NBL_PTLP_AXI_READY_DWLEN (1)
union ptlp_axi_ready_u {
	struct ptlp_axi_ready {
		u32 overtime:32;         /* [31:0] Default:0x5fffff RW */
	} __packed info;
	u32 data[NBL_PTLP_AXI_READY_DWLEN];
} __packed;

#define NBL_PTLP_TLP_ECPU_ADDR_SIZE_ADDR  (0xf490ec)
#define NBL_PTLP_TLP_ECPU_ADDR_SIZE_DEPTH (1)
#define NBL_PTLP_TLP_ECPU_ADDR_SIZE_WIDTH (32)
#define NBL_PTLP_TLP_ECPU_ADDR_SIZE_DWLEN (1)
union ptlp_tlp_ecpu_addr_size_u {
	struct ptlp_tlp_ecpu_addr_size {
		u32 dbg:32;              /* [31:0] Default:0x100000 RW */
	} __packed info;
	u32 data[NBL_PTLP_TLP_ECPU_ADDR_SIZE_DWLEN];
} __packed;

#define NBL_PTLP_TLP_EMP_ADDR_SIZE_ADDR  (0xf490f0)
#define NBL_PTLP_TLP_EMP_ADDR_SIZE_DEPTH (1)
#define NBL_PTLP_TLP_EMP_ADDR_SIZE_WIDTH (32)
#define NBL_PTLP_TLP_EMP_ADDR_SIZE_DWLEN (1)
union ptlp_tlp_emp_addr_size_u {
	struct ptlp_tlp_emp_addr_size {
		u32 dbg:32;              /* [31:0] Default:0x100000 RW */
	} __packed info;
	u32 data[NBL_PTLP_TLP_EMP_ADDR_SIZE_DWLEN];
} __packed;

#define NBL_PTLP_AXI_BASE_ADDR_ADDR  (0xf490f4)
#define NBL_PTLP_AXI_BASE_ADDR_DEPTH (1)
#define NBL_PTLP_AXI_BASE_ADDR_WIDTH (32)
#define NBL_PTLP_AXI_BASE_ADDR_DWLEN (1)
union ptlp_axi_base_addr_u {
	struct ptlp_axi_base_addr {
		u32 dbg:32;              /* [31:0] Default:0x60000000 RW */
	} __packed info;
	u32 data[NBL_PTLP_AXI_BASE_ADDR_DWLEN];
} __packed;

#define NBL_PTLP_CLR_INT_ADDR  (0xf490fc)
#define NBL_PTLP_CLR_INT_DEPTH (1)
#define NBL_PTLP_CLR_INT_WIDTH (32)
#define NBL_PTLP_CLR_INT_DWLEN (1)
union ptlp_clr_int_u {
	struct ptlp_clr_int {
		u32 dbg:1;               /* [0] Default:0x0 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_CLR_INT_DWLEN];
} __packed;

#define NBL_PTLP_E2H_READY_ADDR  (0xf49100)
#define NBL_PTLP_E2H_READY_DEPTH (1)
#define NBL_PTLP_E2H_READY_WIDTH (32)
#define NBL_PTLP_E2H_READY_DWLEN (1)
union ptlp_e2h_ready_u {
	struct ptlp_e2h_ready {
		u32 dbg:1;               /* [0] Default:0x1 RO */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_E2H_READY_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_TLP_EN_ADDR  (0xf49104)
#define NBL_PTLP_CFG_E_TLP_EN_DEPTH (1)
#define NBL_PTLP_CFG_E_TLP_EN_WIDTH (32)
#define NBL_PTLP_CFG_E_TLP_EN_DWLEN (1)
union ptlp_cfg_e_tlp_en_u {
	struct ptlp_cfg_e_tlp_en {
		u32 dbg:1;               /* [0] Default:0x0 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_TLP_EN_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_TLP_SEQID_ADDR  (0xf49108)
#define NBL_PTLP_CFG_E_TLP_SEQID_DEPTH (1)
#define NBL_PTLP_CFG_E_TLP_SEQID_WIDTH (32)
#define NBL_PTLP_CFG_E_TLP_SEQID_DWLEN (1)
union ptlp_cfg_e_tlp_seqid_u {
	struct ptlp_cfg_e_tlp_seqid {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_TLP_SEQID_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_TLP_ADDR_LOW_ADDR  (0xf4910c)
#define NBL_PTLP_CFG_E_TLP_ADDR_LOW_DEPTH (1)
#define NBL_PTLP_CFG_E_TLP_ADDR_LOW_WIDTH (32)
#define NBL_PTLP_CFG_E_TLP_ADDR_LOW_DWLEN (1)
union ptlp_cfg_e_tlp_addr_low_u {
	struct ptlp_cfg_e_tlp_addr_low {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_TLP_ADDR_LOW_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_TLP_ADDR_HIGH_ADDR  (0xf49110)
#define NBL_PTLP_CFG_E_TLP_ADDR_HIGH_DEPTH (1)
#define NBL_PTLP_CFG_E_TLP_ADDR_HIGH_WIDTH (32)
#define NBL_PTLP_CFG_E_TLP_ADDR_HIGH_DWLEN (1)
union ptlp_cfg_e_tlp_addr_high_u {
	struct ptlp_cfg_e_tlp_addr_high {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_TLP_ADDR_HIGH_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_ID_ADDR_LOW_ADDR  (0xf49114)
#define NBL_PTLP_CFG_E_ID_ADDR_LOW_DEPTH (1)
#define NBL_PTLP_CFG_E_ID_ADDR_LOW_WIDTH (32)
#define NBL_PTLP_CFG_E_ID_ADDR_LOW_DWLEN (1)
union ptlp_cfg_e_id_addr_low_u {
	struct ptlp_cfg_e_id_addr_low {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_ID_ADDR_LOW_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_ID_ADDR_HIGH_ADDR  (0xf49118)
#define NBL_PTLP_CFG_E_ID_ADDR_HIGH_DEPTH (1)
#define NBL_PTLP_CFG_E_ID_ADDR_HIGH_WIDTH (32)
#define NBL_PTLP_CFG_E_ID_ADDR_HIGH_DWLEN (1)
union ptlp_cfg_e_id_addr_high_u {
	struct ptlp_cfg_e_id_addr_high {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_ID_ADDR_HIGH_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_TLP_NOTIFY_ADDR  (0xf4911c)
#define NBL_PTLP_CFG_E_TLP_NOTIFY_DEPTH (1)
#define NBL_PTLP_CFG_E_TLP_NOTIFY_WIDTH (32)
#define NBL_PTLP_CFG_E_TLP_NOTIFY_DWLEN (1)
union ptlp_cfg_e_tlp_notify_u {
	struct ptlp_cfg_e_tlp_notify {
		u32 keep:16;             /* [15:0] Default:0x0 RW */
		u32 eop:1;               /* [16] Default:0x0 RW */
		u32 sop:1;               /* [17] Default:0x0 RW */
		u32 len:8;               /* [25:18] Default:0x0 RW */
		u32 vld:1;               /* [26] Default:0x0 WO */
		u32 rsv:5;               /* [31:27] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_TLP_NOTIFY_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_TLP_DATA_DW0_ADDR  (0xf49120)
#define NBL_PTLP_CFG_E_TLP_DATA_DW0_DEPTH (1)
#define NBL_PTLP_CFG_E_TLP_DATA_DW0_WIDTH (32)
#define NBL_PTLP_CFG_E_TLP_DATA_DW0_DWLEN (1)
union ptlp_cfg_e_tlp_data_dw0_u {
	struct ptlp_cfg_e_tlp_data_dw0 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_TLP_DATA_DW0_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_TLP_DATA_DW1_ADDR  (0xf49124)
#define NBL_PTLP_CFG_E_TLP_DATA_DW1_DEPTH (1)
#define NBL_PTLP_CFG_E_TLP_DATA_DW1_WIDTH (32)
#define NBL_PTLP_CFG_E_TLP_DATA_DW1_DWLEN (1)
union ptlp_cfg_e_tlp_data_dw1_u {
	struct ptlp_cfg_e_tlp_data_dw1 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_TLP_DATA_DW1_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_TLP_DATA_DW2_ADDR  (0xf49128)
#define NBL_PTLP_CFG_E_TLP_DATA_DW2_DEPTH (1)
#define NBL_PTLP_CFG_E_TLP_DATA_DW2_WIDTH (32)
#define NBL_PTLP_CFG_E_TLP_DATA_DW2_DWLEN (1)
union ptlp_cfg_e_tlp_data_dw2_u {
	struct ptlp_cfg_e_tlp_data_dw2 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_TLP_DATA_DW2_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_TLP_DATA_DW3_ADDR  (0xf4912c)
#define NBL_PTLP_CFG_E_TLP_DATA_DW3_DEPTH (1)
#define NBL_PTLP_CFG_E_TLP_DATA_DW3_WIDTH (32)
#define NBL_PTLP_CFG_E_TLP_DATA_DW3_DWLEN (1)
union ptlp_cfg_e_tlp_data_dw3_u {
	struct ptlp_cfg_e_tlp_data_dw3 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_TLP_DATA_DW3_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_TLP_DATA_DW4_ADDR  (0xf49130)
#define NBL_PTLP_CFG_E_TLP_DATA_DW4_DEPTH (1)
#define NBL_PTLP_CFG_E_TLP_DATA_DW4_WIDTH (32)
#define NBL_PTLP_CFG_E_TLP_DATA_DW4_DWLEN (1)
union ptlp_cfg_e_tlp_data_dw4_u {
	struct ptlp_cfg_e_tlp_data_dw4 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_TLP_DATA_DW4_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_TLP_DATA_DW5_ADDR  (0xf49134)
#define NBL_PTLP_CFG_E_TLP_DATA_DW5_DEPTH (1)
#define NBL_PTLP_CFG_E_TLP_DATA_DW5_WIDTH (32)
#define NBL_PTLP_CFG_E_TLP_DATA_DW5_DWLEN (1)
union ptlp_cfg_e_tlp_data_dw5_u {
	struct ptlp_cfg_e_tlp_data_dw5 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_TLP_DATA_DW5_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_TLP_DATA_DW6_ADDR  (0xf49138)
#define NBL_PTLP_CFG_E_TLP_DATA_DW6_DEPTH (1)
#define NBL_PTLP_CFG_E_TLP_DATA_DW6_WIDTH (32)
#define NBL_PTLP_CFG_E_TLP_DATA_DW6_DWLEN (1)
union ptlp_cfg_e_tlp_data_dw6_u {
	struct ptlp_cfg_e_tlp_data_dw6 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_TLP_DATA_DW6_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_TLP_DATA_DW7_ADDR  (0xf4913c)
#define NBL_PTLP_CFG_E_TLP_DATA_DW7_DEPTH (1)
#define NBL_PTLP_CFG_E_TLP_DATA_DW7_WIDTH (32)
#define NBL_PTLP_CFG_E_TLP_DATA_DW7_DWLEN (1)
union ptlp_cfg_e_tlp_data_dw7_u {
	struct ptlp_cfg_e_tlp_data_dw7 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_TLP_DATA_DW7_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_TLP_DATA_DW8_ADDR  (0xf49140)
#define NBL_PTLP_CFG_E_TLP_DATA_DW8_DEPTH (1)
#define NBL_PTLP_CFG_E_TLP_DATA_DW8_WIDTH (32)
#define NBL_PTLP_CFG_E_TLP_DATA_DW8_DWLEN (1)
union ptlp_cfg_e_tlp_data_dw8_u {
	struct ptlp_cfg_e_tlp_data_dw8 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_TLP_DATA_DW8_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_TLP_DATA_DW9_ADDR  (0xf49144)
#define NBL_PTLP_CFG_E_TLP_DATA_DW9_DEPTH (1)
#define NBL_PTLP_CFG_E_TLP_DATA_DW9_WIDTH (32)
#define NBL_PTLP_CFG_E_TLP_DATA_DW9_DWLEN (1)
union ptlp_cfg_e_tlp_data_dw9_u {
	struct ptlp_cfg_e_tlp_data_dw9 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_TLP_DATA_DW9_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_TLP_DATA_DW10_ADDR  (0xf49148)
#define NBL_PTLP_CFG_E_TLP_DATA_DW10_DEPTH (1)
#define NBL_PTLP_CFG_E_TLP_DATA_DW10_WIDTH (32)
#define NBL_PTLP_CFG_E_TLP_DATA_DW10_DWLEN (1)
union ptlp_cfg_e_tlp_data_dw10_u {
	struct ptlp_cfg_e_tlp_data_dw10 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_TLP_DATA_DW10_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_TLP_DATA_DW11_ADDR  (0xf4914c)
#define NBL_PTLP_CFG_E_TLP_DATA_DW11_DEPTH (1)
#define NBL_PTLP_CFG_E_TLP_DATA_DW11_WIDTH (32)
#define NBL_PTLP_CFG_E_TLP_DATA_DW11_DWLEN (1)
union ptlp_cfg_e_tlp_data_dw11_u {
	struct ptlp_cfg_e_tlp_data_dw11 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_TLP_DATA_DW11_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_TLP_DATA_DW12_ADDR  (0xf49150)
#define NBL_PTLP_CFG_E_TLP_DATA_DW12_DEPTH (1)
#define NBL_PTLP_CFG_E_TLP_DATA_DW12_WIDTH (32)
#define NBL_PTLP_CFG_E_TLP_DATA_DW12_DWLEN (1)
union ptlp_cfg_e_tlp_data_dw12_u {
	struct ptlp_cfg_e_tlp_data_dw12 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_TLP_DATA_DW12_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_TLP_DATA_DW13_ADDR  (0xf49154)
#define NBL_PTLP_CFG_E_TLP_DATA_DW13_DEPTH (1)
#define NBL_PTLP_CFG_E_TLP_DATA_DW13_WIDTH (32)
#define NBL_PTLP_CFG_E_TLP_DATA_DW13_DWLEN (1)
union ptlp_cfg_e_tlp_data_dw13_u {
	struct ptlp_cfg_e_tlp_data_dw13 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_TLP_DATA_DW13_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_TLP_DATA_DW14_ADDR  (0xf49158)
#define NBL_PTLP_CFG_E_TLP_DATA_DW14_DEPTH (1)
#define NBL_PTLP_CFG_E_TLP_DATA_DW14_WIDTH (32)
#define NBL_PTLP_CFG_E_TLP_DATA_DW14_DWLEN (1)
union ptlp_cfg_e_tlp_data_dw14_u {
	struct ptlp_cfg_e_tlp_data_dw14 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_TLP_DATA_DW14_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_TLP_DATA_DW15_ADDR  (0xf4915c)
#define NBL_PTLP_CFG_E_TLP_DATA_DW15_DEPTH (1)
#define NBL_PTLP_CFG_E_TLP_DATA_DW15_WIDTH (32)
#define NBL_PTLP_CFG_E_TLP_DATA_DW15_DWLEN (1)
union ptlp_cfg_e_tlp_data_dw15_u {
	struct ptlp_cfg_e_tlp_data_dw15 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_TLP_DATA_DW15_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_TLP2_EN_ADDR  (0xf491a4)
#define NBL_PTLP_CFG_E_TLP2_EN_DEPTH (1)
#define NBL_PTLP_CFG_E_TLP2_EN_WIDTH (32)
#define NBL_PTLP_CFG_E_TLP2_EN_DWLEN (1)
union ptlp_cfg_e_tlp2_en_u {
	struct ptlp_cfg_e_tlp2_en {
		u32 dbg:1;               /* [0] Default:0x0 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_TLP2_EN_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_TLP2_ADDR_LOW_ADDR  (0xf491ac)
#define NBL_PTLP_CFG_E_TLP2_ADDR_LOW_DEPTH (1)
#define NBL_PTLP_CFG_E_TLP2_ADDR_LOW_WIDTH (32)
#define NBL_PTLP_CFG_E_TLP2_ADDR_LOW_DWLEN (1)
union ptlp_cfg_e_tlp2_addr_low_u {
	struct ptlp_cfg_e_tlp2_addr_low {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_TLP2_ADDR_LOW_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_TLP2_ADDR_HIGH_ADDR  (0xf491b0)
#define NBL_PTLP_CFG_E_TLP2_ADDR_HIGH_DEPTH (1)
#define NBL_PTLP_CFG_E_TLP2_ADDR_HIGH_WIDTH (32)
#define NBL_PTLP_CFG_E_TLP2_ADDR_HIGH_DWLEN (1)
union ptlp_cfg_e_tlp2_addr_high_u {
	struct ptlp_cfg_e_tlp2_addr_high {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_TLP2_ADDR_HIGH_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_ID2_ADDR_LOW_ADDR  (0xf491b4)
#define NBL_PTLP_CFG_E_ID2_ADDR_LOW_DEPTH (1)
#define NBL_PTLP_CFG_E_ID2_ADDR_LOW_WIDTH (32)
#define NBL_PTLP_CFG_E_ID2_ADDR_LOW_DWLEN (1)
union ptlp_cfg_e_id2_addr_low_u {
	struct ptlp_cfg_e_id2_addr_low {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_ID2_ADDR_LOW_DWLEN];
} __packed;

#define NBL_PTLP_CFG_E_ID2_ADDR_HIGH_ADDR  (0xf491b8)
#define NBL_PTLP_CFG_E_ID2_ADDR_HIGH_DEPTH (1)
#define NBL_PTLP_CFG_E_ID2_ADDR_HIGH_WIDTH (32)
#define NBL_PTLP_CFG_E_ID2_ADDR_HIGH_DWLEN (1)
union ptlp_cfg_e_id2_addr_high_u {
	struct ptlp_cfg_e_id2_addr_high {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_E_ID2_ADDR_HIGH_DWLEN];
} __packed;

#define NBL_PTLP_I2H_READY_ADDR  (0xf49200)
#define NBL_PTLP_I2H_READY_DEPTH (1)
#define NBL_PTLP_I2H_READY_WIDTH (32)
#define NBL_PTLP_I2H_READY_DWLEN (1)
union ptlp_i2h_ready_u {
	struct ptlp_i2h_ready {
		u32 dbg:1;               /* [0] Default:0x1 RO */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_I2H_READY_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TLP_EN_ADDR  (0xf49204)
#define NBL_PTLP_CFG_I_TLP_EN_DEPTH (1)
#define NBL_PTLP_CFG_I_TLP_EN_WIDTH (32)
#define NBL_PTLP_CFG_I_TLP_EN_DWLEN (1)
union ptlp_cfg_i_tlp_en_u {
	struct ptlp_cfg_i_tlp_en {
		u32 dbg:1;               /* [0] Default:0x0 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TLP_EN_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TLP_SEQID_ADDR  (0xf49208)
#define NBL_PTLP_CFG_I_TLP_SEQID_DEPTH (1)
#define NBL_PTLP_CFG_I_TLP_SEQID_WIDTH (32)
#define NBL_PTLP_CFG_I_TLP_SEQID_DWLEN (1)
union ptlp_cfg_i_tlp_seqid_u {
	struct ptlp_cfg_i_tlp_seqid {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TLP_SEQID_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TLP_ADDR_LOW_ADDR  (0xf4920c)
#define NBL_PTLP_CFG_I_TLP_ADDR_LOW_DEPTH (1)
#define NBL_PTLP_CFG_I_TLP_ADDR_LOW_WIDTH (32)
#define NBL_PTLP_CFG_I_TLP_ADDR_LOW_DWLEN (1)
union ptlp_cfg_i_tlp_addr_low_u {
	struct ptlp_cfg_i_tlp_addr_low {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TLP_ADDR_LOW_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TLP_ADDR_HIGH_ADDR  (0xf49210)
#define NBL_PTLP_CFG_I_TLP_ADDR_HIGH_DEPTH (1)
#define NBL_PTLP_CFG_I_TLP_ADDR_HIGH_WIDTH (32)
#define NBL_PTLP_CFG_I_TLP_ADDR_HIGH_DWLEN (1)
union ptlp_cfg_i_tlp_addr_high_u {
	struct ptlp_cfg_i_tlp_addr_high {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TLP_ADDR_HIGH_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_ID_ADDR_LOW_ADDR  (0xf49214)
#define NBL_PTLP_CFG_I_ID_ADDR_LOW_DEPTH (1)
#define NBL_PTLP_CFG_I_ID_ADDR_LOW_WIDTH (32)
#define NBL_PTLP_CFG_I_ID_ADDR_LOW_DWLEN (1)
union ptlp_cfg_i_id_addr_low_u {
	struct ptlp_cfg_i_id_addr_low {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_ID_ADDR_LOW_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_ID_ADDR_HIGH_ADDR  (0xf49218)
#define NBL_PTLP_CFG_I_ID_ADDR_HIGH_DEPTH (1)
#define NBL_PTLP_CFG_I_ID_ADDR_HIGH_WIDTH (32)
#define NBL_PTLP_CFG_I_ID_ADDR_HIGH_DWLEN (1)
union ptlp_cfg_i_id_addr_high_u {
	struct ptlp_cfg_i_id_addr_high {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_ID_ADDR_HIGH_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TLP_NOTIFY_ADDR  (0xf4921c)
#define NBL_PTLP_CFG_I_TLP_NOTIFY_DEPTH (1)
#define NBL_PTLP_CFG_I_TLP_NOTIFY_WIDTH (32)
#define NBL_PTLP_CFG_I_TLP_NOTIFY_DWLEN (1)
union ptlp_cfg_i_tlp_notify_u {
	struct ptlp_cfg_i_tlp_notify {
		u32 keep:16;             /* [15:0] Default:0x0 RW */
		u32 eop:1;               /* [16] Default:0x0 RW */
		u32 sop:1;               /* [17] Default:0x0 RW */
		u32 len:8;               /* [25:18] Default:0x0 RW */
		u32 vld:1;               /* [26] Default:0x0 WO */
		u32 rsv:5;               /* [31:27] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TLP_NOTIFY_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TLP_DATA_DW0_ADDR  (0xf49220)
#define NBL_PTLP_CFG_I_TLP_DATA_DW0_DEPTH (1)
#define NBL_PTLP_CFG_I_TLP_DATA_DW0_WIDTH (32)
#define NBL_PTLP_CFG_I_TLP_DATA_DW0_DWLEN (1)
union ptlp_cfg_i_tlp_data_dw0_u {
	struct ptlp_cfg_i_tlp_data_dw0 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TLP_DATA_DW0_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TLP_DATA_DW1_ADDR  (0xf49224)
#define NBL_PTLP_CFG_I_TLP_DATA_DW1_DEPTH (1)
#define NBL_PTLP_CFG_I_TLP_DATA_DW1_WIDTH (32)
#define NBL_PTLP_CFG_I_TLP_DATA_DW1_DWLEN (1)
union ptlp_cfg_i_tlp_data_dw1_u {
	struct ptlp_cfg_i_tlp_data_dw1 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TLP_DATA_DW1_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TLP_DATA_DW2_ADDR  (0xf49228)
#define NBL_PTLP_CFG_I_TLP_DATA_DW2_DEPTH (1)
#define NBL_PTLP_CFG_I_TLP_DATA_DW2_WIDTH (32)
#define NBL_PTLP_CFG_I_TLP_DATA_DW2_DWLEN (1)
union ptlp_cfg_i_tlp_data_dw2_u {
	struct ptlp_cfg_i_tlp_data_dw2 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TLP_DATA_DW2_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TLP_DATA_DW3_ADDR  (0xf4922c)
#define NBL_PTLP_CFG_I_TLP_DATA_DW3_DEPTH (1)
#define NBL_PTLP_CFG_I_TLP_DATA_DW3_WIDTH (32)
#define NBL_PTLP_CFG_I_TLP_DATA_DW3_DWLEN (1)
union ptlp_cfg_i_tlp_data_dw3_u {
	struct ptlp_cfg_i_tlp_data_dw3 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TLP_DATA_DW3_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TLP_DATA_DW4_ADDR  (0xf49230)
#define NBL_PTLP_CFG_I_TLP_DATA_DW4_DEPTH (1)
#define NBL_PTLP_CFG_I_TLP_DATA_DW4_WIDTH (32)
#define NBL_PTLP_CFG_I_TLP_DATA_DW4_DWLEN (1)
union ptlp_cfg_i_tlp_data_dw4_u {
	struct ptlp_cfg_i_tlp_data_dw4 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TLP_DATA_DW4_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TLP_DATA_DW5_ADDR  (0xf49234)
#define NBL_PTLP_CFG_I_TLP_DATA_DW5_DEPTH (1)
#define NBL_PTLP_CFG_I_TLP_DATA_DW5_WIDTH (32)
#define NBL_PTLP_CFG_I_TLP_DATA_DW5_DWLEN (1)
union ptlp_cfg_i_tlp_data_dw5_u {
	struct ptlp_cfg_i_tlp_data_dw5 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TLP_DATA_DW5_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TLP_DATA_DW6_ADDR  (0xf49238)
#define NBL_PTLP_CFG_I_TLP_DATA_DW6_DEPTH (1)
#define NBL_PTLP_CFG_I_TLP_DATA_DW6_WIDTH (32)
#define NBL_PTLP_CFG_I_TLP_DATA_DW6_DWLEN (1)
union ptlp_cfg_i_tlp_data_dw6_u {
	struct ptlp_cfg_i_tlp_data_dw6 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TLP_DATA_DW6_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TLP_DATA_DW7_ADDR  (0xf4923c)
#define NBL_PTLP_CFG_I_TLP_DATA_DW7_DEPTH (1)
#define NBL_PTLP_CFG_I_TLP_DATA_DW7_WIDTH (32)
#define NBL_PTLP_CFG_I_TLP_DATA_DW7_DWLEN (1)
union ptlp_cfg_i_tlp_data_dw7_u {
	struct ptlp_cfg_i_tlp_data_dw7 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TLP_DATA_DW7_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TLP_DATA_DW8_ADDR  (0xf49240)
#define NBL_PTLP_CFG_I_TLP_DATA_DW8_DEPTH (1)
#define NBL_PTLP_CFG_I_TLP_DATA_DW8_WIDTH (32)
#define NBL_PTLP_CFG_I_TLP_DATA_DW8_DWLEN (1)
union ptlp_cfg_i_tlp_data_dw8_u {
	struct ptlp_cfg_i_tlp_data_dw8 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TLP_DATA_DW8_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TLP_DATA_DW9_ADDR  (0xf49244)
#define NBL_PTLP_CFG_I_TLP_DATA_DW9_DEPTH (1)
#define NBL_PTLP_CFG_I_TLP_DATA_DW9_WIDTH (32)
#define NBL_PTLP_CFG_I_TLP_DATA_DW9_DWLEN (1)
union ptlp_cfg_i_tlp_data_dw9_u {
	struct ptlp_cfg_i_tlp_data_dw9 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TLP_DATA_DW9_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TLP_DATA_DW10_ADDR  (0xf49248)
#define NBL_PTLP_CFG_I_TLP_DATA_DW10_DEPTH (1)
#define NBL_PTLP_CFG_I_TLP_DATA_DW10_WIDTH (32)
#define NBL_PTLP_CFG_I_TLP_DATA_DW10_DWLEN (1)
union ptlp_cfg_i_tlp_data_dw10_u {
	struct ptlp_cfg_i_tlp_data_dw10 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TLP_DATA_DW10_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TLP_DATA_DW11_ADDR  (0xf4924c)
#define NBL_PTLP_CFG_I_TLP_DATA_DW11_DEPTH (1)
#define NBL_PTLP_CFG_I_TLP_DATA_DW11_WIDTH (32)
#define NBL_PTLP_CFG_I_TLP_DATA_DW11_DWLEN (1)
union ptlp_cfg_i_tlp_data_dw11_u {
	struct ptlp_cfg_i_tlp_data_dw11 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TLP_DATA_DW11_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TLP_DATA_DW12_ADDR  (0xf49250)
#define NBL_PTLP_CFG_I_TLP_DATA_DW12_DEPTH (1)
#define NBL_PTLP_CFG_I_TLP_DATA_DW12_WIDTH (32)
#define NBL_PTLP_CFG_I_TLP_DATA_DW12_DWLEN (1)
union ptlp_cfg_i_tlp_data_dw12_u {
	struct ptlp_cfg_i_tlp_data_dw12 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TLP_DATA_DW12_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TLP_DATA_DW13_ADDR  (0xf49254)
#define NBL_PTLP_CFG_I_TLP_DATA_DW13_DEPTH (1)
#define NBL_PTLP_CFG_I_TLP_DATA_DW13_WIDTH (32)
#define NBL_PTLP_CFG_I_TLP_DATA_DW13_DWLEN (1)
union ptlp_cfg_i_tlp_data_dw13_u {
	struct ptlp_cfg_i_tlp_data_dw13 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TLP_DATA_DW13_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TLP_DATA_DW14_ADDR  (0xf49258)
#define NBL_PTLP_CFG_I_TLP_DATA_DW14_DEPTH (1)
#define NBL_PTLP_CFG_I_TLP_DATA_DW14_WIDTH (32)
#define NBL_PTLP_CFG_I_TLP_DATA_DW14_DWLEN (1)
union ptlp_cfg_i_tlp_data_dw14_u {
	struct ptlp_cfg_i_tlp_data_dw14 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TLP_DATA_DW14_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TLP_DATA_DW15_ADDR  (0xf4925c)
#define NBL_PTLP_CFG_I_TLP_DATA_DW15_DEPTH (1)
#define NBL_PTLP_CFG_I_TLP_DATA_DW15_WIDTH (32)
#define NBL_PTLP_CFG_I_TLP_DATA_DW15_DWLEN (1)
union ptlp_cfg_i_tlp_data_dw15_u {
	struct ptlp_cfg_i_tlp_data_dw15 {
		u32 dbg:32;              /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TLP_DATA_DW15_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TL_PF_FLR_ACK_ADDR  (0xf49300)
#define NBL_PTLP_CFG_I_TL_PF_FLR_ACK_DEPTH (1)
#define NBL_PTLP_CFG_I_TL_PF_FLR_ACK_WIDTH (32)
#define NBL_PTLP_CFG_I_TL_PF_FLR_ACK_DWLEN (1)
union ptlp_cfg_i_tl_pf_flr_ack_u {
	struct ptlp_cfg_i_tl_pf_flr_ack {
		u32 dbg:8;               /* [7:0] Default:0x0 RW */
		u32 rsv:24;              /* [31:8] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TL_PF_FLR_ACK_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TL_VF_FLR_ACK_ADDR  (0xf49304)
#define NBL_PTLP_CFG_I_TL_VF_FLR_ACK_DEPTH (1)
#define NBL_PTLP_CFG_I_TL_VF_FLR_ACK_WIDTH (512)
#define NBL_PTLP_CFG_I_TL_VF_FLR_ACK_DWLEN (16)
union ptlp_cfg_i_tl_vf_flr_ack_u {
	struct ptlp_cfg_i_tl_vf_flr_ack {
		u32 dbg_arr[16];         /* [511:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TL_VF_FLR_ACK_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TL_PF_FLR_REQ_ADDR  (0xf49400)
#define NBL_PTLP_CFG_I_TL_PF_FLR_REQ_DEPTH (1)
#define NBL_PTLP_CFG_I_TL_PF_FLR_REQ_WIDTH (32)
#define NBL_PTLP_CFG_I_TL_PF_FLR_REQ_DWLEN (1)
union ptlp_cfg_i_tl_pf_flr_req_u {
	struct ptlp_cfg_i_tl_pf_flr_req {
		u32 dbg:8;               /* [7:0] Default:0x0 RO */
		u32 rsv:24;              /* [31:8] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TL_PF_FLR_REQ_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ0_ADDR  (0xf49404)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ0_DEPTH (1)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ0_WIDTH (32)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ0_DWLEN (1)
union ptlp_cfg_i_tl_vf_flr_req0_u {
	struct ptlp_cfg_i_tl_vf_flr_req0 {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TL_VF_FLR_REQ0_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ1_ADDR  (0xf49408)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ1_DEPTH (1)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ1_WIDTH (32)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ1_DWLEN (1)
union ptlp_cfg_i_tl_vf_flr_req1_u {
	struct ptlp_cfg_i_tl_vf_flr_req1 {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TL_VF_FLR_REQ1_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ2_ADDR  (0xf4940c)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ2_DEPTH (1)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ2_WIDTH (32)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ2_DWLEN (1)
union ptlp_cfg_i_tl_vf_flr_req2_u {
	struct ptlp_cfg_i_tl_vf_flr_req2 {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TL_VF_FLR_REQ2_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ3_ADDR  (0xf49410)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ3_DEPTH (1)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ3_WIDTH (32)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ3_DWLEN (1)
union ptlp_cfg_i_tl_vf_flr_req3_u {
	struct ptlp_cfg_i_tl_vf_flr_req3 {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TL_VF_FLR_REQ3_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ4_ADDR  (0xf49414)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ4_DEPTH (1)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ4_WIDTH (32)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ4_DWLEN (1)
union ptlp_cfg_i_tl_vf_flr_req4_u {
	struct ptlp_cfg_i_tl_vf_flr_req4 {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TL_VF_FLR_REQ4_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ5_ADDR  (0xf49418)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ5_DEPTH (1)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ5_WIDTH (32)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ5_DWLEN (1)
union ptlp_cfg_i_tl_vf_flr_req5_u {
	struct ptlp_cfg_i_tl_vf_flr_req5 {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TL_VF_FLR_REQ5_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ6_ADDR  (0xf4941c)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ6_DEPTH (1)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ6_WIDTH (32)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ6_DWLEN (1)
union ptlp_cfg_i_tl_vf_flr_req6_u {
	struct ptlp_cfg_i_tl_vf_flr_req6 {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TL_VF_FLR_REQ6_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ7_ADDR  (0xf49420)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ7_DEPTH (1)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ7_WIDTH (32)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ7_DWLEN (1)
union ptlp_cfg_i_tl_vf_flr_req7_u {
	struct ptlp_cfg_i_tl_vf_flr_req7 {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TL_VF_FLR_REQ7_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ8_ADDR  (0xf49424)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ8_DEPTH (1)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ8_WIDTH (32)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ8_DWLEN (1)
union ptlp_cfg_i_tl_vf_flr_req8_u {
	struct ptlp_cfg_i_tl_vf_flr_req8 {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TL_VF_FLR_REQ8_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ9_ADDR  (0xf49428)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ9_DEPTH (1)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ9_WIDTH (32)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ9_DWLEN (1)
union ptlp_cfg_i_tl_vf_flr_req9_u {
	struct ptlp_cfg_i_tl_vf_flr_req9 {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TL_VF_FLR_REQ9_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ10_ADDR  (0xf4942c)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ10_DEPTH (1)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ10_WIDTH (32)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ10_DWLEN (1)
union ptlp_cfg_i_tl_vf_flr_req10_u {
	struct ptlp_cfg_i_tl_vf_flr_req10 {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TL_VF_FLR_REQ10_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ11_ADDR  (0xf49430)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ11_DEPTH (1)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ11_WIDTH (32)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ11_DWLEN (1)
union ptlp_cfg_i_tl_vf_flr_req11_u {
	struct ptlp_cfg_i_tl_vf_flr_req11 {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TL_VF_FLR_REQ11_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ12_ADDR  (0xf49434)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ12_DEPTH (1)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ12_WIDTH (32)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ12_DWLEN (1)
union ptlp_cfg_i_tl_vf_flr_req12_u {
	struct ptlp_cfg_i_tl_vf_flr_req12 {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TL_VF_FLR_REQ12_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ13_ADDR  (0xf49438)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ13_DEPTH (1)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ13_WIDTH (32)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ13_DWLEN (1)
union ptlp_cfg_i_tl_vf_flr_req13_u {
	struct ptlp_cfg_i_tl_vf_flr_req13 {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TL_VF_FLR_REQ13_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ14_ADDR  (0xf4943c)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ14_DEPTH (1)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ14_WIDTH (32)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ14_DWLEN (1)
union ptlp_cfg_i_tl_vf_flr_req14_u {
	struct ptlp_cfg_i_tl_vf_flr_req14 {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TL_VF_FLR_REQ14_DWLEN];
} __packed;

#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ15_ADDR  (0xf49440)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ15_DEPTH (1)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ15_WIDTH (32)
#define NBL_PTLP_CFG_I_TL_VF_FLR_REQ15_DWLEN (1)
union ptlp_cfg_i_tl_vf_flr_req15_u {
	struct ptlp_cfg_i_tl_vf_flr_req15 {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_CFG_I_TL_VF_FLR_REQ15_DWLEN];
} __packed;

#define NBL_PTLP_ERROR_ADDR  (0xf4a000)
#define NBL_PTLP_ERROR_DEPTH (1)
#define NBL_PTLP_ERROR_WIDTH (32)
#define NBL_PTLP_ERROR_DWLEN (1)
union ptlp_error_u {
	struct ptlp_error {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_ERROR_DWLEN];
} __packed;

#define NBL_PTLP_WARNING_ADDR  (0xf4a004)
#define NBL_PTLP_WARNING_DEPTH (1)
#define NBL_PTLP_WARNING_WIDTH (32)
#define NBL_PTLP_WARNING_DWLEN (1)
union ptlp_warning_u {
	struct ptlp_warning {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_WARNING_DWLEN];
} __packed;

#define NBL_PTLP_CFG_ADDR  (0xf4a040)
#define NBL_PTLP_CFG_DEPTH (1)
#define NBL_PTLP_CFG_WIDTH (32)
#define NBL_PTLP_CFG_DWLEN (1)
union ptlp_cfg_u {
	struct ptlp_cfg {
		u32 ptlp_axi_werr:1;     /* [0] Default:0x0 RC */
		u32 ptlp_axi_rerr:1;     /* [1] Default:0x0 RC */
		u32 ptlp_axi_ready_err:1; /* [2] Default:0x0 RC */
		u32 rsv:29;              /* [31:3] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_CFG_DWLEN];
} __packed;

#define NBL_PTLP_E_NEXT_SEQ_ID_ADDR  (0xf4a12c)
#define NBL_PTLP_E_NEXT_SEQ_ID_DEPTH (1)
#define NBL_PTLP_E_NEXT_SEQ_ID_WIDTH (32)
#define NBL_PTLP_E_NEXT_SEQ_ID_DWLEN (1)
union ptlp_e_next_seq_id_u {
	struct ptlp_e_next_seq_id {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_E_NEXT_SEQ_ID_DWLEN];
} __packed;

#define NBL_PTLP_E_TLP_ADDR_ADDR  (0xf4a130)
#define NBL_PTLP_E_TLP_ADDR_DEPTH (1)
#define NBL_PTLP_E_TLP_ADDR_WIDTH (32)
#define NBL_PTLP_E_TLP_ADDR_DWLEN (1)
union ptlp_e_tlp_addr_u {
	struct ptlp_e_tlp_addr {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_E_TLP_ADDR_DWLEN];
} __packed;

#define NBL_PTLP_E_STATUS_ADDR  (0xf4a134)
#define NBL_PTLP_E_STATUS_DEPTH (1)
#define NBL_PTLP_E_STATUS_WIDTH (32)
#define NBL_PTLP_E_STATUS_DWLEN (1)
union ptlp_e_status_u {
	struct ptlp_e_status {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_E_STATUS_DWLEN];
} __packed;

#define NBL_PTLP_I_NEXT_SEQ_ID_ADDR  (0xf4a22c)
#define NBL_PTLP_I_NEXT_SEQ_ID_DEPTH (1)
#define NBL_PTLP_I_NEXT_SEQ_ID_WIDTH (32)
#define NBL_PTLP_I_NEXT_SEQ_ID_DWLEN (1)
union ptlp_i_next_seq_id_u {
	struct ptlp_i_next_seq_id {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_I_NEXT_SEQ_ID_DWLEN];
} __packed;

#define NBL_PTLP_I_TLP_ADDR_ADDR  (0xf4a230)
#define NBL_PTLP_I_TLP_ADDR_DEPTH (1)
#define NBL_PTLP_I_TLP_ADDR_WIDTH (32)
#define NBL_PTLP_I_TLP_ADDR_DWLEN (1)
union ptlp_i_tlp_addr_u {
	struct ptlp_i_tlp_addr {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_I_TLP_ADDR_DWLEN];
} __packed;

#define NBL_PTLP_I_STATUS_ADDR  (0xf4a234)
#define NBL_PTLP_I_STATUS_DEPTH (1)
#define NBL_PTLP_I_STATUS_WIDTH (32)
#define NBL_PTLP_I_STATUS_DWLEN (1)
union ptlp_i_status_u {
	struct ptlp_i_status {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_I_STATUS_DWLEN];
} __packed;

#define NBL_PTLP_H2I_I_PTLP_RAM_ERR_INFO_ADDR  (0xf4a250)
#define NBL_PTLP_H2I_I_PTLP_RAM_ERR_INFO_DEPTH (1)
#define NBL_PTLP_H2I_I_PTLP_RAM_ERR_INFO_WIDTH (32)
#define NBL_PTLP_H2I_I_PTLP_RAM_ERR_INFO_DWLEN (1)
union ptlp_h2i_i_ptlp_ram_err_info_u {
	struct ptlp_h2i_i_ptlp_ram_err_info {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PTLP_H2I_I_PTLP_RAM_ERR_INFO_DWLEN];
} __packed;

#endif
