// Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#ifndef NBL_DL4S_H
#define NBL_DL4S_H 1

#include <linux/types.h>

#define NBL_DL4S_BASE (0x00614000)

#define NBL_DL4S_INT_STATUS_ADDR  (0x614000)
#define NBL_DL4S_INT_STATUS_DEPTH (1)
#define NBL_DL4S_INT_STATUS_WIDTH (32)
#define NBL_DL4S_INT_STATUS_DWLEN (1)
union dl4s_int_status_u {
	struct dl4s_int_status {
		u32 ucor_err:1;          /* [0] Default:0x0 RWC */
		u32 cor_err:1;           /* [1] Default:0x0 RWC */
		u32 fifo_uflw_err:1;     /* [2] Default:0x0 RWC */
		u32 fifo_dflw_err:1;     /* [3] Default:0x0 RWC */
		u32 cif_err:1;           /* [4] Default:0x0 RWC */
		u32 parity_err:1;        /* [5] Default:0x0 RWC */
		u32 ce_mod_err:1;        /* [6] Default:0x0 RWC */
		u32 rec_len_err:1;       /* [7] Default:0x0 RWC */
		u32 rec_ver_err:1;       /* [8] Default:0x0 RWC */
		u32 rsv:23;              /* [31:9] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_INT_STATUS_DWLEN];
} __packed;

#define NBL_DL4S_INT_MASK_ADDR  (0x614004)
#define NBL_DL4S_INT_MASK_DEPTH (1)
#define NBL_DL4S_INT_MASK_WIDTH (32)
#define NBL_DL4S_INT_MASK_DWLEN (1)
union dl4s_int_mask_u {
	struct dl4s_int_mask {
		u32 ucor_err:1;          /* [0] Default:0x0 RW */
		u32 cor_err:1;           /* [1] Default:0x0 RW */
		u32 fifo_uflw_err:1;     /* [2] Default:0x0 RW */
		u32 fifo_dflw_err:1;     /* [3] Default:0x0 RW */
		u32 cif_err:1;           /* [4] Default:0x0 RW */
		u32 parity_err:1;        /* [5] Default:0x0 RW */
		u32 ce_mod_err:1;        /* [6] Default:0x0 RW */
		u32 rec_len_err:1;       /* [7] Default:0x0 RW */
		u32 rec_ver_err:1;       /* [8] Default:0x0 RW */
		u32 rsv:23;              /* [31:9] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_INT_MASK_DWLEN];
} __packed;

#define NBL_DL4S_INT_SET_ADDR  (0x614008)
#define NBL_DL4S_INT_SET_DEPTH (1)
#define NBL_DL4S_INT_SET_WIDTH (32)
#define NBL_DL4S_INT_SET_DWLEN (1)
union dl4s_int_set_u {
	struct dl4s_int_set {
		u32 ucor_err:1;          /* [0] Default:0x0 WO */
		u32 cor_err:1;           /* [1] Default:0x0 WO */
		u32 fifo_uflw_err:1;     /* [2] Default:0x0 WO */
		u32 fifo_dflw_err:1;     /* [3] Default:0x0 WO */
		u32 cif_err:1;           /* [4] Default:0x0 WO */
		u32 parity_err:1;        /* [5] Default:0x0 WO */
		u32 ce_mod_err:1;        /* [6] Default:0x0 WO */
		u32 rec_len_err:1;       /* [7] Default:0x0 WO */
		u32 rec_ver_err:1;       /* [8] Default:0x0 WO */
		u32 rsv:23;              /* [31:9] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_INT_SET_DWLEN];
} __packed;

#define NBL_DL4S_COR_ERR_INFO_ADDR  (0x614010)
#define NBL_DL4S_COR_ERR_INFO_DEPTH (1)
#define NBL_DL4S_COR_ERR_INFO_WIDTH (32)
#define NBL_DL4S_COR_ERR_INFO_DWLEN (1)
union dl4s_cor_err_info_u {
	struct dl4s_cor_err_info {
		u32 ram_addr:10;         /* [9:0] Default:0x0 RO */
		u32 rsv1:6;              /* [15:10] Default:0x0 RO */
		u32 ram_id:4;            /* [19:16] Default:0x0 RO */
		u32 rsv:12;              /* [31:20] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_COR_ERR_INFO_DWLEN];
} __packed;

#define NBL_DL4S_UNCOR_ERR_INFO_ADDR  (0x614018)
#define NBL_DL4S_UNCOR_ERR_INFO_DEPTH (1)
#define NBL_DL4S_UNCOR_ERR_INFO_WIDTH (32)
#define NBL_DL4S_UNCOR_ERR_INFO_DWLEN (1)
union dl4s_uncor_err_info_u {
	struct dl4s_uncor_err_info {
		u32 ram_addr:10;         /* [9:0] Default:0x0 RO */
		u32 rsv1:6;              /* [15:10] Default:0x0 RO */
		u32 ram_id:4;            /* [19:16] Default:0x0 RO */
		u32 rsv:12;              /* [31:20] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_UNCOR_ERR_INFO_DWLEN];
} __packed;

#define NBL_DL4S_PARITY_ERR_INFO_ADDR  (0x614030)
#define NBL_DL4S_PARITY_ERR_INFO_DEPTH (1)
#define NBL_DL4S_PARITY_ERR_INFO_WIDTH (32)
#define NBL_DL4S_PARITY_ERR_INFO_DWLEN (1)
union dl4s_parity_err_info_u {
	struct dl4s_parity_err_info {
		u32 ram_addr:10;         /* [9:0] Default:0x0 RO */
		u32 rsv1:6;              /* [15:10] Default:0x0 RO */
		u32 ram_id:4;            /* [19:16] Default:0x0 RO */
		u32 rsv:12;              /* [31:20] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_PARITY_ERR_INFO_DWLEN];
} __packed;

#define NBL_DL4S_CIF_ERR_INFO_ADDR  (0x614038)
#define NBL_DL4S_CIF_ERR_INFO_DEPTH (1)
#define NBL_DL4S_CIF_ERR_INFO_WIDTH (32)
#define NBL_DL4S_CIF_ERR_INFO_DWLEN (1)
union dl4s_cif_err_info_u {
	struct dl4s_cif_err_info {
		u32 addr:30;             /* [29:0] Default:0x0 RO */
		u32 wr_err:1;            /* [30] Default:0x0 RO */
		u32 ucor_err:1;          /* [31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_CIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_DL4S_CAR_CTRL_ADDR  (0x614100)
#define NBL_DL4S_CAR_CTRL_DEPTH (1)
#define NBL_DL4S_CAR_CTRL_WIDTH (32)
#define NBL_DL4S_CAR_CTRL_DWLEN (1)
union dl4s_car_ctrl_u {
	struct dl4s_car_ctrl {
		u32 sctr_car:1;          /* [0] Default:0x1 RW */
		u32 rctr_car:1;          /* [1] Default:0x1 RW */
		u32 rc_car:1;            /* [2] Default:0x1 RW */
		u32 tbl_rc_car:1;        /* [3] Default:0x1 RW */
		u32 rsv:28;              /* [31:4] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_CAR_CTRL_DWLEN];
} __packed;

#define NBL_DL4S_INIT_START_ADDR  (0x614104)
#define NBL_DL4S_INIT_START_DEPTH (1)
#define NBL_DL4S_INIT_START_WIDTH (32)
#define NBL_DL4S_INIT_START_DWLEN (1)
union dl4s_init_start_u {
	struct dl4s_init_start {
		u32 init_start:1;        /* [0] Default:0x0 WO */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_INIT_START_DWLEN];
} __packed;

#define NBL_DL4S_INTF_DATA_BUF_TH_ADDR  (0x614124)
#define NBL_DL4S_INTF_DATA_BUF_TH_DEPTH (1)
#define NBL_DL4S_INTF_DATA_BUF_TH_WIDTH (32)
#define NBL_DL4S_INTF_DATA_BUF_TH_DWLEN (1)
union dl4s_intf_data_buf_th_u {
	struct dl4s_intf_data_buf_th {
		u32 aful_high_th:8;      /* [7:0] Default:224 RW */
		u32 aful_low_th:8;       /* [15:8] Default:200 RW */
		u32 drop_th:8;           /* [23:16] Default:168 RW */
		u32 rsv:8;               /* [31:24] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_INTF_DATA_BUF_TH_DWLEN];
} __packed;

#define NBL_DL4S_REC_UDP_IV_BUF_TH_ADDR  (0x614180)
#define NBL_DL4S_REC_UDP_IV_BUF_TH_DEPTH (1)
#define NBL_DL4S_REC_UDP_IV_BUF_TH_WIDTH (32)
#define NBL_DL4S_REC_UDP_IV_BUF_TH_DWLEN (1)
union dl4s_rec_udp_iv_buf_th_u {
	struct dl4s_rec_udp_iv_buf_th {
		u32 aful_high_th:8;      /* [7:0] Default:32 RW */
		u32 aful_low_th:8;       /* [15:8] Default:24 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_REC_UDP_IV_BUF_TH_DWLEN];
} __packed;

#define NBL_DL4S_REC_UDP_DATA_BUF_TH_ADDR  (0x614188)
#define NBL_DL4S_REC_UDP_DATA_BUF_TH_DEPTH (1)
#define NBL_DL4S_REC_UDP_DATA_BUF_TH_WIDTH (32)
#define NBL_DL4S_REC_UDP_DATA_BUF_TH_DWLEN (1)
union dl4s_rec_udp_data_buf_th_u {
	struct dl4s_rec_udp_data_buf_th {
		u32 aful_high_th:8;      /* [7:0] Default:32 RW */
		u32 aful_low_th:8;       /* [15:8] Default:24 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_REC_UDP_DATA_BUF_TH_DWLEN];
} __packed;

#define NBL_DL4S_INTF_DATA_BUF_STATUS_CURR_ADDR  (0x614224)
#define NBL_DL4S_INTF_DATA_BUF_STATUS_CURR_DEPTH (1)
#define NBL_DL4S_INTF_DATA_BUF_STATUS_CURR_WIDTH (32)
#define NBL_DL4S_INTF_DATA_BUF_STATUS_CURR_DWLEN (1)
union dl4s_intf_data_buf_status_curr_u {
	struct dl4s_intf_data_buf_status_curr {
		u32 nempty:1;            /* [0] Default:0x0 RO */
		u32 nfull:1;             /* [1] Default:0x1 RO */
		u32 naempty:1;           /* [2] Default:0x0 RO */
		u32 nafull:1;            /* [3] Default:0x1 RO */
		u32 cnt:8;               /* [11:4] Default:0x0 RO */
		u32 rsv:20;              /* [31:12] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_INTF_DATA_BUF_STATUS_CURR_DWLEN];
} __packed;

#define NBL_DL4S_REC_UDP_IV_BUF_STATUS_CURR_ADDR  (0x614280)
#define NBL_DL4S_REC_UDP_IV_BUF_STATUS_CURR_DEPTH (1)
#define NBL_DL4S_REC_UDP_IV_BUF_STATUS_CURR_WIDTH (32)
#define NBL_DL4S_REC_UDP_IV_BUF_STATUS_CURR_DWLEN (1)
union dl4s_rec_udp_iv_buf_status_curr_u {
	struct dl4s_rec_udp_iv_buf_status_curr {
		u32 nempty:1;            /* [0] Default:0x0 RO */
		u32 nfull:1;             /* [1] Default:0x1 RO */
		u32 naempty:1;           /* [2] Default:0x0 RO */
		u32 nafull:1;            /* [3] Default:0x1 RO */
		u32 cnt:8;               /* [11:4] Default:0x0 RO */
		u32 rsv:20;              /* [31:12] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_REC_UDP_IV_BUF_STATUS_CURR_DWLEN];
} __packed;

#define NBL_DL4S_REC_UDP_INFO_STATUS_CURR_ADDR  (0x614284)
#define NBL_DL4S_REC_UDP_INFO_STATUS_CURR_DEPTH (1)
#define NBL_DL4S_REC_UDP_INFO_STATUS_CURR_WIDTH (32)
#define NBL_DL4S_REC_UDP_INFO_STATUS_CURR_DWLEN (1)
union dl4s_rec_udp_info_status_curr_u {
	struct dl4s_rec_udp_info_status_curr {
		u32 nempty:1;            /* [0] Default:0x0 RO */
		u32 nfull:1;             /* [1] Default:0x1 RO */
		u32 naempty:1;           /* [2] Default:0x0 RO */
		u32 nafull:1;            /* [3] Default:0x1 RO */
		u32 cnt:8;               /* [11:4] Default:0x0 RO */
		u32 rsv:20;              /* [31:12] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_REC_UDP_INFO_STATUS_CURR_DWLEN];
} __packed;

#define NBL_DL4S_REC_UDP_INFO_DONE_STATUS_CURR_ADDR  (0x61428c)
#define NBL_DL4S_REC_UDP_INFO_DONE_STATUS_CURR_DEPTH (1)
#define NBL_DL4S_REC_UDP_INFO_DONE_STATUS_CURR_WIDTH (32)
#define NBL_DL4S_REC_UDP_INFO_DONE_STATUS_CURR_DWLEN (1)
union dl4s_rec_udp_info_done_status_curr_u {
	struct dl4s_rec_udp_info_done_status_curr {
		u32 nempty:1;            /* [0] Default:0x0 RO */
		u32 nfull:1;             /* [1] Default:0x1 RO */
		u32 naempty:1;           /* [2] Default:0x0 RO */
		u32 nafull:1;            /* [3] Default:0x1 RO */
		u32 cnt:8;               /* [11:4] Default:0x0 RO */
		u32 rsv:20;              /* [31:12] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_REC_UDP_INFO_DONE_STATUS_CURR_DWLEN];
} __packed;

#define NBL_DL4S_REC_UDP_DATA_DONE_STATUS_CURR_ADDR  (0x614290)
#define NBL_DL4S_REC_UDP_DATA_DONE_STATUS_CURR_DEPTH (1)
#define NBL_DL4S_REC_UDP_DATA_DONE_STATUS_CURR_WIDTH (32)
#define NBL_DL4S_REC_UDP_DATA_DONE_STATUS_CURR_DWLEN (1)
union dl4s_rec_udp_data_done_status_curr_u {
	struct dl4s_rec_udp_data_done_status_curr {
		u32 nempty:1;            /* [0] Default:0x0 RO */
		u32 nfull:1;             /* [1] Default:0x1 RO */
		u32 naempty:1;           /* [2] Default:0x0 RO */
		u32 nafull:1;            /* [3] Default:0x1 RO */
		u32 cnt:8;               /* [11:4] Default:0x0 RO */
		u32 rsv:20;              /* [31:12] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_REC_UDP_DATA_DONE_STATUS_CURR_DWLEN];
} __packed;

#define NBL_DL4S_L4S_RX_SYNC_ADDR  (0x614420)
#define NBL_DL4S_L4S_RX_SYNC_DEPTH (1)
#define NBL_DL4S_L4S_RX_SYNC_WIDTH (32)
#define NBL_DL4S_L4S_RX_SYNC_DWLEN (1)
union dl4s_l4s_rx_sync_u {
	struct dl4s_l4s_rx_sync {
		u32 redun_cnt:16;        /* [15:0] Default:0x0 RCTR */
		u32 cnt:16;              /* [31:16] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DL4S_L4S_RX_SYNC_DWLEN];
} __packed;

#define NBL_DL4S_L4S_RX_INFO_ADDR  (0x614424)
#define NBL_DL4S_L4S_RX_INFO_DEPTH (1)
#define NBL_DL4S_L4S_RX_INFO_WIDTH (32)
#define NBL_DL4S_L4S_RX_INFO_DWLEN (1)
union dl4s_l4s_rx_info_u {
	struct dl4s_l4s_rx_info {
		u32 cnt:16;              /* [15:0] Default:0x0 RCTR */
		u32 drcnt:16;            /* [31:16] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DL4S_L4S_RX_INFO_DWLEN];
} __packed;

#define NBL_DL4S_L4S_RX_LEN_ADDR  (0x614428)
#define NBL_DL4S_L4S_RX_LEN_DEPTH (1)
#define NBL_DL4S_L4S_RX_LEN_WIDTH (32)
#define NBL_DL4S_L4S_RX_LEN_DWLEN (1)
union dl4s_l4s_rx_len_u {
	struct dl4s_l4s_rx_len {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DL4S_L4S_RX_LEN_DWLEN];
} __packed;

#define NBL_DL4S_L4S_RX_CELL_ADDR  (0x61442c)
#define NBL_DL4S_L4S_RX_CELL_DEPTH (1)
#define NBL_DL4S_L4S_RX_CELL_WIDTH (32)
#define NBL_DL4S_L4S_RX_CELL_DWLEN (1)
union dl4s_l4s_rx_cell_u {
	struct dl4s_l4s_rx_cell {
		u32 cnt:16;              /* [15:0] Default:0x0 RCTR */
		u32 rsv1:8;              /* [23:16] Default:0x0 RO */
		u32 rsv:8;               /* [31:24] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_L4S_RX_CELL_DWLEN];
} __packed;

#define NBL_DL4S_L4S_TX_INFO_ADDR  (0x614430)
#define NBL_DL4S_L4S_TX_INFO_DEPTH (1)
#define NBL_DL4S_L4S_TX_INFO_WIDTH (32)
#define NBL_DL4S_L4S_TX_INFO_DWLEN (1)
union dl4s_l4s_tx_info_u {
	struct dl4s_l4s_tx_info {
		u32 cell_cnt:16;         /* [15:0] Default:0x0 RCTR */
		u32 pkt_cnt:16;          /* [31:16] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DL4S_L4S_TX_INFO_DWLEN];
} __packed;

#define NBL_DL4S_L4S_TX_LEN_ADDR  (0x614434)
#define NBL_DL4S_L4S_TX_LEN_DEPTH (1)
#define NBL_DL4S_L4S_TX_LEN_WIDTH (32)
#define NBL_DL4S_L4S_TX_LEN_DWLEN (1)
union dl4s_l4s_tx_len_u {
	struct dl4s_l4s_tx_len {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DL4S_L4S_TX_LEN_DWLEN];
} __packed;

#define NBL_DL4S_REC_PARSE_RX_ADDR  (0x614440)
#define NBL_DL4S_REC_PARSE_RX_DEPTH (1)
#define NBL_DL4S_REC_PARSE_RX_WIDTH (32)
#define NBL_DL4S_REC_PARSE_RX_DWLEN (1)
union dl4s_rec_parse_rx_u {
	struct dl4s_rec_parse_rx {
		u32 ind_cnt:8;           /* [7:0] Default:0x0 RCTR */
		u32 redun_head_cnt:8;    /* [15:8] Default:0x0 RCTR */
		u32 redun_cnt:8;         /* [23:16] Default:0x0 RCTR */
		u32 sync_cnt:8;          /* [31:24] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DL4S_REC_PARSE_RX_DWLEN];
} __packed;

#define NBL_DL4S_REC_PARSE_INFO_ADDR  (0x614444)
#define NBL_DL4S_REC_PARSE_INFO_DEPTH (1)
#define NBL_DL4S_REC_PARSE_INFO_WIDTH (32)
#define NBL_DL4S_REC_PARSE_INFO_DWLEN (1)
union dl4s_rec_parse_info_u {
	struct dl4s_rec_parse_info {
		u32 eop_cnt:8;           /* [7:0] Default:0x0 RCTR */
		u32 info_cnt:8;          /* [15:8] Default:0x0 RCTR */
		u32 rcnt:8;              /* [23:16] Default:0x0 RCTR */
		u32 wcnt:8;              /* [31:24] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DL4S_REC_PARSE_INFO_DWLEN];
} __packed;

#define NBL_DL4S_REC_PARSE_RES_ADDR  (0x614448)
#define NBL_DL4S_REC_PARSE_RES_DEPTH (1)
#define NBL_DL4S_REC_PARSE_RES_WIDTH (32)
#define NBL_DL4S_REC_PARSE_RES_DWLEN (1)
union dl4s_rec_parse_res_u {
	struct dl4s_rec_parse_res {
		u32 eor_cnt:16;          /* [15:0] Default:0x0 RCTR */
		u32 sor_cnt:16;          /* [31:16] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DL4S_REC_PARSE_RES_DWLEN];
} __packed;

#define NBL_DL4S_REC_PARSE_INI_ADDR  (0x61444c)
#define NBL_DL4S_REC_PARSE_INI_DEPTH (1)
#define NBL_DL4S_REC_PARSE_INI_WIDTH (32)
#define NBL_DL4S_REC_PARSE_INI_DWLEN (1)
union dl4s_rec_parse_ini_u {
	struct dl4s_rec_parse_ini {
		u32 resync_cnt:8;        /* [7:0] Default:0x0 RCTR */
		u32 init_cnt:8;          /* [15:8] Default:0x0 RCTR */
		u32 eob_cnt:8;           /* [23:16] Default:0x0 RCTR */
		u32 sob_cnt:8;           /* [31:24] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DL4S_REC_PARSE_INI_DWLEN];
} __packed;

#define NBL_DL4S_REC_DEPART_ADDR  (0x614450)
#define NBL_DL4S_REC_DEPART_DEPTH (1)
#define NBL_DL4S_REC_DEPART_WIDTH (32)
#define NBL_DL4S_REC_DEPART_DWLEN (1)
union dl4s_rec_depart_u {
	struct dl4s_rec_depart {
		u32 eob_cnt:8;           /* [7:0] Default:0x0 RCTR */
		u32 sob_cnt:8;           /* [15:8] Default:0x0 RCTR */
		u32 eor_cnt:8;           /* [23:16] Default:0x0 RCTR */
		u32 sor_cnt:8;           /* [31:24] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DL4S_REC_DEPART_DWLEN];
} __packed;

#define NBL_DL4S_REC_DEPART_INFO_ADDR  (0x614454)
#define NBL_DL4S_REC_DEPART_INFO_DEPTH (1)
#define NBL_DL4S_REC_DEPART_INFO_WIDTH (32)
#define NBL_DL4S_REC_DEPART_INFO_DWLEN (1)
union dl4s_rec_depart_info_u {
	struct dl4s_rec_depart_info {
		u32 eop_cnt:8;           /* [7:0] Default:0x0 RCTR */
		u32 cnt:8;               /* [15:8] Default:0x0 RCTR */
		u32 eicv_cnt:8;          /* [23:16] Default:0x0 RCTR */
		u32 loss_cnt:8;          /* [31:24] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DL4S_REC_DEPART_INFO_DWLEN];
} __packed;

#define NBL_DL4S_REC_DEPART_HEAD_ADDR  (0x614458)
#define NBL_DL4S_REC_DEPART_HEAD_DEPTH (1)
#define NBL_DL4S_REC_DEPART_HEAD_WIDTH (32)
#define NBL_DL4S_REC_DEPART_HEAD_DWLEN (1)
union dl4s_rec_depart_head_u {
	struct dl4s_rec_depart_head {
		u32 cnt:8;               /* [7:0] Default:0x0 RCTR */
		u32 rsv:24;              /* [31:8] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_REC_DEPART_HEAD_DWLEN];
} __packed;

#define NBL_DL4S_REC_DEP_ADA_ADDR  (0x614460)
#define NBL_DL4S_REC_DEP_ADA_DEPTH (1)
#define NBL_DL4S_REC_DEP_ADA_WIDTH (32)
#define NBL_DL4S_REC_DEP_ADA_DWLEN (1)
union dl4s_rec_dep_ada_u {
	struct dl4s_rec_dep_ada {
		u32 eob_cnt:8;           /* [7:0] Default:0x0 RCTR */
		u32 sob_cnt:8;           /* [15:8] Default:0x0 RCTR */
		u32 eor_cnt:8;           /* [23:16] Default:0x0 RCTR */
		u32 sor_cnt:8;           /* [31:24] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DL4S_REC_DEP_ADA_DWLEN];
} __packed;

#define NBL_DL4S_REC_DEP_ADA_INFO_ADDR  (0x614464)
#define NBL_DL4S_REC_DEP_ADA_INFO_DEPTH (1)
#define NBL_DL4S_REC_DEP_ADA_INFO_WIDTH (32)
#define NBL_DL4S_REC_DEP_ADA_INFO_DWLEN (1)
union dl4s_rec_dep_ada_info_u {
	struct dl4s_rec_dep_ada_info {
		u32 eop_cnt:8;           /* [7:0] Default:0x0 RCTR */
		u32 rsv:24;              /* [31:8] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_REC_DEP_ADA_INFO_DWLEN];
} __packed;

#define NBL_DL4S_REC_UPD_ADA_ADDR  (0x614470)
#define NBL_DL4S_REC_UPD_ADA_DEPTH (1)
#define NBL_DL4S_REC_UPD_ADA_WIDTH (32)
#define NBL_DL4S_REC_UPD_ADA_DWLEN (1)
union dl4s_rec_upd_ada_u {
	struct dl4s_rec_upd_ada {
		u32 eop_cnt:8;           /* [7:0] Default:0x0 RCTR */
		u32 icv_cnt:8;           /* [15:8] Default:0x0 RCTR */
		u32 sob_cnt:8;           /* [23:16] Default:0x0 RCTR */
		u32 rsv:8;               /* [31:24] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_REC_UPD_ADA_DWLEN];
} __packed;

#define NBL_DL4S_REC_UPDATE_ADDR  (0x614480)
#define NBL_DL4S_REC_UPDATE_DEPTH (1)
#define NBL_DL4S_REC_UPDATE_WIDTH (32)
#define NBL_DL4S_REC_UPDATE_DWLEN (1)
union dl4s_rec_update_u {
	struct dl4s_rec_update {
		u32 bp_rcnt:8;           /* [7:0] Default:0x0 RCTR */
		u32 bp_wcnt:8;           /* [15:8] Default:0x0 RCTR */
		u32 cip_rcnt:8;          /* [23:16] Default:0x0 RCTR */
		u32 cip_wcnt:8;          /* [31:24] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DL4S_REC_UPDATE_DWLEN];
} __packed;

#define NBL_DL4S_REC_UPDATE_INFO_ADDR  (0x614484)
#define NBL_DL4S_REC_UPDATE_INFO_DEPTH (1)
#define NBL_DL4S_REC_UPDATE_INFO_WIDTH (32)
#define NBL_DL4S_REC_UPDATE_INFO_DWLEN (1)
union dl4s_rec_update_info_u {
	struct dl4s_rec_update_info {
		u32 eop_cnt:8;           /* [7:0] Default:0x0 RCTR */
		u32 cnt:8;               /* [15:8] Default:0x0 RCTR */
		u32 icv_cnt:8;           /* [23:16] Default:0x0 RCTR */
		u32 cell_cnt:8;          /* [31:24] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DL4S_REC_UPDATE_INFO_DWLEN];
} __packed;

#define NBL_DL4S_UNL4S_RX_INFO_ADDR  (0x614490)
#define NBL_DL4S_UNL4S_RX_INFO_DEPTH (1)
#define NBL_DL4S_UNL4S_RX_INFO_WIDTH (32)
#define NBL_DL4S_UNL4S_RX_INFO_DWLEN (1)
union dl4s_unl4s_rx_info_u {
	struct dl4s_unl4s_rx_info {
		u32 cell_cnt:16;         /* [15:0] Default:0x0 RCTR */
		u32 pkt_cnt:16;          /* [31:16] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DL4S_UNL4S_RX_INFO_DWLEN];
} __packed;

#define NBL_DL4S_UNL4S_RX_LEN_ADDR  (0x614494)
#define NBL_DL4S_UNL4S_RX_LEN_DEPTH (1)
#define NBL_DL4S_UNL4S_RX_LEN_WIDTH (32)
#define NBL_DL4S_UNL4S_RX_LEN_DWLEN (1)
union dl4s_unl4s_rx_len_u {
	struct dl4s_unl4s_rx_len {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DL4S_UNL4S_RX_LEN_DWLEN];
} __packed;

#define NBL_DL4S_UNL4S_TX_INFO_ADDR  (0x6144a0)
#define NBL_DL4S_UNL4S_TX_INFO_DEPTH (1)
#define NBL_DL4S_UNL4S_TX_INFO_WIDTH (32)
#define NBL_DL4S_UNL4S_TX_INFO_DWLEN (1)
union dl4s_unl4s_tx_info_u {
	struct dl4s_unl4s_tx_info {
		u32 cell_cnt:16;         /* [15:0] Default:0x0 RCTR */
		u32 pkt_cnt:16;          /* [31:16] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DL4S_UNL4S_TX_INFO_DWLEN];
} __packed;

#define NBL_DL4S_UNL4S_TX_LEN_ADDR  (0x6144a4)
#define NBL_DL4S_UNL4S_TX_LEN_DEPTH (1)
#define NBL_DL4S_UNL4S_TX_LEN_WIDTH (32)
#define NBL_DL4S_UNL4S_TX_LEN_DWLEN (1)
union dl4s_unl4s_tx_len_u {
	struct dl4s_unl4s_tx_len {
		u32 cnt:32;              /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DL4S_UNL4S_TX_LEN_DWLEN];
} __packed;

#define NBL_DL4S_RD_INFO_ADDR  (0x6144b0)
#define NBL_DL4S_RD_INFO_DEPTH (1)
#define NBL_DL4S_RD_INFO_WIDTH (32)
#define NBL_DL4S_RD_INFO_DWLEN (1)
union dl4s_rd_info_u {
	struct dl4s_rd_info {
		u32 unl4s_cnt:16;        /* [15:0] Default:0x0 RCTR */
		u32 l4s_cnt:16;          /* [31:16] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DL4S_RD_INFO_DWLEN];
} __packed;

#define NBL_DL4S_INT_TX_ADDR  (0x6144b4)
#define NBL_DL4S_INT_TX_DEPTH (1)
#define NBL_DL4S_INT_TX_WIDTH (32)
#define NBL_DL4S_INT_TX_DWLEN (1)
union dl4s_int_tx_u {
	struct dl4s_int_tx {
		u32 data_cnt:16;         /* [15:0] Default:0x0 RCTR */
		u32 info_cnt:16;         /* [31:16] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DL4S_INT_TX_DWLEN];
} __packed;

#define NBL_DL4S_REC_DEP_ADA_IV_ADDR  (0x614564)
#define NBL_DL4S_REC_DEP_ADA_IV_DEPTH (1)
#define NBL_DL4S_REC_DEP_ADA_IV_WIDTH (32)
#define NBL_DL4S_REC_DEP_ADA_IV_DWLEN (1)
union dl4s_rec_dep_ada_iv_u {
	struct dl4s_rec_dep_ada_iv {
		u32 val:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_REC_DEP_ADA_IV_DWLEN];
} __packed;

#define NBL_DL4S_REC_DEP_ADA_SN_ADDR  (0x614568)
#define NBL_DL4S_REC_DEP_ADA_SN_DEPTH (1)
#define NBL_DL4S_REC_DEP_ADA_SN_WIDTH (32)
#define NBL_DL4S_REC_DEP_ADA_SN_DWLEN (1)
union dl4s_rec_dep_ada_sn_u {
	struct dl4s_rec_dep_ada_sn {
		u32 val:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_REC_DEP_ADA_SN_DWLEN];
} __packed;

#define NBL_DL4S_REC_DEP_ADA_CE_ADDR  (0x61456c)
#define NBL_DL4S_REC_DEP_ADA_CE_DEPTH (1)
#define NBL_DL4S_REC_DEP_ADA_CE_WIDTH (32)
#define NBL_DL4S_REC_DEP_ADA_CE_DWLEN (1)
union dl4s_rec_dep_ada_ce_u {
	struct dl4s_rec_dep_ada_ce {
		u32 len:11;              /* [10:0] Default:0x0 RO */
		u32 rsv1:5;              /* [15:11] Default:0x0 RO */
		u32 sid:10;              /* [25:16] Default:0x0 RO */
		u32 rsv:6;               /* [31:26] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_REC_DEP_ADA_CE_DWLEN];
} __packed;

#define NBL_DL4S_INIT_DONE_ADDR  (0x614600)
#define NBL_DL4S_INIT_DONE_DEPTH (1)
#define NBL_DL4S_INIT_DONE_WIDTH (32)
#define NBL_DL4S_INIT_DONE_DWLEN (1)
union dl4s_init_done_u {
	struct dl4s_init_done {
		u32 done:1;              /* [0] Default:0x0 RO */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_INIT_DONE_DWLEN];
} __packed;

#define NBL_DL4S_VER_YEAR_MONTH_ADDR  (0x614604)
#define NBL_DL4S_VER_YEAR_MONTH_DEPTH (1)
#define NBL_DL4S_VER_YEAR_MONTH_WIDTH (32)
#define NBL_DL4S_VER_YEAR_MONTH_DWLEN (1)
union dl4s_ver_year_month_u {
	struct dl4s_ver_year_month {
		u32 month:8;             /* [7:0] Default:0x06 RO */
		u32 year:8;              /* [15:8] Default:0x22 RO */
		u32 version:8;           /* [23:16] Default:0x21 RO */
		u32 reg_type:8;          /* [31:24] Default:0x5a RO */
	} __packed info;
	u32 data[NBL_DL4S_VER_YEAR_MONTH_DWLEN];
} __packed;

#define NBL_DL4S_REG_TEST_ADDR  (0x614608)
#define NBL_DL4S_REG_TEST_DEPTH (1)
#define NBL_DL4S_REG_TEST_WIDTH (32)
#define NBL_DL4S_REG_TEST_DWLEN (1)
union dl4s_reg_test_u {
	struct dl4s_reg_test {
		u32 reg_test:32;         /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_DL4S_REG_TEST_DWLEN];
} __packed;

#define NBL_DL4S_REC_FULL_DROP_ADDR  (0x614610)
#define NBL_DL4S_REC_FULL_DROP_DEPTH (1)
#define NBL_DL4S_REC_FULL_DROP_WIDTH (32)
#define NBL_DL4S_REC_FULL_DROP_DWLEN (1)
union dl4s_rec_full_drop_u {
	struct dl4s_rec_full_drop {
		u32 en:1;                /* [0] Default:0x0 RW */
		u32 rsv:31;              /* [31:1] Default:0x00 RO */
	} __packed info;
	u32 data[NBL_DL4S_REC_FULL_DROP_DWLEN];
} __packed;

#define NBL_DL4S_REC_HEAD_VERSION_ADDR  (0x614630)
#define NBL_DL4S_REC_HEAD_VERSION_DEPTH (1)
#define NBL_DL4S_REC_HEAD_VERSION_WIDTH (32)
#define NBL_DL4S_REC_HEAD_VERSION_DWLEN (1)
union dl4s_rec_head_version_u {
	struct dl4s_rec_head_version {
		u32 v0:16;               /* [15:0] Default:0x0302 RW */
		u32 v1:16;               /* [31:16] Default:0x0303 RW */
	} __packed info;
	u32 data[NBL_DL4S_REC_HEAD_VERSION_DWLEN];
} __packed;

#define NBL_DL4S_SCH_ADDR  (0x6146c0)
#define NBL_DL4S_SCH_DEPTH (1)
#define NBL_DL4S_SCH_WIDTH (32)
#define NBL_DL4S_SCH_DWLEN (1)
union dl4s_sch_u {
	struct dl4s_sch {
		u32 pri:2;               /* [1:0] Default:0x2 RW */
		u32 rsv:30;              /* [31:2] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_SCH_DWLEN];
} __packed;

#define NBL_DL4S_TAB_KEY_SALT_ADDR  (0x624000)
#define NBL_DL4S_TAB_KEY_SALT_DEPTH (1024)
#define NBL_DL4S_TAB_KEY_SALT_WIDTH (512)
#define NBL_DL4S_TAB_KEY_SALT_DWLEN (16)
union dl4s_tab_key_salt_u {
	struct dl4s_tab_key_salt {
		u32 key_arr[8];          /* [255:0] Default:0x0 RW */
		u32 salt:32;             /* [287:256] Default:0x0 RW */
		u32 mode:2;              /* [289:288] Default:0x0 RW */
		u32 ena:1;               /* [290] Default:0x0 RW */
		u32 rsv:29;              /* [511:291] Default:0x0 RO */
		u32 rsv_arr[6];          /* [511:291] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DL4S_TAB_KEY_SALT_DWLEN];
} __packed;
#define NBL_DL4S_TAB_KEY_SALT_REG(r) (NBL_DL4S_TAB_KEY_SALT_ADDR + \
		(NBL_DL4S_TAB_KEY_SALT_DWLEN * 4) * (r))

#endif
