// Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#ifndef NBL_DDMUX_H
#define NBL_DDMUX_H 1

#include <linux/types.h>

#define NBL_DDMUX_BASE (0x00984000)

#define NBL_DDMUX_INT_STATUS_ADDR  (0x984000)
#define NBL_DDMUX_INT_STATUS_DEPTH (1)
#define NBL_DDMUX_INT_STATUS_WIDTH (32)
#define NBL_DDMUX_INT_STATUS_DWLEN (1)
union ddmux_int_status_u {
	struct ddmux_int_status {
		u32 ucor_err:1;          /* [0] Default:0x0 RWC */
		u32 cor_err:1;           /* [1] Default:0x0 RWC */
		u32 fifo_uflw_err:1;     /* [2] Default:0x0 RWC */
		u32 fifo_dflw_err:1;     /* [3] Default:0x0 RWC */
		u32 parity_err:1;        /* [4] Default:0x0 RWC */
		u32 cif_err:1;           /* [5] Default:0x0 RWC */
		u32 eth0_rdy_err:1;      /* [6] Default:0x0 RWC */
		u32 eth1_rdy_err:1;      /* [7] Default:0x0 RWC */
		u32 eth2_rdy_err:1;      /* [8] Default:0x0 RWC */
		u32 eth3_rdy_err:1;      /* [9] Default:0x0 RWC */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DDMUX_INT_STATUS_DWLEN];
} __packed;

#define NBL_DDMUX_INT_MASK_ADDR  (0x984004)
#define NBL_DDMUX_INT_MASK_DEPTH (1)
#define NBL_DDMUX_INT_MASK_WIDTH (32)
#define NBL_DDMUX_INT_MASK_DWLEN (1)
union ddmux_int_mask_u {
	struct ddmux_int_mask {
		u32 ucor_err:1;          /* [0] Default:0x0 RW */
		u32 cor_err:1;           /* [1] Default:0x0 RW */
		u32 fifo_uflw_err:1;     /* [2] Default:0x0 RW */
		u32 fifo_dflw_err:1;     /* [3] Default:0x0 RW */
		u32 parity_err:1;        /* [4] Default:0x0 RW */
		u32 cif_err:1;           /* [5] Default:0x0 RW */
		u32 eth0_rdy_err:1;      /* [6] Default:0x0 RW */
		u32 eth1_rdy_err:1;      /* [7] Default:0x0 RW */
		u32 eth2_rdy_err:1;      /* [8] Default:0x0 RW */
		u32 eth3_rdy_err:1;      /* [9] Default:0x0 RW */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DDMUX_INT_MASK_DWLEN];
} __packed;

#define NBL_DDMUX_INT_SET_ADDR  (0x984008)
#define NBL_DDMUX_INT_SET_DEPTH (1)
#define NBL_DDMUX_INT_SET_WIDTH (32)
#define NBL_DDMUX_INT_SET_DWLEN (1)
union ddmux_int_set_u {
	struct ddmux_int_set {
		u32 ucor_err:1;          /* [0] Default:0x0 WO */
		u32 cor_err:1;           /* [1] Default:0x0 WO */
		u32 fifo_uflw_err:1;     /* [2] Default:0x0 WO */
		u32 fifo_dflw_err:1;     /* [3] Default:0x0 WO */
		u32 parity_err:1;        /* [4] Default:0x0 WO */
		u32 cif_err:1;           /* [5] Default:0x0 WO */
		u32 eth0_rdy_err:1;      /* [6] Default:0x0 WO */
		u32 eth1_rdy_err:1;      /* [7] Default:0x0 WO */
		u32 eth2_rdy_err:1;      /* [8] Default:0x0 WO */
		u32 eth3_rdy_err:1;      /* [9] Default:0x0 WO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DDMUX_INT_SET_DWLEN];
} __packed;

#define NBL_DDMUX_UCOR_ERR_INFO_ADDR  (0x98400c)
#define NBL_DDMUX_UCOR_ERR_INFO_DEPTH (1)
#define NBL_DDMUX_UCOR_ERR_INFO_WIDTH (32)
#define NBL_DDMUX_UCOR_ERR_INFO_DWLEN (1)
union ddmux_ucor_err_info_u {
	struct ddmux_ucor_err_info {
		u32 ram_addr:28;         /* [27:0] Default:0x0 RO */
		u32 ram_id:4;            /* [31:28] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DDMUX_UCOR_ERR_INFO_DWLEN];
} __packed;

#define NBL_DDMUX_COR_ERR_INFO_ADDR  (0x984014)
#define NBL_DDMUX_COR_ERR_INFO_DEPTH (1)
#define NBL_DDMUX_COR_ERR_INFO_WIDTH (32)
#define NBL_DDMUX_COR_ERR_INFO_DWLEN (1)
union ddmux_cor_err_info_u {
	struct ddmux_cor_err_info {
		u32 ram_addr:28;         /* [27:0] Default:0x0 RO */
		u32 ram_id:4;            /* [31:28] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DDMUX_COR_ERR_INFO_DWLEN];
} __packed;

#define NBL_DDMUX_PARITY_ERR_INFO_ADDR  (0x98402c)
#define NBL_DDMUX_PARITY_ERR_INFO_DEPTH (1)
#define NBL_DDMUX_PARITY_ERR_INFO_WIDTH (32)
#define NBL_DDMUX_PARITY_ERR_INFO_DWLEN (1)
union ddmux_parity_err_info_u {
	struct ddmux_parity_err_info {
		u32 ram_addr:28;         /* [27:0] Default:0x0 RO */
		u32 ram_id:4;            /* [31:28] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DDMUX_PARITY_ERR_INFO_DWLEN];
} __packed;

#define NBL_DDMUX_CIF_ERR_INFO_ADDR  (0x984044)
#define NBL_DDMUX_CIF_ERR_INFO_DEPTH (1)
#define NBL_DDMUX_CIF_ERR_INFO_WIDTH (32)
#define NBL_DDMUX_CIF_ERR_INFO_DWLEN (1)
union ddmux_cif_err_info_u {
	struct ddmux_cif_err_info {
		u32 addr:30;             /* [29:0] Default:0x0 RO */
		u32 wr_err:1;            /* [30] Default:0x0 RO */
		u32 ucor_err:1;          /* [31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DDMUX_CIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_DDMUX_CAR_CTRL_ADDR  (0x984100)
#define NBL_DDMUX_CAR_CTRL_DEPTH (1)
#define NBL_DDMUX_CAR_CTRL_WIDTH (32)
#define NBL_DDMUX_CAR_CTRL_DWLEN (1)
union ddmux_car_ctrl_u {
	struct ddmux_car_ctrl {
		u32 sctr_car:1;          /* [0] Default:0x1 RW */
		u32 rctr_car:1;          /* [1] Default:0x1 RW */
		u32 rc_car:1;            /* [2] Default:0x1 RW */
		u32 tbl_rc_car:1;        /* [3] Default:0x1 RW */
		u32 rsv:28;              /* [31:4] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DDMUX_CAR_CTRL_DWLEN];
} __packed;

#define NBL_DDMUX_ETH0_FC_TH_ADDR  (0x98411c)
#define NBL_DDMUX_ETH0_FC_TH_DEPTH (1)
#define NBL_DDMUX_ETH0_FC_TH_WIDTH (32)
#define NBL_DDMUX_ETH0_FC_TH_DWLEN (1)
union ddmux_eth0_fc_th_u {
	struct ddmux_eth0_fc_th {
		u32 fc_th:11;            /* [10:0] Default:320 RW */
		u32 rsv:21;              /* [31:11] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DDMUX_ETH0_FC_TH_DWLEN];
} __packed;

#define NBL_DDMUX_ETH1_FC_TH_ADDR  (0x984120)
#define NBL_DDMUX_ETH1_FC_TH_DEPTH (1)
#define NBL_DDMUX_ETH1_FC_TH_WIDTH (32)
#define NBL_DDMUX_ETH1_FC_TH_DWLEN (1)
union ddmux_eth1_fc_th_u {
	struct ddmux_eth1_fc_th {
		u32 fc_th:11;            /* [10:0] Default:320 RW */
		u32 rsv:21;              /* [31:11] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DDMUX_ETH1_FC_TH_DWLEN];
} __packed;

#define NBL_DDMUX_ETH2_FC_TH_ADDR  (0x984124)
#define NBL_DDMUX_ETH2_FC_TH_DEPTH (1)
#define NBL_DDMUX_ETH2_FC_TH_WIDTH (32)
#define NBL_DDMUX_ETH2_FC_TH_DWLEN (1)
union ddmux_eth2_fc_th_u {
	struct ddmux_eth2_fc_th {
		u32 fc_th:11;            /* [10:0] Default:320 RW */
		u32 rsv:21;              /* [31:11] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DDMUX_ETH2_FC_TH_DWLEN];
} __packed;

#define NBL_DDMUX_ETH3_FC_TH_ADDR  (0x984128)
#define NBL_DDMUX_ETH3_FC_TH_DEPTH (1)
#define NBL_DDMUX_ETH3_FC_TH_WIDTH (32)
#define NBL_DDMUX_ETH3_FC_TH_DWLEN (1)
union ddmux_eth3_fc_th_u {
	struct ddmux_eth3_fc_th {
		u32 fc_th:11;            /* [10:0] Default:320 RW */
		u32 rsv:21;              /* [31:11] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DDMUX_ETH3_FC_TH_DWLEN];
} __packed;

#define NBL_DDMUX_ETH_LINK_FC_EN_ADDR  (0x98412c)
#define NBL_DDMUX_ETH_LINK_FC_EN_DEPTH (1)
#define NBL_DDMUX_ETH_LINK_FC_EN_WIDTH (32)
#define NBL_DDMUX_ETH_LINK_FC_EN_DWLEN (1)
union ddmux_eth_link_fc_en_u {
	struct ddmux_eth_link_fc_en {
		u32 eth0_link_fc_en:1;   /* [0] Default:0x1 RW */
		u32 eth1_link_fc_en:1;   /* [1] Default:0x1 RW */
		u32 eth2_link_fc_en:1;   /* [2] Default:0x1 RW */
		u32 eth3_link_fc_en:1;   /* [3] Default:0x1 RW */
		u32 rsv:28;              /* [31:4] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DDMUX_ETH_LINK_FC_EN_DWLEN];
} __packed;

#define NBL_DDMUX_ETH0_RDY_TIMEOUT_ADDR  (0x984130)
#define NBL_DDMUX_ETH0_RDY_TIMEOUT_DEPTH (1)
#define NBL_DDMUX_ETH0_RDY_TIMEOUT_WIDTH (32)
#define NBL_DDMUX_ETH0_RDY_TIMEOUT_DWLEN (1)
union ddmux_eth0_rdy_timeout_u {
	struct ddmux_eth0_rdy_timeout {
		u32 eth0_rdy_timeout:16; /* [15:0] Default:0xffff RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DDMUX_ETH0_RDY_TIMEOUT_DWLEN];
} __packed;

#define NBL_DDMUX_ETH1_RDY_TIMEOUT_ADDR  (0x984134)
#define NBL_DDMUX_ETH1_RDY_TIMEOUT_DEPTH (1)
#define NBL_DDMUX_ETH1_RDY_TIMEOUT_WIDTH (32)
#define NBL_DDMUX_ETH1_RDY_TIMEOUT_DWLEN (1)
union ddmux_eth1_rdy_timeout_u {
	struct ddmux_eth1_rdy_timeout {
		u32 eth1_rdy_timeout:16; /* [15:0] Default:0xffff RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DDMUX_ETH1_RDY_TIMEOUT_DWLEN];
} __packed;

#define NBL_DDMUX_ETH2_RDY_TIMEOUT_ADDR  (0x984138)
#define NBL_DDMUX_ETH2_RDY_TIMEOUT_DEPTH (1)
#define NBL_DDMUX_ETH2_RDY_TIMEOUT_WIDTH (32)
#define NBL_DDMUX_ETH2_RDY_TIMEOUT_DWLEN (1)
union ddmux_eth2_rdy_timeout_u {
	struct ddmux_eth2_rdy_timeout {
		u32 eth2_rdy_timeout:16; /* [15:0] Default:0xffff RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DDMUX_ETH2_RDY_TIMEOUT_DWLEN];
} __packed;

#define NBL_DDMUX_ETH3_RDY_TIMEOUT_ADDR  (0x98413c)
#define NBL_DDMUX_ETH3_RDY_TIMEOUT_DEPTH (1)
#define NBL_DDMUX_ETH3_RDY_TIMEOUT_WIDTH (32)
#define NBL_DDMUX_ETH3_RDY_TIMEOUT_DWLEN (1)
union ddmux_eth3_rdy_timeout_u {
	struct ddmux_eth3_rdy_timeout {
		u32 eth3_rdy_timeout:16; /* [15:0] Default:0xffff RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DDMUX_ETH3_RDY_TIMEOUT_DWLEN];
} __packed;

#define NBL_DDMUX_ETH_RDY_MASK_EN_ADDR  (0x984140)
#define NBL_DDMUX_ETH_RDY_MASK_EN_DEPTH (1)
#define NBL_DDMUX_ETH_RDY_MASK_EN_WIDTH (32)
#define NBL_DDMUX_ETH_RDY_MASK_EN_DWLEN (1)
union ddmux_eth_rdy_mask_en_u {
	struct ddmux_eth_rdy_mask_en {
		u32 eth0_rsy_mask_en:1;  /* [0] Default:0x0 RW */
		u32 eth1_rdy_mask_en:1;  /* [1] Default:0x0 RW */
		u32 eth2_rdy_mask_en:1;  /* [2] Default:0x0 RW */
		u32 eth3_rdy_mask_en:1;  /* [3] Default:0x0 RW */
		u32 rsv:28;              /* [31:4] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DDMUX_ETH_RDY_MASK_EN_DWLEN];
} __packed;

#define NBL_DDMUX_FWD_DPORT_ADDR  (0x984144)
#define NBL_DDMUX_FWD_DPORT_DEPTH (1)
#define NBL_DDMUX_FWD_DPORT_WIDTH (32)
#define NBL_DDMUX_FWD_DPORT_DWLEN (1)
union ddmux_fwd_dport_u {
	struct ddmux_fwd_dport {
		u32 action_id:6;         /* [5:0] Default:0x9 RW */
		u32 rsv:26;              /* [31:6] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_DDMUX_FWD_DPORT_DWLEN];
} __packed;

#define NBL_DDMUX_OUT_FLAG_MASK_ADDR  (0x984148)
#define NBL_DDMUX_OUT_FLAG_MASK_DEPTH (1)
#define NBL_DDMUX_OUT_FLAG_MASK_WIDTH (32)
#define NBL_DDMUX_OUT_FLAG_MASK_DWLEN (1)
union ddmux_out_flag_mask_u {
	struct ddmux_out_flag_mask {
		u32 mask:32;             /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_DDMUX_OUT_FLAG_MASK_DWLEN];
} __packed;

#define NBL_DDMUX_ETH0_TX_PKT_ADDR  (0x984800)
#define NBL_DDMUX_ETH0_TX_PKT_DEPTH (1)
#define NBL_DDMUX_ETH0_TX_PKT_WIDTH (32)
#define NBL_DDMUX_ETH0_TX_PKT_DWLEN (1)
union ddmux_eth0_tx_pkt_u {
	struct ddmux_eth0_tx_pkt {
		u32 eth0_tx_pkt:32;      /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH0_TX_PKT_DWLEN];
} __packed;

#define NBL_DDMUX_ETH0_TX_BYTE_ADDR  (0x984804)
#define NBL_DDMUX_ETH0_TX_BYTE_DEPTH (1)
#define NBL_DDMUX_ETH0_TX_BYTE_WIDTH (64)
#define NBL_DDMUX_ETH0_TX_BYTE_DWLEN (2)
union ddmux_eth0_tx_byte_u {
	struct ddmux_eth0_tx_byte {
		u32 eth0_tx_byte_arr[2]; /* [63:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH0_TX_BYTE_DWLEN];
} __packed;

#define NBL_DDMUX_ETH0_TX_UC_ADDR  (0x98480c)
#define NBL_DDMUX_ETH0_TX_UC_DEPTH (1)
#define NBL_DDMUX_ETH0_TX_UC_WIDTH (32)
#define NBL_DDMUX_ETH0_TX_UC_DWLEN (1)
union ddmux_eth0_tx_uc_u {
	struct ddmux_eth0_tx_uc {
		u32 eth0_tx_uc:32;       /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH0_TX_UC_DWLEN];
} __packed;

#define NBL_DDMUX_ETH0_TX_MC_ADDR  (0x984810)
#define NBL_DDMUX_ETH0_TX_MC_DEPTH (1)
#define NBL_DDMUX_ETH0_TX_MC_WIDTH (32)
#define NBL_DDMUX_ETH0_TX_MC_DWLEN (1)
union ddmux_eth0_tx_mc_u {
	struct ddmux_eth0_tx_mc {
		u32 eth0_tx_mc:32;       /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH0_TX_MC_DWLEN];
} __packed;

#define NBL_DDMUX_ETH0_TX_BC_ADDR  (0x984814)
#define NBL_DDMUX_ETH0_TX_BC_DEPTH (1)
#define NBL_DDMUX_ETH0_TX_BC_WIDTH (32)
#define NBL_DDMUX_ETH0_TX_BC_DWLEN (1)
union ddmux_eth0_tx_bc_u {
	struct ddmux_eth0_tx_bc {
		u32 eth0_tx_bc:32;       /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH0_TX_BC_DWLEN];
} __packed;

#define NBL_DDMUX_ETH0_TX_LESS_60_ADDR  (0x984818)
#define NBL_DDMUX_ETH0_TX_LESS_60_DEPTH (1)
#define NBL_DDMUX_ETH0_TX_LESS_60_WIDTH (32)
#define NBL_DDMUX_ETH0_TX_LESS_60_DWLEN (1)
union ddmux_eth0_tx_less_60_u {
	struct ddmux_eth0_tx_less_60 {
		u32 eth0_tx_less_60:32;  /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH0_TX_LESS_60_DWLEN];
} __packed;

#define NBL_DDMUX_ETH0_TX_61_123_ADDR  (0x984820)
#define NBL_DDMUX_ETH0_TX_61_123_DEPTH (1)
#define NBL_DDMUX_ETH0_TX_61_123_WIDTH (32)
#define NBL_DDMUX_ETH0_TX_61_123_DWLEN (1)
union ddmux_eth0_tx_61_123_u {
	struct ddmux_eth0_tx_61_123 {
		u32 eth0_tx_61_123:32;   /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH0_TX_61_123_DWLEN];
} __packed;

#define NBL_DDMUX_ETH0_TX_124_251_ADDR  (0x984824)
#define NBL_DDMUX_ETH0_TX_124_251_DEPTH (1)
#define NBL_DDMUX_ETH0_TX_124_251_WIDTH (32)
#define NBL_DDMUX_ETH0_TX_124_251_DWLEN (1)
union ddmux_eth0_tx_124_251_u {
	struct ddmux_eth0_tx_124_251 {
		u32 eth0_tx_124_251:32;  /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH0_TX_124_251_DWLEN];
} __packed;

#define NBL_DDMUX_ETH0_TX_252_507_ADDR  (0x984828)
#define NBL_DDMUX_ETH0_TX_252_507_DEPTH (1)
#define NBL_DDMUX_ETH0_TX_252_507_WIDTH (32)
#define NBL_DDMUX_ETH0_TX_252_507_DWLEN (1)
union ddmux_eth0_tx_252_507_u {
	struct ddmux_eth0_tx_252_507 {
		u32 eth0_tx_252_507:32;  /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH0_TX_252_507_DWLEN];
} __packed;

#define NBL_DDMUX_ETH0_TX_508_1019_ADDR  (0x98482c)
#define NBL_DDMUX_ETH0_TX_508_1019_DEPTH (1)
#define NBL_DDMUX_ETH0_TX_508_1019_WIDTH (32)
#define NBL_DDMUX_ETH0_TX_508_1019_DWLEN (1)
union ddmux_eth0_tx_508_1019_u {
	struct ddmux_eth0_tx_508_1019 {
		u32 eth0_tx_508_1019:32; /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH0_TX_508_1019_DWLEN];
} __packed;

#define NBL_DDMUX_ETH0_TX_1020_1514_ADDR  (0x984830)
#define NBL_DDMUX_ETH0_TX_1020_1514_DEPTH (1)
#define NBL_DDMUX_ETH0_TX_1020_1514_WIDTH (32)
#define NBL_DDMUX_ETH0_TX_1020_1514_DWLEN (1)
union ddmux_eth0_tx_1020_1514_u {
	struct ddmux_eth0_tx_1020_1514 {
		u32 eth0_tx_1020_1514:32; /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH0_TX_1020_1514_DWLEN];
} __packed;

#define NBL_DDMUX_ETH0_TX_LARGE_1514_ADDR  (0x984834)
#define NBL_DDMUX_ETH0_TX_LARGE_1514_DEPTH (1)
#define NBL_DDMUX_ETH0_TX_LARGE_1514_WIDTH (32)
#define NBL_DDMUX_ETH0_TX_LARGE_1514_DWLEN (1)
union ddmux_eth0_tx_large_1514_u {
	struct ddmux_eth0_tx_large_1514 {
		u32 eth0_tx_large_1514:32; /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH0_TX_LARGE_1514_DWLEN];
} __packed;

#define NBL_DDMUX_ETH0_TX_MAC_ERR_ADDR  (0x984838)
#define NBL_DDMUX_ETH0_TX_MAC_ERR_DEPTH (1)
#define NBL_DDMUX_ETH0_TX_MAC_ERR_WIDTH (32)
#define NBL_DDMUX_ETH0_TX_MAC_ERR_DWLEN (1)
union ddmux_eth0_tx_mac_err_u {
	struct ddmux_eth0_tx_mac_err {
		u32 eth0_tx_mac_err:32;  /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH0_TX_MAC_ERR_DWLEN];
} __packed;

#define NBL_DDMUX_ETH1_TX_PKT_ADDR  (0x984900)
#define NBL_DDMUX_ETH1_TX_PKT_DEPTH (1)
#define NBL_DDMUX_ETH1_TX_PKT_WIDTH (32)
#define NBL_DDMUX_ETH1_TX_PKT_DWLEN (1)
union ddmux_eth1_tx_pkt_u {
	struct ddmux_eth1_tx_pkt {
		u32 eth1_tx_pkt:32;      /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH1_TX_PKT_DWLEN];
} __packed;

#define NBL_DDMUX_ETH1_TX_BYTE_ADDR  (0x984904)
#define NBL_DDMUX_ETH1_TX_BYTE_DEPTH (1)
#define NBL_DDMUX_ETH1_TX_BYTE_WIDTH (64)
#define NBL_DDMUX_ETH1_TX_BYTE_DWLEN (2)
union ddmux_eth1_tx_byte_u {
	struct ddmux_eth1_tx_byte {
		u32 eth1_tx_byte_arr[2]; /* [63:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH1_TX_BYTE_DWLEN];
} __packed;

#define NBL_DDMUX_ETH1_TX_UC_ADDR  (0x98490c)
#define NBL_DDMUX_ETH1_TX_UC_DEPTH (1)
#define NBL_DDMUX_ETH1_TX_UC_WIDTH (32)
#define NBL_DDMUX_ETH1_TX_UC_DWLEN (1)
union ddmux_eth1_tx_uc_u {
	struct ddmux_eth1_tx_uc {
		u32 eth1_tx_uc:32;       /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH1_TX_UC_DWLEN];
} __packed;

#define NBL_DDMUX_ETH1_TX_MC_ADDR  (0x984910)
#define NBL_DDMUX_ETH1_TX_MC_DEPTH (1)
#define NBL_DDMUX_ETH1_TX_MC_WIDTH (32)
#define NBL_DDMUX_ETH1_TX_MC_DWLEN (1)
union ddmux_eth1_tx_mc_u {
	struct ddmux_eth1_tx_mc {
		u32 eth1_tx_mc:32;       /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH1_TX_MC_DWLEN];
} __packed;

#define NBL_DDMUX_ETH1_TX_BC_ADDR  (0x984914)
#define NBL_DDMUX_ETH1_TX_BC_DEPTH (1)
#define NBL_DDMUX_ETH1_TX_BC_WIDTH (32)
#define NBL_DDMUX_ETH1_TX_BC_DWLEN (1)
union ddmux_eth1_tx_bc_u {
	struct ddmux_eth1_tx_bc {
		u32 eth1_tx_bc:32;       /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH1_TX_BC_DWLEN];
} __packed;

#define NBL_DDMUX_ETH1_TX_LESS_60_ADDR  (0x984918)
#define NBL_DDMUX_ETH1_TX_LESS_60_DEPTH (1)
#define NBL_DDMUX_ETH1_TX_LESS_60_WIDTH (32)
#define NBL_DDMUX_ETH1_TX_LESS_60_DWLEN (1)
union ddmux_eth1_tx_less_60_u {
	struct ddmux_eth1_tx_less_60 {
		u32 eth1_tx_less_60:32;  /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH1_TX_LESS_60_DWLEN];
} __packed;

#define NBL_DDMUX_ETH1_TX_61_123_ADDR  (0x984920)
#define NBL_DDMUX_ETH1_TX_61_123_DEPTH (1)
#define NBL_DDMUX_ETH1_TX_61_123_WIDTH (32)
#define NBL_DDMUX_ETH1_TX_61_123_DWLEN (1)
union ddmux_eth1_tx_61_123_u {
	struct ddmux_eth1_tx_61_123 {
		u32 eth1_tx_61_123:32;   /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH1_TX_61_123_DWLEN];
} __packed;

#define NBL_DDMUX_ETH1_TX_124_251_ADDR  (0x984924)
#define NBL_DDMUX_ETH1_TX_124_251_DEPTH (1)
#define NBL_DDMUX_ETH1_TX_124_251_WIDTH (32)
#define NBL_DDMUX_ETH1_TX_124_251_DWLEN (1)
union ddmux_eth1_tx_124_251_u {
	struct ddmux_eth1_tx_124_251 {
		u32 eth1_tx_124_251:32;  /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH1_TX_124_251_DWLEN];
} __packed;

#define NBL_DDMUX_ETH1_TX_252_507_ADDR  (0x984928)
#define NBL_DDMUX_ETH1_TX_252_507_DEPTH (1)
#define NBL_DDMUX_ETH1_TX_252_507_WIDTH (32)
#define NBL_DDMUX_ETH1_TX_252_507_DWLEN (1)
union ddmux_eth1_tx_252_507_u {
	struct ddmux_eth1_tx_252_507 {
		u32 eth1_tx_252_507:32;  /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH1_TX_252_507_DWLEN];
} __packed;

#define NBL_DDMUX_ETH1_TX_508_1019_ADDR  (0x98492c)
#define NBL_DDMUX_ETH1_TX_508_1019_DEPTH (1)
#define NBL_DDMUX_ETH1_TX_508_1019_WIDTH (32)
#define NBL_DDMUX_ETH1_TX_508_1019_DWLEN (1)
union ddmux_eth1_tx_508_1019_u {
	struct ddmux_eth1_tx_508_1019 {
		u32 eth1_tx_508_1019:32; /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH1_TX_508_1019_DWLEN];
} __packed;

#define NBL_DDMUX_ETH1_TX_1020_1514_ADDR  (0x984930)
#define NBL_DDMUX_ETH1_TX_1020_1514_DEPTH (1)
#define NBL_DDMUX_ETH1_TX_1020_1514_WIDTH (32)
#define NBL_DDMUX_ETH1_TX_1020_1514_DWLEN (1)
union ddmux_eth1_tx_1020_1514_u {
	struct ddmux_eth1_tx_1020_1514 {
		u32 eth1_tx_1020_1514:32; /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH1_TX_1020_1514_DWLEN];
} __packed;

#define NBL_DDMUX_ETH1_TX_LARGE_1514_ADDR  (0x984934)
#define NBL_DDMUX_ETH1_TX_LARGE_1514_DEPTH (1)
#define NBL_DDMUX_ETH1_TX_LARGE_1514_WIDTH (32)
#define NBL_DDMUX_ETH1_TX_LARGE_1514_DWLEN (1)
union ddmux_eth1_tx_large_1514_u {
	struct ddmux_eth1_tx_large_1514 {
		u32 eth1_tx_large_1514:32; /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH1_TX_LARGE_1514_DWLEN];
} __packed;

#define NBL_DDMUX_ETH1_TX_MAC_ERR_ADDR  (0x984938)
#define NBL_DDMUX_ETH1_TX_MAC_ERR_DEPTH (1)
#define NBL_DDMUX_ETH1_TX_MAC_ERR_WIDTH (32)
#define NBL_DDMUX_ETH1_TX_MAC_ERR_DWLEN (1)
union ddmux_eth1_tx_mac_err_u {
	struct ddmux_eth1_tx_mac_err {
		u32 eth1_tx_mac_err:32;  /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH1_TX_MAC_ERR_DWLEN];
} __packed;

#define NBL_DDMUX_ETH2_TX_PKT_ADDR  (0x984a00)
#define NBL_DDMUX_ETH2_TX_PKT_DEPTH (1)
#define NBL_DDMUX_ETH2_TX_PKT_WIDTH (32)
#define NBL_DDMUX_ETH2_TX_PKT_DWLEN (1)
union ddmux_eth2_tx_pkt_u {
	struct ddmux_eth2_tx_pkt {
		u32 eth2_tx_pkt:32;      /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH2_TX_PKT_DWLEN];
} __packed;

#define NBL_DDMUX_ETH2_TX_BYTE_ADDR  (0x984a04)
#define NBL_DDMUX_ETH2_TX_BYTE_DEPTH (1)
#define NBL_DDMUX_ETH2_TX_BYTE_WIDTH (64)
#define NBL_DDMUX_ETH2_TX_BYTE_DWLEN (2)
union ddmux_eth2_tx_byte_u {
	struct ddmux_eth2_tx_byte {
		u32 eth2_tx_byte_arr[2]; /* [63:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH2_TX_BYTE_DWLEN];
} __packed;

#define NBL_DDMUX_ETH2_TX_UC_ADDR  (0x984a0c)
#define NBL_DDMUX_ETH2_TX_UC_DEPTH (1)
#define NBL_DDMUX_ETH2_TX_UC_WIDTH (32)
#define NBL_DDMUX_ETH2_TX_UC_DWLEN (1)
union ddmux_eth2_tx_uc_u {
	struct ddmux_eth2_tx_uc {
		u32 eth2_tx_uc:32;       /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH2_TX_UC_DWLEN];
} __packed;

#define NBL_DDMUX_ETH2_TX_MC_ADDR  (0x984a10)
#define NBL_DDMUX_ETH2_TX_MC_DEPTH (1)
#define NBL_DDMUX_ETH2_TX_MC_WIDTH (32)
#define NBL_DDMUX_ETH2_TX_MC_DWLEN (1)
union ddmux_eth2_tx_mc_u {
	struct ddmux_eth2_tx_mc {
		u32 eth2_tx_mc:32;       /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH2_TX_MC_DWLEN];
} __packed;

#define NBL_DDMUX_ETH2_TX_BC_ADDR  (0x984a14)
#define NBL_DDMUX_ETH2_TX_BC_DEPTH (1)
#define NBL_DDMUX_ETH2_TX_BC_WIDTH (32)
#define NBL_DDMUX_ETH2_TX_BC_DWLEN (1)
union ddmux_eth2_tx_bc_u {
	struct ddmux_eth2_tx_bc {
		u32 eth2_tx_bc:32;       /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH2_TX_BC_DWLEN];
} __packed;

#define NBL_DDMUX_ETH2_TX_LESS_60_ADDR  (0x984a18)
#define NBL_DDMUX_ETH2_TX_LESS_60_DEPTH (1)
#define NBL_DDMUX_ETH2_TX_LESS_60_WIDTH (32)
#define NBL_DDMUX_ETH2_TX_LESS_60_DWLEN (1)
union ddmux_eth2_tx_less_60_u {
	struct ddmux_eth2_tx_less_60 {
		u32 eth2_tx_less_60:32;  /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH2_TX_LESS_60_DWLEN];
} __packed;

#define NBL_DDMUX_ETH2_TX_61_123_ADDR  (0x984a20)
#define NBL_DDMUX_ETH2_TX_61_123_DEPTH (1)
#define NBL_DDMUX_ETH2_TX_61_123_WIDTH (32)
#define NBL_DDMUX_ETH2_TX_61_123_DWLEN (1)
union ddmux_eth2_tx_61_123_u {
	struct ddmux_eth2_tx_61_123 {
		u32 eth2_tx_61_123:32;   /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH2_TX_61_123_DWLEN];
} __packed;

#define NBL_DDMUX_ETH2_TX_124_251_ADDR  (0x984a24)
#define NBL_DDMUX_ETH2_TX_124_251_DEPTH (1)
#define NBL_DDMUX_ETH2_TX_124_251_WIDTH (32)
#define NBL_DDMUX_ETH2_TX_124_251_DWLEN (1)
union ddmux_eth2_tx_124_251_u {
	struct ddmux_eth2_tx_124_251 {
		u32 eth2_tx_124_251:32;  /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH2_TX_124_251_DWLEN];
} __packed;

#define NBL_DDMUX_ETH2_TX_252_507_ADDR  (0x984a28)
#define NBL_DDMUX_ETH2_TX_252_507_DEPTH (1)
#define NBL_DDMUX_ETH2_TX_252_507_WIDTH (32)
#define NBL_DDMUX_ETH2_TX_252_507_DWLEN (1)
union ddmux_eth2_tx_252_507_u {
	struct ddmux_eth2_tx_252_507 {
		u32 eth2_tx_252_507:32;  /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH2_TX_252_507_DWLEN];
} __packed;

#define NBL_DDMUX_ETH2_TX_508_1019_ADDR  (0x984a2c)
#define NBL_DDMUX_ETH2_TX_508_1019_DEPTH (1)
#define NBL_DDMUX_ETH2_TX_508_1019_WIDTH (32)
#define NBL_DDMUX_ETH2_TX_508_1019_DWLEN (1)
union ddmux_eth2_tx_508_1019_u {
	struct ddmux_eth2_tx_508_1019 {
		u32 eth2_tx_508_1019:32; /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH2_TX_508_1019_DWLEN];
} __packed;

#define NBL_DDMUX_ETH2_TX_1020_1514_ADDR  (0x984a30)
#define NBL_DDMUX_ETH2_TX_1020_1514_DEPTH (1)
#define NBL_DDMUX_ETH2_TX_1020_1514_WIDTH (32)
#define NBL_DDMUX_ETH2_TX_1020_1514_DWLEN (1)
union ddmux_eth2_tx_1020_1514_u {
	struct ddmux_eth2_tx_1020_1514 {
		u32 eth2_tx_1020_1514:32; /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH2_TX_1020_1514_DWLEN];
} __packed;

#define NBL_DDMUX_ETH2_TX_LARGE_1514_ADDR  (0x984a34)
#define NBL_DDMUX_ETH2_TX_LARGE_1514_DEPTH (1)
#define NBL_DDMUX_ETH2_TX_LARGE_1514_WIDTH (32)
#define NBL_DDMUX_ETH2_TX_LARGE_1514_DWLEN (1)
union ddmux_eth2_tx_large_1514_u {
	struct ddmux_eth2_tx_large_1514 {
		u32 eth2_tx_large_1514:32; /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH2_TX_LARGE_1514_DWLEN];
} __packed;

#define NBL_DDMUX_ETH2_TX_MAC_ERR_ADDR  (0x984a38)
#define NBL_DDMUX_ETH2_TX_MAC_ERR_DEPTH (1)
#define NBL_DDMUX_ETH2_TX_MAC_ERR_WIDTH (32)
#define NBL_DDMUX_ETH2_TX_MAC_ERR_DWLEN (1)
union ddmux_eth2_tx_mac_err_u {
	struct ddmux_eth2_tx_mac_err {
		u32 eth2_tx_mac_err:32;  /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH2_TX_MAC_ERR_DWLEN];
} __packed;

#define NBL_DDMUX_ETH3_TX_PKT_ADDR  (0x984b00)
#define NBL_DDMUX_ETH3_TX_PKT_DEPTH (1)
#define NBL_DDMUX_ETH3_TX_PKT_WIDTH (32)
#define NBL_DDMUX_ETH3_TX_PKT_DWLEN (1)
union ddmux_eth3_tx_pkt_u {
	struct ddmux_eth3_tx_pkt {
		u32 eth3_tx_pkt:32;      /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH3_TX_PKT_DWLEN];
} __packed;

#define NBL_DDMUX_ETH3_TX_BYTE_ADDR  (0x984b04)
#define NBL_DDMUX_ETH3_TX_BYTE_DEPTH (1)
#define NBL_DDMUX_ETH3_TX_BYTE_WIDTH (64)
#define NBL_DDMUX_ETH3_TX_BYTE_DWLEN (2)
union ddmux_eth3_tx_byte_u {
	struct ddmux_eth3_tx_byte {
		u32 eth3_tx_byte_arr[2]; /* [63:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH3_TX_BYTE_DWLEN];
} __packed;

#define NBL_DDMUX_ETH3_TX_UC_ADDR  (0x984b0c)
#define NBL_DDMUX_ETH3_TX_UC_DEPTH (1)
#define NBL_DDMUX_ETH3_TX_UC_WIDTH (32)
#define NBL_DDMUX_ETH3_TX_UC_DWLEN (1)
union ddmux_eth3_tx_uc_u {
	struct ddmux_eth3_tx_uc {
		u32 eth3_tx_uc:32;       /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH3_TX_UC_DWLEN];
} __packed;

#define NBL_DDMUX_ETH3_TX_MC_ADDR  (0x984b10)
#define NBL_DDMUX_ETH3_TX_MC_DEPTH (1)
#define NBL_DDMUX_ETH3_TX_MC_WIDTH (32)
#define NBL_DDMUX_ETH3_TX_MC_DWLEN (1)
union ddmux_eth3_tx_mc_u {
	struct ddmux_eth3_tx_mc {
		u32 eth3_tx_mc:32;       /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH3_TX_MC_DWLEN];
} __packed;

#define NBL_DDMUX_ETH3_TX_BC_ADDR  (0x984b14)
#define NBL_DDMUX_ETH3_TX_BC_DEPTH (1)
#define NBL_DDMUX_ETH3_TX_BC_WIDTH (32)
#define NBL_DDMUX_ETH3_TX_BC_DWLEN (1)
union ddmux_eth3_tx_bc_u {
	struct ddmux_eth3_tx_bc {
		u32 eth3_tx_bc:32;       /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH3_TX_BC_DWLEN];
} __packed;

#define NBL_DDMUX_ETH3_TX_LESS_60_ADDR  (0x984b18)
#define NBL_DDMUX_ETH3_TX_LESS_60_DEPTH (1)
#define NBL_DDMUX_ETH3_TX_LESS_60_WIDTH (32)
#define NBL_DDMUX_ETH3_TX_LESS_60_DWLEN (1)
union ddmux_eth3_tx_less_60_u {
	struct ddmux_eth3_tx_less_60 {
		u32 eth3_tx_less_60:32;  /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH3_TX_LESS_60_DWLEN];
} __packed;

#define NBL_DDMUX_ETH3_TX_61_123_ADDR  (0x984b20)
#define NBL_DDMUX_ETH3_TX_61_123_DEPTH (1)
#define NBL_DDMUX_ETH3_TX_61_123_WIDTH (32)
#define NBL_DDMUX_ETH3_TX_61_123_DWLEN (1)
union ddmux_eth3_tx_61_123_u {
	struct ddmux_eth3_tx_61_123 {
		u32 eth3_tx_61_123:32;   /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH3_TX_61_123_DWLEN];
} __packed;

#define NBL_DDMUX_ETH3_TX_124_251_ADDR  (0x984b24)
#define NBL_DDMUX_ETH3_TX_124_251_DEPTH (1)
#define NBL_DDMUX_ETH3_TX_124_251_WIDTH (32)
#define NBL_DDMUX_ETH3_TX_124_251_DWLEN (1)
union ddmux_eth3_tx_124_251_u {
	struct ddmux_eth3_tx_124_251 {
		u32 eth3_tx_124_251:32;  /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH3_TX_124_251_DWLEN];
} __packed;

#define NBL_DDMUX_ETH3_TX_252_507_ADDR  (0x984b28)
#define NBL_DDMUX_ETH3_TX_252_507_DEPTH (1)
#define NBL_DDMUX_ETH3_TX_252_507_WIDTH (32)
#define NBL_DDMUX_ETH3_TX_252_507_DWLEN (1)
union ddmux_eth3_tx_252_507_u {
	struct ddmux_eth3_tx_252_507 {
		u32 eth3_tx_252_507:32;  /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH3_TX_252_507_DWLEN];
} __packed;

#define NBL_DDMUX_ETH3_TX_508_1019_ADDR  (0x984b2c)
#define NBL_DDMUX_ETH3_TX_508_1019_DEPTH (1)
#define NBL_DDMUX_ETH3_TX_508_1019_WIDTH (32)
#define NBL_DDMUX_ETH3_TX_508_1019_DWLEN (1)
union ddmux_eth3_tx_508_1019_u {
	struct ddmux_eth3_tx_508_1019 {
		u32 eth3_tx_508_1019:32; /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH3_TX_508_1019_DWLEN];
} __packed;

#define NBL_DDMUX_ETH3_TX_1020_1514_ADDR  (0x984b30)
#define NBL_DDMUX_ETH3_TX_1020_1514_DEPTH (1)
#define NBL_DDMUX_ETH3_TX_1020_1514_WIDTH (32)
#define NBL_DDMUX_ETH3_TX_1020_1514_DWLEN (1)
union ddmux_eth3_tx_1020_1514_u {
	struct ddmux_eth3_tx_1020_1514 {
		u32 eth3_tx_1020_1514:32; /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH3_TX_1020_1514_DWLEN];
} __packed;

#define NBL_DDMUX_ETH3_TX_LARGE_1514_ADDR  (0x984b34)
#define NBL_DDMUX_ETH3_TX_LARGE_1514_DEPTH (1)
#define NBL_DDMUX_ETH3_TX_LARGE_1514_WIDTH (32)
#define NBL_DDMUX_ETH3_TX_LARGE_1514_DWLEN (1)
union ddmux_eth3_tx_large_1514_u {
	struct ddmux_eth3_tx_large_1514 {
		u32 eth3_tx_large_1514:32; /* [31:0] Default:0x0 RCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH3_TX_LARGE_1514_DWLEN];
} __packed;

#define NBL_DDMUX_ETH3_TX_MAC_ERR_ADDR  (0x984b38)
#define NBL_DDMUX_ETH3_TX_MAC_ERR_DEPTH (1)
#define NBL_DDMUX_ETH3_TX_MAC_ERR_WIDTH (32)
#define NBL_DDMUX_ETH3_TX_MAC_ERR_DWLEN (1)
union ddmux_eth3_tx_mac_err_u {
	struct ddmux_eth3_tx_mac_err {
		u32 eth3_tx_mac_err:32;  /* [31:0] Default:0x0 SCTR */
	} __packed info;
	u32 data[NBL_DDMUX_ETH3_TX_MAC_ERR_DWLEN];
} __packed;

#endif
