// Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#ifndef NBL_UPMEM_H
#define NBL_UPMEM_H 1

#include <linux/types.h>

#define NBL_UPMEM_BASE (0x00108000)

#define NBL_UPMEM_INT_STATUS_ADDR  (0x108000)
#define NBL_UPMEM_INT_STATUS_DEPTH (1)
#define NBL_UPMEM_INT_STATUS_WIDTH (32)
#define NBL_UPMEM_INT_STATUS_DWLEN (1)
union upmem_int_status_u {
	struct upmem_int_status {
		u32 ucor_err:1;          /* [0] Default:0x0 RWC */
		u32 cor_err:1;           /* [1] Default:0x0 RWC */
		u32 cpu_lgc_hzd:1;       /* [2] Default:0x0 RWC */
		u32 parity_err:1;        /* [3] Default:0x0 RWC */
		u32 cif_err:1;           /* [4] Default:0x0 RWC */
		u32 rsv:27;              /* [31:5] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPMEM_INT_STATUS_DWLEN];
} __packed;

#define NBL_UPMEM_INT_MASK_ADDR  (0x108004)
#define NBL_UPMEM_INT_MASK_DEPTH (1)
#define NBL_UPMEM_INT_MASK_WIDTH (32)
#define NBL_UPMEM_INT_MASK_DWLEN (1)
union upmem_int_mask_u {
	struct upmem_int_mask {
		u32 ucor_err:1;          /* [0] Default:0x0 RW */
		u32 cor_err:1;           /* [1] Default:0x0 RW */
		u32 cpu_lgc_hzd:1;       /* [2] Default:0x0 RW */
		u32 parity_err:1;        /* [3] Default:0x0 RW */
		u32 cif_err:1;           /* [4] Default:0x0 RW */
		u32 rsv:27;              /* [31:5] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPMEM_INT_MASK_DWLEN];
} __packed;

#define NBL_UPMEM_INT_SET_ADDR  (0x108008)
#define NBL_UPMEM_INT_SET_DEPTH (1)
#define NBL_UPMEM_INT_SET_WIDTH (32)
#define NBL_UPMEM_INT_SET_DWLEN (1)
union upmem_int_set_u {
	struct upmem_int_set {
		u32 ucor_err:1;          /* [0] Default:0x0 WO */
		u32 cor_err:1;           /* [1] Default:0x0 WO */
		u32 cpu_lgc_hzd:1;       /* [2] Default:0x0 WO */
		u32 parity_err:1;        /* [3] Default:0x0 WO */
		u32 cif_err:1;           /* [4] Default:0x0 WO */
		u32 rsv:27;              /* [31:5] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPMEM_INT_SET_DWLEN];
} __packed;

#define NBL_UPMEM_COR_ERR_INFO_ADDR  (0x10800c)
#define NBL_UPMEM_COR_ERR_INFO_DEPTH (1)
#define NBL_UPMEM_COR_ERR_INFO_WIDTH (32)
#define NBL_UPMEM_COR_ERR_INFO_DWLEN (1)
union upmem_cor_err_info_u {
	struct upmem_cor_err_info {
		u32 ram_addr:12;         /* [11:0] Default:0x0 RO */
		u32 rsv:20;              /* [31:12] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPMEM_COR_ERR_INFO_DWLEN];
} __packed;

#define NBL_UPMEM_PARITY_ERR_INFO_ADDR  (0x108014)
#define NBL_UPMEM_PARITY_ERR_INFO_DEPTH (1)
#define NBL_UPMEM_PARITY_ERR_INFO_WIDTH (32)
#define NBL_UPMEM_PARITY_ERR_INFO_DWLEN (1)
union upmem_parity_err_info_u {
	struct upmem_parity_err_info {
		u32 ram_addr:12;         /* [11:0] Default:0x0 RO */
		u32 rsv:20;              /* [31:12] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPMEM_PARITY_ERR_INFO_DWLEN];
} __packed;

#define NBL_UPMEM_CIF_ERR_INFO_ADDR  (0x10801c)
#define NBL_UPMEM_CIF_ERR_INFO_DEPTH (1)
#define NBL_UPMEM_CIF_ERR_INFO_WIDTH (32)
#define NBL_UPMEM_CIF_ERR_INFO_DWLEN (1)
union upmem_cif_err_info_u {
	struct upmem_cif_err_info {
		u32 addr:30;             /* [29:0] Default:0x0 RO */
		u32 wr_err:1;            /* [30] Default:0x0 RO */
		u32 ucor_err:1;          /* [31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPMEM_CIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_UPMEM_CAR_CTRL_ADDR  (0x108100)
#define NBL_UPMEM_CAR_CTRL_DEPTH (1)
#define NBL_UPMEM_CAR_CTRL_WIDTH (32)
#define NBL_UPMEM_CAR_CTRL_DWLEN (1)
union upmem_car_ctrl_u {
	struct upmem_car_ctrl {
		u32 sctr_car:1;          /* [0] Default:0x1 RW */
		u32 rctr_car:1;          /* [1] Default:0x1 RW */
		u32 rc_car:1;            /* [2] Default:0x1 RW */
		u32 tbl_rc_car:1;        /* [3] Default:0x1 RW */
		u32 rsv:28;              /* [31:4] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPMEM_CAR_CTRL_DWLEN];
} __packed;

#define NBL_UPMEM_INIT_START_ADDR  (0x108104)
#define NBL_UPMEM_INIT_START_DEPTH (1)
#define NBL_UPMEM_INIT_START_WIDTH (32)
#define NBL_UPMEM_INIT_START_DWLEN (1)
union upmem_init_start_u {
	struct upmem_init_start {
		u32 init_start:1;        /* [0] Default:0x0 WO */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPMEM_INIT_START_DWLEN];
} __packed;

#define NBL_UPMEM_MEM_ACCESS_MODE_ADDR  (0x108108)
#define NBL_UPMEM_MEM_ACCESS_MODE_DEPTH (1)
#define NBL_UPMEM_MEM_ACCESS_MODE_WIDTH (32)
#define NBL_UPMEM_MEM_ACCESS_MODE_DWLEN (1)
union upmem_mem_access_mode_u {
	struct upmem_mem_access_mode {
		u32 mode:1;              /* [0] Default:0x0 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPMEM_MEM_ACCESS_MODE_DWLEN];
} __packed;

#define NBL_UPMEM_MEM_ACCESS_EN_ADDR  (0x10810c)
#define NBL_UPMEM_MEM_ACCESS_EN_DEPTH (1)
#define NBL_UPMEM_MEM_ACCESS_EN_WIDTH (32)
#define NBL_UPMEM_MEM_ACCESS_EN_DWLEN (1)
union upmem_mem_access_en_u {
	struct upmem_mem_access_en {
		u32 en:1;                /* [0] Default:0x0 RW */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPMEM_MEM_ACCESS_EN_DWLEN];
} __packed;

#define NBL_UPMEM_MEM_ACCESS_ADDR_ADDR  (0x108110)
#define NBL_UPMEM_MEM_ACCESS_ADDR_DEPTH (1)
#define NBL_UPMEM_MEM_ACCESS_ADDR_WIDTH (32)
#define NBL_UPMEM_MEM_ACCESS_ADDR_DWLEN (1)
union upmem_mem_access_addr_u {
	struct upmem_mem_access_addr {
		u32 row_raddr:12;        /* [11:0] Default:0x0 RW */
		u32 rsv1:4;              /* [15:12] Default:0x0 RO */
		u32 col_raddr:7;         /* [22:16] Default:0x0 RW */
		u32 rsv:9;               /* [31:23] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPMEM_MEM_ACCESS_ADDR_DWLEN];
} __packed;

#define NBL_UPMEM_CFG_TEST_ADDR  (0x108114)
#define NBL_UPMEM_CFG_TEST_DEPTH (1)
#define NBL_UPMEM_CFG_TEST_WIDTH (32)
#define NBL_UPMEM_CFG_TEST_DWLEN (1)
union upmem_cfg_test_u {
	struct upmem_cfg_test {
		u32 test:32;             /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_UPMEM_CFG_TEST_DWLEN];
} __packed;

#define NBL_UPMEM_INIT_DONE_ADDR  (0x108400)
#define NBL_UPMEM_INIT_DONE_DEPTH (1)
#define NBL_UPMEM_INIT_DONE_WIDTH (32)
#define NBL_UPMEM_INIT_DONE_DWLEN (1)
union upmem_init_done_u {
	struct upmem_init_done {
		u32 init_done:1;         /* [0] Default:0x0 RO */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPMEM_INIT_DONE_DWLEN];
} __packed;

#define NBL_UPMEM_MEM_ACCESS_RDATA_ADDR  (0x108404)
#define NBL_UPMEM_MEM_ACCESS_RDATA_DEPTH (1)
#define NBL_UPMEM_MEM_ACCESS_RDATA_WIDTH (32)
#define NBL_UPMEM_MEM_ACCESS_RDATA_DWLEN (1)
union upmem_mem_access_rdata_u {
	struct upmem_mem_access_rdata {
		u32 rdata:32;            /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_UPMEM_MEM_ACCESS_RDATA_DWLEN];
} __packed;

#endif
