// Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#ifndef NBL_NATIVE_ECPU_H
#define NBL_NATIVE_ECPU_H 1

#include <linux/types.h>

#define NBL_NATIVE_ECPU_BASE (0x01004000)

#define NBL_NATIVE_ECPU_INT_STATUS_ADDR  (0x1004000)
#define NBL_NATIVE_ECPU_INT_STATUS_DEPTH (1)
#define NBL_NATIVE_ECPU_INT_STATUS_WIDTH (32)
#define NBL_NATIVE_ECPU_INT_STATUS_DWLEN (1)
union native_ecpu_int_status_u {
	struct native_ecpu_int_status {
		u32 fatal_err:1;         /* [00:00] Default:0x0 RWC */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 RWC */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 RWC */
		u32 rsv4:1;              /* [03:03] Default:0x0 RO */
		u32 cif_err:1;           /* [04:04] Default:0x0 RWC */
		u32 rsv3:1;              /* [05:05] Default:0x0 RO */
		u32 rsv2:1;              /* [06:06] Default:0x0 RO */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 RWC */
		u32 data_cor_err:1;      /* [08:08] Default:0x0 RWC */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_INT_STATUS_DWLEN];
} __packed;

#define NBL_NATIVE_ECPU_INT_MASK_ADDR  (0x1004004)
#define NBL_NATIVE_ECPU_INT_MASK_DEPTH (1)
#define NBL_NATIVE_ECPU_INT_MASK_WIDTH (32)
#define NBL_NATIVE_ECPU_INT_MASK_DWLEN (1)
union native_ecpu_int_mask_u {
	struct native_ecpu_int_mask {
		u32 fatal_err:1;         /* [00:00] Default:0x0 RW */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 RW */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 RW */
		u32 rsv4:1;              /* [03:03] Default:0x0 RO */
		u32 cif_err:1;           /* [04:04] Default:0x0 RW */
		u32 rsv3:1;              /* [05:05] Default:0x0 RO */
		u32 rsv2:1;              /* [06:06] Default:0x0 RO */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 RW */
		u32 data_cor_err:1;      /* [08:08] Default:0x0 RW */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_INT_MASK_DWLEN];
} __packed;

#define NBL_NATIVE_ECPU_INT_SET_ADDR  (0x1004008)
#define NBL_NATIVE_ECPU_INT_SET_DEPTH (1)
#define NBL_NATIVE_ECPU_INT_SET_WIDTH (32)
#define NBL_NATIVE_ECPU_INT_SET_DWLEN (1)
union native_ecpu_int_set_u {
	struct native_ecpu_int_set {
		u32 fatal_err:1;         /* [00:00] Default:0x0 WO */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 WO */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 WO */
		u32 rsv4:1;              /* [03:03] Default:0x0 RO */
		u32 cif_err:1;           /* [04:04] Default:0x0 WO */
		u32 rsv3:1;              /* [05:05] Default:0x0 RO */
		u32 rsv2:1;              /* [06:06] Default:0x0 RO */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 WO */
		u32 data_cor_err:1;      /* [08:08] Default:0x0 WO */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_INT_SET_DWLEN];
} __packed;

#define NBL_NATIVE_ECPU_INIT_DONE_ADDR  (0x100400c)
#define NBL_NATIVE_ECPU_INIT_DONE_DEPTH (1)
#define NBL_NATIVE_ECPU_INIT_DONE_WIDTH (32)
#define NBL_NATIVE_ECPU_INIT_DONE_DWLEN (1)
union native_ecpu_init_done_u {
	struct native_ecpu_init_done {
		u32 done:1;              /* [00:00] Default:0x0 RO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_INIT_DONE_DWLEN];
} __packed;

#define NBL_NATIVE_ECPU_CIF_ERR_INFO_ADDR  (0x1004040)
#define NBL_NATIVE_ECPU_CIF_ERR_INFO_DEPTH (1)
#define NBL_NATIVE_ECPU_CIF_ERR_INFO_WIDTH (32)
#define NBL_NATIVE_ECPU_CIF_ERR_INFO_DWLEN (1)
union native_ecpu_cif_err_info_u {
	struct native_ecpu_cif_err_info {
		u32 addr:30;             /* [29:00] Default:0x0 RO */
		u32 wr_err:1;            /* [30:30] Default:0x0 RO */
		u32 ucor_err:1;          /* [31:31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_CIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_NATIVE_ECPU_CAR_CTRL_ADDR  (0x1004100)
#define NBL_NATIVE_ECPU_CAR_CTRL_DEPTH (1)
#define NBL_NATIVE_ECPU_CAR_CTRL_WIDTH (32)
#define NBL_NATIVE_ECPU_CAR_CTRL_DWLEN (1)
union native_ecpu_car_ctrl_u {
	struct native_ecpu_car_ctrl {
		u32 sctr_car:1;          /* [00:00] Default:0x1 RW */
		u32 rctr_car:1;          /* [01:01] Default:0x1 RW */
		u32 rc_car:1;            /* [02:02] Default:0x1 RW */
		u32 tbl_rc_car:1;        /* [03:03] Default:0x1 RW */
		u32 rsv:28;              /* [31:04] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_CAR_CTRL_DWLEN];
} __packed;

#define NBL_NATIVE_ECPU_ECRC_GEN_ADDR  (0x1005104)
#define NBL_NATIVE_ECPU_ECRC_GEN_DEPTH (1)
#define NBL_NATIVE_ECPU_ECRC_GEN_WIDTH (32)
#define NBL_NATIVE_ECPU_ECRC_GEN_DWLEN (1)
union native_ecpu_ecrc_gen_u {
	struct native_ecpu_ecrc_gen {
		u32 dbg:1;               /* [00:00] Default:0x0 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_ECRC_GEN_DWLEN];
} __packed;

#define NBL_NATIVE_ECPU_NATIVE_RX_MAXPLAYLOAD_ADDR  (0x1005108)
#define NBL_NATIVE_ECPU_NATIVE_RX_MAXPLAYLOAD_DEPTH (1)
#define NBL_NATIVE_ECPU_NATIVE_RX_MAXPLAYLOAD_WIDTH (32)
#define NBL_NATIVE_ECPU_NATIVE_RX_MAXPLAYLOAD_DWLEN (1)
union native_ecpu_native_rx_maxplayload_u {
	struct native_ecpu_native_rx_maxplayload {
		u32 dbg:10;              /* [09:00] Default:0x214 RW */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_NATIVE_RX_MAXPLAYLOAD_DWLEN];
} __packed;

#define NBL_NATIVE_ECPU_TX_ERR_GEN_ADDR  (0x100510c)
#define NBL_NATIVE_ECPU_TX_ERR_GEN_DEPTH (1)
#define NBL_NATIVE_ECPU_TX_ERR_GEN_WIDTH (32)
#define NBL_NATIVE_ECPU_TX_ERR_GEN_DWLEN (1)
union native_ecpu_tx_err_gen_u {
	struct native_ecpu_tx_err_gen {
		u32 dbg:1;               /* [00:00] Default:0x1 RW */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_TX_ERR_GEN_DWLEN];
} __packed;

#define NBL_NATIVE_ECPU_ERROR_ADDR  (0x1006000)
#define NBL_NATIVE_ECPU_ERROR_DEPTH (1)
#define NBL_NATIVE_ECPU_ERROR_WIDTH (32)
#define NBL_NATIVE_ECPU_ERROR_DWLEN (1)
union native_ecpu_error_u {
	struct native_ecpu_error {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_ERROR_DWLEN];
} __packed;

#define NBL_NATIVE_ECPU_WARNING_ADDR  (0x1006004)
#define NBL_NATIVE_ECPU_WARNING_DEPTH (1)
#define NBL_NATIVE_ECPU_WARNING_WIDTH (32)
#define NBL_NATIVE_ECPU_WARNING_DWLEN (1)
union native_ecpu_warning_u {
	struct native_ecpu_warning {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_WARNING_DWLEN];
} __packed;

#define NBL_NATIVE_ECPU_RX_SPEED_ADDR  (0x1006180)
#define NBL_NATIVE_ECPU_RX_SPEED_DEPTH (1)
#define NBL_NATIVE_ECPU_RX_SPEED_WIDTH (32)
#define NBL_NATIVE_ECPU_RX_SPEED_DWLEN (1)
union native_ecpu_rx_speed_u {
	struct native_ecpu_rx_speed {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_RX_SPEED_DWLEN];
} __packed;

#define NBL_NATIVE_ECPU_RX_RC_SPEED_ADDR  (0x1006184)
#define NBL_NATIVE_ECPU_RX_RC_SPEED_DEPTH (1)
#define NBL_NATIVE_ECPU_RX_RC_SPEED_WIDTH (32)
#define NBL_NATIVE_ECPU_RX_RC_SPEED_DWLEN (1)
union native_ecpu_rx_rc_speed_u {
	struct native_ecpu_rx_rc_speed {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_RX_RC_SPEED_DWLEN];
} __packed;

#define NBL_NATIVE_ECPU_RX_CQ_SPEED_ADDR  (0x1006188)
#define NBL_NATIVE_ECPU_RX_CQ_SPEED_DEPTH (1)
#define NBL_NATIVE_ECPU_RX_CQ_SPEED_WIDTH (32)
#define NBL_NATIVE_ECPU_RX_CQ_SPEED_DWLEN (1)
union native_ecpu_rx_cq_speed_u {
	struct native_ecpu_rx_cq_speed {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_RX_CQ_SPEED_DWLEN];
} __packed;

#define NBL_NATIVE_ECPU_RX_VLD_SPEED_ADDR  (0x100618c)
#define NBL_NATIVE_ECPU_RX_VLD_SPEED_DEPTH (1)
#define NBL_NATIVE_ECPU_RX_VLD_SPEED_WIDTH (32)
#define NBL_NATIVE_ECPU_RX_VLD_SPEED_DWLEN (1)
union native_ecpu_rx_vld_speed_u {
	struct native_ecpu_rx_vld_speed {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_RX_VLD_SPEED_DWLEN];
} __packed;

#define NBL_NATIVE_ECPU_RX_RC_VLD_SPEED_ADDR  (0x1006190)
#define NBL_NATIVE_ECPU_RX_RC_VLD_SPEED_DEPTH (1)
#define NBL_NATIVE_ECPU_RX_RC_VLD_SPEED_WIDTH (32)
#define NBL_NATIVE_ECPU_RX_RC_VLD_SPEED_DWLEN (1)
union native_ecpu_rx_rc_vld_speed_u {
	struct native_ecpu_rx_rc_vld_speed {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_RX_RC_VLD_SPEED_DWLEN];
} __packed;

#define NBL_NATIVE_ECPU_RX_CQ_VLD_SPEED_ADDR  (0x1006194)
#define NBL_NATIVE_ECPU_RX_CQ_VLD_SPEED_DEPTH (1)
#define NBL_NATIVE_ECPU_RX_CQ_VLD_SPEED_WIDTH (32)
#define NBL_NATIVE_ECPU_RX_CQ_VLD_SPEED_DWLEN (1)
union native_ecpu_rx_cq_vld_speed_u {
	struct native_ecpu_rx_cq_vld_speed {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_RX_CQ_VLD_SPEED_DWLEN];
} __packed;

#define NBL_NATIVE_ECPU_DEBUG_INFO_ADDR  (0x1006218)
#define NBL_NATIVE_ECPU_DEBUG_INFO_DEPTH (1)
#define NBL_NATIVE_ECPU_DEBUG_INFO_WIDTH (32)
#define NBL_NATIVE_ECPU_DEBUG_INFO_DWLEN (1)
union native_ecpu_debug_info_u {
	struct native_ecpu_debug_info {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_DEBUG_INFO_DWLEN];
} __packed;

#define NBL_NATIVE_ECPU_TX_SPEED_ADDR  (0x1006280)
#define NBL_NATIVE_ECPU_TX_SPEED_DEPTH (1)
#define NBL_NATIVE_ECPU_TX_SPEED_WIDTH (32)
#define NBL_NATIVE_ECPU_TX_SPEED_DWLEN (1)
union native_ecpu_tx_speed_u {
	struct native_ecpu_tx_speed {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_TX_SPEED_DWLEN];
} __packed;

#define NBL_NATIVE_ECPU_TX_RQ_SPEED_ADDR  (0x1006284)
#define NBL_NATIVE_ECPU_TX_RQ_SPEED_DEPTH (1)
#define NBL_NATIVE_ECPU_TX_RQ_SPEED_WIDTH (32)
#define NBL_NATIVE_ECPU_TX_RQ_SPEED_DWLEN (1)
union native_ecpu_tx_rq_speed_u {
	struct native_ecpu_tx_rq_speed {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_TX_RQ_SPEED_DWLEN];
} __packed;

#define NBL_NATIVE_ECPU_TX_CC_SPEED_ADDR  (0x1006288)
#define NBL_NATIVE_ECPU_TX_CC_SPEED_DEPTH (1)
#define NBL_NATIVE_ECPU_TX_CC_SPEED_WIDTH (32)
#define NBL_NATIVE_ECPU_TX_CC_SPEED_DWLEN (1)
union native_ecpu_tx_cc_speed_u {
	struct native_ecpu_tx_cc_speed {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_TX_CC_SPEED_DWLEN];
} __packed;

#define NBL_NATIVE_ECPU_TX_NORDY_SPEED_ADDR  (0x100628c)
#define NBL_NATIVE_ECPU_TX_NORDY_SPEED_DEPTH (1)
#define NBL_NATIVE_ECPU_TX_NORDY_SPEED_WIDTH (32)
#define NBL_NATIVE_ECPU_TX_NORDY_SPEED_DWLEN (1)
union native_ecpu_tx_nordy_speed_u {
	struct native_ecpu_tx_nordy_speed {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_TX_NORDY_SPEED_DWLEN];
} __packed;

#define NBL_NATIVE_ECPU_TX_VLD_SPEED_ADDR  (0x1006290)
#define NBL_NATIVE_ECPU_TX_VLD_SPEED_DEPTH (1)
#define NBL_NATIVE_ECPU_TX_VLD_SPEED_WIDTH (32)
#define NBL_NATIVE_ECPU_TX_VLD_SPEED_DWLEN (1)
union native_ecpu_tx_vld_speed_u {
	struct native_ecpu_tx_vld_speed {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_TX_VLD_SPEED_DWLEN];
} __packed;

#define NBL_NATIVE_ECPU_TX_RQ_VLD_SPEED_ADDR  (0x1006294)
#define NBL_NATIVE_ECPU_TX_RQ_VLD_SPEED_DEPTH (1)
#define NBL_NATIVE_ECPU_TX_RQ_VLD_SPEED_WIDTH (32)
#define NBL_NATIVE_ECPU_TX_RQ_VLD_SPEED_DWLEN (1)
union native_ecpu_tx_rq_vld_speed_u {
	struct native_ecpu_tx_rq_vld_speed {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_TX_RQ_VLD_SPEED_DWLEN];
} __packed;

#define NBL_NATIVE_ECPU_TX_CC_VLD_SPEED_ADDR  (0x1006298)
#define NBL_NATIVE_ECPU_TX_CC_VLD_SPEED_DEPTH (1)
#define NBL_NATIVE_ECPU_TX_CC_VLD_SPEED_WIDTH (32)
#define NBL_NATIVE_ECPU_TX_CC_VLD_SPEED_DWLEN (1)
union native_ecpu_tx_cc_vld_speed_u {
	struct native_ecpu_tx_cc_vld_speed {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_NATIVE_ECPU_TX_CC_VLD_SPEED_DWLEN];
} __packed;

#endif
