// Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#ifndef NBL_CAP_H
#define NBL_CAP_H 1

#include <linux/types.h>

#define NBL_CAP_BASE (0x00E64000)

#define NBL_CAP_INT_STATUS_ADDR  (0xe64000)
#define NBL_CAP_INT_STATUS_DEPTH (1)
#define NBL_CAP_INT_STATUS_WIDTH (32)
#define NBL_CAP_INT_STATUS_DWLEN (1)
union cap_int_status_u {
	struct cap_int_status {
		u32 cap_done:1;          /* [0] Default:0x0 RWC */
		u32 cif_err:1;           /* [1] Default:0x0 RWC */
		u32 rsv:30;              /* [31:2] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CAP_INT_STATUS_DWLEN];
} __packed;

#define NBL_CAP_INT_MASK_ADDR  (0xe64004)
#define NBL_CAP_INT_MASK_DEPTH (1)
#define NBL_CAP_INT_MASK_WIDTH (32)
#define NBL_CAP_INT_MASK_DWLEN (1)
union cap_int_mask_u {
	struct cap_int_mask {
		u32 cap_done:1;          /* [0] Default:0x0 RW */
		u32 cif_err:1;           /* [1] Default:0x0 RW */
		u32 rsv:30;              /* [31:2] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CAP_INT_MASK_DWLEN];
} __packed;

#define NBL_CAP_INT_SET_ADDR  (0xe64008)
#define NBL_CAP_INT_SET_DEPTH (1)
#define NBL_CAP_INT_SET_WIDTH (32)
#define NBL_CAP_INT_SET_DWLEN (1)
union cap_int_set_u {
	struct cap_int_set {
		u32 cap_done:1;          /* [0] Default:0x0 WO */
		u32 cif_err:1;           /* [1] Default:0x0 WO */
		u32 rsv:30;              /* [31:2] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CAP_INT_SET_DWLEN];
} __packed;

#define NBL_CAP_INIT_DONE_ADDR  (0xe6400c)
#define NBL_CAP_INIT_DONE_DEPTH (1)
#define NBL_CAP_INIT_DONE_WIDTH (32)
#define NBL_CAP_INIT_DONE_DWLEN (1)
union cap_init_done_u {
	struct cap_init_done {
		u32 done:1;              /* [0:0] Default:0x0 RO */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CAP_INIT_DONE_DWLEN];
} __packed;

#define NBL_CAP_CIF_ERR_INFO_ADDR  (0xe64040)
#define NBL_CAP_CIF_ERR_INFO_DEPTH (1)
#define NBL_CAP_CIF_ERR_INFO_WIDTH (32)
#define NBL_CAP_CIF_ERR_INFO_DWLEN (1)
union cap_cif_err_info_u {
	struct cap_cif_err_info {
		u32 addr:30;             /* [29:0] Default:0x0 RO */
		u32 wr_err:1;            /* [30] Default:0x0 RO */
		u32 rsv:1;               /* [31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CAP_CIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_CAP_CAR_CTRL_ADDR  (0xe64100)
#define NBL_CAP_CAR_CTRL_DEPTH (1)
#define NBL_CAP_CAR_CTRL_WIDTH (32)
#define NBL_CAP_CAR_CTRL_DWLEN (1)
union cap_car_ctrl_u {
	struct cap_car_ctrl {
		u32 sctr_car:1;          /* [0] Default:0x1 RW */
		u32 rctr_car:1;          /* [1] Default:0x1 RW */
		u32 rc_car:1;            /* [2] Default:0x1 RW */
		u32 rsv:29;              /* [31:3] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CAP_CAR_CTRL_DWLEN];
} __packed;

#define NBL_CAP_INIT_START_ADDR  (0xe64108)
#define NBL_CAP_INIT_START_DEPTH (1)
#define NBL_CAP_INIT_START_WIDTH (32)
#define NBL_CAP_INIT_START_DWLEN (1)
union cap_init_start_u {
	struct cap_init_start {
		u32 start:1;             /* [0] Default:0x0 WO */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CAP_INIT_START_DWLEN];
} __packed;

#define NBL_CAP_SPORT_ADDR  (0xe64200)
#define NBL_CAP_SPORT_DEPTH (1)
#define NBL_CAP_SPORT_WIDTH (32)
#define NBL_CAP_SPORT_DWLEN (1)
union cap_sport_u {
	struct cap_sport {
		u32 sport_mask:16;       /* [15:0] Default:0x0 RW */
		u32 sport_value:16;      /* [31:16] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_CAP_SPORT_DWLEN];
} __packed;

#define NBL_CAP_PTYPE_ADDR  (0xe64208)
#define NBL_CAP_PTYPE_DEPTH (1)
#define NBL_CAP_PTYPE_WIDTH (32)
#define NBL_CAP_PTYPE_DWLEN (1)
union cap_ptype_u {
	struct cap_ptype {
		u32 ptype_mask:8;        /* [7:0] Default:0x0 RW */
		u32 ptype_value:8;       /* [15:8] Default:0x0 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CAP_PTYPE_DWLEN];
} __packed;

#define NBL_CAP_FLAG_MASK_ADDR  (0xe64220)
#define NBL_CAP_FLAG_MASK_DEPTH (1)
#define NBL_CAP_FLAG_MASK_WIDTH (32)
#define NBL_CAP_FLAG_MASK_DWLEN (1)
union cap_flag_mask_u {
	struct cap_flag_mask {
		u32 flag_mask:32;        /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_CAP_FLAG_MASK_DWLEN];
} __packed;

#define NBL_CAP_FLAG_VALUE_ADDR  (0xe64224)
#define NBL_CAP_FLAG_VALUE_DEPTH (1)
#define NBL_CAP_FLAG_VALUE_WIDTH (32)
#define NBL_CAP_FLAG_VALUE_DWLEN (1)
union cap_flag_value_u {
	struct cap_flag_value {
		u32 flag_value:32;       /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_CAP_FLAG_VALUE_DWLEN];
} __packed;

#define NBL_CAP_DPORT_ACT_ID_ADDR  (0xe64228)
#define NBL_CAP_DPORT_ACT_ID_DEPTH (1)
#define NBL_CAP_DPORT_ACT_ID_WIDTH (32)
#define NBL_CAP_DPORT_ACT_ID_DWLEN (1)
union cap_dport_act_id_u {
	struct cap_dport_act_id {
		u32 dport_act_id:6;      /* [5:0] Default:0x9 RW */
		u32 rsv:26;              /* [31:6] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CAP_DPORT_ACT_ID_DWLEN];
} __packed;

#define NBL_CAP_DPORT_ADDR  (0xe64230)
#define NBL_CAP_DPORT_DEPTH (1)
#define NBL_CAP_DPORT_WIDTH (32)
#define NBL_CAP_DPORT_DWLEN (1)
union cap_dport_u {
	struct cap_dport {
		u32 dport_mask:16;       /* [15:0] Default:0x0 RW */
		u32 dport_value:16;      /* [31:16] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_CAP_DPORT_DWLEN];
} __packed;

#define NBL_CAP_FLOWID_MASK_ADDR  (0xe64238)
#define NBL_CAP_FLOWID_MASK_DEPTH (1)
#define NBL_CAP_FLOWID_MASK_WIDTH (32)
#define NBL_CAP_FLOWID_MASK_DWLEN (1)
union cap_flowid_mask_u {
	struct cap_flowid_mask {
		u32 flowid_mask:17;      /* [16:0] Default:0x0 RW */
		u32 rsv:15;              /* [31:17] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CAP_FLOWID_MASK_DWLEN];
} __packed;

#define NBL_CAP_FLOWID_VALUE_ADDR  (0xe6423c)
#define NBL_CAP_FLOWID_VALUE_DEPTH (1)
#define NBL_CAP_FLOWID_VALUE_WIDTH (32)
#define NBL_CAP_FLOWID_VALUE_DWLEN (1)
union cap_flowid_value_u {
	struct cap_flowid_value {
		u32 flowid_value:17;     /* [16:0] Default:0x0 RW */
		u32 rsv:15;              /* [31:17] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CAP_FLOWID_VALUE_DWLEN];
} __packed;

#define NBL_CAP_FWDACT_RS_FIELD_ACT_ID_ADDR  (0xe64240)
#define NBL_CAP_FWDACT_RS_FIELD_ACT_ID_DEPTH (1)
#define NBL_CAP_FWDACT_RS_FIELD_ACT_ID_WIDTH (32)
#define NBL_CAP_FWDACT_RS_FIELD_ACT_ID_DWLEN (1)
union cap_fwdact_rs_field_act_id_u {
	struct cap_fwdact_rs_field_act_id {
		u32 rs_field0_act_id:6;  /* [5:0] Default:0x0 RW */
		u32 rsv1:2;              /* [7:6] Default:0x0 RO */
		u32 rs_field1_act_id:6;  /* [13:8] Default:0x0 RW */
		u32 rsv:18;              /* [31:14] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CAP_FWDACT_RS_FIELD_ACT_ID_DWLEN];
} __packed;

#define NBL_CAP_FWDACT_RS_FIELD_MASK_ADDR  (0xe64244)
#define NBL_CAP_FWDACT_RS_FIELD_MASK_DEPTH (1)
#define NBL_CAP_FWDACT_RS_FIELD_MASK_WIDTH (32)
#define NBL_CAP_FWDACT_RS_FIELD_MASK_DWLEN (1)
union cap_fwdact_rs_field_mask_u {
	struct cap_fwdact_rs_field_mask {
		u32 rs_field0_mask:16;   /* [15:0] Default:0x0 RW */
		u32 rs_field1_mask:16;   /* [31:16] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_CAP_FWDACT_RS_FIELD_MASK_DWLEN];
} __packed;

#define NBL_CAP_FWDACT_RS_FIELD_VALUE_ADDR  (0xe64248)
#define NBL_CAP_FWDACT_RS_FIELD_VALUE_DEPTH (1)
#define NBL_CAP_FWDACT_RS_FIELD_VALUE_WIDTH (32)
#define NBL_CAP_FWDACT_RS_FIELD_VALUE_DWLEN (1)
union cap_fwdact_rs_field_value_u {
	struct cap_fwdact_rs_field_value {
		u32 rs_field0_value:16;  /* [15:0] Default:0x0 RW */
		u32 rs_field1_value:16;  /* [31:16] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_CAP_FWDACT_RS_FIELD_VALUE_DWLEN];
} __packed;

#define NBL_CAP_EXT_RS_FIELD16_OFT_ADDR  (0xe6424c)
#define NBL_CAP_EXT_RS_FIELD16_OFT_DEPTH (1)
#define NBL_CAP_EXT_RS_FIELD16_OFT_WIDTH (32)
#define NBL_CAP_EXT_RS_FIELD16_OFT_DWLEN (1)
union cap_ext_rs_field16_oft_u {
	struct cap_ext_rs_field16_oft {
		u32 rs_field0_oft:8;     /* [7:0] Default:0x0 RW */
		u32 rs_field1_oft:8;     /* [15:8] Default:0x0 RW */
		u32 rsv:16;              /* [31:16] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CAP_EXT_RS_FIELD16_OFT_DWLEN];
} __packed;

#define NBL_CAP_EXT_RS_FIELD16_MASK_ADDR  (0xe64250)
#define NBL_CAP_EXT_RS_FIELD16_MASK_DEPTH (1)
#define NBL_CAP_EXT_RS_FIELD16_MASK_WIDTH (32)
#define NBL_CAP_EXT_RS_FIELD16_MASK_DWLEN (1)
union cap_ext_rs_field16_mask_u {
	struct cap_ext_rs_field16_mask {
		u32 rs_field0_mask:16;   /* [15:0] Default:0x0 RW */
		u32 rs_field1_mask:16;   /* [31:16] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_CAP_EXT_RS_FIELD16_MASK_DWLEN];
} __packed;

#define NBL_CAP_EXT_RS_FIELD16_VALUE_ADDR  (0xe64254)
#define NBL_CAP_EXT_RS_FIELD16_VALUE_DEPTH (1)
#define NBL_CAP_EXT_RS_FIELD16_VALUE_WIDTH (32)
#define NBL_CAP_EXT_RS_FIELD16_VALUE_DWLEN (1)
union cap_ext_rs_field16_value_u {
	struct cap_ext_rs_field16_value {
		u32 rs_field0_value:16;  /* [15:0] Default:0x0 RW */
		u32 rs_field1_value:16;  /* [31:16] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_CAP_EXT_RS_FIELD16_VALUE_DWLEN];
} __packed;

#define NBL_CAP_EXT_RS_FIELD32_OFT_ADDR  (0xe64258)
#define NBL_CAP_EXT_RS_FIELD32_OFT_DEPTH (1)
#define NBL_CAP_EXT_RS_FIELD32_OFT_WIDTH (32)
#define NBL_CAP_EXT_RS_FIELD32_OFT_DWLEN (1)
union cap_ext_rs_field32_oft_u {
	struct cap_ext_rs_field32_oft {
		u32 rs_field0_oft:8;     /* [7:0] Default:0x0 RW */
		u32 rs_field1_oft:8;     /* [15:8] Default:0x0 RW */
		u32 rs_field2_oft:8;     /* [23:16] Default:0x0 RW */
		u32 rs_field3_oft:8;     /* [31:24] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_CAP_EXT_RS_FIELD32_OFT_DWLEN];
} __packed;

#define NBL_CAP_EXT_RS_FIELD32_MASK_ADDR  (0xe6425c)
#define NBL_CAP_EXT_RS_FIELD32_MASK_DEPTH (4)
#define NBL_CAP_EXT_RS_FIELD32_MASK_WIDTH (32)
#define NBL_CAP_EXT_RS_FIELD32_MASK_DWLEN (1)
union cap_ext_rs_field32_mask_u {
	struct cap_ext_rs_field32_mask {
		u32 rs_field_mask:32;    /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_CAP_EXT_RS_FIELD32_MASK_DWLEN];
} __packed;
#define NBL_CAP_EXT_RS_FIELD32_MASK_REG(r) (NBL_CAP_EXT_RS_FIELD32_MASK_ADDR + \
		(NBL_CAP_EXT_RS_FIELD32_MASK_DWLEN * 4) * (r))

#define NBL_CAP_EXT_RS_FIELD32_VALUE_ADDR  (0xe6426c)
#define NBL_CAP_EXT_RS_FIELD32_VALUE_DEPTH (4)
#define NBL_CAP_EXT_RS_FIELD32_VALUE_WIDTH (32)
#define NBL_CAP_EXT_RS_FIELD32_VALUE_DWLEN (1)
union cap_ext_rs_field32_value_u {
	struct cap_ext_rs_field32_value {
		u32 rs_field_value:32;   /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_CAP_EXT_RS_FIELD32_VALUE_DWLEN];
} __packed;
#define NBL_CAP_EXT_RS_FIELD32_VALUE_REG(r) (NBL_CAP_EXT_RS_FIELD32_VALUE_ADDR + \
		(NBL_CAP_EXT_RS_FIELD32_VALUE_DWLEN * 4) * (r))

#define NBL_CAP_MODE_ADDR  (0xe64300)
#define NBL_CAP_MODE_DEPTH (1)
#define NBL_CAP_MODE_WIDTH (32)
#define NBL_CAP_MODE_DWLEN (1)
union cap_mode_u {
	struct cap_mode {
		u32 cont_cap_num:4;      /* [3:0] Default:0x1 RW */
		u32 cap_mode:1;          /* [4] Default:0x0 RW */
		u32 match_mode:1;        /* [5] Default:0x0 RW */
		u32 match_cmp:1;         /* [6] Default:0x0 RW */
		u32 rsv:25;              /* [31:7] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CAP_MODE_DWLEN];
} __packed;

#define NBL_CAP_MD_START_ADDR  (0xe64304)
#define NBL_CAP_MD_START_DEPTH (1)
#define NBL_CAP_MD_START_WIDTH (32)
#define NBL_CAP_MD_START_DWLEN (1)
union cap_md_start_u {
	struct cap_md_start {
		u32 cap_start:1;         /* [0] Default:0x0 WO */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CAP_MD_START_DWLEN];
} __packed;

#define NBL_CAP_MD_DONE_ADDR  (0xe6430c)
#define NBL_CAP_MD_DONE_DEPTH (1)
#define NBL_CAP_MD_DONE_WIDTH (32)
#define NBL_CAP_MD_DONE_DWLEN (1)
union cap_md_done_u {
	struct cap_md_done {
		u32 cap_done:1;          /* [0] Default:0x0 RC */
		u32 rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CAP_MD_DONE_DWLEN];
} __packed;

#define NBL_CAP_CFG_TEST_ADDR  (0xe64310)
#define NBL_CAP_CFG_TEST_DEPTH (1)
#define NBL_CAP_CFG_TEST_WIDTH (32)
#define NBL_CAP_CFG_TEST_DWLEN (1)
union cap_cfg_test_u {
	struct cap_cfg_test {
		u32 test:32;             /* [31:00] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_CAP_CFG_TEST_DWLEN];
} __packed;

#define NBL_CAP_MD_TABLE_ADDR  (0xe65000)
#define NBL_CAP_MD_TABLE_DEPTH (32)
#define NBL_CAP_MD_TABLE_WIDTH (1024)
#define NBL_CAP_MD_TABLE_DWLEN (32)
union cap_md_table_u {
	struct cap_md_table {
		u32 capped_md_arr[32];   /* [1023:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_CAP_MD_TABLE_DWLEN];
} __packed;
#define NBL_CAP_MD_TABLE_REG(r) (NBL_CAP_MD_TABLE_ADDR + \
		(NBL_CAP_MD_TABLE_DWLEN * 4) * (r))

#endif
